### ISSUE TITLE
Extended limit with source comments

### ISSUE THREAD

**Issue by iGEL** [rubocop-hq/rubocop#2716]
First of all, thanks for RuboCop.

When introducing rubocop into legacy code, you usually can't fix all offences right away. So the usual way I use is to introduce source comments to make RuboCop pass. But complex methods are now just whitelisted, which might lead thoughtless contributors to unintentionally make bad stuff even worse. For offences, that are limited by a numerical value like `Metrics/AbcSize`, it would be really great if you could fix a new maximum.

I'm thinking about something like this:

``` ruby
# rubocop:disable Metrics/AbcSize(Max: 17.10)
```

While a bigger value clearly should be a non autofixable offense, I'm not so sure about what should happen about lower values. While it should be autofixable, I'm not sure whether it should be an offense. What do you guys think?

If you like the idea, I would like to try to implement it.

**Comment by jonas054** [comment]
I have nothing against the idea. It might be a little tricky to implement, as it has to play nicely with `--auto-gen-config` for example.

When it comes to syntax of the comment, I think I would prefer something like
```ruby
# rubocop:set Metrics/AbcSize: Max: 17.10
# [...]
# rubocop:reset Metrics/AbcSize: Max
```

What about other properties? I guess this means that all configuration must be per line rather than per file. Sounds like a lot of work.

**Comment by alexdowad** [comment]
> Sounds like a lot of work.

A lot of work. A **LOT** of work.

**Comment by rrosenblum** [comment]
Sounds like a really cool idea. I also have wanted a bit more control over some of the Metrics cops when working with legacy code. If someone chooses to try and tackle it, it may take a while to implement. I think something like this is nice to have on our radar.

**Comment by bbatsov** [comment]
It's a good idea. I'd just mention there should be a way to alter a few attributes at once and probably `reset` should just restore the default config so it shouldn't take params. I think that a layered `reset` would make this feature way more complex and would be largely redundant in practice.

**Comment by bbatsov** [comment]
Seems that we won't be moving forward with this, so I'll close it.
