### ISSUE TITLE
Get corrections in JSON output

### ISSUE THREAD

**Issue by sils** [rubocop-hq/rubocop#2932]
Hi! We're working on a tool named coala which is designed to provide good user interaction to any static code analysis tool. That way people writing code analysis can concentrate on just doing that and not rewriting user interaction again and again for each language (coala is language independent), OTOH the user only needs to learn one tool.

Because our goal is to reduce redundancy and not create some, we're integrating other tools like rubocop so they feel native for coala users.

For that we'd love it if we could get the fixes associated with the issues. In our JSON output we e.g. ship a unified diff with it: http://pastebin.com/RSArMFvS , other linters just give something like a start and end position and a replacement.

Would it be possible for you to ship the fixes with your JSON output?

(Video demo of coala at https://asciinema.org/a/37941 , if you have more questions just ask me or drop by at https://gitter.im/coala-analyzer/coala )

**Comment by alexdowad** [comment]
RC allows you to create a custom "formatter" class, which controls the CLI output. It sounds like writing your own formatter is what is needed for your use case.

**Comment by sils1297** [comment]
@alexdowad looking at http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Offense it doesn't seem like a custom formatter would even have access to that information

**Comment by alexdowad** [comment]
@sils1297 OK, you are right.

One (big) open project for RC is to provide an API which can be used to invoke it programmatically. When that is done, perhaps we can pass back the information you are asking for.

**Comment by sils1297** [comment]
IMO if you make that information available it should be contained in the JSON output right away, as people usually request JSON when they want a structured dump of all the information for the results.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
