### ISSUE TITLE
0.50.0: Style/InfiniteLoop autocorrection breaks variable scope

### ISSUE THREAD

**Issue by dabroz** [rubocop-hq/rubocop#3301]
`Style/InfiniteLoop` autocorrection breaks variable scope.
## Test case

```
while true
  a = 42
  break
end
puts a # output: 42
```
## Expected behavior

No change, as new variables are introduced in `while`. Alternative is to declare variables before `loop`.
## Actual behavior

```
loop do
  a = 42
  break
end
puts a # output: test.rb:5:in `<main>': undefined local variable or method `a' 
       # for main:Object (NameError)
```
## Steps to reproduce the problem
1. Put test case in a `test.rb` file
2. Run `rubocop -a`
## RuboCop version

```
0.41.2 (using Parser 2.3.1.2, running on ruby 2.3.1 x86_64-darwin14)
```

**Comment by mikegee** [comment]
I confirmed the reported behavior on master.

Two solutions come to mind:
- hoist local variables by pre-assigning `nil` to them above the loop
- avoid auto-correcting when the while loop contains local variable assignment without reference above the loop

**Comment by dabroz** [comment]
This still occurs with rubocop 0.50.0.

**Comment by Drenmi** [comment]
Verified problem is still there on latest `master` (`0.59.1`).
