### ISSUE TITLE
Offences for embedded shell scripts

### ISSUE THREAD

**Issue by tueda** [rubocop-hq/rubocop#3326]
It would be nice if RuboCop could skip embedded shell scripts when a file starts with a shebang that does not contain the string `ruby`, and then the file has a line starting `#!` containing `ruby`. The lines between them are expected to be ignored by Ruby with `-x` option.

---
## Expected behavior

No offences for the following code:

```
#!/bin/sh
exec ruby -S -x "$0" "$@"
#!ruby
puts 'Hello, World!'
```
## Actual behavior

```
$ rubocop foo.rb
Inspecting 1 file
E

Offenses:

foo.rb:2:11: W: `-' interpreted as argument prefix
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
exec ruby -S -x "$0" "$@"
          ^
foo.rb:2:14: W: `-' interpreted as argument prefix
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
exec ruby -S -x "$0" "$@"
             ^
foo.rb:2:14: E: unexpected token tUMINUS
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
exec ruby -S -x "$0" "$@"
             ^

1 file inspected, 3 offenses detected
```

To suppress all the offenses, I need to modify the above code as (though it could be an acceptable workaround)

```
#!/bin/sh
# rubocop:disable all
exec ruby '-S' '-x' "$0" "$@"
#!ruby
# rubocop:enable all
puts 'Hello, World!'
```
## Steps to reproduce the problem

Run Rubocop for the code in "Expected behavior".
## RuboCop version

```
$ rubocop -V
0.41.2 (using Parser 2.3.1.2, running on ruby 2.2.3 x86_64-linux)
```

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
