### ISSUE TITLE
cannot define relative path for rubocop cache

### ISSUE THREAD

**Issue by cpanato** [rubocop-hq/rubocop#3678]
Hello

I tried to set the cache using this:

CacheRootDirectory: ~/.rubocop-cache

and nothing happens, if I add the full path it works and I can see the folder

also not work if use symlink

**Comment by mikegee** [comment]
Could you please clarify?
- What does "nothing happens" mean? No new contents in `~/.rubocop-cache`, or RuboCop won't even run?
- When you say "if I add the full path", do you mean you replaced `~` with the path to your home directory?
- "also not work if use symlink": symlink at what path? pointing to what other path?

**Comment by cpanato** [comment]
1 -if I define:
CacheRootDirectory: ~/.rubocop-cache
the folder is not created with the cache files, but rubocop runs

2 - if I add the full path:
CacheRootDirectory: /User/measuser/.rubocop-cache
the folder is created and the cache files are there. and the next time rubocop runs it is much more fast as expected :)

3- On mac the /tmp is a symlink to /private/tmp
and if define the 
CacheRootDirectory: /tmp

I received the error message for each file the rubocop analyze and it not save the cache and if run t second time and so on the error message wtill continue.


ps. I'm running on MAC Sierra

**Comment by jonas054** [comment]
1 - The tilde expansion is a function of the shell; bash, zsh, or whatever. Ruby's path processing functions don't do it and so far we haven't added this functionality in RuboCop, but I guess we could (I'm adding a feature request label). I think you'll find that a directory called `~` was created in the current directory when you ran.

3 - This is intended behavior in RuboCop. Directory symlinks are considered dangerous, as they constitute a vulnerability for so called symlink attacks. You should set
```yaml
AllCops:
  CacheRootDirectory: /private/tmp
```

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
