### ISSUE TITLE
Bundler/DuplicatedGem does not recognize if statements and the like

### ISSUE THREAD

**Issue by edestecd** [rubocop-hq/rubocop#3752]
This fails and should not:
```ruby
  if RUBY_VERSION < '2.2.5'
    # beaker 3.1+ requires ruby 2.2.5.  Lock to 2.0
    gem 'beaker', '~> 2.0', :require => false
    # beaker-rspec 6.0.0 requires beaker 3.0. Lock to 5.0
    gem 'beaker-rspec', '~> 5.0', :require => false
  else
    gem 'beaker-rspec', :require => false
  end
```

**Comment by backus** [comment]
This is an interesting issue since it seems like bundler doesn't want you to specify different dependency versions depending on the ruby version. Bundler has a construct built in for specifying dependencies depending on the ruby version and if you try to convert your example to their `platforms` construct then you get an error

```ruby
source 'https://rubygems.org'

gem 'beaker-rspec', '~> 5.0', require: false, platforms: :ruby_22
gem 'beaker-rspec', require: false, platforms: :ruby_23
```

```
$ bundle install
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: beaker-rspec (~> 5.0) and beaker-rspec (>= 0). Bundler cannot continue.

 #  from Gemfile:4
 #  -------------------------------------------
 #  gem 'beaker-rspec', '~> 5.0', require: false, platforms: :ruby_22
 >  gem 'beaker-rspec', require: false, platforms: :ruby_23
 #  -------------------------------------------
```

**Comment by mvz** [comment]
Note that for this particular case, you shouldn't need the `if` when using Bundler 1.13.x. You can instead tell Bundler to respect the gems' ruby version requirements like so:

```
ruby RUBY_VERSION

gem 'beaker-rspec', :require => false
```

**Comment by edestecd** [comment]
What if you need to run your Gemfile against multiple ruby versions.
Our app (puppet) supports many versions of ruby and we want travis ci to test all of them.

**Comment by edestecd** [comment]
@mvz From what I understand of the ```ruby``` keyword in bundler, it just fails if ruby is not at the specified version.  We need a Gemfile that works for multiple versions of ruby ;) Can that be done without an if?

**Comment by edestecd** [comment]
This is a very common pattern in puppet module development:
https://github.com/puppetlabs/puppetlabs-apache/blob/master/Gemfile#L45
https://github.com/voxpupuli/puppet-php/blob/master/Gemfile#L58

**Comment by edestecd** [comment]
Hmm, Maybe the ruby version can be an ENV var? Seems like the gem knows what version of ruby it needs and bundler can satisfy this?
https://github.com/puppetlabs/beaker-rspec/blob/master/beaker-rspec.gemspec#L15

I'll mess around with setting the ruby version and see if it works out...

**Comment by mvz** [comment]
> From what I understand of the `ruby` keyword in bundler, it just fails if ruby is not at the specified version.

Yes, but because you set it to `RUBY_VERSION`, ruby is actually automatically at the specified version. As a side effect, Bundler is triggered to ignore all other ruby versions and can therefore use the gems' ruby version requirements.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
