### ISSUE TITLE
`Style/StringLiterals` register offense when using single quotes string literal with backslash escaped single quotes.

### ISSUE THREAD

**Issue by iguchi1124** [rubocop-hq/rubocop#3823]
Based on discussions at here: https://github.com/bbatsov/rubocop/pull/3822#discussion_r93826208

```ruby
# bad 
'Rails.root.join(\'app\', \'models\', \'user.rb\')'

# good
"Rails.root.join('app', 'models', 'user.rb')"
```

`Style/StringLiterals` check for use escape less string instance.

**Comment by bbatsov** [comment]
This can be generalized to other cases when you'd selected a type of string literal that makes you escape a lot of quotes.
