### ISSUE TITLE
Cop Ideas Enforce/Disallow &method

### ISSUE THREAD

**Issue by rrosenblum** [rubocop-hq/rubocop#3840]
Ruby has a syntax which allows the an iterator to pass an object to method as an argument using `&method`. There are reason in which you might want to use this syntax and instances in which you might not want to use this syntax. It would be nice if RuboCop could help enforce some standards around this. If possible, we would like to have a configuration to disallow `&method` and a configuration that would enforce it. This is similar to `Style/SymbolProc` so I don't know if it should be part of that cop or a different cop. 

* See #3826 for a discussion on this syntax. 
* See https://andrewjgrimm.wordpress.com/2011/10/03/in-ruby-method-passes-you/ for information on how `&method` works.
* See http://stackoverflow.com/questions/6976629/is-the-methodmethod-name-idiom-bad-for-perfomance-in-ruby for information on performance

**Comment by bbatsov** [comment]
That would be a useful cop. I definitely would keep it separate from `SymbolProc`.

**Comment by tom-lord** [comment]
Dear future readers who land here from a google search 😸 ...

This can now be enforced with the `rubocop-performance` gem: https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancemethodobjectasblock
