### ISSUE TITLE
Add a cop that checks grouping of accessor methods

### ISSUE THREAD

**Issue by Drenmi** [rubocop-hq/rubocop#3983]
As per [this issue](https://github.com/bbatsov/rubocop/issues/3936#issuecomment-273704948), there should be a cop that checks the grouping of `attr_reader`, `attr_writer` and `attr_accessor`, i.e. `Style/AccessorGrouping`.

All references to accessor methods in the style guide uses a grouped style, e.g.:

```
attr_reader :foo, :bar
```

and I think this should be the default. There is no explicit section on this however, so it should probably be added as part of work on this cop.

**Note:** accessor methods are affected by visibility scopes (`public`, `protected`, `private`) and the cop needs to take this into account.

**Comment by bbatsov** [comment]
> and I think this should be the default. There is no explicit section on this however, so it should probably be added as part of work on this cop.

Agreed.
