### ISSUE TITLE
Performance Rails Cop proposal: Replace Pluck Include? with Where Exists?

### ISSUE THREAD

**Issue by basex** [rubocop-hq/rubocop#4125]
`pluck(:status).include?('element')` can be refactored to `where(status: 'element').exists?`

There is no need to export a lot of data, creating an array and then running include?, when activerecord can check directly if the element exists on the database.

**Comment by Drenmi** [comment]
Additionally, `where(status: 'element').exists?` can be written `exists?(status: 'element')`. 😉 

But that's another cop altogether. 🙂

**Comment by rrosenblum** [comment]
@Drenmi I would prefer using `where(status: 'element').exists?` over `exists?(status: 'element')`. Starting around Rails 4.2, Rails has been deprecating or removing the finder ability of most of the ActiveRecord query methods. Even though I have not seen anything about `exists?` with a condition being deprecated, I wouldn't count on that functionality being supported for much longer.

**Comment by bbatsov** [comment]
We're in the process of moving all Rails-related functionality to a standalone library (gem) named `rubocop-rails`. Please, migrate this issue to its issue tracker https://github.com/rubocop-hq/rubocop-rails/issues/
