### ISSUE TITLE
Options for tolerating a certain number of violations and ratcheting it automatically

### ISSUE THREAD

**Issue by brentsnook** [rubocop-hq/rubocop#4259]
## The problem
I want to run my ideal configuration against a legacy codebase and tolerate a certain number of violations. New code should adhere to the style I want; I want rubocop to fail my build if this number goes up. I'd also like this number to automatically reduce as existing violations are fixed.

This is sometimes referred to as a ratchet as described in my now ancient blog post: https://fuglylogic.wordpress.com/2009/05/29/keeping-on-the-tail-of-code-quality-with-a-ratchet

We use Code Climate but the resulting feedback cycle can be pretty slow. I want something I can run as part of my pre-checkin build.

### --max-violations option
This is the bare minimum that would allow others to build their own ratchet around rubocop. I've done this in the past with older tools like Checkstyle for Java by implementing the rest in Ant.

### ---ratchet option
This could read the number of allowed violations from a separate file, fail if the number is violations is above it and then write the new number of violations back if it decreases.

I'm happy to take a stab at hacking either of these in on a separate branch to prove/develop the concept if people are interested.

**Comment by vergenzt** [comment]
I'm interested in the same problem! I'm currently working to solve it with #4127. You may want to check it out.

**Comment by brentsnook** [comment]
@vergenzt cool, sounds like the exact same problem but different solutions. I think I'd prefer not having to annotate the code for each violation though.

In the above approach I'd also look at generating a report of violations that can be checked into source control. You can then diff the report after a rubocop run to find out the new violations that you just introduced so that they don't get lost in a sea of others.

**Comment by Drenmi** [comment]
@brentsnook: Have you looked into the `--auto-gen-config` command? It gives you a `.rubocop_todo.yml` that does roughly what you're asking for, and can be checked into version control. 🙂

**Comment by brentsnook** [comment]
@Drenmi ` --auto-gen-config` would help suppress existing violations, one problem that I can see though is that it works on a file level; that means that once you've excluded a file then you are free to keep introducing violations of the same type to that file (problem 2 mentioned in #4127). I want violations that I've introduced to show up explicitly without being lost amongst the existing ones.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
