### ISSUE TITLE
Add EnforcedStyle None for EmptyLineAfterMagicComment

### ISSUE THREAD

**Issue by grosser** [rubocop-hq/rubocop#4280]
I'd like to enforce

```
# frozen_string_literal: true
class Foo
end
```

**Comment by bbatsov** [comment]
That looks pretty odd to me - imagine how it'd look if the class had some documentation, it'd be even weirder. However, if enough people want it, we might consider adding it.

**Comment by grosser** [comment]
The trick is to never add documentation :trollface:

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.

**Comment by bbatsov** [comment]
Trust me - that doesn't work very well with 300+ open tickets. 😃 Generally I've come to the believe that if no one wants to implement something probably we don't need it this much, so I'd rather clean up the tracker and focus on the most important tasks (some of which we'll mark with `Help Wanted` of course).
