### ISSUE TITLE
rule suggestion hash inside array

### ISSUE THREAD

**Issue by mockdeep** [rubocop-hq/rubocop#4286]
When a ruby hash is the last item in an array, we can use the same shorthand syntax as for method calls. It would be nice to have a linter to enforce one style or another:

```ruby
# braces
my_array = ['foo', 'bar', { baz: 'butz' }]

# no_braces
my_array = ['foo', 'bar', baz: 'butz']
```

**Comment by bbatsov** [comment]
We should also add a rule about this in the style guide. I definitely think the preferred practice should be to use curly braces.

**Comment by ZimbiX** [comment]
Unless this has been resolved without my knowledge, please re-open the issue
