### ISSUE TITLE
Support for multiline comments / multiline comment annotations indentation

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [rubocop-hq/rubocop#4291]
[The Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide) suggests in the section [Comment Annotations](https://github.com/bbatsov/ruby-style-guide#indent-annotations) that 
subsequent lines of annotations should be indented by two extra spaces.

Example from the **Ruby Style Guide**:
```
def bar
  # FIXME: This has crashed occasionally since v3.2.1. It may
  #   be related to the BarBazUtil upgrade.
  baz(:quux)
end
```

* Is there already a **rubocop rule** for that style guide?
* Does this style guide apply only for **Comment Annotations** or for all **Multiline Comments**?
* In [Issue 1090](https://github.com/bbatsov/rubocop/issues/1090) it is assumed, that **Comment Annotations** are only one line long. Is this still the case?

**Comment by jonas054** [comment]
> Is there already a rubocop rule for that style guide?

No.

> Does this style guide apply only for Comment Annotations or for all Multiline Comments?

It's under the Comment Annotations heading, so it has to be for Comment Annotations only. 

> In Issue 1090 it is assumed, that Comment Annotations are only one line long. Is this still the case?

That's what's implemented, but I think it would be a good idea to change the implementation so we detect some obvious cases of where extra indentation should be added. When it looks like a sentence that continues past a line break, I mean.
