### ISSUE TITLE
Style/FirstParameterIndentation gets confused by non-trivial indentation

### ISSUE THREAD

**Issue by rwz** [rubocop-hq/rubocop#4308]
```ruby
# code.rb

MyClass.my_method(a_hash.merge(
  hello: :world,
  some: :hash,
  goes: :here
), other_arg)
```

--------

## Expected behavior

In this case the first parameter to `MyClass.my_method` would the the result of `a_hash.merge(...)` method call and it should not be indented since it starts on the same line. The arguments to `a_hash.merge` though are indented relative to the line the method was called on, so it should also be ok.

## Actual behavior

```
code.rb:2:3: C: Style/FirstParameterIndentation: Indent the first parameter one step more than a_hash.merge(.
  hello: :world, ...
  ^^^^^^^^^^^^^^
```

## RuboCop version

```
$ rubocop -V
0.48.1
```

**Comment by jonas054** [comment]
> The arguments to a_hash.merge though are indented relative to the line the method was called on, so it should also be ok.

If that's what you want, you should have the configuration

```yaml
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
```

**Comment by jfelchner** [comment]
@jonas054 @bbatsov this should be able to be closed now.
