### ISSUE TITLE
Idea: Cop to warn of dangerous method names

### ISSUE THREAD

**Issue by betesh** [rubocop-hq/rubocop#4359]
This idea is inspired by https://github.com/sparklemotion/nokogiri/issues/1635, where there is a discussion in progress about how Ruby sets a contract that the `name` method on a singleton should return either a resolvable String or `nil`.

Therefore, when `name` is overridden in a singleton, it's quite likely that there is a violation of that contract.

I am sure there are numerous other methods defined in Object, Module, Kernel, etc that should also never be overridden without good reason.  For example, `alias`, `fail`, etc.  I am sure there is a definitive list somewhere, but I don't know where.

We could add a cop to the Lint group that would identify these methods and warn the user that it is dangerous to use these names.

**Comment by rrosenblum** [comment]
ActiveRecord will warn when a user defines a method that overwrites an ActiveRecord method. It might be nice to have a Rails counterpart to this cop.

**Comment by betesh** [comment]
That makes sense--a `Lint/DangerousMethodName` cop for methods like `fail` and `nil?`, and a `Rails/DangerousRailsMethodName` (we need a better name for it but it should be different than the Lint one) to make sure you don't use method names like `blank?`.
