### ISSUE TITLE
Proposal: `rubocop --auto-correct-safe`

### ISSUE THREAD

**Issue by samphilipd** [rubocop-hq/rubocop#4365]
When working on an existing project with inconsistent style, I would like to be able to run `rubocop --auto-correct` on it to fix things like Ruby 1.9 hash syntax, inconsistent indentation, inline rescues etc.

The problem is that auto-correct currently makes some corrections that subtly alter the behaviour of the code. This can break existing code and makes rubocop too dangerous to run on legacy code bases with inadequate test coverage (actually, the kind of code base where a stylistic auto-correct would be most useful).

I propose being able to mark an auto-correction as either **safe** or **dangerous**.

**Safe** corrections are guaranteed to not change the behaviour of the code at all. They are stylistic/syntactic only (e.g. indentation, if/unless modifiers).

**Dangerous** corrections may subtly alter the behaviour of the code and thus some people may not want to run these gung-ho on a large project. An example would be adding `#frozen_string_literal: true` to the head of a file.

Now you could run `rubocop --auto-correct-safe` on a large, legacy project to fix syntactical and stylistic errors and be confident that it would break absolutely nothing.

If you wanted to bring a modern project with excellent test coverage up-to-date with best practices, then you could use `rubocop --auto-correct-dangerous` with full awareness that this may change behaviour of your code, and it is developer's responsibility to make sure it is fully tested.

Just realised there is a (possible) dupe of this - #3998

**Comment by Drenmi** [comment]
I do not think there should be an `--auto-correct-safe` flag. I think auto-correct should be safe by default. 🙂 

There could still be room for a "martial law" flag, I guess, that runs auto-correct for all cops that support it.

**Comment by jonas054** [comment]
If `Style/AndOr` somtimes makes sematic changes to the code, then that's a bug. We should fix that bug or at least add `AutoCorrect: false` to the cop's default configuration.

**Comment by majormoses** [comment]
> I think auto-correct should be safe by default. 

Ideally yes in practicality it is not. I maintain several hundred open source plugins and I find it safer to make the changes myself due to lack of test coverage and rubocop auto correct regularly biting us. What I would like to see is something more along the lines of a dry run to show and let the developer validate that yes it is safe or maybe it requires a bit more intervention. This allows you to view, evaluate the risk, disable any that you are unsure of inline, re-run without dry-run, and then you can come back to work on the ones you disabled.

**Comment by majormoses** [comment]
> that are guaranteed not to change the behavior of the code.

That is a very hard thing to accomplish, a dry run would be safer and easier to implement.

**Comment by gnapse** [comment]
Ok, I get it, but it is disappointing. My whole purpose was to try and use rubocop as a sort of prettierjs for ruby code. But I guess that it's not rubocop's goal to be that, so it's hard to use it as that. I did not like rufo either, so my best bet is to wait for [prettier-ruby](https://github.com/iamsolankiamit/prettier-ruby) to become stable. And then leave rubocop purely as a linter, disabling all style rules and any other rules that conflict with prettier-ruby format.

**Comment by jamiecook** [comment]
I'd second gnapse sentiment here - we've been using rubocop for a while and just ignoring the ability to auto-correct certain things, focussing instead on RubyMine to fix formatting. But recently having worked in the python and haskell space more lately the benefits provided by tools like [black](https://github.com/ambv/black) and [stylish-haskell](https://github.com/jaspervdj/stylish-haskell) I can now see the lack of similar tooling in ruby. 

And currently rubocop is the largest and most mature toolset in this space. I'd love to leverage it more and not rely on immature tools if at all possible (no offence to the prettier-ruby team - just a desire to not be on the bleeding edge)

**Comment by bbatsov** [comment]
Yeah, we are going to do this very soon. It’s now one of the highest
priority items for our team.

**Comment by koic** [comment]
I think that this issue can be integrated with #5980 and closed.

**Comment by bbatsov** [comment]
Agreed.
