### ISSUE TITLE
Rubocop -a changes line endings

### ISSUE THREAD

**Issue by dreamnite** [rubocop-hq/rubocop#4374]
Currently rubocop -a is changing line endings for files. This has previously been reported and fixed in #1566, but appears to have regressed in the current master.

Change that regressed the behavior:
https://github.com/bbatsov/rubocop/commit/fcdbd4d5b3850b15cb87b9b52ed14be0238f96d1

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
