### ISSUE TITLE
Bug in Autocorrect for Layout/IndentHeredoc

### ISSUE THREAD

**Issue by justin808** [rubocop-hq/rubocop#4465]
If your heredoc contains strings with returns, then the lines contained will be left aligned, so the extra indentation in the heredoc is placed in the string, so you cannot indent the heredoc and expect strip_heredoc to fix the issue.

*Before filing the ticket you should replace all text above the horizontal
rule with your own words.*

--------

## Expected behavior

> Describe here how you expected RuboCop to behave in this particular situation.

Offer an option so that if the heredoc contains any `#{foobar}`, then the rule does not apply.

## Actual behavior

> Describe here what actually happened.

Incorrectly formatted output. See images below.

## Steps to reproduce the problem

> This is extremely important! Providing us with a reliable way to reproduce a problem will expedite its solution.

Stay tuned for a test case in https://github.com/shakacode/react_on_rails

## RuboCop version
0.49.1

## Correctly Formatted
![image](https://cloud.githubusercontent.com/assets/1118459/26765823/a60c461a-491f-11e7-8bcc-f344ea3e15f1.png)

## Incorrectly formatted
![image](https://cloud.githubusercontent.com/assets/1118459/26765830/c54cdb66-491f-11e7-8406-f4448d099a0c.png)

## Offense Fixed
![image](https://cloud.githubusercontent.com/assets/1118459/26765826/aa60df64-491f-11e7-83ba-4c04c393c31c.png)

## Test error
![image](https://cloud.githubusercontent.com/assets/1118459/26765827/aee5d1e8-491f-11e7-858b-9adb00460b11.png)

**Comment by jonas054** [comment]
Is this different between different ruby versions? I have not been able to reproduce the problem with stripping the indentation.

**Comment by jonas054** [comment]
@justin808 Please open again if it's still a problem. I've never grasped what the actual problem was or how to reproduce it. Closing.
