### ISSUE TITLE
Help the parser project find more maintainers

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#4532]
RuboCop is powered internally by https://github.com/whitequark/parser and it seems the project is no longer actively maintained https://github.com/whitequark/parser/issues/317#issuecomment-304316789

This means that future Ruby releases would be unsupported by `parser` and by RuboCop as well. Guess we need to find @whitequark some help for the project.

**Comment by whitequark** [comment]
It's not that Parser isn't *maintained at all* (I still look over the issue tracker, watch upstream commits and fix the most critical stuff), it's that I don't really *port upstream changes* anymore.

**Comment by bbatsov** [comment]
That's what I meant by `not actively maintained`. ;-) 

> I don't really port upstream changes anymore.

Anyways, we'll certainly need to find someone to do this, given how many projects depend on `parser` these days.
