### ISSUE TITLE
Modifier form arguments should only use a single line

### ISSUE THREAD

**Issue by NobodysNightmare** [rubocop-hq/rubocop#4540]
In the past I have seen quite a few occurences of `if` and `unless` being used in their modifier form, but then stretching across multiple lines.

I always found this quite irritating and I feel, that the modifier form is only "intended" for single line use.

Though, as many things in rubocop, this is probably opionionated and there might be valid cases that I don't see...

--------

## Expected behavior

The following code sample raises a `Style/*` offense:

```ruby
foo if bar.baz
          .boom
```

## Actual behavior

It reports no offense.

## Steps to reproduce the problem

Inspect the code sample above using rubocop.

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux)
```

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
