### ISSUE TITLE
why not using interpolation in Style::FormatString

### ISSUE THREAD

**Issue by Ana06** [rubocop-hq/rubocop#4565]
Currently `Style/FormatString` cop will complain about things like:

``` Ruby
key = '%s/%s' % [dproject, dp.name]
```

and the autocorrect will change it by:

``` Ruby
key = format('%s/%s', dproject, dp.name)
```

I wonder why not changing it by (using interpolation):

``` Ruby
key = "#{dproject}/#{dp.name}"
```
I find it way more readable. Not sure if can be always be used. :thinking: 

## RuboCop version

```
$ rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.4.1 x86_64-linux-gnu)
```

**Comment by Drenmi** [comment]
They are not directly interchangeable. 🙂 `Kernel#format` does a lot more. It can pad strings, convert between types, and format numbers, depending on which references you use in the template.

There is a way to make it a bit more readable, and we've discussed adding a cop for it. You can name the references like so:

```ruby
format("%<foo>s %<bar>s!", foo: "Hello", bar: "world")
#=> "Hello world!"
```

This cop isn't implemented yet, however.

**Comment by mikegee** [comment]
I was thinking the particular case presented here might be nice to handle: format strings containing only `%s` references could be replaced with interpolation. Yet another cop, or maybe not worth it 🤔

**Comment by Ana06** [comment]
@mikegee 
> format strings containing only %s references could be replaced with interpolation

Another cop would be great! Documenting that string interpolation is prefer in this case in Style::FormatString would also be a good idea :+1:

**Comment by backus** [comment]
> There is a way to make it a bit more readable, and we've discussed adding a cop for it. You can name the references like so

Are you referring to something besides what [`Style/FormatStringToken`](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/format_string_token.rb) does?

**Comment by Drenmi** [comment]
@backus: Ah! I remember this being mentioned, but didn't realize this was actually added. 😍

**Comment by ryanhageman** [comment]
Is this still an issue?
