### ISSUE TITLE
Inconsistant functionality in Performance/CaseWhenSplat

### ISSUE THREAD

**Issue by rrosenblum** [rubocop-hq/rubocop#4680]
```ruby
case foo
when *[1, 2, 3]
  something
when 4
  another_thing
end
```

After breaking `Lint/UnneededSplatExpansion` out into its own gem, `CaseWhenSplat` no longer registers an offense when expanding an array because it expects `UnneededSplatExpansion` to handle the fix in a better way.

I don't like that this cop now treats splat expansion of an array literal differently, but I am not sure what the best way to fix this is.

1. Leave it as is

2. Register an offense for expanding an array, but do not auto-correct. Update the offense message to show the correction and recommend enabling `UnneededSplatExpansion`
3. Register an offense for expanding an array and allow auto-correct to rearrange the order

Will `CaseWhenSplat` and `UnneededSplatExpansion` conflict with each other during auto-correct? Will this wind up reordering the the when statements and removing the expansion?

4. Register an offense for expanding an array and have the auto-correct do the same thing as `UnneededSplatExpansion`

This is how the cop originally worked.

**Comment by bbatsov** [comment]
We're in the process of moving all Performance-related functionality to a standalone library (gem) named `rubocop-performance`. Please, migrate this issue to its issue tracker https://github.com/rubocop-hq/rubocop-performance/issues/
