### ISSUE TITLE
What is the maximum time users are ok with rubocop taking?

### ISSUE THREAD

**Issue by ptarjan** [rubocop-hq/rubocop#4689]
I don't know of another place to have this discussion other than in an issue, sorry.

I'm trying to set an upper bound on how much times users are ok with for their in-editor linting. We're encouraging many of our engineers to write rubocops instead of tests since they provide much quicker feedback, but I want to keep an eye on how much slowdown users will tolerate.

I can't find much research online in this space. I know with asyncronous plugins like `vim-ale` it is less of an issue, but still matters for developer productivity getting the feedback cycles are you edit.

So, I was wondering if anyone in the rubocop community has done any research themselves in this space or knows of any.

Thanks

**Comment by rrosenblum** [comment]
I haven't done any research, but I can speak from my own experiences. Are you interested in the max time it should take to lint an entire project or a single file? Regardless, the time it will take RuboCop to run is going to depend on the number of cops that are enabled and the total size of the code that is going to be linted.

I will have to research how to time a command in VIM to get a more accurate time measurement. The average file linting seems to take 1-3 seconds for me.

**Comment by ptarjan** [comment]
Thanks @rrosenblum. I'm most interested in the single-file timing as that is the in-editor experience.

**Comment by bbatsov** [comment]
> So, I was wondering if anyone in the rubocop community has done any research themselves in this space or knows of any.

I guess not. :-)
