### ISSUE TITLE
Rubocop does not notice redundant merge! 

### ISSUE THREAD

**Issue by bunufi** [rubocop-hq/rubocop#4775]
h2. Description

Rubocop does not always report merge! as in: 
http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Performance/RedundantMerge

--------

## Expected behavior

Rubocop reports merge! and merry devs changes to a better code. 

## Actual behavior

Rubocop does not care about some of the merge! 

## Steps to reproduce the problem

Rubocop the following. 

```
  # tested with rubocop (0.50.0)
  def example_method
    # rubocop notices merge! in this if clause and reports as expected
    if what_if
      @this_works.merge!(one: 1)
    else
      @as_expected.merge!(two: 2)
    end

    # but for this one, it does not and remains silent
    if this_is_strange
      @do_not_work.merge!(nope: 666)
    else
      @do_not_work.merge!(not_at_all: 9)
    end
  end
```

## RuboCop version
```
0.50.0
```

**Comment by jonas054** [comment]
That's because the value returned by either of the last two `merge!`s is the return value of `example_method` and RuboCop can't be sure if those statements can safely be converted to array element assignments.

**Comment by bunufi** [comment]
Thanks for the reply @janraasch. 
Why is `merge!` safer to use here? 
Would it be feasible to add explanation in documentation?

**Comment by jonas054** [comment]
> Would it be feasible to add explanation in documentation?

Yes I think it would. Current documentation is

**This cop identifies places where `Hash#merge!` can be replaced by `Hash#[]=`.**

We could mention that `Hash#[]=` has a different return value than `Hash#merge!`, so whenever the return value is used or could possibly be used, the cop does not suggest a change.
