### ISSUE TITLE
Performance/HashEachMethods triggers with any "values.each"

### ISSUE THREAD

**Issue by DiscipleAndrew** [rubocop-hq/rubocop#4777]
I noticed the following behaviour that was recently introduced, mistakenly I think, by https://github.com/bbatsov/rubocop/issues/4368. It looks like it's missing a check to see if `values` is actually called on an object (i.e. `.values`). Unfortunately I've no idea how to attempt a fix.

--------

## Expected behavior

No offenses detected.

## Actual behavior

```
Inspecting 1 file
C

Offenses:

test.rb:1:1: C: Performance/HashEachMethods: Use each_value instead of values.each.
values.each { |v| puts v }
^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem

Test a Ruby file with the following:
```ruby
values.each { |v| puts v }
```

## RuboCop version

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.4.2 x86_64-linux)
```

**Comment by jmks** [comment]
Your example nearly matches a test case:

```ruby
context 'when receiver is implicit' do
 ...  
  it 'registers an offense for values.each' do
    expect_offense(<<-RUBY.strip_indent)
       values.each { |v| p v }
       ^^^^^^^^^^^ Use `each_value` instead of `values.each`.
    RUBY
  end
```

In this case, I don't think we can tell the difference between an implicit receiver and `values` being something else (variable or method call). In the latter case, I would consider renaming `values` to be something more descriptive.

**Comment by bbatsov** [comment]
This cop was removed.
