### ISSUE TITLE
Should Rails/HasManyOrHasOneDependent require dependent for multiple definitions of the same associated table?

### ISSUE THREAD

**Issue by jpcody** [rubocop-hq/rubocop#4780]
When specifying multiple `has_many` relationships that represent the same underlying records, `dependent: :destroy` should only be present on one of said relationships. 

--------

## Expected behavior

Er, this one is sort of tradeoffy. Maybe it's too much of an edgecase? Maybe it's not safe to require `:dependent` when specifying a `class_name`. Maybe Rails should implement some sort of `as(class_name)` method so users don't have to co-opt `has_many` to get a collection of a given class?

## Actual behavior

Rubocop requests `:dependent` to be defined on all instances of a `has_many`, even if they access the same record, which results in extra queries to the database.

## Steps to reproduce the problem

```RUBY
class Animal
end

class Animal::Mammal
end

class Zoo
  has_many :animals, dependent: :destroy
  has_many :mammals, class_name: "Animal::Mammal", dependent: :destroy
end

Zoo.first.animals  # [#<Animal>, #<Animal>]
Zoo.first.mammals  # [#<Animal::Mammal>, #<Animal::Mammal>]

# Triggers queries for each defined relation
# 1. Pulls back all animals, iterates and deletes
# 2. Queries for all animals where type is mammal (finds none, does nothing)
Zoo.last.destroy
```

The above code would trigger this. If this represents a use case Rubocop would like to handle, I'll be happy to bundle an application or submit a PR. I'm just unclear if Rubocop should care on this one.

## RuboCop version

```
$ rubocop -V
0.5.0
```

**Comment by bbatsov** [comment]
We're in the process of moving all Rails-related functionality to a standalone library (gem) named `rubocop-rails`. Please, migrate this issue to its issue tracker https://github.com/rubocop-hq/rubocop-rails/issues/
