### ISSUE TITLE
Performance/HashEachMethods shouldn't try to enforce replacement of each (each_pair)

### ISSUE THREAD

**Issue by timdiggins** [rubocop-hq/rubocop#4872]
## Context: 

Performance/HashEachMethods is really useful to stop double-iteration -- this is why it is in the "Performance" namespace. Due to https://github.com/bbatsov/rubocop/issues/4368 it is actually working in more areas now and catching items such as

```
h = {}
h.keys.each { |k| p k }
h.values.each { |v| p v }
```

 Thanks!

## Unexpectedly:

However it also deliberately catches items such as 

```
h.each { |k, _v| p k }
h.each { |_k, v| p v }
```

There is no gross **performance** defect that I can see from using `each` rather than `each_key`/`each_value` here (nothing on the order of the double iteration from using h.keys.each). It doesn't detect the synonym `each_pair`.

Could the `Performance/HashEachMethods` application to `.each` be dropped, or at least made configurable? Or split into `Style/HashEachMethods` leaving performance issues in `Performance/HashEachMethods`?

## RuboCop version

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.3.4 x86_64-darwin15)
```

**Comment by Drenmi** [comment]
> There is no gross performance defect that I can see from using `each` rather than `each_key`/`each_value` here (nothing on the order of the double iteration from using `h.keys.each`).

Good point.

> Or split into `Style/HashEachMethods` leaving performance issues in `Performance/HashEachMethods`?

Seems like a sensible approach to me.

**Comment by bbatsov** [comment]
I think we solved this at some point.
