### ISSUE TITLE
Naming/BinaryOperatorParameterName: exclude `#===` from operator list.

### ISSUE THREAD

**Issue by zverok** [rubocop-hq/rubocop#4894]
Reason: the cop's message

> When defining the === operator, name its argument other.

...if I understand it correctly, implies that "other" is the same type as "self", which may be true for operators like `==` or `<`, but typically wrong for `===`. We explicitly define this operator in something that will suit like "pattern" class, and argument name in this case should be name/explanation of "what this pattern able to check".

**Comment by Drenmi** [comment]
There's nothing suggesting that `other` has to be the same type. You can compare anything to anything. 🙂 

If you want to name the argument something else, feel free to inline disable (using `# rubocop:disable Naming/BinaryOperatorParameterName`) or disable the cop altogether.

**Comment by zverok** [comment]
> There's nothing suggesting that `other` has to be the same type.

Then, what's the meaning of this cop? I believe, the idea was to unify the names for _symmetric_ operators (e.g. those that having `a op b` and `b op a` equally meaningful, though not necessary returning equal values). 

When defining methods like `-`, `+`, `==`, choice of the name is just a waist of thinking, so instead of colling it `operand`, `argument`, `divider` or something, Style Guide wisely suggests to have just `other` ("other similar operand"). 

But for "non-symmetric" methods it even [has an exception](https://github.com/bbatsov/ruby-style-guide#other-arg):

> `<<` and `[]` are exceptions to the rule, since their semantics are different.

I believe that `===` should be in line with the latter two.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.

**Comment by zverok** [comment]
Here you go: https://github.com/rubocop-hq/rubocop/pull/6295

It was just not obvious from team reaction (close → read explanation → reopen silently) whether it is agreed on suggestion.
