### ISSUE TITLE
Automatically inline disable offenses

### ISSUE THREAD

**Issue by brandonweiss** [rubocop-hq/rubocop#4897]
I have an idea for a new feature based on what I found we needed on the large app I work on.

I’ve found auto-generating a config to allow progressive integration into an existing app works really well if it's a small small or medium-sized app. But on a large app, I've found a few issues. This path is predicated on the idea that the config can and will be whittled down over time, but that doesn't always happen. Most people forget it's there so a small group winds up trying to do it, making it take longer. And then on a large app, the config will start with many rules disabled, which while it's being whittled down, allows more offenses to be created without anyone knowing it. I know you can increase the bar at which at a cop is totally disabled when auto-generating, but that still doesn't really solve the problem for certain cops like Metric cops, which are configured with a number. I can easily fix some of the offenses in an auto-generated config, but I'm not going to easily be able to refactor 200 methods that are too complex.

What I want is to be able to automatically inline disable certain offenses. This is great because it stops problems for getting worse. And it moves the visibility of the problem to the file. Now other people will see and be incentivized to fix it.

I wrote a simple script that does this. It takes the offenses listed in a JSON format and then each for file and offenses, figures out the starting and ending line and then inserts a disable and enable comment for that cop.

I'm curious if you'd be interested in adding it to RuboCop as an `--auto-inline-disable` flag or something?

**Comment by Drenmi** [comment]
I've experienced the shortcomings of `--auto-gen-config` myself, and I think this could be a good idea.

Ideally there would be some way to tell automatically generated inline disables from ones that were added manually when there was a legitimate call for it.

**Comment by brandonweiss** [comment]
Awesome!

Ah, interesting. I hadn't thought of it being necessary to tell them apart. I guess I don't ever (or at least not that I can remember) inline-disable something “permanently”. It's always something that I intend to remove eventually. Either a scenario like this, where it's too difficult to fix right now. Or it's a bug in RuboCop that I haven't fixed yet. If I find myself needing to inline-disable something permanently, I usually figure out a way to write it's not necessary to add the disable. Can you give me an example of a scenario where you'd want to permanently disable something inline?

If you're curious, here's roughly [what I've got so far](https://gist.github.com/brandonweiss/976cee89e9fb8a5b01b4b61aebe8f6fa). We just overrode the command with a local script and we intercept the call if it has a flag. We change the format to JSON to get all offenses, do some work to find the ending line because the offenses lists the starting line and the length but not the ending line, then we _very carefully_ insert a comment before the starting line disabling the cop and after the ending line enabling the cop. If there's already a disable/enable comment we merge it with the existing one.

I imagine if this was in RuboCop proper it would work something a bit like `--auto-correct`. When an offense was found instead of correcting it it would wrap the node (or figure out the proper node to wrap) with a comments.

**Comment by Drenmi** [comment]
> Can you give me an example of a scenario where you'd want to permanently disable something inline?

One case is using a DSL prone to false positives within a file that is predominantly Ruby. Additionally, it is sometimes required to disable metrics cops for blocks which can't be broken up due to branching keywords like `next`. Then there are small ones, like `base64` offending `Naming/VariableNumber`.

**Comment by brandonweiss** [comment]
@Drenmi Ah, interesting. That makes sense! Although, I guess a question would be, how is that any different from the current situation? Like, right now people inline-disable blocks both temporarily (for a variety of reasons) and permanently (for a variety of reasons). There isn't a way to tell the two apart—you just have to sort of look at it and know.

This potential feature just does automatically what I would normally do manually. Are you saying more generally, irrespective of this feature, you would just like to be able to demarcate inline-disables? Or are you saying that it wasn't a big deal before, but because this feature could potentially be used to add a lot of inline-disables, that it makes sense to note that they were done in a more automated fashion?

I suppose a comment could just be included above the inline-disable that's similar to the comment at the top of the auto-generated config. Something like “Automatically generated on #{timestamp}”.

**Comment by jonas054** [comment]
This sound a lot like #4355, a pull request that looked promising but was closed due to lack of activity.

**Comment by brandonweiss** [comment]
I'm still thinking about it! I wanted to fully exercise my script and see what worked and what didn't by slowly doing our entire, giant codebase with it. I realized I'd way over-complicated it the first time. I hadn't realized that even if an offense spans multiple lines, you can still inline-disable it with one comment at the end of the line that the offense begins on. I had completely misunderstood and though it required both an enable comment at the beginning and a disable comment at the end.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.

**Comment by TSMMark** [comment]
Hey it's been a few years now, any chance this is something that could be resurfaced?

**Comment by bbatsov** [comment]
Everything's possible as long as there's someone willing to work on it. 😄

**Comment by TSMMark** [comment]
Could you provide some guidance how it should be implemented?

**Comment by jonas054** [comment]
What about the `--disable-uncorrectable` option? Isn't that what you're looking for?

**Comment by TSMMark** [comment]
@jonas054 YES that sounds like exactly what this issue is requesting. Thanks a lot for pointing that out.

For the next person, here's more info: https://docs.rubocop.org/rubocop/usage/auto_correct.html#generating-comments

### Generating comments

```shell
$ rubocop --auto-correct --disable-uncorrectable
```

or

```shell
$ rubocop --auto-correct-all --disable-uncorrectable
```

> You can add the flag --disable-uncorrectable, which will generate # rubocop:todo comments in the code to stop the reporting of offenses that could not be corrected automatically.
