### ISSUE TITLE
Performance/RedundantBlockCall expects yield when proc name is the same as a block argument

### ISSUE THREAD

**Issue by Jamedjo** [rubocop-hq/rubocop#4995]
## Actual behaviour

Similar to https://github.com/bbatsov/rubocop/issues/2986, the following code results in **"Performance/RedundantBlockCall: Use yield instead of lazy_block.call"**:

```ruby
  def outer_method(&some_block)
    something do |some_block|
      some_block.call
    end
  end
```

## Expected behaviour

No warning, or a warning from another cop about conflicting names, or warning against having block in the name.

Since the inner argument is the one being called, `yield` would be incorrect and call the outer block.

Arguably this is a naming problem as they would ideally be named differently, and the second usage is technically a proc rather than a block. It still feels like it shouldn't ask for `yield` to be used here though.

## RuboCop version

```
$ rubocop -V
0.50.0 (using Parser 2.4.0.0, running on ruby 2.3.5 x86_64-darwin15)
```

**Comment by Drenmi** [comment]
A note to @akhramov that the future `Lint/ShadowedArgument` should remember to consider block arguments. 🙂

**Comment by akhramov** [comment]
@Drenmi, good catch!

Surprisingly, `Lint/ShadowingOuterLocalVariable` handles this case. I think we could either

- Tweak `Lint/ShadowingOuterLocalVariable` to work with local variables only
- Rename `Lint/ShadowedArgument` to something like `Lint/ShadowingReassignment` and rename `Lint/ShadowingOuterLocalVariable` to something like `Lint/ShadowingDeclaration`.

From the end-user perspective the first option would be better, I think.

WDYT?

**Comment by bbatsov** [comment]
We're in the process of moving all Performance-related functionality to a standalone library (gem) named `rubocop-performance`. Please, migrate this issue to its issue tracker https://github.com/rubocop-hq/rubocop-performance/issues/
