### ISSUE TITLE
Merge Style/RedundantException and Style/ImplicitRuntimeError 

### ISSUE THREAD

**Issue by asherkach** [rubocop-hq/rubocop#5197]
The [`Style/RedundantException`](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/redundant_exception.rb) and [`Style/ImplicitRuntimeError`](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/implicit_runtime_error.rb) should be merged into one cop with a style parameter. Perhaps `Style/RuntimeError` with (enforced) styles `implicit` and `explicit`? Right now, the cops contradict each other, verifying opposite styles.

--------

## Expected behavior

```
$ cat my_config
Style/RuntimeError:
  EnforcedStyle: implict
$ cat test.rb
raise 'my exception'
raise RuntimeError, 'my exception'
$ bundle exec rubocop test.rb --config my_config
Inspecting 1 file
C

Offenses:

test.rb:2:1: C: Style/RuntimeError: Redundant RuntimeError argument can be removed.
raise RuntimeError, 'my exception'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offenses detected
```

and

```
$ cat my_config
Style/RuntimeError:
  EnforcedStyle: explicit
$ cat test.rb
raise 'my exception'
raise RuntimeError, 'my exception'
$ bundle exec rubocop test.rb --config my_config
Inspecting 1 file
C

Offenses:

test.rb:1:1: C: Style/RuntimeError: Use raise with an explicit exception class and message, rather than just a message.
raise 'my exception'
^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offenses detected
```

## Actual behavior

```
$ cat test.rb
raise 'my exception'
raise RuntimeError, 'my exception'
$ bundle exec rubocop test.rb --only Style/RedundantException,Style/ImplicitRuntimeError
Inspecting 1 file
C

Offenses:

test.rb:1:1: C: Style/ImplicitRuntimeError: Use raise with an explicit exception class and message, rather than just a message.
raise 'my exception'
^^^^^^^^^^^^^^^^^^^^
test.rb:2:1: C: Style/RedundantException: Redundant RuntimeError argument can be removed.
raise RuntimeError, 'my exception'
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected
```

## RuboCop version

```
$ rubocop -V
0.46.0 (using Parser 2.4.0.2, running on ruby 2.2.3 x86_64-darwin16)
```

**Comment by asherkach** [comment]
Note that if this is deemed a good idea, I'm happy to own merging these cops.

**Comment by asherkach** [comment]
Ping. Is there any interest in merging these cops? If so, I'm happy to do so.

**Comment by mikegee** [comment]
Seems like a great idea to me. 👍 

Can you confirm these two cops only enforce the styles you've described here? (Many cops are multi-faceted.)

**Comment by bbatsov** [comment]
I'm fine with the proposal.

There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
