### ISSUE TITLE
All Lint/Alignment Cops moved to Layout namespace

### ISSUE THREAD

**Issue by garettarrowood** [rubocop-hq/rubocop#5207]
We currently have at least 11 Cops that deal with alignment.  Most of those are already specified in the `Layout` namespace. Those are:

1. `Layout/AlignArray`
1. `Layout/AlignHash`
1. `Layout/AlignParameters`
1. `Layout/ElseAlignment`
1. `Layout/SpaceAroundOperators` which has an `AllowForAlignment`configuration.
1. `Layout/SpaceBeforeFirstArg` which has an `AllowForAlignment`configuration.
1. `Layout/RescueEnsureAlignment`

However, there are 4 `Lint` namespaced cops that also deal with alignment.  Those are:

1. `Lint/BlockAlignment`
1. `Lint/DefEndAlignment`
1. `Lint/ElseLayout` *
1. `Lint/EndAlignment`

I purpose we move the remaining `Lint` cops over to the `Layout` namespace.

* `Lint/ElseLayout` registers an offense when an `else` has trailing body after it and asks if the author meant to use `elsif`.  Perhaps this doesn't qualify as alignment, but it appears this cop effectually notifies the author that her/his working code is not aligned properly. It seems like more than rubocop can ascertain to suggest flawed logic vs a layout issue. Regardless of classification, this is a layout issue.  Should this be moved, it could possibly be named `Layout/ElseBodyAlignment` to differentiate it from the `Layout/ElseAlignment` cop.

This issue could be broken into 4 separate PRs. One to move each Cop.

**Comment by bbatsov** [comment]
I think we did it this way, as they are lint checks in MRI itself, but this has to be confirmed. I guess the point is that sometimes the alignment problem you'd get is actually a result of the fact you didn't nest something properly and you changed the meaning of the code.

**Comment by Darhazer** [comment]
Currently only `ElseLayout` is in the `Lint` namespace, the other 3 are moved to the `Layout` department

**Comment by garettarrowood** [comment]
@Darhazer - Thanks! In light of this, I will close the issue.
