### ISSUE TITLE
Style/MixinUsage in default rails app

### ISSUE THREAD

**Issue by printercu** [rubocop-hq/rubocop#5237]
Every fresh rails app has `bin/{setup,update}` with toplevel `include FileUtils`.

This cop does not provide autofix, and to fix this warning it requires remastering this files, which results in conflicts when updating rails.

Should this files be added to default exclude list for this cop?

**Comment by Drenmi** [comment]
To be addressed in [rubocop-rails](https://github.com/rubocop-hq/rubocop-rails).
