### ISSUE TITLE
Rails/HasManyOrHasOneDependent with paranoia gem

### ISSUE THREAD

**Issue by printercu** [rubocop-hq/rubocop#5285]
Hi!

Do you have any suggestions how to use gems providing soft-delete (like paranoia) with HasManyOrHasOneDependent cop: I think it's usual to not provide `dependent` option to `has_many` when parent is soft-deletable. Is it supposed just to use `rubocop:disable` for offences in such cases?

## RuboCop version

```
$ rubocop -V
0.52.0 (using Parser 2.4.0.2, running on ruby 2.4.1 x86_64-darwin16)
```

**Comment by bbatsov** [comment]
We're in the process of moving all Rails-related functionality to a standalone library (gem) named `rubocop-rails`. Please, migrate this issue to its issue tracker https://github.com/rubocop-hq/rubocop-rails/issues/
