### ISSUE TITLE
Move Corrector logic out of `PercentLiteral` mixin

### ISSUE THREAD

**Issue by garettarrowood** [rubocop-hq/rubocop#5303]
With the addition of `Corrector` classes introduced in #5269 , all correcting logic should be moved out of mixins to achieve a clear separation of concerns.

`PercentLiteral`'s `correct_percent` method, and all related correction helper methods, should be moved into an existing or new `Corrector` class.

**Comment by ryanhageman** [comment]
Is this still an issue?

**Comment by garettarrowood** [comment]
@ryanhageman - Indeed it is. Ideally, we move all autocorrect logic out of `mixin`s and `cops` and let our `Corrector` classes handle it.
