### ISSUE TITLE
Exclude Emoji from ASCII comment requirements.

### ISSUE THREAD

**Issue by envygeeks** [rubocop-hq/rubocop#5310]
I get that comments should be written in English (or ASCII,) a subset of UTF-8, but Emoji's neither get translated, or adjusted, and are often skipped and overlooked as they fall within the private space of Unicode.  Which means no matter what language a comment is going to, an emoji is an emoji, a universal expression.

**Comment by envygeeks** [comment]
I'm happy to look into this and possibly ship a pull request if this is accepted.

**Comment by pocke** [comment]
Seems good to me, but I think we need a discussion. I have two issues with the proposal.

First, probably it should be optional. There may be people who do not like emoji in comments.

Second, the cop name will be inappropriate. It is a bit strange that `Style/AsciiComment` cop allows non-ASCII characters (emoji).
But I'm not sure what the cop name should be. Maybe it should be `Style/EnglishComment`, but the cop does not check English grammar, so it seems inappropriate also.


What do you think?

**Comment by envygeeks** [comment]
IMO this rule should have never existed because it's particularly prone to being wrong.  Take "Hola Mundo", it's Spanish, and would pass under both rule names.  ASCII neither guarantees, nor promises English, and unless EnglishComment plans to actually test words to ensure they are English, it's prone to just being wrong. Here we flat out disable it because of that, and because we consider it insulting.

My offer to fix this was surfaced from a client, and to ease the pain of the community.

**Comment by deivid-rodriguez** [comment]
I always disable this cop as well since it finds more false than true positives. I expressed [my opinion](https://github.com/bbatsov/rubocop/pull/72#issuecomment-65285436) in the PR introducing this cop.

**Comment by gafrom** [comment]
Sometimes comments do require emotions and it is a natural way to express those with emoji.

@pocke, will the request find its way further?

**Comment by pocke** [comment]
Sorry for my late reply.

I think `ExcludeEmoji` or some option is good feature.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
