### ISSUE TITLE
Metrics/BlockLength to act as Metrics/ClassishLength for modules, classes, and structs

### ISSUE THREAD

**Issue by RKushnir** [rubocop-hq/rubocop#5338]
I suggest that in some cases where a block is occurred, instead of `Metrics/BlockLength` cop, the appropriate `ClassLength` or `ModuleLength` cop is applied. Reason is the fact that the following two definitions are equivalent:
```ruby
class Foo
end

Foo = Class.new do
end
```
So it seems inconsistent that you have different limits depending on how you create a class. The same applies for modules, and for `Struct`s(since [the ruby docs](http://ruby-doc.org/core-2.5.0/Struct.html) suggest using the block form).

PS. I don't know the situation with `MethodLength` cop, probably, there's a similar case for `define_method` and friends.

**Comment by JelF** [comment]
> So it seems inconsistent that you have different limits depending on how you create a class

How can linter know that `Class` is a `::Class`?

**Comment by JelF** [comment]
> @JelF Rubocop has the whole file available (and only one file) while it is evaluating. Nesting a Class within a namespace will be visible to Rubocop.

It is not how it works

```
module Foo
  Bar = Class.new do
  end
end

module Bar
  Class = Object # Can be defined in any file

  Baz = Class.new do
  end
end

p [Foo::Bar.class, Bar::Baz.class]
# => [Class, Object]
```

**Comment by mikegee** [comment]
Good point. Let's make a cop to prevent defining a constant called "Class". 😄

**Comment by JelF** [comment]
> Good point. Let's make a cop to prevent defining a constant called "Class". smile

At least community shoud consider it wrong. As for me, i see nothing wrong with, i.e. `MyLibrary::Class`
