### ISSUE TITLE
Lint/Void documentation doesn't adequately explain changed behavior in 72fb0c2e

### ISSUE THREAD

**Issue by dmolesUC** [rubocop-hq/rubocop#5379]
Under RuboCop 0.47, the following code was considered valid:

```
  def initialize(*args)
    path, *myargs = super(*args)
    @path = ::XML::XXPath.new(path)
    myargs
  end
```

Under RuboCop 0.52, it produces:

```
Lint/Void: Variable myargs used in void context.
        myargs
        ^^^^^^
```

The initializer in question is in a subclass of [XML::Mapping::SingleAttributeNode](http://multi-io.github.io/xml-mapping/XML/Mapping/SingleAttributeNode.html). The XML::Mapping library makes heavy use of a pattern in which superclasses strip leading arguments before leaving the remaining arguments to be processed by subclasses.

Contra #4153, it is not *strictly* impossible to use a return value from an initializer; it's only impossible when the initializer is invoked via `new()`.

Similarly, one can get a return value from a setter via a call to `super`:

```
class Foo
  attr_reader :foo
  
  def initialize
    @foo = 'foo'
  end

  def foo=(value)
    old_foo = @foo
    @foo = value
    old_foo
  end
end

class Bar < Foo
  attr_reader :baz
  
  def foo=(value)
    @baz = super
  end
end

bar = Bar.new
puts "before: foo = #{bar.foo}, baz = #{bar.baz}"
corge = bar.foo = 'qux'
puts "after: corge = #{corge}, foo = #{bar.foo}, baz = #{bar.baz}"

# =>
# before: foo = foo, baz = 
# after: corge = qux, foo = qux, baz = foo
```

I do agree that in general this would be considered bad style, and the appropriate fix in my case is to explicitly disable Lint/Void just for this method with its oddball use case. But in order to understand why the cop was now complaining, I had to dig through its commit history (finding 72fb0c2e) to see what had changed since version 0.47.

## Expected behavior

- code is still valid, or, failing that, the error message, or at least the Lint/Void documentation, explains explicitly that initializer and setter return values are lost *in most cases*.

## Actual behavior

- not at all clear what "void context" is or why this code is an example of it.

## RuboCop version

```
$ bundle exec rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.1 x86_64-darwin16)
```

**Comment by lamont-granquist** [comment]
Also confusingly the value of `super` for an accessor (at least `:[]=`) is the proper return value.

```
[1] pry(main)> class Foo
[1] pry(main)*   def []=(k,v)
[1] pry(main)*     42
[1] pry(main)*   end
[1] pry(main)* end
[6] pry(main)> class Bar < Foo
[6] pry(main)*   def []=(k,v)
[6] pry(main)*     puts super
[6] pry(main)*     44
[6] pry(main)*   end
[6] pry(main)* end
[7] pry(main)> a = Bar.new
=> #<Bar:0x007f88ef3ef650>
[8] pry(main)> a[2]=3
42
=> 3
```

Based on the lack of uniformity of setters returning the return value or not, it seems like this cuts more the other direction and it should be a best practice to always set an explicit return value, because this was very confusing to track down.
