### ISSUE TITLE
Handle an application root directory

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop#5494]
Sometimes RuboCop's behaviour depends on files that are other than analysis target file.
For example:

- `Gemfile.lock` #5473
- `config/environments/` #5455
- `.ruby-version`
  - RuboCop searches `.ruby-version` recursively. #5326 
- Probably we have other dependencies.

The dependencies maybe does not work well in a child directory. For example:

```
$ cd app_root_dir/
$ rubocop # It works.

$ cd child_dir/
$ rubocop # It may be broken something.
```

So, I think RuboCop need to handle an application root directory.

--------

## Expected behavior

RuboCop finds the application root directory that is analysis target. Maybe RuboCop can decide the root directory if the directory has `.rubocop.yml`.
And RuboCop finds files that are necessary for analysis with the directory.

I guess we should not change the finding `.ruby-version` behaviour. Because it works well, and it is same behaviour as rbenv.

## Actual behavior

RuboCop does not know the root directory, so it confuses in a child directory sometimes.

## Steps to reproduce the problem

N/A

## RuboCop version

master

**Comment by tchia04** [comment]
I face a similar issue as well.
If I don't have a Gemfile.lock file, rubocop won't run.

```
$ rm Gemfile.lock
16:24:50 tonyc@greenapple:~/testr  ruby-2.5.5
$ rubocop
Traceback (most recent call last):
	9: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
	8: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
	7: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/bin/rubocop:23:in `<main>'
	6: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/bin/rubocop:23:in `load'
	5: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/rubocop-0.67.2/exe/rubocop:13:in `<top (required)>'
	4: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler.rb:430:in `read_file'
	3: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler/shared_helpers.rb:118:in `filesystem_access'
	2: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler.rb:431:in `block in read_file'
	1: from /Users/tonyc/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler.rb:431:in `open'
/Users/tonyc/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/bundler.rb:431:in `initialize': No such file or directory @ rb_sysopen - /Users/tonyc/testr/Gemfile.lock (Errno::ENOENT)
```

I need a dummy Gemfile.lock file to run any rubocop command which I can create using "bundle init; bundle lock" 

IMHO, rubocop should handle the missing Gemfile.lock more gracefully by not displaying a stack trace but rather say it's not able to infer the ruby-version or whatever the reason it's trying to look for the Gemfile.lock file. 

Couldn't you get the ruby version using "ruby --version"? 

According to https://github.com/rubocop-hq/rubocop/issues/5473, it seems it's needed for the rail development but there are other use cases that doesn't have rail installed or I just wanted to use rubocop to check my Rakefile or *.rake which is not related to rails
