### ISSUE TITLE
Partial autocorrection for Metrics/LineLength

### ISSUE THREAD

**Issue by dkniffin** [rubocop-hq/rubocop#5537]
This isn't quite an issue, but I didn't know where else to ask it. Sorry.

I want to make a PR to add partial support for autocorrecting `Metrics/LineLength`, just in the cases where the long line is a comment.

Before I make that PR, I have two questions about this:
- Would something like this be approved?
- Is it possible to write a “partial autocorrector” function?

**Comment by jackkinsella** [comment]
I, for one, would absolutely love if this existed — in fact, I visited this repo on Github today just to check if this features was supported.

**Comment by Drenmi** [comment]
> Would something like this be approved?

Very likely. It is possible that auto-correction might be disabled by default, but I don't see any reason why we couldn't put it in. 🙂 

> Is it possible to write a “partial autocorrector” function?

If you limit the scope, like you said, to long comment lines, I think it is very possible. 👍 

I hope that answered your questions. I'm closing this issue as answered. Please go ahead and open a PR if you want to work on it. 🙂
