### ISSUE TITLE
Question: Is there a way to set AutoCorrect for all cops to true globally?

### ISSUE THREAD

**Issue by klukacsy** [rubocop-hq/rubocop#5545]
Based on the link below, there are 9 cops which have AutoCorrect option set to false by default.
To enable this option for these, we can set AutoCorrect: true in our .rubocop.yml file for each of these cops.

Question: Is there a way how we can set the AutoCorrect setting for all cops globally to true?

--------

## Expected behavior

Set AutoCorrect to true on a per-cop basis in .rubocop.yml file OR set AutoCorrect to true globally.

## Actual behavior

Set AutoCorrect to true on a per-cop basis in .rubocop.yml file.

**Comment by jonas054** [comment]
The PR #4816 which was released in `v0.51.0` added configuration of common parameters on department level. That should work for `AutoCorrect`. But there's currently no way to globally set `AutoCorrect` for all cops.
