### ISSUE TITLE
Is there a cop that recommends native Ruby methods over regexes?

### ISSUE THREAD

**Issue by ashmaroli** [rubocop-hq/rubocop#5568]
This is either a `question` or a `feature-request`..

The cop I'm inquiring about will flag the following code and provide recommendations accordingly..:
```ruby
string.gsub(%r!/\z!, "")
# => Prefer using `String#chomp(str)` to remove substring `str` at the end of a string over `String#gsub` and regex
```
```ruby
string.split(%r!\s+!).map(&:strip)
# => Unnecessary processing. `String#split` without args strips array elements of whitespace by default.
```

etc, etc..

**Comment by mikegee** [comment]
Those seems like good ideas for cops, and we have some similar cops already.
 [`Performance/StringReplacement`](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/performance/string_replacement.rb) and [`Performance/StartWith`](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/performance/start_with.rb), for instance.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
