### ISSUE TITLE
auto-correct of match? should call match? on regular expression

### ISSUE THREAD

**Issue by JoeCohen** [rubocop-hq/rubocop#5572]
My code has 
_variable_.match(_regexp_)
which RuboCop autocorrects to
_variable_.match?(_regexp_)

When executed, this will blow up if _variable_ is nil:
```ruby
undefined method `match?' for nil:NilClass
```

The auto-correct could be improved if it could recognize when the `match` argument is a regexp, and reverse the caller and the argument.  In other words, if the autocorrector sees
>_something_.match(_regexp_)

that should be corrected to
>_regexp_.match?(_something_)

## Expected behavior

Auto-correct 
>_something_.match(_regexp_)

to
>_regexp_.match?(_something_)

## Actual behavior

Auto-corrects
>_something_.match(_regexp_)

to
>_something_.match(_regexp_)

## Steps to reproduce the problem

Auto-correct a file which includes 
```ruby
def foo
  if x.match(/re/)
    do_something
  end
end
```

## RuboCop version
```
$ rubocop -V
0.52.1 (using Parser 2.4.0.2, running on ruby 2.4.1 x86_64-linux)
```

**Comment by Drenmi** [comment]
> When executed, this will blow up if `variable` is `nil` [...]

I assume you mean "if `variable` is a string"? Since `nil` will result in an error for both `#match` and `#match?`.

We could, upon detecting a regexp literal argument, try to flip the expression, but it would be semantically different from the original.

**Comment by adamrdavid** [comment]
Wondering if this belongs in this issue, but I just ran into an unsafe autocorrect:
`foo =~ /bar_/` # This returns nil if foo is a hash or an array
was autocorrected to:
`/bar_/.match?(foo)` # This returns `TypeError: no implicit conversion of Array into String`

I'm not sure how safe autocorrect is intended to be, but this was definitely a surprise.
