### ISSUE TITLE
[Suggestion] Appveyor Rspec test reporter

### ISSUE THREAD

**Issue by thomthom** [rubocop-hq/rubocop#5718]
Just wanted to mention that the `appveyor-worker` gem now support RSpec in addition to Minitest for it's test reporting. It allows the execute tests to appear in the Test summary on Appveyor.

See relate issue: https://github.com/ukoloff/appveyor-worker/issues/1

I've hooked it up with the RuboCop extension I'm working on:
https://github.com/SketchUp/rubocop-sketchup

You can see an example build here:
https://ci.appveyor.com/project/thomthom/rubocop-sketchup

Working fine so far. Just thought I'd mention it in case you wanted to try it out for RuboCop's own Appveyor integration.

To enable it:

Add `gem "appveyor-worker", '~> 0.2` to `Gemfile`.

Then add to `.rspec`

```
--require appveyor/worker
```

**Comment by SeanPrashad** [comment]
Hey guys! Is this bug still available?

**Comment by thomthom** [comment]
I see there has been work done that refer to this issue. Might it be closed? Only thing that makes we wonder if it shouldn't is that AppVeyor appear to only build 2.5?

https://ci.appveyor.com/project/bbatsov/rubocop

**Comment by koic** [comment]
I will close this issue because RuboCop has been migrated from AppVeyor to GitHub Actions. Thank you.
https://github.com/rubocop-hq/rubocop/pull/7893
