### ISSUE TITLE
MemoizedInstanceVariableName should allow variable names starting with underscore

### ISSUE THREAD

**Issue by legendetm** [rubocop-hq/rubocop#5798]
When memoizing values, then we use **underscore** to indicate that this variable is **only used for caching** and should be used elsewhere. If there is no underscore, then we know there is setter/getter methods or this variable may be used directly in other places.

## Expected behavior

Expect `MemoizedInstanceVariableName` not to trigger offence for `@_foo`.

## Actual behavior

`MemoizedInstanceVariableName` triggers offence for `@_foo`.

## Steps to reproduce the problem
```
def foo
  @_foo ||= compute_foo
end
```
## RuboCop version

```
$ rubocop -V
0.54.0 (using Parser 2.5.1.0, running on ruby 2.4.2 x86_64-darwin16)
```

**Comment by Drenmi** [comment]
We can probably have a configuration option for those who prefer prefix underscore.

> [T]here is setter/getter methods or this variable may be used directly in other places.

All of this seems awkwardly incompatible with the idea of a memoization method. 😅

**Comment by legendetm** [comment]
We use `@_` if the variable is used only for memoization, e.g. caching internal calculations.

You see this a lot in Rails project as well, e.g. https://github.com/rails/rails/blob/master/activerecord/lib/active_record/transactions.rb

**Comment by Drenmi** [comment]
> You see this a lot in Rails project as well, e.g. https://github.com/rails/rails/blob/master/activerecord/lib/active_record/transactions.rb

In none of the cases does the instance variable share a name with the method though.

Either way, a configuration option would be fine.

**Comment by Drenmi** [comment]
Support added in #5844.
