### ISSUE TITLE
Incorrect number of inspected files

### ISSUE THREAD

**Issue by revolter** [rubocop-hq/rubocop#5822]
## Expected behavior

It should inspect all the passed files.

## Actual behavior

It inspects only a part of the files.

## Steps to reproduce the problem

Running:

```bash
bundle exec rubocop Gemfile fastlane/globals.rb Podfile fastlane/Deliverfile fastlane/Pluginfile fastlane/Gymfile fastlane/Fastfile fastlane/Appfile Brewfile
```

prints:

> Inspecting 6 files
> ......
>
> 6 files inspected, no offenses detected

but it should inspect all the 9 files instead.

Running only `bundle exec rubocop` correctly inspects all the 9 files.

## RuboCop version

```
0.55.0
```

**Comment by jgrau** [comment]
On `0.56.0` running `rubocop` only inspects 2 files while it previously inspected all files (hundreds).

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/rubocop/issues/4247

We made a breaking change that dealt with some nasty legacy - some file types were hardcoded in RuboCop and we wanted to make everything configurable. People who had modified the default Include/Exclude patterns are affected by this change.

**Comment by jgrau** [comment]
Awesome. That fixed my issue.
