### ISSUE TITLE
Prefer using slashes in Rails/FilePath cop

### ISSUE THREAD

**Issue by sunny** [rubocop-hq/rubocop#5823]
Under Windows, `Rails.root.join('app', 'models', 'goober')` is equal to `Rails.root.join('app/models/goober')`. They both return a string with forward slashes.

I'm in favor of always using the simple slashes and deprecating the previous join. The current cop suggests this is

> to avoid bugs on operating system that don't use '/' as the path separator

but there is no evidence of such bugs.

More discussion of the issue here: https://twitter.com/tenderlove/status/842064491936280576

![c6-l0cfwyaa6rvc](https://user-images.githubusercontent.com/132/39248695-12eb01cc-489d-11e8-8e47-93f056f0bd2a.jpg)

--------

## Expected behavior

[Rails/FilePath](https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/rails/file_path.rb) should treat as:

```rb
# bad
Rails.root.join('app', 'models', 'goober')

# good
Rails.root.join('app/models/goober')
```

## Actual behavior

Today it treats the following as:

```rb
# good
Rails.root.join('app', 'models', 'goober')

# bad
Rails.root.join('app/models/goober')
```

**Comment by roberts1000** [comment]
Good find.  FWIW, we disable this cop at our shop and use the `"#{Rails.root}/app/models/goober"` format.

**Comment by Drenmi** [comment]
At the very least the style should be configurable.

**Comment by juanxcerv** [comment]
When trying to integrate this change we discovered that there is a difference in how absolute paths are resolved with each approach. 

For example:
```irb
path = File.expand_path('./app/models/user.rb')
# => "/Users/juancervantes/Desktop/synchroform/app/models/user.rb"
Rails.root.join('app', 'models', path)
# => #<Pathname:/Users/juancervantes/Desktop/synchroform/app/models/user.rb>
Rails.root.join("app/models/#{path}")
# => #<Pathname:/Users/juancervantes/Desktop/synchroform/app/models//Users/juancervantes/Desktop/synchroform/app/models/user.rb>
```

We decided to stick with the separate arguments for the sake of consistency.
