### ISSUE TITLE
Don't show `Style/Documentation` for `private_constant` or similar methods

### ISSUE THREAD

**Issue by AlexWayfer** [rubocop-hq/rubocop#5831]
## Expected behavior

No offenses from `Style/Documentation` for modules with class and `private_constant` method.

## Actual behavior

There is offense.

## Steps to reproduce the problem

```ruby
module Foo
  class Bar
  end

  private_constant :Bar
end
```

## RuboCop version

```
$ rubocop -V
0.55.0 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-linux)
```

**Comment by bquorning** [comment]
I’d just add a `:nodoc:` comment…
```rb
module Foo # :nodoc:
  class Bar
  end

  private_constant :Bar
end
```

**Comment by Drenmi** [comment]
I think this request is legitimate, however it is unlikely we will have time to work on it. Since the solution suggested by @bquorning seems like a very reasonable fix, I will close this issue to reduce noise in the tracker. Feel free to open a PR to fix this if keen. 🙇

**Comment by AlexWayfer** [comment]
> it is unlikely we will have time to work on it any time soon

I think it's not a reason for issue closing. Issue is still here.

> Since the solution suggested by @bquorning seems like a very reasonable fix

It's work-around, not fix.

> I will close this issue to reduce noise in the tracker

Please, use another tools for issues management. You can use projects or labels. But issue not resolved, so it should not be closed. Like… "help wanted" or something else, if you don't want to make this. But somebody might want.

I know, the closed issue can be found by search, but it's incorrect status for me anyway. And, I guess, for other people too.
