### ISSUE TITLE
Rubocop - Style/PercentLiteralDelimiters conflict

### ISSUE THREAD

**Issue by thornbird** [rubocop-hq/rubocop#5885]
```
$ rubocop -V
0.52.0 (running on ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin17])
```

Rubocop notifies me to:
`only: [:index, :create]` -> `only: %i[index create]` for the auto-correct

And it did the auto-correction for me:
[Corrected] Style/SymbolArray: Use %i or %I for an array of symbols.

But then it raises error when I want to commit the change:
C: Style/PercentLiteralDelimiters: `%i`-literals should be delimited by `(` and `)`

I should change `only: %i[index create]` to `only: %i(index create)` manually.

The auto-correct and the error does not match.

**Comment by Drenmi** [comment]
Not reproducible in 0.57.1.
