### ISSUE TITLE
Document how to use the parallel flag with the Rake integration

### ISSUE THREAD

**Issue by blkperl** [rubocop-hq/rubocop#5942]
I would like to know how to use the `rake rubocop` task with the parallel flag without breaking the `auto_correct` subtask.

```ruby
 RuboCop::RakeTask.new(:rubocop) do |task|
   task.patterns = [root]
   task.fail_on_error = true
   task.options = %w[--parallel]
 end
```

```
$ rake rubocop:auto_correct
Running RuboCop...
-P/--parallel can not be combined with --auto-correct.
```

I was following the docs here: https://rubocop.readthedocs.io/en/latest/integration_with_other_tools/#rake-integration

## Expected behavior

You should be able to use the `--parallel` flag in the Rake task without breaking the auto_correct task

## Actual behavior

You get the error: `-P/--parallel can not be combined with --auto-correct.`

## Steps to reproduce the problem

Add the following to your rake task

```ruby
   task.options = %w[--parallel]
```

The run `rake rubocop:auto_correct`

## RuboCop version

```
$ rubocop -V
0.54.0 (using Parser 2.5.0.5, running on ruby 2.1.9 x86_64-darwin17.0)
```

**Comment by glennpratt** [comment]
I think context of the desired task name in the supplied block would allow a cleaner workaround... or just ignore the parrallel option when using auto correct.

HACKY WORKAROUND
```ruby
    if caller.grep(/setup_subtasks/).empty?
      task.options = %w[--parallel]
    end
```

**Comment by rrosenblum** [comment]
As far as I know, there isn't a way to add `parallel` without breaking the `auto_correct` task. I tried digging into this a while back to not create the `auto_correct` task if `parallel` is specified, but the tasks are generated before we have access to see the options.

**Comment by terylmiller** [comment]
Remove

> As far as I know, there isn't a way to add `parallel` without breaking the `auto_correct` task. I tried digging into this a while back to not create the `auto_correct` task if `parallel` is specified, but the tasks are generated before we have access to see the options.
> 
> One work around would be to modify the method signature of of `RuboCop::RakeTask.new` to look for a create auto-correct task argument.

**Comment by jaredbeck** [comment]
Maybe this can be closed in favor of https://github.com/rubocop-hq/rubocop/issues/6495?
