### ISSUE TITLE
Layout/ElseAlignment failing to move body of conditional & end to correct indent level

### ISSUE THREAD

**Issue by tgaff** [rubocop-hq/rubocop#5947]
The following looks OK to mine eyes:
```ruby 
      fake_context = if chunks.include?('fake')
        {
          result_status:                    200,
          field1:                           '1'
        }
      else
        {
          result_status:                    200,
          field1:                           'something else',
        }
      end
```

But rubocop disagrees (OK). ` C: [Corrected] Layout/ElseAlignment: Align else with if.`
It then converts it to this:

```ruby
      fake_context = if chunks.include?('fake')
        {
          result_status: 200,
          field1:        '1'
        }
                     else
        {
          result_status: 200,
          field1:        'something else',
        }
      end
```

That seems worse... Note the location of the *else* and the *end*.  At this point if I run `rubocop -a` again it detects that the `end` is out of position

`W: Layout/EndAlignment: end at 47, 6 is not aligned with if at 37, 21.`  but it cannot fix this one.
The inability to fix the `end` might be a secondary bug tied to this.

--------

## Expected behavior
It should change the code to look like this: 
```ruby
      fake_context = if chunks.include?('fake')
                       {
                         result_status: 200,
                         field1:        '1'
                       }
                     else
                       {
                         result_status: 200,
                         field1:        'something else',
                       }
                     end
```

## Actual behavior
It changes it to this:
```ruby
      fake_context = if chunks.include?('fake')
        {
          result_status: 200,
          field1:        '1'
        }
                     else
        {
          result_status: 200,
          field1:        'something else',
        }
      end
```

## Steps to reproduce the problem

Paste the above into a ruby file and execute `rubocop -a`

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.55.0 (using Parser 2.5.1.0, running on ruby 2.3.7 x86_64-darwin17)
```

Also tried master `Using rubocop 0.56.0 (was 0.55.0) from git@github.com:rubocop-hq/rubocop.git (at master@be6eba9)`

**Comment by Drenmi** [comment]
Check your configuration file. `Layout/EndAlignment` is disabled by default. The indentation of the conditional bodies are handled by `Layout/IndentationWidth`, but this might be in relation to the `end`, so unless it is corrected first, it might not be picked up.

Here's what you get with default configuration and `Layout/EndAlignment` enabled:

```sh
Offenses:

tmp.rb:2:3: C: [Corrected] Layout/IndentationWidth: Use 2 (not -13) spaces for indentation.
  { ...
  ^
tmp.rb:6:1: C: [Corrected] Layout/ElseAlignment: Align else with if.
else
^^^^
tmp.rb:9:3: C: [Corrected] Layout/IndentationWidth: Use 2 (not -13) spaces for indentation.
  { ...
  ^
tmp.rb:11:1: W: [Corrected] Layout/EndAlignment: end at 11, 0 is not aligned with if at 1, 15.
end
^^^

1 file inspected, 4 offenses detected, 4 offenses corrected
```

**After:**

```ruby
fake_context = if chunks.include?('fake')
                 {
                   result_status:                    200,
                   field1:                           '1',
                 }
               else
                 {
                   result_status:                    200,
                   field1:                           'something else',
                 }
               end
```

**Comment by tgaff** [comment]
Hi @Drenmi, thanks for the quick reply.

`Layout/EndAlignment` is configured to `Exclude` several files, but not this one - presumably that means it's in the default of off for this file?  
Further `Layout/IndentationWidth` is disabled in a secondary config I hadn't looked at before.


I ran again without any rubocop.yml and get this:

```ruby
      fake_context = if chunks.include?('tenantonly')
                       {
                         result_status: 200,
                         tenant_id:     '1'
                       }
                     else
                       {
                         result_status:                    200,
                         field1:                        'something else',
                       }
      end
```

That's definitely better than what I got before, but still doesn't quite match the style guide.  I'm guessing the `Layout/EndAlignment` problem is considered a bug (although couldn't find it in issues).  If so, that makes this a duplicate.  

Thanks!

**Comment by Drenmi** [comment]
@tgaff Could you provide the output from RuboCop from your second run?
