### ISSUE TITLE
Exclude files in .gitignore

### ISSUE THREAD

**Issue by krisleech** [rubocop-hq/rubocop#595]
I think this would be a nice feature, the easiest implimention would be to run the `rubocop.yml` through erb so that you could have something like:

```
 Excludes:
   <% `git whatever`.each_line do |path| %>
    - <%= path %>
   < % end %>
```

I'd be happy to look at a PR if you think this is useful.

**Comment by kowal** [comment]
@bbatsov #1151 is closed now. Does it mean that excluding files form `.gitignore` won't be supported any time soon?

**Comment by kowal** [comment]
@yujinakayama just wanted to ask if excluding files from `.gitignore` is somewhere in your roadmap? 

thanks

**Comment by AlexWayfer** [comment]
I think this issue should be re-opened due to closed #1151.

**Comment by AlexWayfer** [comment]
Please, @bbatsov or @yujinakayama

**Comment by bbatsov** [comment]
PRs welcome. :-) I guess we're back to the erb idea, as it seems unlikely we'll ever move away from yml.

**Comment by AlexWayfer** [comment]
I'm not sure about ERB or Regexps in YAML, but I think, that files from `.gitignore` can be excluded by default. If somebody will want to include them — we can make an option later, but it doesn't seem normal.

**Comment by kisai** [comment]
I know this is closed, but what about files in `.git/info/exclude`, or more generally `$GIT_DIR/info/exclude` ?

this file is local to the repository clone, so is available for individual clones only. is described in the [official git documentation](https://git-scm.com/docs/gitignore)

I'm using it to exclude a file that I use to help me with my personal workflow, that the rest of the team doesn't want on the repo.

**Comment by AlexWayfer** [comment]
I'm using global gitignore, because files and directories specific for me are local. It's uncomfortable to duplicate the same paths in relatives `.git/info/exclude`.

**Comment by jonas054** [comment]
I'll implement the ERB idea, and push it as a solution for this issue.

**Comment by sandstrom** [comment]
In case anyone finds this issue because they want to ignore all files/directories from .gitignore automatically, here is the relevant link for how to do it:

https://docs.rubocop.org/rubocop/1.27/configuration.html#pre-processing

**Comment by maxim** [comment]
The comment by @sandstrom links to an older version of rubocop docs. It has since been updated with a fix for ignored directories:

https://docs.rubocop.org/rubocop/configuration.html#pre-processing

**Comment by AlexWayfer** [comment]
Just be careful that if there are no ignored files (`git status --ignored --porcelain` returns nothing), like in CI, empty `AllCops/Exclude:` will cause an internal RuboCop error. In such case you should additionally wrap this cycle into some condition.
