### ISSUE TITLE
Proposed Cop: No hardcoded IP Addresses

### ISSUE THREAD

**Issue by tibbon** [rubocop-hq/rubocop#5973]
I'd like to propose an IP address cop. I don't care if it's disabled by default. If people like the idea, I'm totally up for writing the code for it myself. Should work for IPv4 and IPv6 addresses. Perhaps if we get fancy with it there could be some way to allow one type of IP address, but not the other (although I can't think of a real use case). 

IP addresses being fixed in your code is generally a quick way to make something that's non-reusable, brittle, requires a new commit/deploy when the IP changes instead of ENV configuration/relaunch, and to have a failed deploy because something changed. 

This cop would raise a Rubocop failure if it finds any valid IPv4 or IPv6 address in the code.

**Comment by bbatsov** [comment]
Fine by me.
