### ISSUE TITLE
Optional ruby version forcing

### ISSUE THREAD

**Issue by mensfeld** [rubocop-hq/rubocop#5995]
When I analyze an old project with rubocop (historical reasons), that has a ruby-version file pointing to 2.0 I get following exception:

```
Error: Unsupported Ruby version 2.0 found in `.ruby-version`. 2.0-compatible analysis was dropped after version 0.50.
Supported versions: 2.1, 2.2, 2.3, 2.4, 2.5
```

It happens due to the content of `.ruby-version` file.

Is there a way to tell rubocop to pick the lowest (or any) version that is supported instead of rising exception in case an unsupported ruby version is detected?

**Comment by tom-lord** [comment]
I can think of one easy way:

- Add `rubocop` to the `Gemfile`
- `bundle install`
- `bundle exec rubocop`

**Comment by tom-lord** [comment]
Or, switch ruby version via whatever tool you're using - e.g. `rbenv local 2.0`, then `gem install rubocop` will not install an invalid version.

In this case, for example, note that [`v0.50.0`](https://rubygems.org/gems/rubocop/versions/0.5o.0) specifies a dependency of ruby `>= 2.0.0`, whereas [`v0.51.0`](https://rubygems.org/gems/rubocop/versions/0.51.0) specifies a dependency of ruby `>= 2.1.0`.

**Comment by mensfeld** [comment]
@tom-lord thank you for your answer. Unfortunately I cannot add rubocop as a dependency (read only) and I use rubocop that is installed somewhere else.

> Or, switch ruby version via whatever tool you're using - e.g. rbenv local 2.0, then gem install rubocop will not install an invalid version.

I run Rubocop from Ruby `2.5.1`, the problem is that the `.ruby-version` within project directory is used to determne ruby version for the parser, despite the fact that I run rubocop from a different version.

**Comment by tom-lord** [comment]
>  Unfortunately I cannot add rubocop as a dependency (read only)

What do you mean? I'm not saying you need to `git push` the updated `Gemfile` into the master branch, I'm just saying you could add it locally on your machine. Any project forking/branches/etc are beside the point.

> I run Rubocop from Ruby `2.5.1`, the problem is that the `.ruby-version` within project directory is used to determine ruby version for the parser, despite the fact that I run rubocop from a different version.

I'm saying _don't_ run rubocop from ruby `2.5.1`. Install (if you haven't already) ruby `2.0.0`, then switch to using that version, then install rubocop on that version, then run it.

**Comment by mensfeld** [comment]
> What do you mean? I'm not saying you need to git push the updated Gemfile into the master branch, I'm just saying you could add it locally on your machine. Any project forking/branches/etc are beside the point.

I cannot. I have a general Rubocop setup that I use to analyze hundreds of projects. Let's just call it a "global" Rubocop setup. I don't have Rubocop as a dependency in any of the projects. This allows me to upgrade single Rubocop and have it upgraded within all the systems that I analyze with it at the same time. It also allows me not to have Rubocop as a dependency as I like keeping only the business itself in the codebase of my projects. If I would have to add it, I would have to upfront detect a potential problem, inject rubocop, bundle, etc.

> I'm saying don't run rubocop from ruby 2.5.1. Install (if you haven't already) ruby 2.0.0, then switch to using that version, then install rubocop on that version, then run it.

But I don't want to. What I want to is to make Rubocop assume, that upon an unsupported version, if should fallback to the oldest supported, even if this means some inaccuracies.

**Comment by tom-lord** [comment]
The latest rubocop version will not run against a ruby `2.0.0` project.

If you want to use an "inaccurate" version of rubocop, that won't refuse to run against ruby versions that it's incompatible with, then you could fork the project and build your own version of the gem without the `>= 2.1` constraint. (But I wouldn't actually suggest that...)

Or, you could downgrade your global rubocop version.

Or, you could update the legacy project to use ruby `2.1.0+`.

**Comment by mensfeld** [comment]
Ok. So basically impossibru. Let's close it as it gives me a satisfying answer. Thank you!

**Comment by tom-lord** [comment]
My honest answer is simply that your "global usage" is a bad idea. It would be better to add rubocop as a dependency to each project that uses it, and always `bundle exec rubocop`.

If someone else were to clone the project, then how would they know _which version_ of rubocop it's supposed to be checked against?

**Comment by mensfeld** [comment]
@tom-lord well we can agree to disagree here. My use-case is quite specific: I use a single rubocop "bundle" outside of projects not to have to update and maintain rubocop in all the projects. This allows me to update a single rubocop copy/instance and rerun analysis each time new things in rubocop come up. This also (together with applying the same approach for other linters / quality tools) allow me to drastically limit my projects dependencies only to things that are production and test rquired.

If anyone would clone my repositories (those non private) he could always refer to how I run things and just use the same approach.
