### ISSUE TITLE
0.57.2 Layout/ClosingHeredocIndentation incorrectly finds offense

### ISSUE THREAD

**Issue by th7-novu** [rubocop-hq/rubocop#6009]
## Expected behavior

No offense

## Actual behavior

Found offense

## Steps to reproduce the problem
run rubocop with:
```
class Example
  def example
    <<-XML
  <needs-exactly-2-space-indentation>
  </needs-exactly-2-space-indentation>
    XML
  end
end
```

## RuboCop version
0.57.2 (using Parser 2.5.1.0, running on ruby 2.4.1 x86_64-darwin16)

Additionally, running `rubocop -a` claims to have corrected the offense without changing the file, and subsequent runs of `rubocop` output that they corrected the offense every time (and the process exits 0)

**Comment by koic** [comment]
Thanks for opening issue.
This issue related to #5966 and fixed by #6003. Thank you.
