### ISSUE TITLE
Files described .rubocop.yml are not included correctly.

### ISSUE THREAD

**Issue by chionyan** [rubocop-hq/rubocop#6015]
`.rubocop.yml` file contains

```
AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
…
```

When `$ rubocop` run, result is:

`Inspecting 2 files`

This version is `0.57.2` , but in the case of `0.55.0` result is:
`Inspecting 15 files`

Also, 
when description of `Include:…` delete, inspecting 15 files correctly.

I'm Japanese and I can't speak English very well, sorry.

**Comment by bbatsov** [comment]
Please, see https://github.com/rubocop-hq/rubocop/issues/5917. That change was intentional, but it will require you to update your config.
