### ISSUE TITLE
Contradiction between Cops

### ISSUE THREAD

**Issue by badal** [rubocop-hq/rubocop#6020]
Rubocop goes back and forth on the same line between two Cops when a guard clause has two lines:

lib/ama/verifier.rb:48:7: C: Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.
      if min < ERROR_MAX
      ^^
lib/ama/verifier.rb:48:7: C: [Corrected] Style/MultilineIfModifier: Favor a normal if-statement over a modifier clause in a multiline statement.
      raise VerifyError, ...

**Comment by badal** [comment]
Just this four lines, when raise span two lines,

      if error > ERROR_MAX
        raise VerifyError,
              "long message, hence raise written on two lines"
      end

Run rubocop once : it complains, and changes if/then to modifyer. Run again : it complains and changes back to if/end.  And it circles indefinitely ...

**Comment by mikegee** [comment]
I had to wrap the code you posted in a method to get `Style/GuardClause` to complain. And `Style/GuardClause` doesn't autocorrect, so I'm still not able to duplicate the issue with `Style/MultilineIfModifier`.

**Comment by badal** [comment]
Sorry, I changed that part so many times today, that I cannot findthe exact form at that time.
So just forget if, until maybe it appears again. I close.

Thanks for the wonderful tool !
