### ISSUE TITLE
Layout/MultilineHashBraceLayout auto-correct syntax error

### ISSUE THREAD

**Issue by ned** [rubocop-hq/rubocop#6022]
Hi, I noticed that the auto-correct for `Layout/MultilineHashBraceLayout` sometimes causes syntax errors. This seems to happen when

- the closing `}` is on a new line
- the hash is inside a function call
- the last hash entry ends with a comment

--------

## Expected behavior

Don't introduce syntax errors.

## Actual behavior

Auto-correct for `Layout/MultilineHashBraceLayout` can introduce syntax errors when a line ends with a comment.

## Steps to reproduce the problem

Run ` rubocop --only Layout/MultilineHashBraceLayout --auto-correct test.rb` where `test.rb` is the following file:

```ruby
h = f({ x => 1, # foo
        y => 2, # bar
})
```

This is auto-corrected to the following

```ruby
h = f({ x => 1, # foo
        y => 2,} # bar)
```

Notice that the closing `)` of the function is now after the comment.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.57.1 (using Parser 2.5.1.0, running on ruby 2.4.1 x86_64-linux)
```

**Comment by koic** [comment]
Thanks for the feedback. It was reproduced at 0.57.2.
