### ISSUE TITLE
Policy on "disable because I disagree" issues?

### ISSUE THREAD

**Issue by Drenmi** [rubocop-hq/rubocop#6041]
Now and then we get an issue that, in essence, argues that some cop should be disabled by default because the author disagrees with it. These issues tend to be entirely based on Strong Opinion™, and aren't really helpful to the development of RuboCop.

Perhaps we should have something about this in the documentation, that can also be pointed to for quick closure of issues. WDYT @bbatsov?

There are some tangential issues. For example unsafe auto-corrects should rightly be disabled, and perhaps some cops with a high propensity for false positives. This shouldn't affect those.

**Comment by bbatsov** [comment]
Just close such issues. 

> There are some tangential issues. For example unsafe auto-corrects should rightly be disabled, and perhaps some cops with a high propensity for false positives. This shouldn't affect those.

Agreed. Those are going to be finally solved for good by the new Safety levels. We even have a PR in progress on this.
