### ISSUE TITLE
How to disable AbcSize cop for specific lines matching with a regex

### ISSUE THREAD

**Issue by msdundar** [rubocop-hq/rubocop#6043]
Here I have a sample Rails controller:

```ruby
    def show
      breadcrumb t('.common.countries'), countries_path, match: :exact
      breadcrumb @country.name, country_path(@country)
      @pagy, @cities = if params[:term].present?
                         pagy(@country.cities.search(params[:term]))
                       else
                         pagy(@country.cities)
                       end
    end
```

As you can see there are two lines including `breadcrumb`. And rubocop detects Metrics/AbcSize offense for this code:

`Metrics/AbcSize: Assignment Branch Condition size for show is too high. [16.31/15]`

The question is, how can I disable Metrics/AbcSize cops for breadcrumbs? I Googled a bit and found `IgnoredPatterns: ['\A']` setting and applied like this in my rubocop config:

```
Metrics/AbcSize:
  IgnoredPatterns: ['\Abreadcrumb']
```

However rubocop can not recognize `IgnoredPatterns` parameter:

`Warning: unrecognized parameter Metrics/AbcSize:IgnoredPatterns found in .rubocop.yml`

Best regards.

## RuboCop version

```
$ rubocop -V
0.57.2 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-linux)
```

**Comment by asherkach** [comment]
My guess is that you found the `IgnoredPatterns` configuration option for the `Metrics/LineLength` cop. Looking at the [documentation](https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsabcsize) for Metrics/AbcSize, the only configuration it supports is `Max`. Thus the error you are receiving is expected.

**Comment by Drenmi** [comment]
There is no way to tell `Metrics/AbcSize` to ignore some method sends. The finest level of granularity is to inline disable it for the entire method:

```ruby
# rubocop:disable Metrics/AbcSize
def show
  ...
end
# rubocop:enable Metrics/AbcSize
```

As another option, you could also extract the breadcrumb setting in a separate method:

```ruby
def show
  add_breadcrumbs_for_show

  ...
end
```

If you're a fan of DHH's style of Rails, where tangential- or cross cutting concerns are kept "out of the way", you could also use a callback:

```ruby
before_action :add_breadcrumbs

def show
  ...
end

private

def add_breadcrumbs
  ...
end
```

**Comment by MatzFan** [comment]
Was just caught by a similar issue when I saw `Warning: unrecognized parameter Metrics/AbcSize:ExcludedMethods found in .rubocop.yml`

Respectful suggestion: A more helpful message may be something along the lines of `Metrics/AbcSize does not support <offending parameter> parameter. Supported parameters are: <list>`. I originally thought `unrecognized` must have been the result of a typo on my part.

**Comment by jonas054** [comment]
@MatzFan I think that's a good idea. Please open a new issue requesting that change.
