### ISSUE TITLE
Rails.root.join is listed as an offense while written using string interpolation

### ISSUE THREAD

**Issue by shlok007** [rubocop-hq/rubocop#6048]
## Actual behavior

While using string interpolation in ruby, `Rails.root.join` is listed as an offense but I am not sure if it should be. I have attached a screenshot to describe the actual behaviour below.

![screenshot from 2018-06-25 20 22 26](https://user-images.githubusercontent.com/14155445/41858713-25571800-78b8-11e8-9046-7b7c3b2766f1.png)

## RuboCop version

I am using rubocop v0.53.0 in Travis CI.

**Comment by koic** [comment]
This issue has been fixed in #5461 and will not be reproduced in RuboCop 0.57.2. Please upgrade RuboCop to a new version. Thank you.
