### ISSUE TITLE
Question: TargetRubyVersion fuzzy version matching?

### ISSUE THREAD

**Issue by amingilani** [rubocop-hq/rubocop#6050]
This is more of a question than an issue, please feel free to close this when answered.

Can I do fuzzy version matching for `TargetRubyVersion`, e.g. `TargetRubyVersion: "~> 2.4.0"`, and have it match for `2.4.0`, `2.4.1`, and `2.4.2`

**Comment by bbatsov** [comment]
No, that's not possible. Each release of the `parser` targets a specific Ruby version (e.g. `2.3.4`), so in the end we can only target it anyways.
