### ISSUE TITLE
Parser error when running rubocop 0.57.2

### ISSUE THREAD

**Issue by badal** [rubocop-hq/rubocop#6051]
16 files inspected, 9 offenses detected
comparison of Parser::Source::Range with Parser::Source::Range failed
C:/Ruby24/lib/ruby/gems/2.4.0/gems/parser-2.5.1.0/lib/parser/source/tree_rewriter/action.rb:38:in `sort_by'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/parser-2.5.1.0/lib/parser/source/tree_rewriter/action.rb:38:in `ordered_replacements'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/parser-2.5.1.0/lib/parser/source/tree_rewriter.rb:191:in `process'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/corrector.rb:68:in `rewrite'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:126:in `autocorrect_all_cops'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:70:in `autocorrect'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:98:in `block in offenses'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:115:in `investigate'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:94:in `offenses'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cop/team.rb:44:in `inspect_file'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:265:in `inspect_file'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:212:in `block in do_inspection_loop'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:244:in `block in iterate_until_no_changes'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:237:in `loop'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:237:in `iterate_until_no_changes'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:208:in `do_inspection_loop'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:111:in `block in file_offenses'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:129:in `file_offense_cache'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:109:in `file_offenses'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:100:in `process_file'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `each'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `reduce'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:75:in `each_inspected_file'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:67:in `inspect_files'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/runner.rb:39:in `run'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:160:in `execute_runner'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:88:in `execute_runners'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/lib/rubocop/cli.rb:41:in `run'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/exe/rubocop:13:in `block in <top (required)>'
C:/Ruby24/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
C:/Ruby24/lib/ruby/gems/2.4.0/gems/rubocop-0.57.2/exe/rubocop:12:in `<top (required)>'
c:/Ruby24/bin/rubocop:23:in `load'
c:/Ruby24/bin/rubocop:23:in `<main>'

**Comment by koic** [comment]
This seems to duplicate with #6035. And #6049 is open for solving this problem. Thank you.
