### ISSUE TITLE
Style/SymbolProc correction produces errors when the block has multiple arguments

### ISSUE THREAD

**Issue by drbrain** [rubocop-hq/rubocop#6052]
Given the following:

```ruby
require 'pp'

class I
  attr_reader :ref

  def initialize ref
    @ref = ref
  end

  def hash
    @ref.hash
  end

  def eql? other
    @ref == other.ref
  end
end

i1 = I.new '1'
i2 = I.new '2'

h = {
  i2 => %w[two],
  i1 => %w[one],
}

sorted = h.sort_by { |i,| i.ref }

pp sorted
```

For the line `sorted = h.sort_by { |i,| i.ref }` rubocop says I must "Pass &:ref as an argument to sort_by instead of a block" but this change causes NoMethodError because #ref is called on an Array rather than the `I` object as specified.

## Expected behavior

Rubocop does not suggest any correction for this line under Style/SymbolProc.

## Actual behavior

```
$ rubocop --only Style/SymbolProc t.rb
Inspecting 1 file
C

Offenses:

t.rb:28:20: C: Style/SymbolProc: Pass &:ref as an argument to sort_by instead of a block.
sorted = h.sort_by { |i,| i.ref }
                   ^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem

1. Write the above file to `t.rb`
1. Run `ruby t.rb`, note that it returns a sorted Array of Arrays
1. Run `rubocop --only Style/SymbolProc t.rb`
1. See "Pass &:ref as an argument to sort_by instead of a block."
1. Replace that line with `sorted = h.sort_by(&:ref)`
1. `ruby t.rb`, note that it fails with NoMethodError:

```
$ ruby t.rb
Traceback (most recent call last):
        2: from t.rb:27:in `<main>'
        1: from t.rb:27:in `sort_by'
t.rb:27:in `each': undefined method `ref' for [#<I:0x00007fe59592dad8 @ref="2">, ["two"]]:Array (NoMethodError)
```

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -v
0.57.2
```

**Comment by koic** [comment]
Thanks for the feedback. I think that this is a false positive and I opened a PR #6053.
