### ISSUE TITLE
rubocop --auto-gen-conf exits with 1

### ISSUE THREAD

**Issue by Ana06** [rubocop-hq/rubocop#6057]
When rubocop find offenses it exits with 1, which in general is expected. But when running `rubocop --auto-gen-conf ` I would expect that it returns 1 only if something went wrong and 0 in other case, as that there are offenses is expected and doesn't mean that the execution of the command went wrong. :confused:

**Comment by MagedMilad** [comment]
@Ana06 @bbatsov I would like to contribute solving this issue, but I think returning 0 when there are offenses will cause many tests to fail, so should I can those tests to always expect 0 when `--auto-gen-conf` option is present?

**Comment by Ana06** [comment]
@MagedMilad nice that you want to work on that! :cupid: I think `--auto-gen-conf` should return 0 when the todo file is successfully created, without taking into account if there are offenses and the tests should also be changed to follow this.

**Comment by MagedMilad** [comment]
@Ana06 @bbatsov just made a Pull request #6165, But I can't assign a reviewer to it, also I'm not sure this is the right way to handle `auto-gen-config` because it's my first time contributing in rubocop
so any comment on the PR will be very appreciated
