### ISSUE TITLE
CircleCI failed builds

### ISSUE THREAD

**Issue by Vasfed** [rubocop-hq/rubocop#6062]
After adding CircleCI failed builds started to appear on master.

--------

## Expected behavior

Build pass, as it already has succeeded in PR

## Actual behavior
For example: [this build](https://circleci.com/gh/rubocop-hq/rubocop/52?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and [this](https://circleci.com/gh/rubocop-hq/rubocop/205?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

```
Killed
/opt/jruby/bin/jruby -E ASCII -I/usr/local/bundle/gems/rspec-core-3.7.1/lib:/usr/local/bundle/gems/rspec-support-3.7.1/lib /usr/local/bundle/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
224.1214164970006 seconds

RuntimeError: `bundle exec rake ascii_spec` is failed
            sh! at .travis.rb:57
  run_main_task at .travis.rb:44
            run at .travis.rb:9
         <main> at .travis.rb:66
Exited with code 1
```

## Steps to reproduce the problem

Unfortunately this does not have reliable way to reproduce and seems to be CircleCI problem.
Probably can be because of memory overselling and noisy neighbours, when OOM killer awakens.

**Comment by bbatsov** [comment]
I think @bquorning is already looking into this.

**Comment by bquorning** [comment]
I was looking into it, and thought I had it solved by setting JRUBY_OPTS etc. Got 4 green builds in a row on my branch, and now it fails on master. I’m a bit confused.

I am actually on vacation now, so I won’t have time to look into it right away. If anyone knows why the builds are killed, please add a comment.

**Comment by koic** [comment]
The build of CircleCI now succeeds. It is not clear why the build error occurred, but let's open the issue once it gets up again.
https://circleci.com/gh/rubocop-hq/rubocop/353

**Comment by bquorning** [comment]
A few more failing JRuby builds:

- https://circleci.com/gh/rubocop-hq/rubocop/3466
- https://circleci.com/gh/rubocop-hq/rubocop/4380
- https://circleci.com/gh/rubocop-hq/rubocop/4395

**Comment by bbatsov** [comment]
Seems that's resolved now.
