### ISSUE TITLE
Two empty lines before private and protected

### ISSUE THREAD

**Issue by ndbroadbent** [rubocop-hq/rubocop#6063]
I've always used two empty lines before `private` or `protected`:

```ruby
class SomeClass
  def some_public_method
  end


  private

  def private_method
  end
end
```

The `Layout/EmptyLines` cop shows `Extra blank line detected.` 

Would it be possible to make this configurable? Maybe a new option for `Layout/EmptyLinesAroundAccessModifier`?

## RuboCop version

```
$ rubocop -V
0.54.0 (using Parser 2.5.0.5, running on ruby 2.4.3 x86_64-darwin16)
```

**Comment by Ana06** [comment]
It would be possible, but why two lines? :thinking:

**Comment by ndbroadbent** [comment]
I think it's just a personal preference, and it makes it a bit easier to see where a `private` or `protected` section begins. But now I'm looking at Google and can't find anyone else who uses two lines. And the Rails style uses the weird indentation, which I really don't like. So after thinking about it some more, I'll just adopt the Rubocop style guide and forget about this. Fortunately `rubocop -a` fixes everything automatically!
