### ISSUE TITLE
ForceEqualSignAlignment should only align block content

### ISSUE THREAD

**Issue by egze** [rubocop-hq/rubocop#6069]
The current alignment makes it not obvious what variables are set inside  and outside the block. I think rubocop should align only what is **inside** the block.

Here is an example:
```ruby
my_secret_values = [1,2,3,4].map do |i|
  x = i * 2
  secret = x*x
end
```

--------

## Expected behavior

```ruby
my_secret_values = [1, 2, 3, 4].map do |i|
  x      = i * 2
  secret = x * x
end
```

## Actual behavior

```ruby
my_secret_values = [1, 2, 3, 4].map do |i|
  x              = i * 2
  secret         = x * x
end
```

## Steps to reproduce the problem

Run rubocop with autocorrect.

## RuboCop version

Include the output of `rubocop -V`. Here's an example:

```
$ rubocop -V
0.54.0 (using Parser 2.5.1.0, running on ruby 2.4.2 x86_64-darwin17)
```

**Comment by jfelchner** [comment]
This should be fixed in #7211
