### ISSUE TITLE
New  &.  syntax not recognized (rubocop 0.57.2)

### ISSUE THREAD

**Issue by badal** [rubocop-hq/rubocop#6072]
E: Lint/Syntax: unexpected token error
(Using Ruby 2.1 parser; configure using TargetRubyVersion parameter, under AllCops)
      return false if conditions[:day_before]&.< day

**Comment by Darhazer** [comment]
`&.` was added in Ruby 2.3
As the error message says, you have to put 2.3 (or higher) for  `TargetRubyVersion` under `AllCops` in your `.rubocop.yml` file

**Comment by badal** [comment]
Thank you !

 

Michel Demazure

michel@demazure.com

 

De : Maxim Krizhanovsky [mailto:notifications@github.com] 
Envoyé : mercredi 4 juillet 2018 11:07
À : rubocop-hq/rubocop
Cc : Michel Demazure; Author
Objet : Re: [rubocop-hq/rubocop] New &. syntax not recognized (rubocop 0.57.2) (#6072)

 

&. was added in Ruby 2.3
As the error message says, you have to put 2.3 (or higher) for TargetRubyVersion under AllCops in your .rubocop.yml file
