### ISSUE TITLE
[feature request] remove trailing whitespaces

### ISSUE THREAD

**Issue by samueloph** [rubocop-hq/rubocop#6074]
I think the title says it all, it would be nice if rubocop would also remove trailing whitespaces.

**Comment by Darhazer** [comment]
The `Layout/TrailingWhitespace` cop does this. 

Is there a specific code/file that was not corrected by RuboCop?

**Comment by samueloph** [comment]
@Darhazer ah, I had run rubocop on a bunch of files and i found at least one where i didn't correct this. running again specifying the file directly solved. I don't know what went wrong, will try to investigate further and report back if find something.

Thanks.
