### ISSUE TITLE
SpaceBeforeFirstArg 

### ISSUE THREAD

**Issue by Guoxweii** [rubocop-hq/rubocop#6093]
# situation
this code `class Application < Rails::Application`
rubocop give a error Layout/SpaceBeforeFirstArg

```
config/application.rb:10:28: C: Layout/SpaceBeforeFirstArg: Put one space between the method name and the first argument.
  class Application < Rails::Application

```

when i use AutoCorrect

![image](https://user-images.githubusercontent.com/689550/42494653-81aa123c-8453-11e8-94af-759bc06c2bce.png)

why add space before ::

--------
## RuboCop version

```
$ rubocop -V
0.58.0 (using Parser 2.5.1.1, running on ruby 2.4.1 x86_64-darwin16)
```

**Comment by bbatsov** [comment]
Seems like some upstream problem with Parser 2.5.1 https://github.com/whitequark/parser/issues/519#issuecomment-403721097

**Comment by bbatsov** [comment]
0.58.1 is out.
