### ISSUE TITLE
Style/UnneededInterpolation autocorrect needs to dup after .to_s

### ISSUE THREAD

**Issue by lamont-granquist** [rubocop-hq/rubocop#6099]
there is an implicit dup in `"#{str}"` which is missing from `(str).to_s` so Style/UnneededInterpolation's autocorrect may break code which was reliant upon the hidden dup.

```
% pry
[1] pry(main)> str = "foo"
=> "foo"
[2] pry(main)> str.object_id
=> 70256959432840
[3] pry(main)> str2 = "#{str}"
=> "foo"
[4] pry(main)> str2.object_id
=> 70256959692480
[5] pry(main)> str2 << "bar"
=> "foobar"
[6] pry(main)> str
=> "foo"
[7] pry(main)> str2 = (str).to_s
=> "foo"
[8] pry(main)> str2.object_id
=> 70256959432840
[9] pry(main)> str2 << "bar"
=> "foobar"
[10] pry(main)> str
=> "foobar"
[11] pry(main)>
```

**Comment by rrosenblum** [comment]
Makes sense, `String#to_s` essentially returns self. `dup` could be placed before or after the call to `to_s`.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
