### ISSUE TITLE
Rails/Validates autocorrect producing questionable syntax

### ISSUE THREAD

**Issue by tibbon** [rubocop-hq/rubocop#6106]
I'm not entirely sure if this is valid Rails syntax, but the autocorrect is switching from 

`validates_numericality_of :foo, only_integer: true, unless: :blank?`

to:

`validates :foo, numericality: { only_integer: true, unless: :blank? }`

I *think* that ideally, it should be: 

`validates :foo, numericality: { only_integer: true }, unless: :blank?`

Similarly, it's doing this: 

`validates_presence_of :foo, unless: :blank?` to
`validates :foo, presence: { unless: :blank? }`

It's entirely possible that somehow this is valid, but it seems a bit off. Looking at the options in Rails' `presence.rb` it doesn't seem that they are valid options? 

Using Rubocop 0.57.2

**Comment by RKushnir** [comment]
Those are valid options and they are common for all ActiveModel validators. They allow you to adjust behavior of each validator independently, as opposed to the top-level option which applies to all validators at once. So you can say, for example:
```ruby
validates :foo,
  numericality: { only_integer: true, unless: :blank? },
  uniqueness: { unless: :duplicates_are_fine? }
```
