### ISSUE TITLE
Cut 0.58.2?

### ISSUE THREAD

**Issue by kenman345** [rubocop-hq/rubocop#6121]
It appears that a lot of PRs have been merged to master since 0.58.1 has been cut. I would very much love if my PR that was merged were cut into a build to help the team that I had made it for.

**Comment by bbatsov** [comment]
I'll cut a new release in a bit. I'm conflicted as to whether it should be 0.58.2 or 0.59, but let's go with 0.58.2, as the single new feature is tiny.
