### ISSUE TITLE
Reduntant Relationship call cop

### ISSUE THREAD

**Issue by ylaguna** [rubocop-hq/rubocop#6143]
Hi guys, quick question

In a line like this

```class_id = student.class.id```

It is reduntant to call the class relationship, and it should be

```class_id = student.class_id```

There is any cop in RuboCop to prevent this?

**Comment by koic** [comment]
Thank you for asking. A cop that prevents it does not exist in Rails department of RuboCop.

**Comment by koic** [comment]
I will close this issue.
If you are requesting this feature, please open an issue to rubocop-rails repository. Thank you.
https://github.com/rubocop-hq/rubocop-rails
