### ISSUE TITLE
Autocorrecting Style/UnneededCondition changes behaviour

### ISSUE THREAD

**Issue by kkozmic** [rubocop-hq/rubocop#6164]
There's a bug when dealing with the following code:

```
    arr = []
    arr << if @one
             @one
           else
             @two
           end
```

Rubocop reports 
```
test.rb:4:12: C: Style/UnneededCondition: Use double pipes || instead.
    arr << if @one ...
           ^^^^^^^
```
That makes sense. However when ran with `--auto-correct` it changes the code above to
```
    arr = []
    arr << @one || @two
```
That is incorrect as it changes the behaviour of the code.

--------

## Expected behavior

The code should not change its behaviour.

## Actual behavior

The way it's been changed `@one` will *always* be appended to the `arr` (effectively making the `|| @two` part a no-op). Whereas if `@one` is `nil` `@two` should be added instead.

One way to correct it would be to add brackets: `arr << (@one || @two)`. That way the original behaviour would be kept.

## Steps to reproduce the problem

run `rubocop --auto-correct` against the code at the beginning of the ticket.

## RuboCop version

```
0.58.2
```

**Comment by koic** [comment]
Thank you for the feedback. I confirmed this reproduction and I opened a PR #6166.
