### ISSUE TITLE
Style/EmptyCaseCondition autofix breaks code when returning from branches

### ISSUE THREAD

**Issue by triplepointfive** [rubocop-hq/rubocop#6196]
## Expected behavior

Given the smallest example

```ruby
def a
  c = case
      when x.a
        1
      when x.b
        return 2
      end
  c + c
end
```

Run rubocop with autofix mode. Expected to leave it as is (at least working) or format.

## Actual behavior

The result is

```ruby
def a
  c = if x.a
        1
      elsif x.b
        return 2
      end
  c + c
end
```

That's broken program, fails with "void value expression"

## RuboCop version

0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)

**Comment by koic** [comment]
Thanks for the feedback. I confirmed this reproduction and I opened a PR #6207.
