### ISSUE TITLE
Rubocop failed with code 7, using vscode-ruby extension. What is code 7?

### ISSUE THREAD

**Issue by sergiotapia** [rubocop-hq/rubocop#6200]
I'm using this extension and install Rubocop using gem install rubocop.

https://github.com/rubyide/vscode-ruby

I get an error rubocop failed with code=7 what exactly is code 7?

**Comment by bbatsov** [comment]
No idea to be honest. Those are all of our official exit codes - http://www.rubocop.org/en/latest/basic_usage/#exit-codes

**Comment by SHGoldfarb** [comment]
@sergiotapia did you find a solution? I'm having the same issue, and can't find any info on it :(

**Comment by sergiotapia** [comment]
@SHGoldfarb  Nope, I just stopped using Rubocop and moved to prettier

**Comment by SHGoldfarb** [comment]
I solved the issue installing this extension: https://github.com/misogi/vscode-ruby-rubocop

It is meant to work alongside `vscode-ruby`. Linter and formatter work fine.
