### ISSUE TITLE
Warning: "...is a symlink, which is not allowed"

### ISSUE THREAD

**Issue by chortels** [rubocop-hq/rubocop#6228]
**Is your feature request related to a problem? Please describe.**

Hi, 

I'm frustrated when launching rubocop from my CI tool Jenkins. When executing `/bin/rubocop --format=json --out=rubocop-result.json`, Jenkins returns the following message: 

**Warning: <symlink_in_my_computer> is a symlink, which is not allowed.**

And this makes the execution finish with an error. Is there any way to solve this problem?

Regards

**Comment by mikegee** [comment]
That warning is almost certainly coming from the `ResultCache` code here: https://github.com/rubocop-hq/rubocop/blob/d714e247f77457a593792d2ed50483622d3c3686/lib/rubocop/result_cache.rb#L126

I'm not too familiar with that code, but I skimmed it just now. Do you have a `rubocop_cache` directory committed into your project? If you do, try removing that from version control.

**Comment by chortels** [comment]
Hi @mikegee . Thanks for your answer. This .cache/rubocop_cache directory is not committed in my project, but generated when executing bundle install. Is there any way to prevent this directory for being created?

Regards.

**Comment by mikegee** [comment]
You can turn off Rubocop's cache at the command line with `--cache false` or with the `AllCops: UseCache` configuration setting.

**Comment by koic** [comment]
Hi @chortels.
Did this issue be solved with the above `--cache false` option or `AllCops: UseCache` configuration?
