### ISSUE TITLE
Style/EmptyCaseCondition removes comment between case and first when

### ISSUE THREAD

**Issue by triplepointfive** [rubocop-hq/rubocop#6242]
## Expected behavior

```ruby
def foo
  case
  # when bar ...
  when bar
    2
  end
end
```

Calling

`rubocop 1.rb -a --only=Style/EmptyCaseCondition`

shoud fix only branches

## Actual behavior

Comment has gone

```ruby
def foo
  if bar
    2
  end
end
```

## RuboCop version

0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)

**Comment by koic** [comment]
Thank you for the feedback. I confirmed this reproduction and I opened a PR #6257.
