### ISSUE TITLE
Style/MutableConstant and frozen_string_literal

### ISSUE THREAD

**Issue by bquorning** [rubocop-hq/rubocop#6244]
## Expected behavior

In a source file with the magic comment `# frozen_string_literal: true`, all literal strings are frozen. So Style/MutableConstant should not need to recommend I “Freeze mutable objects assigned to constants.”

## Actual behavior

Style/MutableConstant should recommends to freeze Strings assigned to constants, even if all strings in the file are implicitly declared frozen.

## Steps to reproduce the problem

Run RuboCop against e.g. this source file:
```rb
# frozen_string_literal: true

FOO = 'foo'
```

I get this output:
```
Offenses:

test.rb:3:7: C: Style/MutableConstant: Freeze mutable objects assigned to constants.
FOO = 'foo'
      ^^^^^
```

## RuboCop version

```
0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin15)
```

**Comment by bquorning** [comment]
You are right, @koic. I think I got confused about one of my projects using the magic comment and the other one having `.freeze` on constants. I’ll chose the issue for now.

**Comment by devsheva** [comment]
I still have this problem, even though i've specified ruby version in `rubocop.yml` .

```yml

AllCops:
  TargetRubyVersion: 3.1.3
```
