### ISSUE TITLE
Invalid report from Lint/UselessAccessModifier

### ISSUE THREAD

**Issue by gettalong** [rubocop-hq/rubocop#6250]
## Expected behavior

`Lint/UselessAccessModifier` should not flag valid usage.

## Actual behavior

It flags valid usage.

## Steps to reproduce the problem

Run RuboCop on the following file:

~~~ ruby
MyClass = Class.new { private_class_method :new }
~~~

It reports:

~~~
bug.rb:1:23: W: Lint/UselessAccessModifier: Useless private_class_method access modifier.
MyClass = Class.new { private_class_method :new }
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
~~~

However, this should not be reported because if we remove the block `MyClass.new` would work.

## RuboCop version

~~~
0.58.2 (using Parser 2.5.1.2, running on ruby 2.5.0 x86_64-linux)
~~~

**Comment by koic** [comment]
This issue was resolved by #6535.
