### ISSUE TITLE
Layout/EmptyLineAfterGuardClause wrongly inspects lines with heredocs

### ISSUE THREAD

**Issue by bayandin** [rubocop-hq/rubocop#6264]
Rubocop `Layout/EmptyLineAfterGuardClause` auto-correct inserts a new line right after the guard clause line but for case of using heredoc it should insert an empty line after the end of heredoc

--------

## Expected behavior

auto-correct mode produces code like this:

```ruby
raise(<<-FAIL) if true
  boop
FAIL

1
```

## Actual behavior

auto-correct mode produces this code:

```ruby
raise(<<-FAIL) if true

  boop
FAIL
1
```

## Steps to reproduce the problem

Run this rubocop command:

```
bundle exec rubocop --auto-correct --debug --only Layout/EmptyLineAfterGuardClause rubocop_example.rb
```

agains this ruby code:

```ruby
raise(<<-FAIL) if true
  boop
FAIL
1
```

## RuboCop version

```
$ bundle exec rubocop -V
0.59.0 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin17)
```

**Comment by david942j** [comment]
Hi, I found this bug is not fixed completely:
consider this:
```ruby
def foo
  return <<-FAIL if true
    boop
  FAIL
  1
end
```

Expected behavior
----
auto-correct should produce
```ruby
def foo
  return <<-FAIL if true
    boop
  FAIL

  1
end
```
Actual behavior
---
```ruby
def foo
  return <<-FAIL if true

    boop
  FAIL
  1
end
```

RuboCop version
---
```
➔ rubocop -V
0.64.0 (using Parser 2.6.0.0, running on ruby 2.5.3 x86_64-linux)
```

**Comment by nunozex** [comment]
Still happening in 0.79.0.

I try to use the code bellow and rubocop tells me "Layout/EmptyLineAfterGuardClause: Add empty line after guard clause."
`return <<~TEXT if a < 150
      Blblabla
    TEXT`
