### ISSUE TITLE
Naming/FileName should exclude gemspec

### ISSUE THREAD

**Issue by kddeisz** [rubocop-hq/rubocop#6265]
When gems are nested, `bundler` recommends using dashes to separate namespaces (i.e., `bundler-console` becomes `Bundler::Console`). As such, the gemspec is supposed to be named `bundler-console.gemspec`. We should ignore `gemspec` files when running the `Naming/FileName` cop.

## Expected behavior

It allows dashes in gemspec names.

## Actual behavior

It fails with the `Naming/FileName` cop.

## Steps to reproduce the problem

Have a gemspec with a dash in its name. Run rubocop.

## RuboCop version

`0.59.0 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-darwin15)`

**Comment by nutsoriginal** [comment]
Also .pryrc fails with:
> Naming/FileName: The name of this source file (.pryrc) should use snake_case.

**Comment by bbatsov** [comment]
Fix by https://github.com/rubocop-hq/rubocop/pull/6256

**Comment by sinsoku** [comment]
@bbatsov https://github.com/rubocop-hq/rubocop/pull/6256 fixed a false positive for dotfiles (i.e., `.pryrc`).
However, it did not exclude `gemspec` files including dashes.
