### ISSUE TITLE
Infinite loop: Layout/EmptyLinesAroundClassBody & Layout/EmptyLinesAroundAccessModifier

### ISSUE THREAD

**Issue by dennisvandehoef** [rubocop-hq/rubocop#6305]
## Expected behavior

No infinite loop. I would expect my example code to be valid. (or when not, at least no infinite loop :wink:)

## Actual behavior

Rubocop autocorrection will start adding and removing a blank line between the class definition and protected. (it only happens for class definitions that are on two lines)

This also results in Rubocop to be never pleased.

## Steps to reproduce the problem

Use this code:

```ruby
class AVerryLongClassNameDoYouLikeIt < 
  ItEvenInheritsFromALongClassNameSOINeedToAddALineBrake

  protected

  def foobar
  end
end
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.59.1 (using Parser 2.5.1.2, running on ruby 2.5.0 x86_64-darwin17)
```

EDIT: I corrected the code

**Comment by koic** [comment]
Thanks for the feedback.  I confirmed this reproduction and I opened PR #6305.
