### ISSUE TITLE
AccessModifierDeclarations inline with rescue

### ISSUE THREAD

**Issue by stevenspiel** [rubocop-hq/rubocop#6313]
I'm getting odd behavior in rescue statements when AccessModifierDeclarations is set to inline.

.rubocop.yml:

```yaml
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
```

foo.rb:

```Ruby
class Foo
  private def bar
    raise
  rescue StandardError
    1
  end
end
```

When running `bundle exec rubocop -a`, I get the following output:

```
app/services/foo.rb:6:3: C: [Corrected] Layout/RescueEnsureAlignment: rescue at 6, 2 is not aligned with def bar at 4, 10.
  rescue StandardError
  ^^^^^^
```

Even though it says "Corrected", no change is made to the file. It will repeat this error over and over again and there does not seem to be a way to fix it.

--------

## Expected behavior

The following should be valid:

```Ruby
class Foo
  private def bar
    raise
  rescue StandardError
    1
  end
end
```

## Actual behavior

rubocop says the file is corrected, but still registering as an error in subsequent runs.

## Steps to reproduce the problem

1. Clone this repo https://github.com/stevenspiel/access-modifier-declarations-error.git
2. `$ bundle`
3. `$ bundle exec rubocop -a`

## RuboCop version

```
$ [bundle exec] rubocop -V
0.59.1 (using Parser 2.5.1.2, running on ruby 2.4.0 x86_64-darwin17)
```

**Comment by Drenmi** [comment]
Thanks for the report! This seems to be another manifestation of #6258. I'll close this issue so we can track the existing one. Please keep an eye there for updates. :bowing-man:

**Comment by andrew-aladev** [comment]
This issue is not equals to #6258. Inline access modifiers are naturally part of method definition. It was just implemented in `parser` with special wrapping nodes and guys forget to implement it in rubocop.
