### ISSUE TITLE
Exclude file for all but one cop

### ISSUE THREAD

**Issue by Tolsto** [rubocop-hq/rubocop#6323]
I've currently excluded the `schema.rb` file for all cops via `AllCops`:

```
AllCops:
  Exclude:
    - db/schema.rb
```

I now have a custom cop that I'd like to run just for `schema.rb`. 
I've tried:
```
Rails/SchemaCop:
  Include:
    - db/schema.rb
```
However, this doesn't work because the exclude from `AllCops` seems to take precedence over the cop-specific include. Is this the intended behavior? If it is, is there a workaround?

Tested with Rubocop 0.59.1

**Comment by bbatsov** [comment]
I think that Includes had higher precedence than excludes. @jonas054 can you confirm/deny this?

**Comment by jonas054** [comment]
Sorry @Tolsto, but there's currently no way to override an `AllCops:Exclude`. The files matching one of the patterns listed there are taken out of the loop at an early stage. That's just how the algorithm works.

The only workaround is to run the cop in a separate invocation: `rubocop --only Rails/SchemaCop db/schema.rb`. If the file name is given on the command line, excludes properties don't count.

**Comment by Tolsto** [comment]
Thank you for the clarification, @jonas054. Would you welcome a pull request that would introduce a possibility to support the above-mentioned use-case? If so, could you point me in the direction of a possible solution?

**Comment by jonas054** [comment]
I'm trying to think if there could be any unwanted consequences. For example, `vendor` directories are excluded by default but the we also have
```yaml
Rails/AssertNot:
  Include:
    - '**/test/**/*'
```
in default configuration. If that `Include` overrides `AlCops:Exclude`, then I think we'll get inspection of test files of a lot of third party code that we don't want to inspect.

So coming up with the right functionality is hard. Then I think the implementation could be pretty tough too. But if you want to have a go, I think it could be worth it. Start by adding an example in `cli_spec.rb` based on your example at the top of this issue. Then look for the word `Exclude` in `lib/rubocop/*.rb`. That's a start. Let me know when you need more help.

**Comment by Tolsto** [comment]
I don't really know much about the internals of Rubocop yet, so this idea might be ridiculous: Instead of excluding the file via `AllCops` it could also be done by adding an explicit `exclude` to all cops but the one that is supposed to check the file. Of course, this would require to explicitly list every single enabled cop in `.rubocop.yml` which is not desirable. However, if we could dynamically add cop configuration via a Regex it would require just one entry:

```
regex_cop_names:
  - '\A(?!Rails\/SchemaCop).*\z':
      Exclude:
        - db/schema.rb

Rails/SchemaCop:
  Include:
    - db/schema.rb
```  

The advantage of such a solution would be that it shouldn't have any effects on existing configurations. It could also be used to add more complex configurations based on cop namespaces.

**Comment by jonas054** [comment]
I have a feeling it would require more complexity in the code, but if you'd like you can try it and see where it leads.

I'm interested to know though; what's wrong with the workaround solution?

**Comment by salzig** [comment]
Got bitten by the same Exclude/Include problem. `db/schema.rb` is a generated file, so we don't want to run rubocop full Robocop on it. But sadly we need to check some specific things. Fields with database function as default are generated wrong. eg. bad `default: 'uuid()'` vs. good: `default: -> { 'uuid()' }`). So we want to run this specific cop on db/schema.rb, but no other check. 
As far as i understand, the work around is to call rubocop twice. Once generic `rubocop`, and a second time with `rubocop --only OurCop db/schema.rb`. 

Sad, but at lease good to know there is a workaround.

**Comment by Tolsto** [comment]
My workaround for schema.rb looks like this:

```
namespace :db do
  namespace :schema do
    task rubocop_tags: :environment do
      schema_file = "#{Rails.root}/db/schema.rb"
      new_schema = StringIO.new
      new_schema.puts '# rubocop:disable all'
      new_schema.puts '#'
      new_schema.puts File.read(schema_file)
      new_schema.puts '# rubocop:enable all'
      File.write(schema_file, new_schema.string)
    end
  end
end

Rake::Task['db:schema:dump'].enhance do
  Rake::Task['db:schema:rubocop_tags'].invoke
end
```

You can enable the cops that you want to run after the `rubocop:disable all` line

**Comment by jonas054** [comment]
@Tolsto Here's a solution, that's pretty standard and not really a workaround. You don't exclude `db/schema.rb` at the root level `.rubocop.yml`. Instead you add this configuration file:
```yml
# db/.rubocop.yml
AllCops:
  DisabledByDefault: true

Rails/SchemaCop:
  Enabled: true
  Include:
    - schema.rb
```
Then the only file you inspect in the `db` directory is `schema.rb`, and only with `Rails/SchemaCop`. Not sure why I didn't think of this before. :smile:

**Comment by Tolsto** [comment]
@jonas054 That's indeed a very elegant solution. However, the schema comments come more or less for free in my project since I also add some other comments like the Postgres version that was used to create the schema dump. 
Also, I didn't answer your question from September yet: Separate invocations would be very inconvenient since our Rubocop runs on CI systems, pre-commit hooks and IDEs on local systems which would require to make this change in many different places.
