### ISSUE TITLE
Cop ideas from other projects

### ISSUE THREAD

**Issue by rrosenblum** [rubocop-hq/rubocop#6348]
I came across several RuboCop extension gems that may have some useful cops to add to the RuboCop core project. This may also shed more light on what other people see as valuable cops.

https://gitlab.com/gitlab-org/rubocop-gitlab-security
https://github.com/puppetlabs/rubocop-i18n
https://github.com/github/rubocop-github
https://github.com/blueapron/rubocop-blueapron
https://github.com/airbnb/ruby/tree/master/rubocop-airbnb
https://github.com/covermymeds/rubocop-thread_safety

There are also a few gems that add additional formatters that we could consider adding.
https://github.com/eitoball/rubocop-checkstyle_formatter
https://github.com/mikian/rubocop-junit-formatter

I haven't played around with 3rd party formatters, but it seems like we could improve support for them, `rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter`. If we don't currently have a way to support 3rd party formatters in the `.rubocop.yml`, it looks like it could be valuable to add it.

**Comment by thomthom** [comment]
> I haven't played around with 3rd party formatters, but it seems like we could improve support for them, 

Yes please! I'm working on a RuboCop extension to analyse SketchUp Ruby Extensions - and for that wanted a specialised formatter for this purpose. I'm currently resorting to some (kludgy) monkey-patching: https://github.com/SketchUp/rubocop-sketchup/blob/master/lib/rubocop-sketchup.rb#L22
I'd love for an API for this.

Similarly, the extension have some "global" options which I'd like to be able to set via command line (for automation purposes) - saving me from having to write temporary `yml` config files. (https://github.com/SketchUp/rubocop-sketchup/blob/master/manual/configuration.md)

Another thing that would be great is department excludes. (Logged as #5678) I got some custom rules for `rubocop-sketchup` which I based on `rubocop-rspec`. Got a work ticket logged for myself to come up with a PR proposal. (Thought I'd just mention it in the context of reviewing what RuboCop extensions are doing.)

**Comment by pirj** [comment]
@rrosenblum Maybe ask those projects' maintainers (by submitting an issue first) if they'd like to contribute those cops to the main repo or to the corresponding extensions under `rubocop-hq` organisation?
