### ISSUE TITLE
Add linting for to_json

### ISSUE THREAD

**Issue by allcentury** [rubocop-hq/rubocop#6378]
**Is your feature request related to a problem? Please describe.**

classes that override `to_json` need to ensure an optional parameter is
available.

```ruby
class MyClass
  def to_json
  end
end
```

While calling `MyClass.new.to_json` works, calling
`JSON.generate(MyClass.new)` results in an `ArgumentError`. That's because the ruby `JSON` api wants to send additional options (via a hash) to `to_json`, ie `to_json(opts = {})`

**Describe the solution you'd like**

I'd like a linter to catch this as it's not obvious from the ruby JSON docs.

**Describe alternatives you've considered**

**Comment by bquorning** [comment]
> That's because the ruby `JSON` api wants to send additional options (via a hash) to `to_json`, ie `to_json(opts = {})`

Are you sure the argument is a Hash?

```rb
require 'json'
class MyClass
  def to_json(*args)
    p args
    ""
  end
end
JSON.generate(MyClass.new)
#=> [#<JSON::Ext::Generator::State:0x00007faacb155a40>]
```

**Comment by allcentury** [comment]
@bquorning thanks for calling that out - it currently returns a hash-like object: 

https://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html#method-i-generate

from the docs:


    Generate a JSON document from the Ruby data structure obj and return it. state is

    a JSON::State object,

    or a Hash like object (responding to to_hash),

    or an object convertible into a hash by a to_h method, that is used as or to configure a State object.


Using a default of `{}` felt sane, because the api of `State` acts like a hash:

```ruby
[6] pry(#<MyClass>)> args
=> #<JSON::Ext::Generator::State:0x00007fc4959e2af8>
[7] pry(#<MyClass>)> args[:indent]
=> " "
[8] pry(#<MyClass>)> args.to_hash
=> {:indent=>" ", :space=>"", :space_before=>"", :object_nl=>"", :array_nl=>"", :allow_nan=>false, :ascii_only=>false, :max_nesting=>100, :depth=>0, :buffer_initial_length=>1024}
```

that said perhaps just an argument with no default is enough, ie:

```ruby
def to_json(_opts)
end
```

What do you think?

**Comment by bquorning** [comment]
Weird then, that the signature for e.g. [`Date#to_json`](http://ruby-doc.org/stdlib-2.5.1/libdoc/json/rdoc/Date.html#method-i-to_json) says it accepts `*args`.

I found this old commit on Ruby where the documentation for `to_json` signature on `TrueClass`, `FalseClass` and `NilClass` is changed from `state=nil` to `*`: https://github.com/ruby/ruby/commit/e662770dc990a29c0182e8d043b6a5d72cc53f9c

Perhaps we should just recommend having `*` in the signature?
