### ISSUE TITLE
How it is possible to customize Rubocop to favor "if !" to "unless"? Please advise.

### ISSUE THREAD

**Issue by curious725** [rubocop-hq/rubocop#6404]
Of course, I know it goes against standard Ruby style guide but still is there an easy way to customize this behaviour?

**Comment by jonas054** [comment]
Not currently. It's also not clear how we could add a configuration option to the `Style/NegatedIf` cop for this preference. That's because the cop already has an `EnforcedStyle` parameter that's used for another purpose.
