### ISSUE TITLE
New rule idea: Rails/EnumNotNull

### ISSUE THREAD

**Issue by ndbroadbent** [rubocop-hq/rubocop#6416]
I just realized that I wasn't setting a NOT NULL constraint for any of my enum columns. This came to my attention when my API test returned `null` for one of my `state` columns, and I realized that `null` was never a valid value for this particular state column. I think it's a much better practice to define an integer value that represents nothing, e.g. `none: 0`, if that's necessary. This way you can also control the string value that represents `0`, and the ActiveRecord helper methods are consistent when you use a `_prefix`. E.g. you can call `model.foo_type_none?` instead of `!model.foo?` (which checks for the opposite of presence.)

Technically `nil` is a valid value for an enum column, and it just means that the column hasn't been defined yet. But I think that this will lead to errors more often than being a useful default.

My idea is to scan the Rails model source code for `enum` calls and parse out the attribute. It would find the following enums:

```ruby
class Model < ApplicationRecord
  enum state: {
    pending: 0,
    complete: 1,
  }

  enum :foo => %w[bar baz]
  enum 'bar' => %w[hello world]
  enum "baz" => %w[one last example]
end
```

Then it would raise 4 errors for the following migration:

```ruby
class CreateModels < ActiveRecord::Migration[5.2]
  def change
    create_table :models do |t|
      t.integer :state
      t.integer :foo
      t.integer :bar
      t.integer :baz
    end

    change_column_default :models, :state, from: 0, to: 0
    change_column_default :models, :foo, from: 0, to: 0
    change_column_default :models, :bar, from: 0, to: 0
    change_column_default :models, :baz, from: 0, to: 0
  end
end
```

Saying that all of the integer columns must be written as:

```ruby
      t.integer :state, null: false
      t.integer :foo, null: false
      t.integer :bar, null: false
      t.integer :baz, null: false
```

This would have been a very helpful heuristic for me, because I just forgot that integers can be nil, even when I'm setting the default to `0`. Obviously it wouldn't handle all of the cases (custom DSLs, metaprogramming, or calls to `add_column` and `change_column_null`), but it would be nice to catch 99% of these cases.

It would be nice if this was configurable option, and I wouldn't mind if it was disabled by default. But I'd definitely like to use it in my own projects.

**Comment by bbatsov** [comment]
We're in the process of moving all Rails-related functionality to a standalone library (gem) named `rubocop-rails`. Please, migrate this issue to its issue tracker https://github.com/rubocop-hq/rubocop-rails/issues/

**Comment by ndbroadbent** [comment]
Thanks, I moved it to https://github.com/rubocop-hq/rubocop-rails/issues/15
