### ISSUE TITLE
Why are the default rules so restrictive? Does anyone actually use the default Rubocop config in a real-world application?

### ISSUE THREAD

**Issue by ndbroadbent** [rubocop-hq/rubocop#6425]
I'm always frustrated when I use Rubocop out of the box, and I find it almost impossible (or at least very impractical) to write code that meets all of these default restrictions.

The default `Metrics/AbcSize` of 15 is far too low, and I always have to come up with creative solutions just to work around this limit. I think the code I write is actually worse and less maintainable, because the original method is perfectly fine, even if it's 20 lines long and a little bit complex... sometimes you just have to write complicated code. The maximum `Metrics/MethodLength` of 10 lines is extremely difficult to work around, and I don't know how people can build real-world applications with such extreme restrictions.

It would be great if Rubocop provided some sane rules out of the box. I think 99% of companies that use Rubocop are probably turning off most of these metrics, or increasing the limits. Otherwise their developers won't be able to get any work done.

Would it be possible to conduct some polls, or maybe request that companies submit their `.rubocop.yml` files? Then you could come up with a sane default config that most developers can feel comfortable with. I would really like to see what all of the big Ruby companies and agencies are doing. I've found quite a few config files that have been posted on the internet, and they all make lots of customizations and turn off plenty of rules.

I use the [Airbnb Javascript style guide](https://github.com/airbnb/javascript) for eslint, and I've been very happy with it. Everything makes sense and it doesn't feel too restrictive. It would be really nice if I could also feel comfortable using the default set of Rubocop rules without needing to turn off a bunch of things or increase all of the limits.

I would be very happy to be proven wrong, and I'm totally happy to change my coding style and follow all of the best practices, but only if it turns out that big companies and major projects are actually enforcing the default set of rules (e.g. Basecamp, GitHub, Airbnb, Stripe, Shopify). I just get the feeling that this default set of rules is not practical for real-world applications.

**Comment by ndbroadbent** [comment]
> In commercial projects, I never let RuboCop offenses fail the build.

@mvz Interesting, why did you decide on that? I've found it really helpful to enforce my Rubocop rules during CI, and I even enforce them with a git pre-commit hook before I commit any changes. ([Here is the git pre-commit hook I'm using](https://gist.github.com/ndbroadbent/3ee4e1b9740a381bd7ecc098eb9e090f). I run `rubocop -a` so 90% of the time any violations are automatically corrected.

It was very annoying when I was only failing the build, because I would get a notification 5-10 minutes later, and I already moved on to something else. But running it as a pre-commit hook has been really valuable. I also run Rubocop in my text editor, so I usually catch offenses as soon as they happen.

**Comment by mvz** [comment]
Regarding commit hooks:

I've tried using rubocop in a pre-commit hook, but it led to some problems. It's been a while, but as I recall:

- I used `overcommit` to set up the hooks and it kept breaking in strange ways.
- `git rebase` would be hell because offenses might suddenly be triggered and fail the rebase.

I also prefer not to be prevented from committing unfinished work. And in the red-green-refactor cycle, I want to commit as soon as it's green, and not be forced to refactor first.

Using `rubocop -a` seems dangerous, since sometimes the autocorrections have bugs.

Regarding not using RuboCop to fail the build:

Style differences are not that important, functionally, and I'm fine with complexity getting larger temporarily. Because of that, I prefer an automated code review tools such as Hound or Pronto so issues can be ignored or not depending on external factors.

**Comment by ndbroadbent** [comment]
> I used overcommit to set up the hooks and it kept breaking in strange ways.

I'm just using a script that sets up a symlink, so that's been working fine.

> git rebase would be hell because offenses might suddenly be triggered and fail the rebase

Ah right, I'm not sure why I haven't run into that before, but it hasn't been an issue for me.

> I also prefer not to be prevented from committing unfinished work

Good point! I often commit something that isn't ready with "WIP" or "temp" and then switch to another branch. I just changed my `pre-commit` hook to a `commit-msg` hook, and now I'm skipping Rubocop if the commit message starts with: "WIP", "temp", or "tmp". ([I also updated the gist](https://gist.github.com/ndbroadbent/3ee4e1b9740a381bd7ecc098eb9e090f).)

> Using rubocop -a seems dangerous, since sometimes the autocorrections have bugs.

Another really good point. I should really review all the changes instead of committing them automatically. I've just updated the hook again so that any Rubocop violations will abort the commit, but it will still run `rubocop -a` and then ask me to review all of the automatic corrections.

> Style differences are not that important, functionally ... I prefer an automated code review tools such as Hound or Pronto

I agree they're not too important, but it's a real pain when you stop caring about them for a while and then you have go back and fix a lot of things. It took me about 4 days of full-time work just to fix all the errors when I introduced Rubocop to my existing codebase, so don't know want to let the quality slip again.

**Comment by mikegee** [comment]
> Does anyone actually use the default Rubocop config in a real-world application?

Yes. It's fine for new projects.

**Comment by bbatsov** [comment]
They weren't chosen totally arbitrarily, but in the early days when the project had few users we obviously didn't do much research on the defaults. :-) In a few how many complaints some of them would generate I would have definitely thought much more about them (and enabled way fewer cops out of the box). E.g. the rule about the 10-line methods came from the POODR if I recall correctly (or from some talk by Sandy). The AbcSize default was derived similarly. Clearly you'll always have some bigger/more complex methods, but the vast majority should easily fit inside those restrictions (if they are well designed that is ;-) ). 

One of the goal we have before 1.0 is to example and update carefully the default config, but that's going to be a lot of work...

**Comment by ndbroadbent** [comment]
Thanks for the feedback! I just read through [this post from Thoughtbot](https://robots.thoughtbot.com/sandi-metz-rules-for-developers) with advice from Sandi Metz, and they tried restricting themselves to 5-line methods. I thought 10 would be difficult, but 5 lines sounds pretty crazy.

That sounds good about the new default config for 1.0. My request is just to make it something that the majority of companies and developers are comfortable with, and if they want to be more restrictive they can still increase the limits.
