### ISSUE TITLE
Style/GuardClause when initializing a variable in the if body

### ISSUE THREAD

**Issue by ByJIKaHkaz** [rubocop-hq/rubocop#6435]
## Expected behavior

no offences

## Actual behavior

In this test code:

```
# frozen_string_literal: true

def fail
  if (i = 1 + 1) == 2
    i
  end
end

def ok
  loop do
    if (i = 1 + 1) == 2
      i
    end
  end
end

```

When checking the function `ok` there will be no error, but in the function `fail` we get `Style / GuardClause`. And this fix is ​​incorrect, because the variable `i` is not initialized under a postcondition.

```
Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.`
  if (i = 1 + 1) == 2
  ^^
```

## Steps to reproduce the problem

puts code in file or download it from [gist](https://gist.github.com/ByJIKaHkaz/9672cc5e4257d4ba9137f23da56d5986) and run on it `rubocop -a `

## RuboCop version

```
$ rubocop -V
0.60.0
```

**Comment by jonas054** [comment]
What `Style/GuardClause` wants is this:

```ruby
def fail
  return unless (i = 1 + 1) == 2

  i
end
```
You're not the first person to misunderstand what's meant by "guard clause", so perhaps we need to change the message to something more detailed and clear.

**Comment by mikegee** [comment]
> And this fix is ​​incorrect, because the variable `i` is not initialized under a postcondition.

Ruby's behavior around local variable scope violates the principle of least surprise sometimes. @jonas054 example actually does work.
