### ISSUE TITLE
Proposal: add `EnforcedStyle: consistent` to Layout/SpaceInsideBlockBraces

### ISSUE THREAD

**Issue by searls** [rubocop-hq/rubocop#6446]
I'm writing a general-purpose rubocop config that's less picky than the defaults, but still wants to put _some_ constraints in place. I would like to know how y'all would feel about an `EnforcedStyle` for `Layout/SpaceInsideBlockBraces` that ensured only that spacing for blocks was consistent:

``` ruby
# The `consistent` style enforces that block braces are either both opened 
# and closed with space or both opened and closed without it.

# bad
some_array.each {puts e }
some_array.each { puts e}
some_array.each { |e| puts e}
some_array.each {|e| puts e }
some_array.each {|e| 
  puts e 
}

# good
some_array.each {puts e}
some_array.each { puts e }
some_array.each { |e| puts e }
some_array.each {|e| puts e}
some_array.each { |e| 
  puts e 
}
```

Thoughts on this? If this is possible to configure OOTB with Rubocop, please let me know!

**Comment by mikegee** [comment]
[The currently available configuration options](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutspaceinsideblockbraces) don't include an option that covers your proposed style. Making this style one of the available configuration options seems legit to me though. 👍

**Comment by searls** [comment]
I think this is still a good idea, but StandardRB would no longer need it ¯\_(ツ)_/¯
