### ISSUE TITLE
Style/RaiseArgs auto correction to invalid syntax

### ISSUE THREAD

**Issue by DMA57361** [rubocop-hq/rubocop#6509]
I'm running corrections over some older code that hasn't been looked after by Rubocop before, and I've just had the Style/RaiseArgs cop auto-correct a raise that used a dynamically assigned exception class into invalid code.

Specifically the line affected was equivalent to `raise klass.new('oh no')`

## Expected behavior

Correct to `raise klass, 'on no'`

## Actual behavior

The line is corrected to `raise , 'oh no'`

## Steps to reproduce the problem

Given this contrived `eg.rb` file:

```ruby
def do_a_thing
  klass = RuntimeError
  raise klass.new('oh no')
end
```

Run Rubocop corrections:

```
$ bundle exec rubocop --safe-auto-correct eg.rb
Inspecting 1 file
E

Offenses:

eg.rb:3:3: C: [Corrected] Style/RaiseArgs: Provide an exception class and message as arguments to raise.
  raise klass.new('oh no')
  ^^^^^^^^^^^^^^^^^^^^^^^^
eg.rb:3:18: E: Lint/Syntax: unexpected token tNL
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
  raise , 'oh no' ...


1 file inspected, 2 offenses detected, 1 offense corrected
```

The `eg.rb` file is left in this state:

```ruby
def do_a_thing
  klass = RuntimeError
  raise , 'oh no'
end
```

## RuboCop version

```
$ bundle exec rubocop -V
0.60.0 (using Parser 2.5.3.0, running on ruby 2.3.7 x86_64-darwin18)
```

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #6515.
