### ISSUE TITLE
unknown keywords: permitted_classes, permitted_symbols

### ISSUE THREAD

**Issue by reckerswartz** [rubocop-hq/rubocop#6517]
Testing Rails alpha with ruby-2.6.0-preview3
RuboCop added in gemfile from the master branch
--------

```
Error:Rubocop returned exit code: 2
stderr:
unknown keywords: permitted_classes, permitted_symbols
/home/user/.rvm/rubies/ruby-2.6.0-preview3/lib/ruby/2.6.0/psych.rb:328:in `safe_load'
/home//user/.rvm/gems/ruby-2.6.0-preview3@gemset/bundler/gems/rubocop-4d8cd4153928/lib/rubocop/config_loader.rb:189:in `yaml_safe_load'
/home/user/.rvm/gems/ruby-2.6.0-preview3@gemset/bundler/gems/rubocop-4d8cd4153928/lib/rubocop/config_loader.rb:162:in `load_yaml_configuration'
/home/user/.rvm/gems/ruby-2.6.0-preview3@gemset/bundler/gems/rubocop-4d8cd4153928/lib/rubocop/config_loader.rb:41:in `load_file'
/home/user/.rvm/gems/ruby-2.6.0-preview3@gemset/bundler/gems/rubocop-4d8cd4153928/lib/rubocop/config_loader.rb:83:in `configuration_from_file'
/home/user/.rvm/gems/ruby-2.6.0-preview3@gemset/bundler/gems/rubocop-4d8cd4153928/lib/rubocop/config_store.rb:44:in `for'
/home/user/.rvm/gems/ruby-2.6.0-preview3@gemset/bundler/gems/rubocop-4d8cd4153928/lib/rubocop/target_finder.rb:110:in `excluded_dirs'
/home/user/.rvm/gems/ruby-2.6.0-previ ...
```

## RuboCop version

0.60.0 (using Parser 2.5.3.0, running on ruby 2.6.0 x86_64-linux) from master branch

**Comment by koic** [comment]
> unknown keywords: permitted_classes, permitted_symbols

For these kwarg names change, The PR #6470 will not add the new conditional branch using `Gem::Version.new(Psych::VERSION)`. It is the same as for the following reasons.

> Because the kwargs API was not included in the latest stable psych gemrelease, 3.0.3:
https://github.com/ruby/psych/blob/v3.0.3/lib/psych.rb#L318
> It's only been a part of beta releases of the next minor.
> No real user will be affected by the API change.

https://github.com/ruby/psych/pull/378#issuecomment-437551151

Thank you.
