### ISSUE TITLE
Crash caused by InfiiniteLoop cop when empty scope declaration at bottom of class/module

### ISSUE THREAD

**Issue by hopsoft** [rubocop-hq/rubocop#6520]
When the `Style/InfiniteLoop` cop is enabled, rubocop crashes with an infinite loop detection on classes/modules with an empty placeholder for `protected` or `private`.

```ruby
class Example

  # nothing here yet
  private

end
```

The class above will trigger this error.

```sh
RuboCop::Runner::InfiniteCorrectionLoop: Infinite loop detected in /path/to/file.rb.
```
--------

## Expected behavior

If this is undesired syntax, a warning should be emitted rather than crashing and halting.

## Actual behavior

Rubocop crashes and halts.

## Steps to reproduce the problem

1. Enable the following cop
    ```yml
    Style/InfiniteLoop:
      Enabled: true
    ```
1. Create a class like the one above
1. Run rubocop

## RuboCop version

```
$ bundle exec rubocop -V
0.60.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin17
```

**Comment by Drenmi** [comment]
Note that this doesn't happen because of the `Style/InfiniteLoop` cop, which dictates the style for `while true` type loops. It happens because two RuboCop cops with conflicting styles keep auto-correcting the file back and forth. Figuring out which ones will require a bit of testing. 🙂

**Comment by shaicoleman** [comment]
The specific example above seems to work correctly with `0.62.0`, but here's another case where it fails:

```
class Example
      private

  def my_method; end
    end
```
