### ISSUE TITLE
Empty line is a code smell

### ISSUE THREAD

**Issue by yegor256** [rubocop-hq/rubocop#6525]
Would be great to prohibit empty lines inside method bodies: https://www.yegor256.com/2014/11/03/empty-line-code-smell.html

**Comment by agrimm** [comment]
There's other cops for methods that are too big.

**Comment by jaredbeck** [comment]
At first, I thought this was a bad idea, but then I looked through 100 of my own methods and found only 3 methods containing an empty line. All three were empty lines above comments. Two were `TODO:` comments, and one was explaining a few lines that should be extracted into their own method. So, in every case, it was something that I'd like to fix. So, I have to agree with Yegor. If someone built this cop, I would probably give it a try. That said, this cop would not be used by many people, perhaps fewer than 1%. So, maybe it should not be in rubocop core?

**Comment by pocke** [comment]
Maybe @yegor256's idea is good. But I think it is not RuboCop matter.
I think reek is better to implement this feature. https://github.com/troessner/reek
Reek is Ruby code smell detector.


By the way, I'm not sure this is good feature. Maybe this feature will be too noisy for many people.

**Comment by jaredbeck** [comment]
Also, the proposed cop would conflict with eg. `Layout/EmptyLineAfterGuardClause`, another reason for the former to be disabled by default.
