### ISSUE TITLE
Improved warning messages for unrecognized cop parameters

### ISSUE THREAD

**Issue by MatzFan** [rubocop-hq/rubocop#6533]
Enhancement described in [comment](https://github.com/rubocop-hq/rubocop/issues/6043#issuecomment-442052322) on #6043

Current warning messages do not state supported parameters for a given cop.

I would like to see warning messages of the following format:
`<cop> does not support <offending parameter> parameter. Supported parameters are: <list of supported parameters>`

This would improve UX, as currently `Warning: unrecognized parameter <cop>:<bad parameter>` gives no user feedback as to the supported options - I had assumed the error was a typo on my part in once case, for example.

Keep up the awesome work, you keep us honest :smile:

**Comment by Drenmi** [comment]
Definitely agree with this @MatzFan. 🙂 Are you interested in submitting a PR?

**Comment by MatzFan** [comment]
will give it a go.

**Comment by MagedMilad** [comment]
@Drenmi could I work on this? :smile:

**Comment by Drenmi** [comment]
Nice idea @MatzFan, and nice work @MagedMilad. I left a comment on your PR. 🙂
