### ISSUE TITLE
Cop detects unexpected special characters

### ISSUE THREAD

**Issue by doloopwhile** [rubocop-hq/rubocop#6536]
**Is your feature request related to a problem? Please describe.**

I'm sometimes frustrated when special character such as '\b' is unexpectedly mixed in codes.
It is known macOS's Japanese IME sometimes input '\b' (hidden) around Japanese characters.

**Describe the solution you'd like**

Creating new cop which find '\b' in codes and warn it.

**Describe alternatives you've considered**

Nothing

**Additional context**

Nothing

**Comment by bquorning** [comment]
> sometimes

Could you please provide a concrete code example where this new cop should detect something?
