### ISSUE TITLE
Style(?)/RegexRedundantDotAsterisk

### ISSUE THREAD

**Issue by kke** [rubocop-hq/rubocop#6543]
I've quite often bumped into something like `/.*foo.*/` or `/foo.*/` or /.*foo/`.

A leading, trailing or surrounding `.*` does nothing:

```
irb(main):001:0> "foo bar baz".match?(/.*bar.*/)
=> true
irb(main):002:0> "foo bar baz".match?(/bar.*/)
=> true
irb(main):003:0> "foo bar baz".match?(/bar/)
=> true
irb(main):004:0> "foo bar baz".match?(/.*bar/)
=> true
irb(main):005:0> "foo bar".match?(/.*bar.*/)
=> true
irb(main):006:0> "foo bar".match?(/.*foo/)
=> true
```

Performance-wise I think it is already handled by the regex engine because it makes almost zero impact on benchmark.

Copping regexes could be a slippery slope though.

**Comment by Drenmi** [comment]
Hi, @kke!

I have been spending quite a bit of time thinking about abstruse regular expressions lately. It's technically not Ruby, so I'd say it's probably out of scope for RuboCop, but I definitely think there's potential for another tool. It could also benefit from having some form of complexity check for regular expressions, in addition to linting rules like the one you described. 🙂

**Comment by bquorning** [comment]
> Performance-wise I think it is already handled by the regex engine because it makes almost zero impact on benchmark.

On short strings, `.*` matches very few characters and the performance impact is not noticeable. But on longer strings I’m seeing huge performance improvement by removing unnecessary globs:

```rb
require 'benchmark/ips'

Benchmark.ips do |x|
  long_string = 'foo bar baz ' * 1_000_000

  x.report("two .*s")         { long_string.match?(/.*bar.*/) }
  x.report("one leading .*")  { long_string.match?(/.*bar/)   }
  x.report("one trailing .*") { long_string.match?(/bar.*/)   }
  x.report("no .*")           { long_string.match?(/bar/)     }

  x.compare!
end
```

```
Warming up --------------------------------------
             two .*s     1.000  i/100ms
      one leading .*     1.000  i/100ms
     one trailing .*     1.000  i/100ms
               no .*   238.417k i/100ms
Calculating -------------------------------------
             two .*s      8.789  (±11.4%) i/s -     44.000  in   5.038491s
      one leading .*      8.704  (± 0.0%) i/s -     44.000  in   5.072076s
     one trailing .*      2.851  (± 0.0%) i/s -     15.000  in   5.282417s
               no .*      5.449M (± 6.2%) i/s -     27.180M in   5.010015s

Comparison:
               no .*:  5448632.1 i/s
             two .*s:        8.8 i/s - 619920.96x  slower
      one leading .*:        8.7 i/s - 626027.19x  slower
     one trailing .*:        2.9 i/s - 1910988.32x  slower
```

That said, I agree with @Drenmi that optimizing regular expressions is beyond the capabilities of RuboCop. The `ast` and `parser` gems are immensely useful in converting Ruby source code into a tree of `AST::Node` objects. But it doesn’t provide any advanced parsing tools for Regexp nodes.
