### ISSUE TITLE
Add `--safe-auto-correct` to documentation - very useful.

### ISSUE THREAD

**Issue by parreirat** [rubocop-hq/rubocop#6569]
Version - `0.61.1 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin17)`

**Is your feature request related to a problem? Please describe.**

Not related to any problem. Just a really useful feature that should be more advertised.

**Describe the solution you'd like**

Adding it to:
- https://github.com/rubocop-hq/rubocop/wiki/Automatic-Corrections
- https://github.com/rubocop-hq/rubocop/blob/36404b40cbdac743b596c8520877c4ca3eee5691/manual/basic_usage.md

**Comment by jaredbeck** [comment]
Docs added by https://github.com/rubocop-hq/rubocop/pull/6583/commits/8581c7a44d9f313a0274caa0fe7830fabbcb0e49 in https://github.com/rubocop-hq/rubocop/pull/6583

**Comment by tejasbubane** [comment]
I guess this issue can be closed.

**Comment by pocke** [comment]
@tejasbubane Thank you!
