### ISSUE TITLE
Naming/PredicateName suggest invalid rename

### ISSUE THREAD

**Issue by thomthom** [rubocop-hq/rubocop#6575]
Naming/PredicateName can currently suggest an invalid rename of a method.

Example code snippet:

```ruby
class BoundingBox
  # ...
  def is_2d?
    @points.size == 4
  end
end
```

--------

## Expected behavior

I expect RuboCop to suggest a method name which is valid Ruby syntax. Or simply allow `is_` prefix when the remainder starts with a number.

## Actual behavior

```
modules/boundingbox.rb:35:9: C: Naming/PredicateName: Rename is_2d? to 2d?.
```

However, if one were to perform the suggested rename you'll get SyntaxError:

```
SyntaxError: (irb):1: syntax error, unexpected tINTEGER
```

## Steps to reproduce the problem

```ruby
class BoundingBox
  # ...
  def is_2d?
    @points.size == 4
  end
end
```

## RuboCop version

```
0.61.1 (using Parser 2.5.3.0, running on ruby 2.2.6 x64-mingw32)
```

**Comment by Drenmi** [comment]
Great point @thomthom. Thanks for the report! 🙇

**Comment by tejasbubane** [comment]
@Drenmi I have raised a PR for this - https://github.com/rubocop-hq/rubocop/pull/6663
