### ISSUE TITLE
"coverage not found" readme badge

### ISSUE THREAD

**Issue by matkoniecz** [rubocop-hq/rubocop#6592]
Either coverage counter should be fixed or badge should be removed

**Comment by MagedMilad** [comment]
@matkoniecz created a simple PR so fix the coverage badge, could you check that?

**Comment by matkoniecz** [comment]
Fromwhat I see at https://github.com/rubocop-hq/rubocop/blob/93792f0bacfe9cee41d1ba6bc9f706b28fd6ab77/README.md - PR #6593 fixes this issue.
