### ISSUE TITLE
0.62 - Passing list of files and directories on command line fails

### ISSUE THREAD

**Issue by ccasabona** [rubocop-hq/rubocop#6620]
Starting with 0.62, entering a list of files or directories often results in zero files inspected.  We are using OS 10.14.2.

--------
## Expected behavior

The command:

`rubocop app`

in versions below 0.62 has resulted in rubocop reporting that it inspected all the files in the app directory.

## Actual behavior

Rubocop reports that it did not inspect any files.

`~/sites/saurus/saurus rubocop app/models
Inspecting 0 files

0 files inspected, no offenses detected
`

## Steps to reproduce the problem

Adding /** causes the command to work:

'
~/sites/saurus/saurus rubocop app/models/**
Inspecting 76 files
............................................................................

76 files inspected, no offenses detected
`

Adding the /** does not work for a single directory:

`~/sites/saurus/saurus rubocop app/**
Inspecting 0 files

0 files inspected, no offenses detected
`

## RuboCop version

~/sites/saurus/saurus rubocop -V
0.62.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin18)

**Comment by ccasabona** [comment]
To inspect just the files in a directory, this works:

`~/sites/saurus/saurus rubocop app/**/**
Inspecting 192 files
................................................................................................................................................................................................

192 files inspected, no offenses detected`

**Comment by ccasabona** [comment]
The command that works is

rubocop app/**/**

**Comment by ccasabona** [comment]
Git is taking out the asterisks.  The command I am using is 

> rubocop app/asteriskasterisk/asteriskasterisk

**Comment by rodrigomanhaes** [comment]
@ccasabona calling `rubocop app/**/*` overrides the `Exclude` definitions on config file.

**Comment by rodrigomanhaes** [comment]
I think this issue should be reopen.
