### ISSUE TITLE
AppVeyor CI breaking after Bundler 2.0 release

### ISSUE THREAD

**Issue by roooodcastro** [rubocop-hq/rubocop#6624]
## Expected behavior

I have an open PR (#6584) and its build should be passing on all checks.

## Actual behavior

The AppVeyor build is failing because [bundler got updated to 2.0.0 today](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html) and it no longer supports Ruby versions <2.3, so this breaks the build for `ruby_version=22` and `ruby_version=22-x64`.

This new bundler version also requires the rubygems version to be at least 3.0.0, and `appveyor.yml` explicitly specifies version `2.6.14`, so all other builds also fail because of that (for Ruby versions 2.3 through 2.5).

## Steps to reproduce the problem

I think that any new push to an open PR from today will fail because of this, so just open a new PR I guess?

## RuboCop version

Not relevant.

**Comment by bquorning** [comment]
I’ll take a look later today.
