### ISSUE TITLE
Passing directory to rubocop doesn't work

### ISSUE THREAD

**Issue by tiagotex** [rubocop-hq/rubocop#6625]
On CI we only want to run rubocop in a few directories, to achieve this we pass the directories paths as arguments, as specified in the manual:

```
Alternatively you can pass rubocop a list of files and directories to check:

$ rubocop app spec lib/something.rb
```
[source](https://docs.rubocop.org/en/latest/basic_usage/)

Since we updated rubocop 0.61.1 → 0.62.0 this stopped working, as you can see bellow, if we pass a directory as an argument rubocop will stop inspecting all files.

I've narrowed down the breaking change to this PR https://github.com/rubocop-hq/rubocop/pull/6546

I will poke around and try to fix it.

--------

## Expected behavior

```
=> rubocop app
Inspecting 911 files
```
`app` is one of the directories of the project

## Actual behavior

```
=> rubocop app
Inspecting 0 files
```
`app` is one of the directories of the project

I did some experiments and using `../main_directory/app` somehow fixes the problem.`./app` still has the same problem

```
=> rubocop ../project/app
Inspecting 911 files
``` 

## Steps to reproduce the problem

Run `rubocop directory_path`

## RuboCop version

```
0.62.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin18)
```

**Comment by bbatsov** [comment]
Yeah, the moment I saw the title I was pretty sure it was broken by this change. I'll give you and @AlexWayfer some time to see if that's something easy to fix, otherwise I'll revert the PR and issue a bugfix release.

**Comment by roooodcastro** [comment]
The `--modified` flag [here in the PR](https://github.com/rubocop-hq/rubocop/pull/6546/files#diff-af441552566679e9498e0a466229a484R107) is a likely culprit. Without it, the `ls-files` command will return all of the files versioned by git, but with it, it will only return the modified and **unstaged** ones.

**Comment by tiagotex** [comment]
@roooodcastro I think that might be another problem, the problem described in this PR is that the files found `ls_git_files` does not have the same prefix as `all_files`.

That might be another problem, how do you get that problem?

**Comment by AlexWayfer** [comment]
I'm sorry for this. I can try to help, but I see opened PR and I'm grateful, I'll watch it.

**Comment by jcouball** [comment]
I have a similar problem: since upgrading from 0.61.1 to 0.62.0, when I run Rubocop without any arguments, it does not inspect any files in my project.

with 0.61.1:

```
$ bundle exec rubocop
Inspecting 13 files
.............

13 files inspected, no offenses detected
$
```

with 0.62.0:

```
$ bundle exec rubocop
Inspecting 0 files


0 files inspected, no offenses detected
$
```

**Comment by jcouball** [comment]
> > I have a similar problem: since upgrading from 0.61.1 to 0.62.0, when I run Rubocop without any arguments, it does not inspect any files in my project.
> 
> Is this directory Git-repository?

Correction: after reading PR #6546, I understand the question better.  This directory IS in an ignored directory within a git repository.

Some context:

I am working on a Cookiecutter template that generates a Ruby project.  To test the template, I have Cucumber/Aruba tests that generates a new Ruby project using the Cookiecutter template with various combinations of input. The tests runs bundle install, rubocop, rspec, etc. within the generated project.

After looking at PR #6546, I think the problem is that Aruba runs commands in my project's `tmp/aruba` directory and I have `tmp` in my .gitignore

For my use case, PR #6546 breaks Rubocop.  

FWIW, I agree with @bbatsov and others who suggested that feature not be enabled by default.

Is there a way to configure this to work in my use case?

**Comment by bbatsov** [comment]
I've just reverted this feature and I'll issue a bugfix release soon.

**Comment by AlexWayfer** [comment]
I apologize to all of you about problems with `git` integration. I'll try to be smarter and more careful.
