### ISSUE TITLE
Error running "rubocop --require rubocop-rspec"

### ISSUE THREAD

**Issue by mellansquare** [rubocop-hq/rubocop#6634]
I'm trying to update rubocop after getting the following deprecation warning when running my spec:

> "DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:

```ruby
admin { true }
```

> To automatically update from static attributes to dynamic ones,
> install rubocop-rspec and run:
>
> rubocop \
>  --require rubocop-rspec \
>  --only FactoryBot/AttributeDefinedStatically \
>  --auto-correct"

I've installed the rubocop gem successfully but when I run 'rubocop --require rubocop-rspec" as above I get a failure.  

Mention the following information in the issue report:
0.61.1 (using Parser 2.5.3.0, running on ruby 2.3.4 x86_64-linux)`

It's actually much longer but I'm not sure how to get the whole backtrace to come up in the terminal so I can copy/paste it across.

Thanks!

**Comment by mellansquare** [comment]
Thanks! I'm a total beginner. Does it matter where I put the .rubocop.yml file?

**Comment by tejasbubane** [comment]
@mellansquare Ref: https://rubocop.readthedocs.io/en/latest/configuration/

> RuboCop will start looking for the configuration file in the directory where the inspected file is and continue its way up to the root directory.

Best place would be the project root directory if you want the config to be applicable to the entire project.

**Comment by Drenmi** [comment]
@mellansquare I hope the directions provided solved your issue. If not, feel free to re-open. 🙇
