### ISSUE TITLE
promote Performance/LstripRstrip to Style/LstripRstrip

### ISSUE THREAD

**Issue by matkoniecz** [rubocop-hq/rubocop#6637]
Unlike many other Performance cops `Performance/LstripRstrip` is not making code less readable and is a good idea independent from performance improvements.

As  #5977 will cause performance cops to be disabled by default I suggest to rescue this one as it is useful to avoid `lstrip.rstrip` where `strip` that is more readable and shorter exists.

It may be also useful to expand description with a note that this change may improve performance (as it would no longer be implied)

------

Other usual issue fields are not applicable - I spotted it during reviewing https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

**Comment by matkoniecz** [comment]
https://github.com/rubocop-hq/rubocop/pull/6636 is an example of pull moving between categories

**Comment by Drenmi** [comment]
Thanks for pointing this out, @matkoniecz. 🙇 Unless there's any unexpected behaviour or Ruby warnings from using `#lstrip` + `#rstrip`, it should go in the `Style` department, but moving it out of `Performance` seems like a good idea nonetheless.
