### ISSUE TITLE
Performance/RangeInclude is not safe

### ISSUE THREAD

**Issue by viktors** [rubocop-hq/rubocop#6641]
`Performance/RangeInclude` should not suggest to use `Range#cover?` instead of `Range#include?`  in safe mode, nor should it auto-correct it in safe mode, because they don't provide equal results.

```
#!/usr/bin/env ruby
# frozen_string_literal: true

p ('a'..'b').include?('aa') # false
p ('a'..'b').cover?('aa') # true
```

--------

## Expected behavior

`Performance/RangeInclude` should not run in safe mode.

## Actual behavior

`Performance/RangeInclude` replaces `Range#include?` with `Range#cover?`.

## Steps to reproduce the problem

See example script above.

## RuboCop version

```
$ rubocop -V
0.62.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin17)
```

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #6647.
