### ISSUE TITLE
Load user-specific settings from XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by FranklinYu** [rubocop-hq/rubocop#6662]
**Is your feature request related to a problem? Please describe.**

I don’t like to clutter my home directory, and I only synchronize my `XDG_CONFIG_HOME`.

**Describe the solution you'd like**

If the file `~/.rubocop.yml` is missing, check whether environment variable `$XDG_CONFIG_HOME` is defined. If yes, then load from `$XDG_CONFIG_HOME/rubocop/config.yml`; otherwise load from `~/.config/rubocop/config.yml`.

**Describe alternatives you've considered**

N/A

**Additional context**

Latest standard specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.8.html
Arch Linux Wiki: https://wiki.archlinux.org/index.php/XDG_Base_Directory

I can try PR if anyone is interested.

**Comment by bbatsov** [comment]
PRs welcome!

**Comment by FranklinYu** [comment]
I'm not familiar with the code base, but a simple search indicates that I should do it here:

https://github.com/rubocop-hq/rubocop/blob/19845704d148918eb9d7e8d00e1892fc7111854d/lib/rubocop/file_finder.rb#L43-L44

I'm still wondering whether `FileFinder` is used anywhere besides configuration loading? If so, modifying this file may affect other functions.

**Comment by FranklinYu** [comment]
This is closed by #6895 IIUC. Thanks!
