### ISSUE TITLE
Another wrong auto-correct by Style/SafeNavigation

### ISSUE THREAD

**Issue by buehmann** [rubocop-hq/rubocop#6670]
rubocop 0.62.0 autocorrects
```ruby
foo.bar unless foo
```
into
```ruby
foo&.bar
```
which changes the behaviour of the code. (In fact, `foo.bar if foo` is auto-corrected to the very same result.)

Admittedly, the `foo.method unless foo` construct seems very rare because if effectively calls the method on `nil` or `false` only. (In our case, this wrong auto-correction actually revealed a long-standing bug). But rubocop should avoid changing the meaning of code.

**Comment by bquorning** [comment]
I’m able to reproduce this bug.

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #6672.
