### ISSUE TITLE
Performance/ChainArrayAllocation -> map!, flatten!, and compact! return nil if unmodified

### ISSUE THREAD

**Issue by jackphelps** [rubocop-hq/rubocop#6684]
The [Performance/ChainArrayAllocation cop](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/performance/chain_array_allocation.rb) suggests `map!`, `flatten!`, and `compact!` over their non-mutating counterparts when following another new array allocation. However, each of these methods returns `nil` if they don't modify the array, rather than returning the array itself. This seems unsafe.

--------

## Expected behavior

I expect it to suggest performance improvements that don't change behavior. In this case, the non-mutating methods always return the resulting array.

## Actual behavior

Following the cop's suggestions might return the modified array, but might return `nil` if the array was not modified. See documentation for the methods, e.g. here: https://ruby-doc.org/core-2.5.1/Array.html#method-i-uniq-21

I don't remember if this behavior was different at some point, but not recently.

## Steps to reproduce the problem

```
[1,2].map{|i|i}.uniq
=> [1,2]
[1,2].map{|i|i}.uniq!
=> nil
```

## RuboCop version

```
rubocop -V
0.63.0 (using Parser 2.6.0.0, running on ruby 2.5.0 x86_64-darwin17)
```

## THANK YOU FOR ALL YOUR HARD WORK 🚀 🦄 💖 
I can submit a PR if you'd like, haven't gotten to contribute here before.

**Comment by Drenmi** [comment]
Thanks for the report! 🙂 

> I can submit a PR if you'd like, haven't gotten to contribute here before.

The performance cops don't really receive a lot of love, so feel free to have a go at it. Any help is greatly appreciated. Feel free to reach out to me if you need help. You can find my e-mail on my profile. 🙂

**Comment by pocke** [comment]
I think this cop's behaviour is correct, but the message is not good.
You can separate method calls with bang to avoid nil.
The documentation says:

```ruby
# bad
array = ["a", "b", "c"]
array.compact.flatten.map { |x| x.downcase }

# good
array = ["a", "b", "c"]
array.compact!
array.flatten!
array.map! { |x| x.downcase }
array
```

https://github.com/rubocop-hq/rubocop/blob/19d65afe162a5c095d81fd69982c1308fbbf9b46/lib/rubocop/cop/performance/chain_array_allocation.rb#L6-L22


But the cop just says "Use compact...flatten! instead of compact...flatten.".  It is misleadding.
