### ISSUE TITLE
Prefer `block_given?` to `iterator?`

### ISSUE THREAD

**Issue by znz** [rubocop-hq/rubocop#6688]
**Is your feature request related to a problem? Please describe.**

[The <code>iterator?</code> form is mildly deprecated](https://github.com/ruby/ruby/blob/d3c0b20949916aa7b432a0498a8016d67a7822ad/vm_eval.c#L2101-L2102).

**Describe the solution you'd like**

Recommend to use `block_given?` instead of `iterator?`.

**Additional context**

- [Prefer block_given? to iterator?](https://github.com/ruby/ruby/commit/c20aae965e2e79fcf4c443b266f7012157d5b23b)
- [Feature #15547 deprecate iterator?](https://bugs.ruby-lang.org/issues/15547)

**Comment by Drenmi** [comment]
Oh, wow. That is some old stuff. Had never heard about this alias before. 🙂

**Comment by tejasbubane** [comment]
I assume this would go in a new `Lint/BlockGiven` cop. Or is there a better place in existing cops? @Drenmi

**Comment by koic** [comment]
I think we can create the new `Lint/KernelIteratorPredicate` cop, which will be the deprecated method name.
