### ISSUE TITLE
test-queue + simplecov + Ruby 2.2/2.3/2.4 is slow

### ISSUE THREAD

**Issue by bquorning** [rubocop-hq/rubocop#6694]
I’ve found that `COVERAGE=true rake spec` runs slow on Ruby 2.2, 2.3, and 2.4.

As an experiment, I ran `rake spec` with and without `COVERAGE=true` on our CI, and got these numbers:

| Ruby  | Without coverage | With coverage |
| ---   | ---              | ---           |
| 2.2   | 0:28             | **1:31**      |
| 2.3   | 0:24             | **1:29**      |
| 2.4   | 0:23             | **1:24**      |
| 2.5   | 0:22             |  0:27         |
| 2.6   | 0:21             |  0:32         |
| head  | 0:21             |  0:31         |
| jruby | 2:12             |  2:31         |

Now I tried running `rspec` (to avoid using the parallel runner, test-queue) with and without coverage:

| Ruby  | Without coverage | With coverage |
| ---   | ---              | ---           |
| 2.2   | 0:51             | 0:50          |
| 2.3   | 0:43             | 0:53          |
| 2.4   | 0:42             | 0:42          |
| 2.5   | 0:42             | 0:42          |
| 2.6   | 0:39             | 0:37          |
| head  | 0:38             | 0:39          |
| jruby | 2:18             | 2:35          |

As you can see, the combination of test-queue, simplecov, and Ruby 2.2/2.3/2.4 is slow. What can we do about it?

 1. Don't collect coverage data on Ruby 2.2, 2.3 and 2.4.
 2. Don't use test-queue on Ruby 2.2, 2.3 and 2.4.
 3. Don't collect any coverage data at all.

I lean most towards 3, not least because the others require adding special cases to the CI config. A few more options

 4. Only collect code coverage on the master branch (i.e. after each merge)
 5. Only collect code coverage on the master branch, in a scheduled daily CI run.

Which option is right depends on how code coverage is currently used. Does anyone go to Code Climate and verify that a PR doesn’t reduce code coverage? If so, we should probably move towards adding an integration instead (https://docs.codeclimate.com/docs/workflow)

**Comment by bquorning** [comment]
@koic @Drenmi I would like to hear your input on this issue.

**Comment by koic** [comment]
Thanks for early catch up and sharing 👍 

Currently, I cannot make effective use of coverage at this repository 💦 On the other hand, parallel testing seems to work effectively. So if I had to say then I will choose 3.
But it is not yet considered a big issue yet at present to me.

BTW, I'm curious that Appveyor matrix is slower than CircleCI matrix and it may be good to consider dropping the Appveyor from the CI matrix.

And I was wondering if there is the similar problem in other repositories that use test-queue + simplecov + Ruby 2.2/2.3/2.4. If you'd like to report to either (or both test-queue and simplecov), something change may come.

**Comment by deivid-rodriguez** [comment]
I do like checking code coverage on PRs in my repos, it helps me find out uncovered or dead code. But when I've setup repos to do so, I've indeed used codeclimate's integration, or [its browser extension](https://codeclimate.com/browser-extension/).

Given the results you've shown, it sounds like a problem with the coverage core library that has been resolved in recent rubies, right?

**Comment by Drenmi** [comment]
I like having the coverage reported, because it can be used as an indication to and an evaluation criteria for people who are reading the RuboCop `README` for the first time.

**Comment by koic** [comment]
I reduced the matrix of Appvayor at #6718. I think that this issue can be closed because CI speed is comfortable now (And still the bottleneck to the whole CI matrix is Appvayor matrix) . Thank you all for your opinion ❤️
