### ISSUE TITLE
Add a cleanup task to the Rubocop CLI

### ISSUE THREAD

**Issue by mberlanda** [rubocop-hq/rubocop#6716]
**Is your feature request related to a problem? Please describe.**

It happens when performing major code refactoring, that some dead references in `.rubocop.yml` or `rubocop-todo.tml`.

Sometimes is not that easy to detect and we keep useless exceptions in large projects.

**Describe the solution you'd like**

I would like to be able to run some command like `bundle exec rubocop --dead-references` or `bundle exec rubocop --cleanup`

**Describe alternatives you've considered**

Since this option is not available, I did this perl script to parse my configuration files and lookup for existing files. You can find it here:

https://gist.github.com/mberlanda/3769af5af844fdc82fbf9d55f7e250f3

**Additional context**

I am willing to create a pull request adding this feature if you consider it a value added to the gem (of course I would rewrite the logic in ruby)

**Comment by bquorning** [comment]
I think there are arguments for and against this feature.

“Configuration clean-up” clearly isn’t the core feature of RuboCop. Its main concern should be to read config, and check Ruby syntax.

But I think this is a decent nice-to-have feature. So if the Ruby implementation is pretty simple, I guess a PR would get accepted.

**Comment by rrosenblum** [comment]
This sounds similar to what is accomplished with `rubocop --auto-gen-config`. All offenses for the project will be re-evaluated and new config files will be generated. This included updating the number of offenses and removing references to files that no longer exist.

**Comment by mberlanda** [comment]
It looks like the most appropriate usage of rubocop config files is `.rubocop.yml` for passing options or disabling cops, and the `.rubocop_todo.yml` to collect exceptions.

In this scenario, `--auto-gen-config` is more than enough.

Most of the projects I joined did not respect this convention, but it is not so difficult to cleanup those files. I would close the issue then.

If anyone need some cleanup, you can find in the issue description a link to the gist with the snippet I am currently using.
