### ISSUE TITLE
Layout/EndOfLine does not choose correct default line ending

### ISSUE THREAD

**Issue by enkessler** [rubocop-hq/rubocop#6720]
The Layout/EndOfLine cop automatically decides the 'correct' line ending when set to `:native`. However, the logic used to make that decision does not come to the correct answer when using JRuby. The check being used is `RuboCop::Platform.windows?` which just does an inspection of `RUBY_PLATFORM`:

`RUBY_PLATFORM =~ /cygwin|mswin|mingw|bccwin|wince|emx/`

However, when using JRuby the value of `RUBY_PLATFORM` will be `java`, even when using Windows. This results in the cop deciding that it is in a non-Windows environment and thus check for 'lf' line endings instead of 'crlf'.

--------

## Expected behavior

The Layout/EndOfLine cop should natively use 'crlf' line endings for Windows with JRuby.

## Actual behavior

The Layout/EndOfLine cop natively uses 'lf' line endings for Windows with JRuby.

## Steps to reproduce the problem

- use Windows
- use JRuby (9.1.17, in my case)
- have a Ruby file with crlf line endings

Run rubocop against the file and the generated report will contain violations for Layout/EndOfLine.

## RuboCop version

`0.63.1 (using Parser 2.6.0.0, running on jruby 2.3.3 java)`
--

**Comment by mikegee** [comment]
Do you know how Rubocop can know the correct line ending on JRuby?

**Comment by enkessler** [comment]
Using `RbConfig::CONFIG['host_os']` instead of using `RUBY_PLATFORM` seems to be [the way](https://idiosyncratic-ruby.com/42-ruby-config.html). I get `'mswin32'` when I check it instead of getting `'java'`, like I do `RUBY_PLATFORM`.

**Comment by Drenmi** [comment]
Thanks for the report and investigation @enkessler! 🙇 Would you be interested in opening a PR for this?

**Comment by enkessler** [comment]
I can take a crack at it some time this week, sure.
