### ISSUE TITLE
Metrics/BlockLength not respecting 'Max' parameter

### ISSUE THREAD

**Issue by peterzhu2118** [rubocop-hq/rubocop#6728]
I have the following set in my `.rubocop.yml`:
```yaml
Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 50
```

The max length of a block allowed should be 50 lines long, however it gives me an error for a block that is 28 lines long:
```
config/environments/development.rb:3:1: C: Metrics/BlockLength: Block has too many lines. [28/25]
Rails.application.configure do ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I have verified that the `.rubocop.yml` is a valid YAML. I have also verified this also occurs on CI. I'm running rubocop version 0.63.1.

## Expected behavior

No error outputted.

## Actual behavior

See above.

## Steps to reproduce the problem

See above.

## RuboCop version

```
$ rubocop -V
0.63.1 (using Parser 2.6.0.0, running on ruby 2.5.1 x86_64-linux)
```

**Comment by pocke** [comment]
Could you give me more information? I cannot reproduce it.

```bash
$ rubocop -V
0.63.1 (using Parser 2.6.0.0, running on ruby 2.7.0 x86_64-linux)

$ cat .rubocop.yml
Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 50

$ cat test.rb
foo do
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
  a
end
```

```
$ rubocop
Inspecting 1 file
C

Offenses:

test.rb:1:1: C: Metrics/BlockLength: Block has too many lines. [51/50]
foo do ...
^^^^^^

1 file inspected, 1 offense detected
```


Specifing `Max` works well on my local machine.

**Comment by peterzhu2118** [comment]
@pocke @koic I've created a [repo](https://github.com/peterzhu2118/rubocop-problem) to demo this issue. I've also [set up CI](https://circleci.com/gh/peterzhu2118/rubocop-problem/2) on that repo to show the problem.

**Comment by peterzhu2118** [comment]
Ah I figured it out, I accidentally put `Metrics/BlockLength` twice in my `.rubocop.yml`, the second one took precedence over the first.

**Comment by pocke** [comment]
I see. Thanks for your reporting! @peterzhu2118
