### ISSUE TITLE
Style/NumericLiterals autocorrect is not safe

### ISSUE THREAD

**Issue by JoeCohen** [rubocop-hq/rubocop#6734]
Style/NumericLiterals autocorrector is not safe.  
--------

In particular, it is not safe to correct `== 0` to `.zero?` because
`nil == 0` => `false`
whereas
`nil.zero?` => NoMethodError: undefined method `zero?' for nil:NilClass

There's no way that RuboCop could differentiate cases where correction would be safe from those where it's unsafe.

Therefore, the style corrector should be tagged as unsafe. It would also make sense to add to the documentation a sentence explaining why autocorrection is unsafe.

**Comment by JoeCohen** [comment]
Alternatively:
-  the cop could ignore `zero?` in the same way it ignores `nonzero?`
- the cop could flag ` == 0`, but the autocorrect would leave it alone.

My preference is simply to tag the autocorrect as unsafe. Having RuboCop make the correction at the same time as it's correcting ` > 0` and ` < 0` is a big time saver.

If you let me know how you'd like to proceed I will try to create a PR.

**Comment by Drenmi** [comment]
@JoeCohen I'm okay with marking auto-correct as unsafe. PR greatly appreciated. 🙇

**Comment by JoeCohen** [comment]
Closing the Issue. I misread the Manual: I meant **Style/NumericPredicate** buI was looking at **Style/NumericLiterals**.
**Style/NumericPredicate** already does exactly what I requested.
My apologies.
