### ISSUE TITLE
Docs are transformed, leading to incorrect examples.

### ISSUE THREAD

**Issue by JoshCheek** [rubocop-hq/rubocop#6744]
The issue
---------

On [this](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/IndentHeredoc) page for `Layout/IndentHeredoc`, the docs show this example, which makes it seem like RuboCop wants to replace string literals with heredocs, if they end in a newline.

![image](https://user-images.githubusercontent.com/77495/52447972-06738200-2af8-11e9-8a1d-6458173f9500.png)

After contemplating it for several minutes, I decided it must be wrong. Checking the source [code](https://github.com/rubocop-hq/rubocop/blob/24e2c79f5735b2d6c9943b7bdd686cd143cbb3f2/lib/rubocop/cop/layout/indent_heredoc.rb#L15-L25) we see this is the case:

![image](https://user-images.githubusercontent.com/77495/52448158-a29d8900-2af8-11e9-8e73-a6a20ecd84c5.png)

While making this issue, I discovered that those were not the official docs, which are at [docs.rubocop.org](https://docs.rubocop.org/en/latest/cops_layout/#layoutindentheredoc) and are correct. But, bear with me, I still think RuboCop should care because it was much much easier to find these docs than the official ones. This is what Google returned, the real docs aren't even in the search results:

![image](https://user-images.githubusercontent.com/77495/52448601-0ffde980-2afa-11e9-9ae0-15433bd52513.png)

Even after I found the [real](https://docs.rubocop.org/en/latest/cops_layout/#layoutindentheredoc) docs, I couldn't find the second link by searching:

![image](https://user-images.githubusercontent.com/77495/52448637-286e0400-2afa-11e9-8d73-5dfdea574154.png)

Analysis
--------

So it seems like RuboCop should either make it easier for the real docs to be found, or for their docs to be rendered correctly by 3rd party doc sites. Here are things I'd look into:

* Maybe the docs should contain a link to the official ones so that no matter where I find them, I can get back to the correct ones.
* Maybe this is happening because of some configuration within Rubocop that needs to be modified (it's hard for me to imagine they would transform your code samples)
* Maybe there's some SEO protocol the official site isn't following which is why it doesn't show up in the search results.

**Comment by marcotc** [comment]
[rubydoc.info](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/IndentHeredoc) is now correct, maybe they refreshed their software or something 🤔.
