### ISSUE TITLE
Style/StderrPuts isn't the same thing when there is no message

### ISSUE THREAD

**Issue by chrisseaton** [rubocop-hq/rubocop#6746]
## Expected behavior

Not to replace `$stderr.puts` (with no argument) with `warn` (with no argument) because they don't do the same thing - the former prints a new line, the latter prints nothing.

## Actual behavior

`$stderr.puts` (with no argument) is replaced with `warn` (with no argument).

## Steps to reproduce the problem

A file with just `$stderr.puts` (with no argument) in, compared to a file with just `warn` (with no argument) in. They don't do the same thing, but Rubocop suggests I swap from the former to the latter, and does so automatically if asked to fix.

This breaks real specs I have.

## RuboCop version

```
$ rubocop -V
0.63.1 (using Parser 2.6.0.0, running on ruby 2.6.1 x86_64-darwin18)
```

**Comment by kke** [comment]
I think this is also a ruby bug and filed an issue about it to: https://bugs.ruby-lang.org/issues/15596

```
> warn
=> nil
> warn nil

=> nil
```

Kernel#warn is written in C and does not act like a regular Ruby method that would have been defined as `def warn(msg = nil)` if it was Ruby. 

It's still a rubocop bug for TargetRubyVersions that do not have a fix for it (which is all versions until it's fixed at some point)

**Comment by chrisseaton** [comment]
I think it's more like

```
def self.warn(*messages)
  messages.each do |m|
    $stderr.puts m
  end
end
```

Which is why it doesn't print anything for no message.

**Comment by luciamo** [comment]
I'm going to take a look at this issue and see if I can help ;)

**Comment by chrisseaton** [comment]
Thank you very much!
