### ISSUE TITLE
Support a way to disable formatting based style rules

### ISSUE THREAD

**Issue by orta** [rubocop-hq/rubocop#6750]
## Is your feature request related to a problem? Please describe.

Hello there, with [prettier-ruby](https://github.com/prettier/plugin-ruby), [rubyfmt](https://github.com/samphippen/rubyfmt) and [rufo](https://github.com/ruby-formatter/rufo) all starting to gain traction - I'd like to be able to easily tell RuboCop "please let another tool handle the formatting of my code"

This is a common pattern in JavaScript projects where code linters have plugins which exist to make the tools not step on each others feet:

- https://github.com/prettier/tslint-config-prettier
- https://github.com/prettier/eslint-plugin-prettier 

## Describe the solution you'd like

The simplest idea I had was that in the RuboCop config you could disable formatting in a similar way to how you can turn on rails support:

```
formatting: false
```

A more complex approach might be to knowingly delegate to specific formatters:

```
formatting: "prettier"
```

But I'm not really sure if there's enough value there to pulls its weight in the additional complexity. 

## Describe alternatives you've considered

These tools could ship there own RuboCop config ymls which users inherit from - the downside to this is that it ties any update to your formatter to your linter also (As new/renamed rules will then break until there's a new release of your linter)

There could also be a separate gem whose job it is to coordinate the two versions (like the plugins above) it's work, but it's a reasonable answer.

Is it worth having something like this is RuboCop instead though?

**Comment by kddeisz** [comment]
Is it possible to disable groups of cops, as in `Style/*`?

**Comment by bquorning** [comment]
I regularly use
```yaml
Metrics:
  Enabled: false
```
I would assume the same would work for `Style`.
