### ISSUE TITLE
Rails/Validation cannot autocorrect validation methods with parenthesis properly

### ISSUE THREAD

**Issue by robturtle** [rubocop-hq/rubocop#6800]
If you have a code like:

```ruby
validates_presence_of(:user, :address)
```

The autocorrection of `Rails/Validation` will generate code with incorrect syntax. 

## Expected behavior

```ruby
validates :user, :address, presence: true
```
## Actual behavior

```ruby
validates(:user, :address), presence: true
```

## Steps to reproduce the problem

2. inside an ActiveRecord class, insert line `validates_presence_of(:user, :address)`
3. call `rubocop -a`

## RuboCop version

```
$ [bundle exec] rubocop -V
0.65.0 (using Parser 2.5.3.0, running on ruby 2.5.3 x86_64-darwin16)
```

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #6807.
