### ISSUE TITLE
Not safe applied cops 'Style/Next' and 'Style/SafeNavigation' at the same time

### ISSUE THREAD

**Issue by blockchaining** [rubocop-hq/rubocop#6812]
Hello,

Running rubocop (0.65.0) on this code 'with the --safe-auto-correct option) break it : 

```
      user = User.where(email: email).first
      if user
        user.notifications.create(
          title: 'abc'
        )
      end
```

Result in :  

```
      next unless useruser&.notifications&.create(
        title: 'abc'
      )
```

Cops applied : "Style/Next" then "Style/SafeNavigation"
Code is broken by the "useruser" new variable, like both cops where applied on the same original code.

But, if i run those cops one after the other with the "--only" option, i got this result : 

```
      next unless user
      user.notifications.create(
         title: 'abc'
      )
```

No code broken, and "Style/SafeNavigation" become unnecessary.

Best regards

**Comment by Darhazer** [comment]
This issue is the same as #6738 and it's fixed in Rubocop 0.68.1
