### ISSUE TITLE
RuboCop::Cop::Lint::UnusedConstant

### ISSUE THREAD

**Issue by dawlib** [rubocop-hq/rubocop#6817]
There are situations when I'm refactoring the code and sometimes I forget to remove constant's declaration after removing its usage from the code, so such garbage like unused constants declarations remains in the code.

If there would remain some declaration of an unused constant in the code, I would like to be warned as I'm after `RuboCop::Cop::Lint::UnusedArgument` cop or similar.

There is a need to consider two situations:
1. When a constant is publicly accessible - this one probably is a bit tricky.
2. When a constant is private - in that case, a cop definitely should look for a constant's usage in the scope where it's declared.

**Comment by bbatsov** [comment]
Sounds like a task for @Drenmi. ;-)

**Comment by karimatthews** [comment]
Plus one for this request. This feature would be really useful.
