### ISSUE TITLE
Automatically Generated Configuration - wrong message

### ISSUE THREAD

**Issue by belgoros** [rubocop-hq/rubocop#6863]
## Expected behavior

If  `.rubocop.yml` file alteady exists in the project root, 
when running `rubocop --auto-gen-config` it would be more correct **to not display** the following message:
```
Configuration file not found: /Users/path/to/my/project/.rubocop.yml
```
what is a little bit confusing as the file does exist.

## Actual behavior

- create `rubocop.yml` file manually in your project root.
- run `rubocop --auto-gen-config` in the terminal
- observe the generated message:
```
Added inheritance from `.rubocop_todo.yml` in `.rubocop.yml`.
Configuration file not found: /Users/path/to/my/project/.rubocop.yml
```

If you remove the manually created `.rubocop.yml` file in your project root, then run `rubocop --auto-gen-config` command, everything goes as it should:
- no confusing message displayed
- `rubocop_todo_yml` file is generated filled with all the offences added
- a new `rubocop.yml`is generated with `inherit_from: .rubocop_todo.yml` added on the first line.

## Steps to reproduce the problem

See actual behavior section

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.66.0 (using Parser 2.6.2.0, running on ruby 2.6.1 x86_64-darwin18)
```

**Comment by jonas054** [comment]
I can't reproduce the problem. What's the contents of the manually created `.rubocop.yml`? What's the current directory when you run?

**Comment by belgoros** [comment]
@jonas054 Thank you for your response. The content I put into a manually created `.rubocop.yml` file was as follows:
```
Rails:
  Enabled: true
```
Of course, I ran the `rubocop --auto-gen-config` command from the root of the project.

What is weird, I could not reproduce the same issue on a [freshly created Rails project](https://github.com/belgoros/rubocop-exampe) using Ruby `2.6.2` version.
You can see the commute log what I was doing.
This time, the content previously created `.rubocop.yml` was updated with `inherit_from: .rubocop_todo.yml`:
```
inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true
```
and a new `rubocop_todo.yml` file was created.

So, I do not know why it happened on another project using Ruby `2.6.1` and the same Rubocop version.
