### ISSUE TITLE
promote Performance/RedundantSortBy to Style/RedundantSortBy

### ISSUE THREAD

**Issue by matkoniecz** [rubocop-hq/rubocop#6871]
Unlike many other Performance cops `Performance/RedundantSortBy` is not making code less readable and is a good idea independent from performance improvements.

As #5977 will cause performance cops to be disabled by default I suggest to rescue this one

It may be also useful to expand description with a note that this change may improve performance (as it would no longer be implied)

------

Other usual issue fields are not applicable - I spotted it during reviewing https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

#6637 ("promote Performance/LstripRstrip to Style/LstripRstrip") is a closely related issue that was fixed in #6870 by @anuja-joshi 

There are also `Performance/UnneededSort`, `Performance/Sample`, <s>`Performance/RedundantMatch`</s> that also improve (at least in my opinion) code quality, independent from performance improvements but I think that creating now separate issues for them is a poor idea (if that would be a good idea I may create a separate issue for each, I am planning to do it also if RedundantSortBy would be fixed without fixing three additional ones).

**Comment by bbatsov** [comment]
> Performance/UnneededSort, Performance/Sample, Performance/Sample

Seems you made some mistake here.

**Comment by matkoniecz** [comment]
Fixed.

**Comment by bbatsov** [comment]
> Performance/UnneededSort, Performance/Sample, Performance/RedundantMatch

I agree about the first two, but `RedundantMatch` should stay in Performance IMO.

**Comment by matkoniecz** [comment]
I crossed it out in the report.

**Comment by matkoniecz** [comment]
@bbatsov Is it a good idea to look over Performance cops again whatever there is still something worth rescuing? Or is it something that you did already during making 32ed7d197855b66e16f1ef1a7ecdc409112ead14 ?

**Comment by bbatsov** [comment]
Well, I not that worried about those cops as they are not going to die. :-) Took a quick look at some of the others, but nothing seemed like an obvious choice to go to style. Let me know if you have any ideas.

**Comment by matkoniecz** [comment]
`RedundantMerge`, `RedundantSortBy`, `ChainArrayAllocation` looks like candidates but I am not 100% sure, I am even less sure about `RedundantBlockCall`.

`RedundantMatch` was rejected.

> Well, I not that worried about those cops as they are not going to die

I know, but I would be happy to have in optional performance add-on
