### ISSUE TITLE
--debug should explain inclusion/exclusion

### ISSUE THREAD

**Issue by jaredbeck** [rubocop-hq/rubocop#6873]
## Is your feature request related to a problem? Please describe.

People have trouble with [Including/Excluding files](https://docs.rubocop.org/en/latest/configuration/#includingexcluding-files), eg. https://github.com/rubocop-hq/rubocop/issues/6567, https://github.com/rubocop-hq/rubocop/issues/4477, https://github.com/rubocop-hq/rubocop/issues/5480

## Describe the solution you'd like

`--debug` should list the relevant inclusion/exclusion configuration for a particular file. For example:

```
Scanning ./foo/bar.rb
Excluded by ./foo/.rubocop.yaml, then included by ./.rubocop.yaml
Scanning ./baz.rb
Excluded by default.yml, then included by ./.rubocop.yml
```

**Comment by bbatsov** [comment]
That's not a bad idea.

**Comment by jaredbeck** [comment]
I'm still working on this.

> Feel free to re-open it if you ever come back to it.

I don't have permission to re-open this, and I don't want to create a new issue and lose the context here. Feel free to leave it closed though, and just wait for my PR.

**Comment by paulschreiber** [comment]
@jaredbeck did this work get done under a different issue or flag?
