### ISSUE TITLE
Naming/RescuedExceptionsVariableName invalid report

### ISSUE THREAD

**Issue by mensfeld** [rubocop-hq/rubocop#6893]
When I run rubocop __0.67.2__ with following code:
```ruby
handled = [StandardError]

begin
  raise StandardError
rescue *handled
  false
end
```

I get the following error:

```
test.rb:5:8: C: Naming/RescuedExceptionsVariableName: Use e instead of *handled.
rescue *handled
       ^^^^^^^^
```
--------

## Expected behavior

I should not get this offense.

## Actual behavior

I do get the offense.

## Steps to reproduce the problem

- Create a file with the code above
- Run Rubocop  on it

## RuboCop version

```
$ [bundle exec] rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.6.2 x86_64-linux)
```

**Comment by bbatsov** [comment]
Thanks for reporting this. The cop is certainly rough around the edges, but we'll fix it soon.

**Comment by mensfeld** [comment]
It's not stale - it's still present.

**Comment by bbatsov** [comment]
Yeah, there's a PR that targets it, but it got stuck a while ago. See https://github.com/rubocop-hq/rubocop/pull/6908
