### ISSUE TITLE
`Naming/RescuedExceptionsVariableName` does not handle multiple rescues

### ISSUE THREAD

**Issue by anthony-robin** [rubocop-hq/rubocop#6902]
Just after upgrading to Rubocop `v0.67.2`, I discovered that if we have more that one `rescue`, only the first will be flagged with an offense.

## Expected behavior

I should get an offense from Rubocop for any individual `rescue` that does not follow the defined configuration.

## Actual behavior

Only the first `rescue` is being flagged.

## Steps to reproduce the problem

```ruby
class MyController < ApplicationController
  def create
    # some code here
  rescue MyException => exception # <= flagged
    render_my_exception(exception)
  rescue MyAnotherException => exception # <= not flagged
    render_an_another_exception(exception)
  end
end
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.6.1 x86_64-darwin18)
```

**Comment by AlexWayfer** [comment]
Another example:

```ruby
# frozen_string_literal: true

def foo
  puts 'foo'
rescue ArgumentError => e
  raise unless e.message
end

def bar
  puts 'bar'
rescue ArgumentError => exception
  raise unless exception.message
end
```

(there are no offenses)
