### ISSUE TITLE
Error while parsing Gemfile

### ISSUE THREAD

**Issue by ryz310** [rubocop-hq/rubocop#6917]
An error occurred executing RuboCop v0.67.2.
Outputs error as following:

```
/usr/local/bundle/gems/rubocop-0.67.2/exe/rubocop:16:in `[]': no implicit conversion of String into Integer (TypeError)
	from /usr/local/bundle/gems/rubocop-0.67.2/exe/rubocop:16:in `<top (required)>'
	from /usr/local/bundle/bin/rubocop:29:in `load'
	from /usr/local/bundle/bin/rubocop:29:in `<main>'
```

And the related code is following:

https://github.com/rubocop-hq/rubocop/blob/1ec76b9251edb0e3edd159a72ec7fde58e1a22f8/exe/rubocop#L12-L16

I'm using Bundler in version v1.14 and the implement of `LockFileParser#dependencies` looks different between v1.14 and v1.15. 

https://github.com/bundler/bundler/commit/9febe9a5d19d1dac8a7bd032fc2b3ab029288646#diff-3c625d3cd7d7604b3e2e3c5487a5ede6L64

So I thought it should be changed requirement version for bundler in RuboCop gemspec.

https://github.com/rubocop-hq/rubocop/blob/1ec76b9251edb0e3edd159a72ec7fde58e1a22f8/rubocop.gemspec#L44

**Comment by bbatsov** [comment]
@koic Can you check this out?

**Comment by koic** [comment]
I checked this issue and I opened a PR #6919.
