### ISSUE TITLE
Explicit/implicit .where — does Rubocop HQ have an opinion?

### ISSUE THREAD

**Issue by rlue** [rubocop-hq/rubocop#6920]
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

Our team was discussing a stylistic preference about how to call `#where`—in, say, the `Post` model, should it be `where` or `Post.where`?

Is there a cop (or would Rubocop HQ consider adding one) to enforce one style over the other?

## Describe alternatives you've considered

N/A

## Additional context

FWIW, it appears that in some of the large-scale open source Rails applications I've looked through, there tends to be some inconsistency, with a strong tendency toward implicit `where`s:

* GitLab CE has 294 implicit / 5 explicit
* Discourse has 98 implicit / 70 explicit
* RubyGems.org has 26 implicit / 3 explicit

**Comment by Drenmi** [comment]
While the core team may individually have opinions on style, the RuboCop core team doesn't. We are just concerned with building the linter. Ruby is a long standing language, and people are already quite cemented in their opinions of style. Trying to have an official stance inevitably leads to a lot of bike shedding, and people opening issues to forcefully promote their own preferred style, which is draining, and detracts from the work. (The Ruby Style Guide repo is a great place for people to discuss though.)

We can certainly add a cop for this though, making it configurable. 🙂

Note though, that this only applies to class methods. If you try to call `#where` from an instance method, you'll get a `NoMethodError`.

**Comment by rlue** [comment]
Super cool! I'll take a peek at what it takes to build a cop one of these weekends, just to see if I can contribute here myself. Thanks!
