### ISSUE TITLE
Ignore offenses currently found in codebase, but enforce newly introduced ones?

### ISSUE THREAD

**Issue by rlue** [rubocop-hq/rubocop#6925]
## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

Our team is adopting a new set of cops (via [`rubocop-rspec`](https://github.com/rubocop-hq/rubocop-rspec)). The current codebase has over 3,000 offenses, most of which require some manual intervention, so we're anticipating a long transition phase.

We'd like to start enforcing these cops in new code, without the existing failures breaking our CI. Does Rubocop have a "migration" / "adoption" mode that might, for example, generate a list of ignorable offenses and store it in a dotfile somewhere? If not, would the team consider adding such a feature?

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by Drenmi** [comment]
Hi, @rlue!

We do have a feature that lets you generate a TODO list:

```ruby
bundle exec rubocop --auto-gen-config
```

This is not perfect though. There is no way for us to reliably tell what's "new code" and not, and so it works by exclusion of the cop on a file-by-file basis. Then you can go ahead to "fix" one file at a time, or one cop at a time, or one cop and file at a time, depending what makes more sense for your project.

Another option is to use inline disables:

```ruby
# rubocop:disable RSpec/ExampleCop
describe "offending code" do
  ...
end
# rubocop:enable RSpec/ExampleCop
```

Although this is likely not feasible for thousands of offenses, and is usually used to whitelist a false positive, and thus an indication that the code inside doesn't need fixing.
