### ISSUE TITLE
Drop support for Ruby 2.2 and 2.3

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#6945]
Both of them reached their EOL already and according to our official support policy we don't need to support them anymore.

I don't have a strong take on this, but I'd rather remove them mostly to speed up the test suite. The final decision will also depend on how widely 2.2 and 2.3 are still used in the wild, of course. @rubocop-hq/rubocop-core Any thoughts on this?

**Comment by Darhazer** [comment]
I would vote for dropping 2.2. The same discussion applies as with [dropping support for 2.1](https://github.com/rubocop-hq/rubocop/pull/5990) - dropping from the runtime but preserving the parsing support.
2.3 got its EOL recently and we may give users some more time to switch. Let's drop just 1 version at a time. 

According to JetBrains stats, [2.2 was used by 20% of developers in 2017](https://www.jetbrains.com/research/devecosystem-2017/ruby/) and only [8% in 2018](https://www.jetbrains.com/research/devecosystem-2018/ruby/). 2.3 dropped from 58% to 23%. 20% is still a high number.

**Comment by bbatsov** [comment]
Hmm, that's interesting. Even 8% seems like a lot to me, but I guess we can drop 2.2 if no one objects strongly to this.

**Comment by pirj** [comment]
I'd be interested in seeing the statistics of Ruby version used for the latest RuboCop gem versions.

This might give a better insight into how many people will get upset that they are unable to update RuboCop without updating the Ruby version.

In the case when the users of newer versions of RuboCop mostly also prefer newer Ruby versions, I don't see a good reason not to drop support for both 2.2 and 2.3.

Unfortunately, RubyGems [does not keep track of per-version downloads](https://github.com/rubygems/rubygems.org/issues/1439).
Even with this, it would be possible to infer the used corresponding Ruby version.

What can be measured though is the number of downloads per version of RuboCop gem. It wouldn't mean, of course, that the users of older RuboCop versions are the users of older Ruby versions, but it may be quite likely to be so.

RuboCop version / downloads | 04.17 | add new dates here along with a diff (e.g. +1,400)
----------------------------| ----- | ------------
0.67.2 | 140,728 |
0.67.1 | 16,470 |
0.67.0 | 2,296 |
0.66.0 | 350,092 |
0.65.0 | 740,399 |
0.64.0 | 458,107 |
0.63.1 | 674,662 |
0.63.0 | 127,228 |
0.62.0 | 413,987 |
0.61.1 | 602,118 |
0.61.0 | 31,724 |
0.60.0 | 1,248,781 |
0.59.2 | 1,328,397 |
0.59.1 | 497,177 |
0.59.0 | 463,760 |
only major'ish versions below | |
0.49.1 | 5,739,695 |
0.46.0 | 1,582,279 |
0.45.0 | 836,511 |
0.43.0 | 787,059 |
0.42.0 | 1,475,544 |
0.44.1 | 392,734 |

Basing on the early adopter growing rate, and the download trends for older versions we could make a better decision on this.

**Comment by luke-hill** [comment]
Kind of an obvious point, but the users who are using old rubies (Perhaps for a legacy app or two out of 10-15 apps at a company), are likely to also have old outdated code. And as such, are unlikely to want to run things like rubocop on it that often.

Also given rubocop's popularity as a highly used gem, making it as optimal as possible whilst catering to a large proportion of the userbase I would say is a key point (Yes 8% is large, but 92% is larger..)

**Comment by bbatsov** [comment]
Well, let's drop 2.2 and see how things go. I don't really expect much of a fallout from this.

**Comment by koic** [comment]
Ruby is new released on every year, and old version becomes EOL around March.
AFAIK,  When RuboCop dropped support for Ruby 2.0 and Ruby 2.1, it was about a year after EOL.

I think it is a good time to drop Ruby 2.2 by convention since Ruby 2.3 became EOL.
IMO, It would be good to support Ruby 2.3.

**Comment by Drenmi** [comment]
I've always been a proponent of not supporting old versions. It is really a disservice to enable teams to stay on outdated and unsupported versions. Having popular libraries nudge people along will benefit everyone in the end. Rails does a great job of this (Rails 6 required Ruby 2.5 or higher.)

**Comment by pirj** [comment]
Please don't get me wrong, I'm all for dropping support for EOL versions. However, some libraries, e.g. RSpec, do support Ruby 1.8.7 onwards.

**Comment by pirj** [comment]
Diversity across used RuboCop versions being in use is noticeable.

Version | Downloads per week
--- | ---
0.67.2 | 73411
0.66.0 | 25066
0.64.0 | 45369
0.58.2 | 25442+
0.54.0 | 29335+
0.49.1 | 29955

**Comment by koic** [comment]
> Well, let's drop 2.2 and see how things go. I don't really expect much of a fallout from this.

Sure. I opened a PR #7026.

**Comment by Eneroth3** [comment]
I may be late to the party (or too early to a drop support for Ruby 2.4 issue that hasn't yet been created). However I have some general thoughts on dropping Ruby support.

Ruby is used for the live API in SketchUp, meaning quite a few people are relying on old Ruby versions. It's not like a rails server where an admin is responsible for keeping things up to date, but up to a sometimes not very tech-savvy end user to update, which includes buying new SketchUp licenses. Also the free version (for non-commercial use) was dropped in 2017 meaning many hobbyists are stuck there, on Ruby 2.2.4.

While it's possible to manually exclude Style/SafeNavigation and other cops related to newer Ruby features, along with writing a comment as of why you do it, it would be more straight forward for SketchUp extension developers to just directly target the older Ruby version. If it's not too much problem it would be nice if Rubocop could keep support a bit longer than the official life cycle.

**Comment by luke-hill** [comment]
@Eneroth3 - You can still use rubocop with ruby 2.2, 2.1 or even lower if you want (Just an older pinned version). What this is saying is going forward to only target newer users of Ruby (or new-ish), with the rubocop restrictions.

**Comment by Eneroth3** [comment]
@luke-hill I don't really follow. I (as a developer) can update my standalone Ruby interpreter to the newest version at any time. However my users are often stuck in Ruby 2.2, and thus my ruby code needs to be compatible with it.

In my case we are not talking about server admins but woodworkers, carpenters, architects etc that would have to pay for a new SketchUp version to update their Ruby interpreter.

**Comment by bbatsov** [comment]
That's what `TargetRubyVersion` is for. RuboCop can't run on Ruby 2.2, but it can make sure that a codebase is compatible with Ruby 2.2 using that setting.

**Comment by Eneroth3** [comment]
Oh, my bad. I thought this discussion as about dropping Ruby 2.2 support in `TargetRubyVersion`. I'm currently running Rubocop 0.75.0, which doesn't support anything under Ruby 2.3 as `TargetRubyVersion`.
