### ISSUE TITLE
Style/TrailingCommaInArguments works weirdly with heredocs

### ISSUE THREAD

**Issue by radar** [rubocop-hq/rubocop#6955]
Hello, I am experiencing what I would call "weirdness" with `Style/TrailingCommaInArguments` and heredocs.

Here is a short piece of code which raises an offense:

```
expect(response.body).to eq(
  <<~CSV
    "csv","123","abc"
    "3","4","5"
  CSV
)
```

--------

## Expected behavior

I would expect Rubocop to not raise offences at this code.

## Actual behavior

When I run `rubocop` over this file, I see this offense listed:

```
app/thing.rb:2:3: C: Style/TrailingCommaInArguments: Put a comma after the last parameter of a multiline method call.
  <<~CSV
  ^^^^^^

1 file inspected, 1 offense detected
```

Running `rubocop` with `-a` changes the first line of the heredoc to be:

```
<<~CSV,
```

This is not any kind of Ruby code that I (or I'm guessing, my colleagues) would write. It seems a weird thing to be doing, especially in this case where the heredoc is the _only_ argument to this method.

## Steps to reproduce the problem

See above.

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ bundle exec rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.6.2 x86_64-darwin18)
```

**Comment by cllns** [comment]
Also running into this issue right now. It looks like a duplicate of https://github.com/rubocop-hq/rubocop/issues/6837

**Comment by radar** [comment]
Closing this one in favour of #6837.
