### ISSUE TITLE
Style/Lambda with unused argument bug

### ISSUE THREAD

**Issue by rramsden** [rubocop-hq/rubocop#6956]
### Context

When using `--auto-correct` with a "stabby lambda" function where arguments are unused results in syntactically incorrect code:

```ruby
c = -> event do
  puts 'Hello world'
end
```

Is autocorrected to the following:

```ruby
c = lambda(_) do |_event|
  puts 'Hello world'
end
```

Which returns the following error when executed:

```
test.rb:3:in `<main>': undefined local variable or method `_' for main:Object (NameError)
```

--------

## Expected behavior

Should not inject `_` arguments into lambda e.g. `lambda(_)` this is not allowed in Ruby. The result should be the following code:

```ruby
c = lambda do |_event|
  puts 'Hello world'
end
```

## Actual behavior

Inserts `_` as an argument to lambda function e.g. `lambda(_)`

## Steps to reproduce the problem

1. Insert the example code in the above context into a file.
2. Run `rubocop --auto-correct` on the file.
3. Try executing the formatted code, it will not work.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.4.5 x86_64-darwin18)
```

## Ruby version

```
$ ruby -v
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin18]
```

**Comment by koic** [comment]
Thanks for your feedback. I opened a PR #6958.
