### ISSUE TITLE
An error occurred while SketchupSuggestions/Compatibility cop was inspecting file

### ISSUE THREAD

**Issue by brodao** [rubocop-hq/rubocop#6961]
The attached file raise error.

  [exec] An error occurred while SketchupSuggestions/Compatibility cop was inspecting W:/brodao/ws_ruby/pulley/src/actools_su/support.rb:31:8.
     [exec] An error occurred while SketchupSuggestions/Compatibility cop was inspecting W:/brodao/ws_ruby/pulley/src/actools_su/support.rb:31:41.
     [exec] An error occurred while SketchupSuggestions/Compatibility cop was inspecting W:/brodao/ws_ruby/pulley/src/actools_su/support.rb:39:10.
     [exec] Errors are usually caused by RuboCop bugs.
     [exec] Please, report your problems to RuboCop's issue tracker.
     [exec] https://github.com/rubocop-hq/rubocop/issues
     [exec] Mention the following information in the issue report:
     [exec] 0.63.1 (using Parser 2.6.0.0, running on ruby 2.5.3 x64-mingw32)
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/ast/traversal.rb:50:in `block in on_begin'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/ast/traversal.rb:50:in `each'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/ast/traversal.rb:50:in `on_begin'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/cop/commissioner.rb:35:in `block (2 levels) in <class:Commissioner>'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/ast/traversal.rb:13:in `walk'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/cop/commissioner.rb:46:in `investigate'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:116:in `investigate'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:104:in `offenses'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/cop/team.rb:44:in `inspect_file'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:280:in `inspect_file'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:227:in `block in do_inspection_loop'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:259:in `block in iterate_until_no_changes'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:252:in `loop'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:252:in `iterate_until_no_changes'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:223:in `do_inspection_loop'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:126:in `block in file_offenses'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:144:in `file_offense_cache'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:124:in `file_offenses'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:112:in `process_file'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:89:in `block in each_inspected_file'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `each'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `reduce'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:86:in `each_inspected_file'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:76:in `inspect_files'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/runner.rb:48:in `run'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:174:in `execute_runner'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:75:in `execute_runners'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/lib/rubocop/cli.rb:47:in `run'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/exe/rubocop:13:in `block in <top (required)>'
     [exec] C:/Ruby25-x64/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
     [exec] C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubocop-0.63.1/exe/rubocop:12:in `<top (required)>'
     [exec] C:/Ruby25-x64/bin/rubocop:23:in `load'
     [exec] C:/Ruby25-x64/bin/rubocop:23:in `<main>'
[support.zip](https://github.com/rubocop-hq/rubocop/files/3113351/support.zip)

**Comment by koic** [comment]
`SketchupSuggestions/Compatibility` cop is not a RuboCop core's cop.
https://github.com/SketchUp/rubocop-sketchup/blob/master/lib/rubocop/sketchup/cop/suggestions/compatibility.rb

Can you please report to https://github.com/SketchUp/rubocop-sketchup repo?
Thank you.
