### ISSUE TITLE
Style/StringHashKeys is not safe for autocorrection

### ISSUE THREAD

**Issue by fig** [rubocop-hq/rubocop#6980]
I don't believe that `Style/StringHashKeys` should be labeled as safe for autocorrection.

As an example, a Hash may be passed as the second argument to `String#gsub`. If the matched text is one of its keys, the corresponding value is the replacement string. Converting the String key to a Symbol will break the replacement.

--------

## Steps to reproduce the problem

example scenario:

```ruby
"The sky is green.".gsub(/green/, "green" => "blue")
# => "The sky is blue."
```
after auto correct:
```ruby
"The sky is green.".gsub(/green/, green: "blue")
# => "The sky is ."
```

## RuboCop version

```
$ rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.6.3 x86_64-linux)
```

--------

A solution might be to ignore StringHashKeys if they occur as an argument to `#gsub` / `#gsub!`

**Comment by tejasbubane** [comment]
There are existing exceptions in `Style/StringHashKeys` for `IO.popen`, etc. So I added `gsub` and `gsub!` to the list.
