### ISSUE TITLE
Layout/IndentFirstParameter crashing on method definition

### ISSUE THREAD

**Issue by NoahTheDuke** [rubocop-hq/rubocop#6992]
`Layout/IndentFirstParameter` crashes on the following code:
```ruby
module Foo
  def bar(
    arg: nil
  )
    true
  end
end
```

```
Scanning /Users/noah/dev/test.rb
An error occurred while Layout/IndentFirstParameter cop was inspecting /Users/noah/dev/test.rb:2:2.
Unknown style special_for_inner_method_call_in_parentheses selected!
/Users/noah/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubocop-0.68.0/lib/rubocop/cop/mixin/configurable_enforced_style.rb:67:in `style'
```
--------

## Expected behavior

Don't crash, potentially throw a linting error.

## Actual behavior

Crashes.

## Steps to reproduce the problem

See code above.

## RuboCop version

```
$ rubocop -V
0.68.0 (using Parser 2.6.3.0, running on ruby 2.5.3 x86_64-darwin18)
```

**Comment by mensfeld** [comment]
Can confirm. Same on my side.

**Comment by bbatsov** [comment]
@maxh Can you take a look? Seems we'll need to do a quick bugfix release for this.

**Comment by erikjenks** [comment]
Can confirm seeing this with `ruby 2.6.0` as well

**Comment by Darhazer** [comment]
The EnforcedStyle should be set to either `consistent` or `align_parentheses`.
Might be used as a workaround (set EnforcedStyle for the cop in .rubocop.yml) until a new version is released

**Comment by phene** [comment]
Neither `consistent` nor `align_parentheses` enforces the style used in the example. I ended up disabling it until it's fixed.

**Comment by maxh** [comment]
Sorry to miss this! Thanks for the fix, @Drenmi. I've reconfigured my GitHub settings so I am properly notified about messages in this repo. I just noticed https://github.com/rubocop-hq/rubocop/issues/6936 and created https://github.com/rubocop-hq/rubocop/pull/7072. Feel free to tag me if there's anything else I should look into -- I should see it now.
