### ISSUE TITLE
Add an alias from FirstParameterIndentation to IndentFirstParameter

### ISSUE THREAD

**Issue by Floppy** [rubocop-hq/rubocop#7014]
The change in https://github.com/rubocop-hq/rubocop/pull/6982 breaks compatibility with older rubocop versions by removing the old name in the same version update as the new one is added. Adding an alias (with deprecation warning) for the old name temporarily would help people to migrate in a gentler fashion.

It would also allow shared config gems like https://github.com/toshimaru/rubocop-rails_config to support both older and newer versions of rubocop. I've had to drop support for older Rubocop in my PR to fix the config option in that project: https://github.com/toshimaru/rubocop-rails_config/pull/43

**Comment by bbatsov** [comment]
We currently don't have a concept of aliases. I've been thinking about this for a while, but getting this right would be tricky.

**Comment by bbatsov** [comment]
One more things - that's not a simple rename. The old cop was split in two - one cop handling params (definitions) and one handling arguments (invocations).

**Comment by Floppy** [comment]
ah, thanks @bbatsov - I'll update my fix to add both the new halves.

**Comment by Floppy** [comment]
I've resolved my problem with this specific issue, but I definitely think it's worth considering adding aliases to help with the upgrade path for rubocop users.
