### ISSUE TITLE
Remove rubocop-performance post install message

### ISSUE THREAD

**Issue by roberts1000** [rubocop-hq/rubocop#7042]
Can the post install message about the `rubocop-performance` be removed at some point? It's already documented at https://github.com/rubocop-hq/rubocop/blob/master/manual/extensions.md and that should be sufficient.

My team embeds the rubocop gem in a wrapping gem that installs rubocop-performance and configures a premade .rubocop.yml file.  The post install message makes some developers think they need to take some action.

**Comment by bbatsov** [comment]
Yeah, I agree we should remove it at this point. @koic Can you handle this?

**Comment by koic** [comment]
I agree too. I opened a PR #7049.

**Comment by roberts1000** [comment]
Thanks for the fast turnaround!
