### ISSUE TITLE
An option for Lint/HandleExceptions to accept comments

### ISSUE THREAD

**Issue by dduugg** [rubocop-hq/rubocop#7052]
## Is your feature request related to a problem? Please describe.

I find that `Lint/HandleExceptions` is often bypassed with a `nil` in the `rescue` block. This is not helpful, whereas comments would be. However, a `rescue` block consisting of only a comment will still trigger a `Lint/HandleExceptions` offense.

## Describe the solution you'd like

I would like an option to allow comments within a rescue block to avoid `Lint/HandleExceptions`. Perhaps `AllowComments: true`.

## Describe alternatives you've considered

- Instead of a config option, allow comments in all cases
- Disable the cop
- Also ban rescue blocks consisting of `nil` with no add'l context
- Continue with status quo

## Additional context

n/a

**Comment by tejasbubane** [comment]
There are two parts to this:

1. Add config option `AllowComments` - done in #7060 
1. Do not allow rescue blocks consisting of `nil` (especially single line rescue) - I will do this once above is merged to avoid conflicts.

**Comment by rmm5t** [comment]
I like this, and I think it should be the new default.

**Comment by tejasbubane** [comment]
Fixed in #7297

**Comment by sergeyk** [comment]
This issue should be closed, as it was fixed

**Comment by koic** [comment]
I agree with @rmm5t. I opened PR #7805.
