### ISSUE TITLE
To check the value of "Enabled" in YAML configuration is true or false

### ISSUE THREAD

**Issue by unasuke** [rubocop-hq/rubocop#7056]
## Is your feature request related to a problem? Please describe.
Our team occurred a problem that, unexpected  cop was in effect.
The cause was the wrong config value like an "Enabled: disabled".

## Describe the solution you'd like

I think it's helpful to check the value of a yaml key "Enabled".

Like this.

![Screenshot from 2019-05-18 19-11-37](https://user-images.githubusercontent.com/4487291/57968068-cc403900-79a0-11e9-8885-78ac2c6a66c2.png)

## Describe alternatives you've considered

none.

## Additional context

I already have a patch!

**Comment by koic** [comment]
This issue is addressed in #7272.
