### ISSUE TITLE
Style/MethodCallWithoutArgsParentheses option for methods *with* args

### ISSUE THREAD

**Issue by mockdeep** [rubocop-hq/rubocop#7057]
## Is your feature request related to a problem? Please describe.

As an alternative to `Style/MethodCallWithArgsParentheses` where there are methods where we *do not* want parenthesis around method calls that take args, it would be nice to enforce consistency for the negative case as well.

## Describe the solution you'd like

I'd like to have something like an `IncludedMethods` option where we can specify methods that should *never* have parens:

```yaml
Style/MethodCallWithoutArgsParentheses:
  IncludedMethods:
    - exit
    - puts
    - require
    - warn
```

## Describe alternatives you've considered

This might also make sense as some sort of a `NeverParens` option under `Style/MethodCallWithArgsParentheses`.

**Comment by tejasbubane** [comment]
Duplicate of #6967.

**Comment by mockdeep** [comment]
@tejasbubane I saw that issue before, but it didn't look like the same thing as what I'm asking for here. It looks like they're asking for more sophisticated ways to ignore methods, but I'm looking for a more strict "inverse" option.

**Comment by mockdeep** [comment]
This issue is still relevant.
