### ISSUE TITLE
[Propose] use formatador instead of ruby-progressbar

### ISSUE THREAD

**Issue by zw963** [rubocop-hq/rubocop#7058]
Following is a gif animation for compare two. first is formatador.

![Peek 2019-05-19 13-31](https://user-images.githubusercontent.com/549126/57978200-dd3d8880-7a3a-11e9-938e-ab9055a1b35e.gif)

And, [formatador](https://github.com/geemus/formatador) is more feature riched than ruby-progressbar, and no any external dependency.

Thank you.

**Comment by bbatsov** [comment]
Is there any concrete problem such a change is going to solve?

**Comment by zw963** [comment]
no any problem，just more beautiful? :)
