### ISSUE TITLE
Style/RedundantBegin causes syntax errors in Rake tasks

### ISSUE THREAD

**Issue by dangerous** [rubocop-hq/rubocop#7087]
The Style/RedundantBegin can introduce a syntax error to a Rake task
--------

Rake task is as follows:
```
$ cat lib/tasks/example.rake
desc 'An example Rake task'
task :example do
  begin
    puts "Hello there!"
  rescue
    puts "Oh no!"
  end
end
```

## Expected behavior

Rubocop does not correct the file

## Actual behavior

```
$ ruby -c lib/tasks/example.rake
Syntax OK
$ rubocop --only Style/RedundantBegin -a lib/tasks/example.rake
Inspecting 1 file
C

Offenses:

lib/tasks/example.rake:3:3: C: [Corrected] Style/RedundantBegin: Redundant begin block detected. (https://github.com/rubocop-hq/ruby-style-guide#begin-implicit)
  begin
  ^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
$ ruby -c lib/tasks/example.rake
lib/tasks/example.rake:5: syntax error, unexpected keyword_rescue, expecting keyword_end
  rescue
        ^
lib/tasks/example.rake:8: syntax error, unexpected keyword_end, expecting end-of-input
```

## Steps to reproduce the problem

See above

## RuboCop version

```
$ rubocop -V
0.67.2 (using Parser 2.6.2.1, running on ruby 2.6.3 x86_64-darwin18)
```

**Comment by rrosenblum** [comment]
I was unable to reproduce the issue using RuboCop master and Ruby 2.6.3. The corrected code appears to have the correct syntax for me.

```ruby
task :example do
  puts 'Hello there!'
rescue
  puts 'Oh no!'
end
```

As a sanity check, is the version of Ruby that you are using to check the syntax of the file the same version of Ruby that is being used with RuboCop? The error output looks like it comes from a version of Ruby prior to when implicit begins were added to blocks (I think 2.5 or 2.6).
