### ISSUE TITLE
Requiring both rubocop-rails and rubocop-performance in rubocop.yml throws warning 

### ISSUE THREAD

**Issue by RicardoTrindade** [rubocop-hq/rubocop#7104]
--------

## Expected behavior

When requiring both rubocop-rails and rubocop-performance no warnings are thrown

## Actual behavior

When running rubocop a warning is thrown  `.rubocop.yml:2: require is concealed by line 3`

## Steps to reproduce the problem
If you require both rubocop-rails and rubocop-performance in .rubocop.yml like this
```
require: rubocop-rails
require: rubocop-performance
```
It will throw a warning `.rubocop.yml:2: require is concealed by line 3 `

## RuboCop version
0.71.0

```
$ [bundle exec] rubocop -V
0.71.0 (using Parser 2.6.3.0, running on ruby 2.5.5 x86_64-linux)
```
Not sure if we should ignore the warning or update the `config_loader.rb` to ignore the require field on the .rubocop.yml

**Comment by koic** [comment]
Please use the YAML's array notation.

```yaml
require: 
  - rubocop-performance
  - rubocop-rails
```

https://github.com/rubocop-hq/rubocop/blob/v0.71.0/.rubocop.yml#L4-L7

**Comment by RicardoTrindade** [comment]
oh right sorry, thanks!
