### ISSUE TITLE
Style/StderrPuts: dangerous autocorrection

### ISSUE THREAD

**Issue by radiospiel** [rubocop-hq/rubocop#7108]
## Expected behavior

Style/StderrPuts should autocorrect `STDERR.puts "foo"` into `Kernel.warn "foo"` or not at all. The current behavior would call "warn", even if it is not Kernel.warn, but something else completely in the current context.  

## Actual behavior

Style/StderrPuts autocorrects `STDERR.puts "foo"` into `warn "foo"`.

**Comment by rrosenblum** [comment]
This sounds like a reasonable request to me. The code looks like it will be easy to update.

**Comment by bjeanes** [comment]
This is still an issue
