### ISSUE TITLE
Update style guide links

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#7120]
We recently started publishing the Ruby Style Guide to https://rubystyle.guide. As the guide looks much better there and the navigation is better I think we should update the base URL to point to it.

The plan is to publish the RSpec and Rails guides under rspec.rubystyle.guide and rais.rubystyle.guide in the weeks to come.

**Comment by bbatsov** [comment]
FYI - https://rails.rubystyle.guide and https://rspec.rubystyle.guide are up as well.

**Comment by malyshkosergey** [comment]
@bbatsov, I've updated base url and opened PR
https://github.com/rubocop-hq/rubocop/pull/7139

Could you please let me know if we need to update rails and rspec links somewhere as well?
Haven't found it yet so if you can give the tip I can do it as well. Thanks!

**Comment by bbatsov** [comment]
> Could you please let me know if we need to update rails and rspec links somewhere as well?

They should be updated in `rubocop-rspec` and `rubocop-rails`.
