### ISSUE TITLE
CI fails with ruby-head

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop#7124]
CI fails with ruby-head.
For example: https://circleci.com/gh/rubocop-hq/rubocop/57757?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
ruby -I lib -r rubocop -e 'exit 0'
Traceback (most recent call last):
	4: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /home/circleci/project/lib/rubocop.rb:3:in `<top (required)>'
	1: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- parser (LoadError)
Exited with code 1
```

--------

## Expected behavior

CI passes.

## Actual behavior

Ci fails.

## Steps to reproduce the problem

We can reproduce it with `rubocophq/circleci-ruby-snapshot:latest` docker image.

```console
$ docker run --rm -it rubocophq/circleci-ruby-snapshot:latest

# In docker
$ cd
$ git clone https://github.com/rubocop-hq/rubocop
$ cd rubocop
$ bundle install
$ ruby -I lib -r rubocop -e 'exit 0'
Traceback (most recent call last):
        4: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        3: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        2: from /home/circleci/rubocop/lib/rubocop.rb:3:in `<top (required)>'
        1: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- parser (LoadError)
```

I guess it is a bundler's bug. Because I can avoid the bug with bundler v2.0.1.

```console
# In the docker container
$ gem install bundler
$ bundle _2.0.1_ install
$ ruby -I lib -r rubocop -e 'exit 0' # It works.
```

Recently bundler's master branch was merged to ruby repository.
https://github.com/ruby/ruby/commit/8f37629519ad330032a38ac0e871b2912ed38a1b

## RuboCop version

master

**Comment by koic** [comment]
Thank you for your investigation. Can you open this issue to the Ruby developers team or the Bundler team?

**Comment by pocke** [comment]
>  Can you open this issue to the Ruby developers team or the Bundler team?

Sure :+1:

**Comment by tejasbubane** [comment]
Can we allow failure for `ruby-head` so the CI is green?

**Comment by pocke** [comment]
Personally, I'd like to keep it strict. Because I guess anyone will not notice a failure for ruby-head if we allow the failure.
And we can ignore a failure manually if it is not related to the pull request.

**Comment by rrosenblum** [comment]
`ruby-head` was allowed to fail when we had the build in TravisCI. I think the idea was to be able to keep an eye on how RuboCop worked with the latest Ruby, but we didn't care about the actual failure since `ruby-head` isn't always stable.

**Comment by bquorning** [comment]
I don’t think CircleCI has a concept of “allowed failures”. As I recall it, when we switched from Travis to Circle, it was decided to just make the `ruby-head` steps _not_ required status checks.
