### ISSUE TITLE
Set `safe` standards and/or implement --preserve-ast option

### ISSUE THREAD

**Issue by dgollahon** [rubocop-hq/rubocop#7152]
Unless things have changed in the past couple of months and I missed it, I don't think there are clear guidelines for what makes a cop "safe". For background, it will likely help to read https://github.com/rubocop-hq/rubocop/pull/6714#issuecomment-466766807 and @Drenmi's follow-up.

If there is only going to be one level of safe, I would prefer it to be something that is AST-unmodifying. Otherwise, I can't trust it and will always apply cops one at a time, run the tests, and then scan every change that was autocorrected. If we had a mode where `rubocop` could assert that the output AST exactly matched the input AST, I wouldn't feel nearly as paranoid and could run at least some cops with confidence.

Otherwise, I think we could have three levels of safety: `preserve-ast`, `conservative`, and `aggressive` or something like that. The first is only for things like formatting cops, the second would be for things that are extremely unlikely to cause problems in practice, and the last could enable everything that has autocorrect. There could also be a fourth category where between `preserve-ast` and `conservative` for some cases where you change the AST but you can do static analysis you are extremely confident in, but I think those cases are vanishingly rare in ruby and would probably belong in the middle category.

If we went with a three-way model, it would probably be good to set some expectations for rough %s or community false positive rates for the non ast-preserving categories.

Since corrections are relatively rare compared to checks, running an AST diff would probably be very cheap to check after every correction actually performed. This would save users from a lot of dangerous, unintentional semantic changes when rubocop has bugs and would generate quality bug reports faster.

No matter what is chosen, i think the policy should be documented and enforced. `--safe` currently feels like a misnomer to me and I have disabled a _lot_ of autocorrects over the years for badly misbehaving.

Note: This is a feature I would be willing to work on if there is consensus.

**Comment by bbatsov** [comment]
> I would prefer it to be something that is AST-unmodifying. 

It's not as simple as this - even replacing the name of one method with an alias would technically modify the AST. :-) And there are cases where the changes to the AST would be bigger, but the semantics would be the same. Generally I don't think it's worth exploring this direction, although I'm open to doing some research in that direction. I think the idea of some levels of safety has some merits and has been discussed in the past. The only real problem is that all such changes are pretty big and no one really has the time to tackle them. :-) 

> No matter what is chosen, i think the policy should be documented and enforced. --safe currently feels like a misnomer to me and I have disabled a lot of autocorrects over the years for badly misbehaving.

Well, I think the standard exists even today, we just never did a focused sweet of the existing cops to apply it. There are 3 levels:

* Safe + Safe auto-correct
* Safe + Unsafe auto-correct
* Unsafe

If a cop yield false positives or suggests changes to the cop that are not exactly equivalent it's unsafe, otherwise it's safe.  Auto-corrects can get tricky and we have to factor in many trade-offs (e.g. a subjective good correction with a slight risk of breakage vs no correction or a restricted correction).

Seems to me that just putting all this in writing at a prominent place in the docs, plus going though the cops would solve most of the problems people experience today. I don't recall many cases when someone reported a cop as unsafe, and we didn't know about that. The problem was that it was simply not marked as unsafe. I think that this audit will be much easier to execute and it's also something we have to do prior to 1.0 anyways, as I've promised that we'd reconsider the cops enabled by default (reduce their number) and some of the controversial default settings.

**Comment by dgollahon** [comment]
> It's not as simple as this - even replacing the name of one method with an alias would technically modify the AST. :-)

I'm aware, that's what I'm saying I would prefer, if that were the only way to be 100% sure about some cops. This is probably not what most people would prefer for cases like stdlib aliases. I'm thinking of cases where I just want to format a new codebase (there are tons of should-be-whitespace-only changes and I don't trust rubocop enough without hand-auditing all changes). If I can say "run all the cops that definitely won't change the AST" and trust it, then I have way fewer corrections to audit.

To be clear, I would still prefer multiple levels of safety, I just said that to say that, personally, if I could only have two built-in speeds it'd be "It works 100% of the time" and "Autocorrect at your own risk". Having the "this works almost always, but semantic changes are technically possible" category is still helpful, just not something you can blindly trust.

> Well, I think the standard exists even today, we just never did a focused sweet of the existing cops to apply it.

If so I don't think it's very clear to the end user and inconsistently enforced.

> Safe + Safe auto-correct
> Safe + Unsafe auto-correct
> Unsafe

I'm not sure I understand your categories here, what do you mean by safe + unsafe auto-correct? Isn't that just unsafe? Cops are only marked as safe/unsafe, right? So my options seem to be: no autocorrect, "safe" autocorrect, and autocorrect everything (+ hand enabling/disabling cops i want/don't want to be on). I would also like a level below safe that still does work for me that is like "guaranteed" or something.

> If a cop yield false positives or suggests changes to the cop that are not exactly equivalent it's unsafe, otherwise it's safe.

I think it's the "exactly equivalent" point here that is a little uncertain. The referenced issue isn't exactly equivalent nor is any kind of aliasing. These are reasonable corrections and would fit in my middle category, but they're not like a lot of structural changes that really should be exactly equivalent.

The other problem is just that I've had a lot of cop autocorrects mangle my code over the years that generated clearly unintended semantic changes. This is inevitable given how complex the ruby grammar is. Most of these broken correctors get bugfixed within a reasonable time horizon, but every time i can remember trying to format a large amount of code, something has gotten screwed up somewhere that I had to detect. I think diffing the AST could make this problem impossible for a pretty decent minority of cops, particularly in Layout.

> Seems to me that just putting all this in writing at a prominent place in the docs, plus going though the cops would solve most of the problems people experience today.

That would help a lot, agreed.

> I don't recall many cases when someone reported a cop as unsafe, and we didn't know about that.

I don't know if it's really been truly a lot or not, but I can definitely remember multiple cases in rubocop proper and there have been some others in rubocop-rspec (though i think many of these just need an audit too).

> I think that this audit will be much easier to execute and it's also something we have to do prior to 1.0 anyways, as I've promised that we'd reconsider the cops enabled by default (reduce their number) and some of the controversial default settings.

That's good, and I'm sure will help, but I think improving internal assertions and providing access to guarantees would increase trust and rubocop's quality. It would also make enabling/upgrading any ast-preserving cops much less stressful.

Maybe as a full-fledged user-facing feature would be too ambitious to start, but it should be possible to add a little macro or something that hooks into the autocorrection process after select cops are enabled and just does an assert and fails with a "This shouldn't happen, please open an issue with the following information...". That said, I haven't looked at where exactly one could hook in something like that so it may be a little trickier than i think.

To avoid sounding too negative here, I am very pleased with the progress `rubocop` has been making on advertising the relative danger of certain autocorrects and generally improving the user experience overall, but I really think rubocop would be even better with more solid assurances it will do the Right Thing for you.
