### ISSUE TITLE
Cops discussion links + vote button

### ISSUE THREAD

**Issue by Lukom** [rubocop-hq/rubocop#7154]
Hey, is it possible to add a possibility to vote for each rule + link to the discussion like it's on http://www.betterspecs.org/ ?

![image](https://user-images.githubusercontent.com/187657/59713050-24c05b80-9217-11e9-8ec3-adc7bb15009d.png)

It's frustrating when I do not fully agree with the rule and don't have a possibility to discuss it or easy way to find such a discussion if it took place. Additionally, the rating button will show how much this rule is supported by the people.

**Comment by bbatsov** [comment]
> Hey, is it possible to add a possibility to vote for each rule + link to the discussion like it's on http://www.betterspecs.org/ ?

The discussions usually happen in https://github.com/rubocop-hq/ruby-style-guide (https://rubystyle.guide). At this initially this was the case, at some point they shifted mostly here. 
In general the idea is that RuboCop should follow the evolution of the Ruby style guide.
I don't think that voting helps much, as it's easy to fake if you're persistent enough, so I prefer good arguments over a high vote count, but that's just me. :-) 

I agree it makes sense to link some rules in the style guide to the discussions that spawned them. For cops themselves links to the style guide should be enough IMO. No need to repeat ourselves.

> It's frustrating when I do not fully agree with the rule and don't have a possibility to discuss it or easy way to find such a discussion if it took place. 

I definitely think that it's not hard to start discussions today, I guess the problem that has to be solved is making those easier to find. The other thing that's very hard is to get everyone to agree on one particular style. :D 

P.S. Better Specs has been dead for quite a while. Recently it was superseded by a newer project that's also under RuboCop HQ - https://rspec.rubystyle.guide.

**Comment by koic** [comment]
I completely agree with @bbatsov that good arguments should be preferred over voting and reaction.

**Comment by Lukom** [comment]
> the problem that has to be solved is making those easier to find

100%! So, start including links to discussions under rules. Let's start this trend. People of 21 century have the right to comment!

> The other thing that's very hard is to get everyone to agree on one particular style.

This is where voting strikes. If it's hard to decide – start a discussion on StackOverflow, and by voting, we can easily find the best answer. This answer will have the Power because it'll contain arguments, upvoted comments and community support (votes count).
