### ISSUE TITLE
Style/ConditionalAssignment causes undefined method `column' for nil:NilClass

### ISSUE THREAD

**Issue by znz** [rubocop-hq/rubocop#7165]
## Expected behavior

Do not raise exception.

## Actual behavior

When

- `EnforcedStyle: assign_inside_condition`
- condition without else
- auto correction

causes error:

> undefined method `column' for nil:NilClass

## Steps to reproduce the problem

```
% cat .rubocop.yml
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
% cat a.rb
foo ||=
  if foo1?
    foo1
  elsif foo2?
    foo2
  end
% rubocop -a --only Style/ConditionalAssignment a.rb
Inspecting 1 file


0 files inspected, no offenses detected
undefined method `column' for nil:NilClass
```

## RuboCop version

> 0.71.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin18)

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #7166.
