### ISSUE TITLE
A cop for Rdoc documentation

### ISSUE THREAD

**Issue by jigarius** [rubocop-hq/rubocop#7175]
## Is your feature request related to a problem? Please describe.

I come from a PHP / Drupal background and I recently started working on Ruby. One thing I really like about Drupal is that they have a coding standard for documenting code. So, there are standard ways of documenting classes, functions, variables, etc.

## Describe the solution you'd like

It would be cool to have a cop which would enforce Rdoc syntax in a given Ruby code repo. So, if a class is not documented, the cop would say "please document the class as per Rdoc spec", until the comment format matches the Rdoc specs.

## Describe alternatives you've considered

I haven't tried anything yet. Just thinking aloud. Any recommendations / suggestions are welcome.

**Comment by koic** [comment]
I think that you can use `Style/Documentation` cop and `Style/DocumentationMethod` cop .

- https://docs.rubocop.org/en/stable/cops_style/#styledocumentation
- https://docs.rubocop.org/en/stable/cops_style/#styledocumentationmethod

`Style/DocumentationMethod` is disabled by default. You can enable it by setting the following in .rubocop.yml.

```yaml
Style/DocumentationMethod:
  Enabled: true
```

The following is an example.

```console
% cat .rubocop.yml
Style/DocumentationMethod:
  Enabled: true

% cat example.rb
# frozen_string_literal: true

class Example
  def do_something
    puts 'hello'
  end
end

% rubocop
Inspecting 1 file
C

Offenses:

example.rb:3:1: C: Style/Documentation: Missing top-level class documentation comment.
class Example
^^^^^
example.rb:4:3: C: Style/DocumentationMethod: Missing method documentation comment.
  def do_something ...
  ^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected
```

On the other hand, I think that it is too much responsibility for RuboCop to do the analysis of RDoc. It should be left to RDoc.
