### ISSUE TITLE
Running after `--auto-gen-config` does not ignore all convention offenses

### ISSUE THREAD

**Issue by sevenmaxis** [rubocop-hq/rubocop#7205]
I've generated `.rubocop_todo.yml` by `rubocop --auto-gen-config` command and get 13445 offenses.
Then I run just `rubocop` and still get 3858 offenses.
Seems that `.rubocop_todo.yml` doesn't work as expected.

**Comment by jcraigk** [comment]
@sevenmaxis There are various situations where you will get what you are describing.  For example, `Metrics/LineLength:Max` is a special case.  Also if you have specific `Exclude`s under certain Cops, then when you inherit from the TODO, the Exclude you specified will completely override the TODO's list (not a merge), producing warnings.

**Comment by jonas054** [comment]
@sevenmaxis We need more details.

- Which cops still report offenses?
- What does you `.rubocop.yml` look like?
- What does the generated `.rubocop_todo.yml` look like?
- What's the version and platform? (run `rubocop -V`)

**Comment by sevenmaxis** [comment]
Thanks to all, I was using `.rubocop_todo.yml` with old `.rubocop.yml`. It was resolved after I cleaned up the `.rubocop.yml`.
