### ISSUE TITLE
Project purpose and usage are sometimes misunderstood.

### ISSUE THREAD

**Issue by ngw** [rubocop-hq/rubocop#7206]
Some people misunderstand Rubocop purpose, I think we might need some kind of disclaimer on the purpose of the project and a couple lines about quality != consistency.

The website and the README should display some kind of disclaimer on how to use this, eventually some considerations on how to use rubocop and not blindly follow all the defaults. We clearly can't fix everything but if people is misunderstanding rubocop *this much* I feel like we should do something.

My understanding of rubocop is that it's a way to enforce consistency in a project, eventually in a CD environment, NOT to say that "string" is bad and 'string' is good in absolute terms.

I might even try if I receive an ok. (disclaimer: not native english speaker).

## Additional context

I've been rejected from a job in the past because my tech test had 150 "offenses". More than half were "string" instead of 'string', then I had { block } instead of {block} (debatable: https://rubystyle.guide/#spaces-braces), then some I might even agree like having params longer than 3 chars (but that was minsweeper so I had x: and y: all over the place), I then forgot some fronzen_string_literal. The project is in attachment.

[minesweeper.zip](https://github.com/rubocop-hq/rubocop/files/3383082/minesweeper.zip)

**Comment by bbatsov** [comment]
> Some people misunderstand Rubocop purpose, I think we might need some kind of disclaimer on the purpose of the project and a couple lines about quality != consistency.

I think we already covered this here https://rubystyle.guide/#a-note-about-consistency

> I've been rejected from a job in the past because my tech test had 150 "offenses". More than half were "string" instead of 'string', then I had { block } instead of {block} (debatable: https://rubystyle.guide/#spaces-braces), then some I might even agree like having params longer than 3 chars (but that was minsweeper so I had x: and y: all over the place), I then forgot some fronzen_string_literal. The project is in attachment.

That's a weird story. I'm sorry to hear this, but probably you don't want work for a company that evaluates people in this manner anyways.

**Comment by ngw** [comment]
> On 17 Jul 2019, at 06:56, Bozhidar Batsov <notifications@github.com> wrote:
> 
> Some people misunderstand Rubocop purpose, I think we might need some kind of disclaimer on the purpose of the project and a couple lines about quality != consistency.
> 
> I think we already covered this here https://rubystyle.guide/#a-note-about-consistency <https://rubystyle.guide/#a-note-about-consistency>
> I've been rejected from a job in the past because my tech test had 150 "offenses". More than half were "string" instead of 'string', then I had { block } instead of {block} (debatable: https://rubystyle.guide/#spaces-braces <https://rubystyle.guide/#spaces-braces>), then some I might even agree like having params longer than 3 chars (but that was minsweeper so I had x: and y: all over the place), I then forgot some fronzen_string_literal. The project is in attachment.
> 
> That's a weird story. I'm sorry to hear this, but probably you don't want work for a company that evaluates people in this manner anyways.
> 

That’s for sure, but I believe my ticket is still valid, isn’t it? I don’t know if the person doing this was technical (apparently product manager - so no) but there could be misunderstandings, isn’t it? At the end it’s 100 “offences” to the code, if I wasn’t a dev that wouldn’t sound nice :) (I mean I’m interested in an opinion too, first time this ever happened to me). Am I being too anal?

HAND, ngw
