### ISSUE TITLE
A Cop to detect wasteful initializations

### ISSUE THREAD

**Issue by ashmaroli** [rubocop-hq/rubocop#7207]
## Is your feature request related to a problem? Please describe.

I frequently encounter non-memoized method definitions that involve generation of a constant object that doesn't depend on the state of the Class / Module.

### Example

Given that there's a class with following instance methods:

```ruby
def fallback_data(config)
  {
    :foo => "bar",
    :sit => "amet",
  }.merge(config)
end

def cross_over(type)
  return unless %w[lorem ipsum dolor sit amet alpha].include?(type)

  # proceed doing stuff
end
```
The Hash generated in `:fallback_data` and the intermediate array in `:cross_over` are both going to remain the same in any given instance of the Class. Multiple calls to these methods are going to allocate those objects unnecessarily .

## Describe the solution you'd like

Flag such methods and recommend stashing the *constant-value* objects as "constants", or consider memoizing them as "singleton methods"

**Comment by Drenmi** [comment]
Hi, @ashmaroli!

The performance cops have recently been moved to [their own repository](https://github.com/rubocop-hq/rubocop-performance). Please help move your issue over there. Thank you! 🙇

**Comment by ashmaroli** [comment]
@Drenmi Will you be able to *transfer this issue* using the GitHub UI?
https://help.github.com/en/articles/transferring-an-issue-to-another-repository
