### ISSUE TITLE
Autocorrect support for Lint/ErbNewArguments

### ISSUE THREAD

**Issue by dduugg** [rubocop-hq/rubocop#7219]
The `Lint/ErbNewArguments` cop introduced in https://github.com/rubocop-hq/rubocop/pull/5845 produces messages like "Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments." and "Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: '-') instead."

It would be nice if there was an autocorrect to remove the 2nd arg and convert the subsequent ones to kwargs.

**Comment by koic** [comment]
Thanks for the feedback. I opened a PR #7221.

**Comment by dduugg** [comment]
Wow, that was fast! Thanks!
