### ISSUE TITLE
Rubocop `Exclude:` wildcard match files in parent directory (`..`)

### ISSUE THREAD

**Issue by vfonic** [rubocop-hq/rubocop#7220]
This was a difficult bug to find. :)

I wrote a huge bug description here, but I managed to narrow the issue down to a simple repo. Here's the repo: https://github.com/vfonic/rubokop

Here are the repro steps:

```sh
~/Developer/Ruby/rubokop $ rubocop rubi_spec.rb -d -c config/config.yml
configuration from /Users/viktor/Developer/Ruby/rubokop/config/config.yml
Default configuration from /Users/viktor/.rvm/gems/ruby-2.6.3/gems/rubocop-0.73.0/config/default.yml
Inspecting 1 file
Scanning /Users/viktor/Developer/Ruby/rubokop/rubi_spec.rb
.

1 file inspected, no offenses detected
Finished in 0.11867799982428551 seconds
~/Developer/Ruby/rubokop $ rubocop rubi_spec.rb -d -c config/.rubocop.yml
configuration from /Users/viktor/Developer/Ruby/rubokop/config/.rubocop.yml
Default configuration from /Users/viktor/.rvm/gems/ruby-2.6.3/gems/rubocop-0.73.0/config/default.yml
Inspecting 1 file
Scanning /Users/viktor/Developer/Ruby/rubokop/rubi_spec.rb
C

Offenses:

rubi_spec.rb:2:3: C: Metrics/MethodLength: Method has too many lines. [12/10]
  def asd ...
  ^^^^^^^

1 file inspected, 1 offense detected
Finished in 0.11422099964693189 seconds
```

I understand that config files starting with `.rubocop` are treated differently, but I'd expect `'**/*_spec.rb'` to be interpreted the same way (to match all of the file paths, no matter where they are found).

Is this a rubocop bug or desired behavior?

## RuboCop version

```sh
$ [bundle exec] rubocop -V
0.73.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin18)
```

**Comment by buehmann** [comment]
I did not know that rubocop behaved that way, but at least it is documented: https://rubocop.readthedocs.io/en/latest/configuration/#path-relativity

**Comment by vfonic** [comment]
I'm aware of that. The issue is that I'm using a wildcard: `'**/*_spec.rb'` but the file doesn't get excluded. I believe it should.

(the issue is probably in relative path resolution having `..` in it, I _think_)

**Comment by buehmann** [comment]
The path `**/*_spec.rb` gets evaluated relative to the location of `config/.rubocop.yml`; so it effectively excludes `config/**/*_spec.rb`.

**Comment by vfonic** [comment]
Aaaaaaaah. Now I understand why it's happening. :) Thanks!

I guess this is a WONTFIX then? I'll close it.
