### ISSUE TITLE
A proper home page and a better documentation portal

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#7223]
As we're inching closer to the release of RuboCop 1.0 I was wondering if it makes sense to invest in a proper home page and a better documentation portal. 

RuboCop used to have a homepage, but we forgot about it as some point (http://rubocop-hq.github.io/rubocop/). It was pretty basic, though, and there was a lot of room for improvement. 

Our current docs site is powered by RTD, which is quite limiting in many ways (mostly stemming from the use of Markdown, which is poorly suited for complex technical documentation). I'd say that our documentation doesn't reflect well on the project, but I don't enjoy working with RTD much and have struggled to find motivation to improve the docs, because of this. 

Recently I replaced the home page and the docs portal of my other more prominent project (CIDER) with https://cider.mx and https://docs.cider.mx and I wonder if it makes sense to do something similar for RuboCop as well. I guess that's mostly a question for @rubocop-hq/rubocop-core, but everyone's welcome to share their perspective.

**Comment by bbatsov** [comment]
Seems there are no objections to doing this and I can tackle at some point the manual conversion itself, which should pretty straightforward. The only thing that will required a bit of work is the landing page and the generator for the cop docs.

**Comment by laurmurclar** [comment]
Seems like some work has been done on this lately :) Looks good but I have some feedback about the `Contents` sidebar - should I open another issue or is this the right place to discuss it?

**Comment by bbatsov** [comment]
I was looking for this ticket the other day, but I couldn't find it. 😆 

> Seems like some work has been done on this lately :)

Yeah, I finally replaced the old docs site a couple of days ago. 

> Looks good but I have some feedback about the Contents sidebar - should I open another issue or is this the right place to discuss it?

I think it'd be best to file a separate issue.
