### ISSUE TITLE
EnforcedSyle options for Style/InfiniteLoop

### ISSUE THREAD

**Issue by dduugg** [rubocop-hq/rubocop#7227]
## Is your feature request related to a problem? Please describe.

The `Style/InfiniteLoop` cop requires the use of `loop do` over `while true`. I would like an option to require the latter instead, as it has better performance characteristics (it doesn't create a new scope). See the Ruby Kaigi [talk](https://rubykaigi.org/2019/presentations/ktou.html) on "Better CSV processing with Ruby 2.6" (in particular, [slides](https://slide.rabbit-shocker.org/authors/kou/rubykaigi-2019/) 43-45)

## Describe the solution you'd like

`EnforcedStyle: LoopDo` (default)
```ruby
# bad
while true
  work
end

# good
loop do
  work
end
```
`EnforcedStyle: WhileTrue`
```ruby
# bad
loop do
  work
end

# good
while true
  work
end
```

**Comment by koic** [comment]
I'm a native Japanese speaker and I joined RubyKaigi 2019 and listened to them. I heard about the YouTube recording again now. This may be a bit confusing if only slides are referenced...

In conclusion, they are not always recommended to use `while true`.

Basically, it is recommended to use `loop` and is told to use `while true` unavoidably when it becomes a bottleneck. Their talks are against making `while true` in all contexts.

Therefore I think an option to limit to `while true` should not provided. I will close this feature request.

BTW, RubyKaigi is a conference I look forward to every year. I'm happy to be quoted from the conference. Thank you :-)
