### ISSUE TITLE
auto-correct Style/InverseMethods and Style/SymbolProc together inverts meaning of code

### ISSUE THREAD

**Issue by manlon** [rubocop-hq/rubocop#7236]
Code like

```[:a, false, :b, false].reject { |x| !x }```

violates `Style/InverseMethods` and `Style/SymbolProc`. Fixing one or the other should be enough but when `--auto-correct`'d we get 

```[:a, false, :b, false].select(&:!)```

which has the opposite meaning. I realize Style/SymbolProc is not auto-correct-safe but here the correction _would_ be safe except for interfering with Style/InverseMethods (and this can be seen with `rubocop --safe --auto-correct`).

--------

## Expected behavior

After applying the auto-correction for Style/InverseMethods there should be no violation for Style/SymbolProc so it should not apply.

## Actual behavior

Style/SymbolProc correction was applied changing the meaning of the code.

## Steps to reproduce the problem

* have a file test.rb:
```
puts([:a, false, :b, false].reject { |x| !x })
```
* `rubocop --auto-correct test.rb`
```Offenses:

test.rb:3:6: C: [Corrected] Style/InverseMethods: Use select instead of inverting reject.
puts([:a, false, :b, false].reject { |x| !x })
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.rb:3:36: C: [Corrected] Style/SymbolProc: Pass &:! as an argument to reject instead of a block.
puts([:a, false, :b, false].reject { |x| !x })
                                   ^^^^^^^^^^
```
* `ruby test.rb` now produces different output

## RuboCop version

0.73.0 (using Parser 2.6.3.0, running on ruby 2.6.0 x86_64-darwin18)

**Comment by Drenmi** [comment]
Thanks for your report @manlon! 🙏 

I have made a PR that marks the auto-correct of `Style/InverseMethods` as incompatible with that of `Style/SymbolProc`, so in the case they both want to correct, the former should back off.
