### ISSUE TITLE
Infinite loop  correcting Layout/EmptyLinesAroundAccessModifier

### ISSUE THREAD

**Issue by libc** [rubocop-hq/rubocop#7246]
Infinite loop when correcting the following code with the default config:

```ruby
class A
  attr_reader :private
  def private?
    private
  end
end
```

I looked in the opened issues, and couldn't find anything related, but hope it's not a duplicate.

--------

## Expected behavior

Something reasonable, preferably without spurious spaces around `private`

## Actual behavior

```
➜  a bundle exec rubocop -c .rubocop.yml  -a a.rb
Inspecting 1 file
C

Offenses:

a.rb:6:1: C: [Corrected] Layout/EmptyLinesAroundMethodBody: Extra empty line detected at method body beginning.
a.rb:6:5: C: [Corrected] Layout/EmptyLinesAroundAccessModifier: Keep a blank line before and after private.
    private
    ^^^^^^^
a.rb:8:1: C: [Corrected] Layout/EmptyLinesAroundMethodBody: Extra empty line detected at method body end.

0 files inspected, 3 offenses detected, 3 offenses corrected
Infinite loop detected in /private/tmp/a/a.rb.
/Users/eugene/.rvm/gems/ruby-2.5.3/bundler/gems/rubocop-f51c53c0be3c/lib/rubocop/runner.rb:268:in `check_for_infinite_loop'
```

## Steps to reproduce the problem

Create Gemfile

```ruby
source 'https://rubygems.org'

gem "rubocop", github: "rubocop-hq/rubocop"
```

Create a.rb
```ruby
class A
  attr_reader :private
  def private?
    private
  end
end
```

Create empty .rubocop.yml

```bash
touch .rubocop.yml
```

Run:
```bash
bundle && bundle exec rubocop -c .rubocop.yml  -a a.rb
```

## RuboCop version

I used the latest master (f51c53c0be3c16b47407c947d85beb3db21e86ac). It's also possible to reproduce on the release version.

```
0.73.0 (using Parser 2.6.3.0, running on ruby 2.5.3 x86_64-darwin18)
```

**Comment by buehmann** [comment]
I think this is a symptom of the underlying #7212: If `Layout/EmptyLinesAroundAccessModifier` did not detect `private` within the method definition above, there would be no infinite loop.

**Comment by dmitryv** [comment]
I'm facing the same issue with the following code:

```
class A
  def test
    return nil if public
  end

  def test2; end
end
```

However it works fine if I remove the test2 method definition:

```
class A
  def test
    return nil if public
  end
end
```
