### ISSUE TITLE
Layout/SpaceInsideStringInterpolation auto-correct gives infinite loops with multiline interpolations

### ISSUE THREAD

**Issue by halfwhole** [rubocop-hq/rubocop#7252]
`Layout/SpaceInsideStringInterpolation` can give infinite loops for multiline string interpolations upon running auto-correct, when run alongside `Layout/SpaceBeforeComment` and `Layout/ClosingParenthesisIndentation`.

--------

## Expected behavior

Perhaps multiline interpolations can simply be ignored, similar to the suggestion in https://github.com/rubocop-hq/rubocop/issues/5620, or any other reasonable fix terminating the loop would also be possible.

## Actual behavior

Infinite loop.

## Steps to reproduce the problem

On running autocorrect, this one gives an infinite loop with `Layout/SpaceBeforeComment`:

```
"#{ # comment
foo
}"
```

```
Offenses:

test.rb:1:4: C: [Corrected] Layout/SpaceBeforeComment: Put a space before an end-of-line comment.
"#{# comment
   ^^^^^^^^^
test.rb:1:4: C: [Corrected] Layout/SpaceInsideStringInterpolation: Space inside string interpolation detected.
"#{ # comment
   ^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in [...]/test.rb.
```

And this one gives an infinite loop with `Layout/ClosingParenthesisIndentation`:
```
"#{
        foo
}"
```

```
Offenses:

test.rb:3:1: C: [Corrected] Layout/ClosingParenthesisIndentation: Indent ) to column 6 (not 0)
}"
^
test.rb:3:1: C: [Corrected] Layout/SpaceInsideStringInterpolation: Space inside string interpolation detected.
      }"
^^^^^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in [...]/test.rb.
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.74.0 (using Parser 2.6.3.0, running on ruby 2.5.1 x86_64-linux)
```

**Comment by buehmann** [comment]
@halfwhole Thanks for your report. I created pull request #7255 ignoring multi-line interpolation completely for now.
