### ISSUE TITLE
Fatal exceptions in `rubocop --auto-gen-config` produce empty rubocop_todo.yml

### ISSUE THREAD

**Issue by jcraigk** [rubocop-hq/rubocop#7254]
When using CLI command `rubocop --auto-gen-config`, an empty `.rubocop_todo.yml` file is generated and a line is placed in `.rubocop.yml` to inherit from this file when an error occurs during the process.  For example, if you are inheriting from a gem in `.rubocop.yml` and you have not run `bundle install` to include the gem, when running `rubocop --auto-gen-config` the following output is observed:

```
Added inheritance from `.rubocop_todo.yml` in `.rubocop.yml`.
Unable to find gem my-rubocop-gem; is the gem installed? Gem::MissingSpecError
```

It seems the intended behavior would be that the error is thrown first and no changes to files are written in failure cases.

--------

## Expected behavior

When any fatal exception occurs during execution of the `rubocop --auto-gen-config` command, it should be displayed and there should be no changes to `.rubocop.yml` or `.rubocop_todo.yml`.

## Actual behavior

An empty `.rubocop_todo.yml` file is generated and a line is placed at the top of `.rubocop.yml` to inherit from this empty file when a fatal exception occurs.

## Steps to reproduce the problem

1. Add the following lines to `.rubocop.yml`:

```
inherit_gem:
  nonexistent-rubocop-gem:
    - default.yml
```

2. Run `rubocop auto-gen-config`.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.74.0 (using Parser 2.6.3.0, running on ruby 2.6.3 x86_64-darwin17)
```

**Comment by woarewe** [comment]
Hi, everyone!
I started to investigate this bug and I also found some interesting behavior.
If you run rubocop for a project in another directory it creates files `.rubocop.yml` and `.rubocop_todo.yml` in the current directory instead of the path which passed to params. Some example below:
```shell
➜  rubocop-test rubocop -v
0.75.0
➜  rubocop-test cat ~/Development/Projects/commercial/clang_journey/.rubocop.yml
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6.3

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80
➜  rubocop-test ls -a
.  ..
➜  rubocop-test rubocop --auto-gen-config  ~/Development/Projects/commercial/clang_journey
Added inheritance from `.rubocop_todo.yml` in `.rubocop.yml`.
Phase 1 of 2: run Metrics/LineLength cop
# Deleted logs...
7 files inspected, 2 offenses detected
Created .rubocop_todo.yml.
➜  rubocop-test ls -a
.                 ..                .rubocop.yml      .rubocop_todo.yml
```
