### ISSUE TITLE
Exclude corrected errors from output

### ISSUE THREAD

**Issue by AlecRust** [rubocop-hq/rubocop#7265]
## Is your feature request related to a problem? Please describe.

After adding lots of files e.g. using `rails generate` and running `rubocop -a` via a pre-commit hook, I get a noisy output with most of the output displaying errors that have already been automatically corrected.

**To see just the list of errors I need to address, I need to run `rubocop -a` again manually.**

![screenshot](https://i.imgur.com/XuMbqlc.png)

## Describe the solution you'd like

The ability (a flag?) to exclude "corrected" errors from the output, or display "x errors automatically corrected" instead of the verbose output for each one.

## Additional context

`--format simple` doesn't really help here since most of the output remains about the "corrected" errors which I don't care about.

![screenshot](https://i.imgur.com/xPD7c6h.png)

**Comment by buehmann** [comment]
As long as RuboCop does not support this out of the box, you could use a [custom formatter](http://www.rubocop.org/en/stable/extensions/#custom-formatters), e.g. by subclassing an existing one:
```ruby
class HideCorrectedFormatter < RuboCop::Formatter::SimpleTextFormatter
  def file_finished(file, offenses)
    super(file, offenses.reject(&:corrected?))
  end
end
```
