### ISSUE TITLE
Don't use `#send` etc. to include or prepend modules

### ISSUE THREAD

**Issue by bquorning** [rubocop-hq/rubocop#7274]
Back in the day (before Ruby 2.1), `Module.include` and `Module.prepend` were private methods. So when people authored gems / patched monkeys, they wrote e.g. `Foo.send(:include, MyPatch)`. In our day and age, I think we should encourage everybody to just write `Foo.include(MyPatch)`.

## Describe the solution you'd like

Recommend calling `Foo.include(Bar)` over `Foo.send(:include, Bar)`, `Foo.public_send(:include, M)`, etc.

Recommend calling `Foo.prepend(Bar)` over `Foo.send(:prepend, Bar)`, `Foo.public_send(:prepend, M)`, etc.

## Describe alternatives you've considered

None

## Additional context

None

**Comment by koic** [comment]
I think it makes sense because it can be unified with a new mix-in style using public `include` and `prepend` (and `extend`) methods. I opened a PR #7279.
