### ISSUE TITLE
Tidelift funding

### ISSUE THREAD

**Issue by tiegz** [rubocop-hq/rubocop#7282]
Hello!

Just wanted to say thanks to all the maintainers of Rubocop -- I've been using it on projects for years and appreciate all of your work and time.

I’m an engineer at Tidelift, saw your README's [Funding section](https://github.com/rubocop-hq/rubocop#funding), and noticed that [Rubocop currently has almost $1000 per month on Tidelift](https://tidelift.com/lifter/search/rubygems/rubocop) that could be claimed. 

In short, Tidelift is a "managed open source" subscription for companies, in which we use their dependency trees to determine which packages are depended upon and, therefore, should get the funds. You can read more about Tidelift’s subscription service [on our site](https://tidelift.com/subscription).

The tasks we ask you to perform are things that most maintainers already do (e.g. provide release notes, validate the license of a package, and monitor and alert for security vulnerabilities), but you can find the specific details in [this blog post](https://blog.tidelift.com/how-to-start-earning-money-for-your-open-source-project-with-tidelift) by @kszu.

Please let me know what you think! Both @phated and I are happy to answer any other questions you might have. 🤖 ❤️ 

Thanks again!

-tieg

**Comment by bbatsov** [comment]
Thanks for reaching out! You've reminded me that I got a couple of emails from Tidelift last year and I completely forgot to respond to them. 😄 I guess GitHub is a much better way to get a hold of a project maintainer than email. 😉
