### ISSUE TITLE
Style/FrozenStringLiteralComment should not be considered as safe for autocorrection

### ISSUE THREAD

**Issue by jonathantribouharet** [rubocop-hq/rubocop#7287]
Hi,
I think `Style/FrozenStringLiteralComment` should not be considered as safe for autocorrection.

For example:

```
my_string = 'foo'
my_string << 'will crash with frozen_string_literal'
```

This code will crash with an error `can't modify frozen String (FrozenError)`.

Regards,
John

**Comment by buehmann** [comment]
Thanks, I opened a pull request for this: https://github.com/rubocop-hq/rubocop/pull/7307
