### ISSUE TITLE
Add JUnit formatter

### ISSUE THREAD

**Issue by jpserra** [rubocop-hq/rubocop#7303]
Some CI tools expect test results to be formatted as JUnit XML. It would be interesting to support this for rubocop Cop results so we can add a step in the pipeline to check for rubocop offenses.

## Solution

Include a JUnit formatter in rubocop

**Comment by buehmann** [comment]
What would be an example of such a CI tool?

**Comment by jpserra** [comment]
not to say it's the only format supported but Jenkins can be configured to
use it

**Comment by thomthom** [comment]
Same for AppVeyor: https://www.appveyor.com/docs/running-tests/#uploading-xml-test-results

**Comment by koic** [comment]
This issue has been closed by #7701.
