### ISSUE TITLE
Style/YodaCondition: not necessarily safe to autocorrect

### ISSUE THREAD

**Issue by jbodah** [rubocop-hq/rubocop#7345]
I was reviewing a PR on one of our projects and was surprised to see `Style/YodaCondition` was marked as safe to autocorrect: https://github.com/rubocop-hq/rubocop/blob/master/manual/cops_style.md#styleyodacondition

It's a gotcha in Ruby that operators are not necessarily commutative. Take the following example:

```rb
class MyKlass
  def ==(other)
    true
  end
end

obj = MyKlass.new
obj == 'string'
#=> true
'string' == obj 
#=> false
```

This is a trivial examples but I have run into several real cases in the wild where this occurs in Rails apps

It seems like some literals _are_ commutative in some cases (e.g. integers will delegate to `MyKlass#==` even if the integer is the receiver)

**Comment by knu** [comment]
I agree.  Reversing operands is an unsafe modification in Ruby and can easily break existing code that is written for a reason.
