### ISSUE TITLE
Deprecate and remove support for non-namespaced cop references

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#7355]
## Is your feature request related to a problem? Please describe.

I've noticed that many people still have in their configs cops without a department prefix - e.g. simply `LineLength`.
I was under the impression we stopped supporting this a while ago and I guess now's the time to do it. 

## Describe the solution you'd like

Let's start issuing warnings for people to fix their configs/ignore directives for the next several versions and drop this completely afterwards.

@jonas054 Mind looking into this?

**Comment by Drenmi** [comment]
Wow. This must be very old. It's the first time I hear about it having been a thing. 😅

**Comment by bbatsov** [comment]
Yeah, there was a time where departments didn't existed. :-)

**Comment by jonas054** [comment]
> Mind looking into this?

Not at all. :)
