### ISSUE TITLE
Style/UnneededSort is unsafe

### ISSUE THREAD

**Issue by dmitryv** [rubocop-hq/rubocop#7366]
When sorting field value is nil, max_by returns first element of array, but sort_by...last returns the last one. Tested using ruby 2.3.3 and 2.6.3

```
2.6.3 :001 > a = [{id: 1, created_at: nil}, {id: 2, created_at: nil}]
2.6.3 :002 > a.sort_by{|x| x[:created_at]}.last[:id]
 => 2
2.6.3 :003 > a.max_by{|x| x[:created_at]}[:id]
 => 1
```

--------

## Steps to reproduce the problem

```
$ cat test.rb
a = [{id: 1, created_at: nil}, {id: 2, created_at: nil}]
a.sort_by{|x| x[:created_at]}.last[:id]
```

```
$ rubocop --safe-auto-correct --only Style/UnneededSort test.rb
Inspecting 1 file
C

Offenses:

test.rb:2:3: C: [Corrected] Style/UnneededSort: Use max_by instead of sort_by...last.
a.sort_by{|x| x[:created_at]}.last[:id]
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

```
$ cat test.rb
a = [{id: 1, created_at: nil}, {id: 2, created_at: nil}]
a.max_by{|x| x[:created_at]}[:id]
```

## RuboCop version

```
0.74.0 (using Parser 2.6.4.1, running on ruby 2.3.3 x86_64-darwin18)
```

**Comment by bbatsov** [comment]
Great catch!

**Comment by buehmann** [comment]
I don't believe this is an issue. The API docs clearly state that `sort_by` is unstable:

> The result is not guaranteed to be stable. When two keys are equal, the order of the corresponding elements is unpredictable.

https://ruby-doc.org/core-2.6.5/Enumerable.html#method-i-sort_by

So anybody using `sort_by.last` on a list with duplicates who expects a certain item to be returned relies on undefined behaviour and already has a bug in his code.

**Comment by koic** [comment]
Ah, that makes sense!
