### ISSUE TITLE
Layout/IndentationConsistency adds spaces to multi-line strings

### ISSUE THREAD

**Issue by dmitryv** [rubocop-hq/rubocop#7370]
--------

## Expected behavior

Ignore multi-line strings

## Steps to reproduce the problem

```
$ cat test.rb
  x = 'a'
y = 'b
c'
```

```
$ rubocop --auto-correct --only Layout/IndentationConsistency ./test.rb
Inspecting 1 file
C

Offenses:

test.rb:2:1: C: [Corrected] Layout/IndentationConsistency: Inconsistent indentation detected.
y = 'b ...
^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

```
$ cat test.rb
  x = 'a'
  y = 'b
  c'
```

```
"b\nc" == "b\n  c"
 => false
```

## RuboCop version

```
0.74.0 (using Parser 2.6.4.1, running on ruby 2.3.3 x86_64-darwin18)
```

**Comment by buehmann** [comment]
This has the same root cause as #7177.

**Comment by buehmann** [comment]
And here is some work on this from 3 months ago: https://github.com/rubocop-hq/rubocop/compare/master...buehmann:spec/alignment_corrector

I haven't gotten around to continuing on that. I still don't like the way I am testing the `AlignmentCorrector`.
