### ISSUE TITLE
Provide a --ignore-path option

### ISSUE THREAD

**Issue by soullivaneuh** [rubocop-hq/rubocop#7380]
## Is your feature request related to a problem? Please describe.

In order to simplify lint tool configuration, we are building a common linter tool for all our projects: https://gitlab.com/nexylan/pretty/

Rubocop works well installed globally, but it will analyses any file, even file ignored by git.

The configuration have an exclude section, but it does not fit my need because the goal is to get ride of per-project configuration file.

## Describe the solution you'd like

Have a `--ignore-path` option (default to `.rubocopignore`) to specify an ignore file.

The file must follow the git ignore format to simplify the process.

Usage example:

```
rubocop --ignore-path .gitignore .
```

A lot of lint tools already provide this option like `eslint`, `prettier` or even `stylelint`.

## Describe alternatives you've considered

I may build a script to transpile the `.gitignore` content to a rubocop config on the fly.

But it is quite heavy to do and the .gitignore format may be not the same as the rubocop exclusion pattern (like `!/path` patterns).

## Additional context

Some gems may help you achieve this feature with ease:

- https://github.com/robotdana/fast_ignore
- https://gitlab.com/lbriais/dir_glob_ignore

**Comment by BobbyMcWho** [comment]
Take a look at the [config docs](https://docs.rubocop.org/en/stable/configuration/) and see if any of those work for you, there's quite a few options, including pulling from remote yml files.

**Comment by soullivaneuh** [comment]
@BobbyMcWho I saw the doc, but I don't see how this help me with my feature request.

Could please give me some hint?

**Comment by soullivaneuh** [comment]
I would love to have any feedback on it. :+1:
