### ISSUE TITLE
Cannot determine formatter for "p"

### ISSUE THREAD

**Issue by Kjarrigan** [rubocop-hq/rubocop#7389]
## Actual behavior

`Cannot determine formatter for "p"`

## Steps to reproduce the problem

`rubocop -fp`

## RuboCop version

```
$ [bundle exec] rubocop -V
0.75.0
```
Caused by https://github.com/rubocop-hq/rubocop/pull/7317 as the logic of determining the formatter matches the "first" letters.¹ Since [p] is now not unique anymore this can't work
(noticed this myself when I tried to introduce my own formatter couple months ago)

What works is `rubocop -fpr` but that's not what the help tells.

So either change the help or replace the logic with an actual "pattern" match rather than a `starts with`

```
    -f, --format FORMATTER           Choose an output formatter. This option
                                     can be specified multiple times to enable
                                     multiple formatters at the same time.
                                       [pr]rogress (default)
                                       [pa]cman
```

¹ - https://github.com/rubocop-hq/rubocop/pull/6407#issuecomment-439799743

**Comment by Kjarrigan** [comment]
that's the actual call we use in our CI - we like to see both the progress and the offenses output:
`rubocop --color -fp -fo`

**Comment by bbatsov** [comment]
Thanks for the detailed bug report! 

>  an actual "pattern" match rather than a starts with

Probably that'd be a better approach.

**Comment by zmaupin** [comment]
I'll see if I can get something together to fix this.

**Comment by jfhinchcliffe** [comment]
Whoop! Looks like we had a crack at the same time, @zmaupin 😆
