### ISSUE TITLE
Pacman formatter depends on tput

### ISSUE THREAD

**Issue by cremno** [rubocop-hq/rubocop#7391]
The new Pacman formatter depends on the *nix only `tput` command. You could use `mode` on Windows but a better solution would be using `IO#winsize` which is part of Ruby's standard library.

**Comment by bbatsov** [comment]
Your suggestions sounds good to me. I guess we didn't review the original PR carefully enough.

**Comment by laurenball** [comment]
hey @bbatsov and @koic I could take this on!

**Comment by cremno** [comment]
Another possibility: since `rubocop` already depends on `ruby-progressbar` you could built upon [its code](https://github.com/jfelchner/ruby-progressbar/blob/releases/v1.10.1/lib/ruby-progressbar/calculators/length.rb). It doesn't really support Windows either (just defaults to 80) but at least it doesn't fail because of a missing executable.
