### ISSUE TITLE
Gemspec/RequiredRubyVersion should be aware of Gem::Requirement

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop#7408]
## Is your feature request related to a problem? Please describe.

Recent bundler uses `Gem::Requirement` for `required_ruby_version` in gemspec.
https://github.com/bundler/bundler/pull/7209

But Gemspec/RequiredRubyVersion is not aware of `Gem::Requirement`. So the cop ignores buggy code if it uses `Gem::Requirement`.

```ruby
Gem::Specification.new do |spec|
  # The cop should add an offesne to this code if .rubocop.yml does not specify `TargetRubyVersion: 2.5`.
  # But it doesn't.
  spec.required_ruby_version = Gem::Requirement.new(">= 2.5.0")
end
```

## Describe the solution you'd like

The cop should aware of `Gem::Requirement`.

## Describe alternatives you've considered

nothing

## Additional context

nothing

**Comment by mvz** [comment]
@marcandre can you please reopen this so it will get noticed by whoever wants to work on it?

**Comment by mvz** [comment]
Thanks, @koic!

**Comment by marcandre** [comment]
> @marcandre can you please reopen this so it will get noticed by whoever wants to work on it?

Oops, sorry, I did mean to reopen it, thanks for the ping, and thanks @koic :-)
