### ISSUE TITLE
New cop: Detect return with argument on the top-level

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop#7425]
## Is your feature request related to a problem? Please describe.

`return` has been allowed on the top-level since Ruby 2.4.

```ruby
foo

return # Since Ruby 2.4.

bar # It is never executed.
```

But the argument of `return` is ignored always.

```ruby
return 1 # 1 is always ignored.
```

It will be detected since Ruby 2.7. https://github.com/ruby/ruby/commit/aa97410b0a85cb4ceb956ab943b5eee92a128411
But RuboCop doesn't.

## Describe the solution you'd like

Add a new cop to detect the problem. Maybe it will be named `Lint/TopLevelReturnWithArgument`.

## Describe alternatives you've considered

nothing

## Additional context

nothing

**Comment by lizzzp1** [comment]
Can I take a stab at this?
