### ISSUE TITLE
How to detect when the result of Array#sort isn't captured?

### ISSUE THREAD

**Issue by cstyles** [rubocop-hq/rubocop#7446]
## Is your feature request related to a problem? Please describe.

Apologies if this already exists but I couldn't find anything by searching. Is there a way to report when the result of something like `Array#sort` or `Hash#merge` isn't captured?

## Describe the solution you'd like

I'd like to see a cop that will detect when these types of methods are called but their return value isn't stored in a variable, passed as an argument, or used in some other way. In that case, I would like it if `rubocop` would suggest `Array#sort!` or `Hash#merge!` to do the operation in-place.

edit: It occurred to me after the fact that it's not always apparent that we're calling `sort` or `merge` on an `Array` or `Hash` and we wouldn't necessarily want to suggest `sort!` for other (possibly user-defined) classes where `sort` might have side effects. So I don't think this is easy to implement, at least not for a dynamically typed language like Ruby.

**Comment by buehmann** [comment]
I haven't tried this, but it looks as if https://docs.rubocop.org/en/stable/cops_lint/#lintvoid could do the trick.

**Comment by cstyles** [comment]
Oh wow, that's exactly what I wanted!

It looks like the list of methods that it checks for doesn't include `merge`. I just opened a PR to add it. Thanks for your help!
