### ISSUE TITLE
Request to add Code of Conduct

### ISSUE THREAD

**Issue by agusputra** [rubocop-hq/rubocop#7472]
Can we have [Code of Conduct](https://www.contributor-covenant.org) and add that link to the README.md or CONTRIBUTING.md?

**Comment by Drenmi** [comment]
> Everyone's welcome to suggest their favourite code of conduct and I'll explore them when I can.

How about a modified version of [The Ruby Community Conduct Guideline](https://www.ruby-lang.org/en/conduct)?

Some of the rationales for this:

- It is simple (i.e. more of a _code_ than a legal framework), which seems proportionate, as we don't really have a problem with misconduct.

- It comes free of any political baggage and contention.

- It was adopted by a community very similar to our own, after [a lot of discussion](https://bugs.ruby-lang.org/issues/12004).

**Comment by bbatsov** [comment]
@Drenmi Great idea! 

How modified? Just replacing Ruby with RuboCop perhaps?

**Comment by koic** [comment]
I completely agree with @Drenmi suggestion. I think it is a good opinion to match The Ruby Community Conduct Guideline if CoC will be added.
