### ISSUE TITLE
Autocorrect zero

### ISSUE THREAD

**Issue by ricglz0201** [rubocop-hq/rubocop#7488]
## Describe the solution you'd like

I think it will be nice and non-intrusive that when you run the autocorrect the `Style/NumericPredicate` cop can fix the problems of `foo  == 0`. And if it's not possible I just wanted to know the why

**Comment by Drenmi** [comment]
Hi, @ricglz0201!

The reason for this is for the case where `foo` is `nil`. Compare:

```ruby
foo = nil

foo == 0
#=> false
```

to:

```ruby
foo = nil

foo.zero?
#=> NoMethodError (undefined method `zero?' for nil:NilClass)
```

So we don't auto-correct to prevent breaking existing code. (Even though I personally think that the second behaviour is much better, as implicit comparisons to `nil` are almost always 1) a bug waiting to happen or 2) a developer oversight.)
