### ISSUE TITLE
Cop Idea: Useless trailing comma in block arguments

### ISSUE THREAD

**Issue by mvz** [rubocop-hq/rubocop#7492]
## Is your feature request related to a problem? Please describe.

The following two block invocations do different things:

```ruby
[[1, 2, 3], [3, 4, 5]].each { |a| p [a] }
[[1, 2, 3], [3, 4, 5]].each { |a,| p [a] }
```

The following two block invocations do exactly the same thing:

```ruby
[[1, 2, 3], [3, 4, 5]].each { |a, b| p [a, b] }
[[1, 2, 3], [3, 4, 5]].each { |a, b,| p [a, b] }
```

This is surprising, so it makes sense to enforce a consistent style there.

## Describe the solution you'd like

I'd like RuboCop to enforce the removal of the final comma in the second example, so the code reads like so:

```ruby
[[1, 2, 3], [3, 4, 5]].each { |a, b| p [a, b] }
```

## Describe alternatives you've considered

The behavior is actually more similar to the one-argument case *with* a comma, so having a trailing comma could be enforced instead. However, visually, removal of the comma is more pleasing, and more in line with other cops that remove extra commas by default. I suppose the enforced style could also be a setting.

## Additional context

N/A.

**Comment by pawptart** [comment]
This is handled for method definitions by `Style/TrailingCommaInArguments` and seems to support enforced style as a setting ([docs](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/TrailingCommaInArguments)).

I can look into putting a PR out for this if you'd like.

**Comment by mvz** [comment]
That would be great.

The enforced style option for `Style/TrailingCommaInArguments` only seems to be about the multi-line case, which is disallowed for blocks (`Layout/MultilineBlockLayout` flags it). So, I think it makes sense to leave that setting out to start with.

In fact, when `Layout/MultilineBlockLayout` autocorrect is used, it removes trailing comma's, even in the single-argument case :thinking: .

**Comment by pawptart** [comment]
I just saw [#7628], so I'll take a look at that as well.

**Comment by mvz** [comment]
Thanks, @pawptart!
