### ISSUE TITLE
Feature: Have `Lint/RescueException` allow `rescue Exception` if exception is re-raised

### ISSUE THREAD

**Issue by patbl** [rubocop-hq/rubocop#7501]
`Lint/RescueException` prohibits `rescue Exception` in all cases, but occasionally you do want to rescue `Exception`. The examples I can think of are (1) error reporting ([example](https://github.com/getsentry/raven-ruby/blob/94306bca394cdaf223e47b6c9b460af6748e8803/lib/raven/integrations/rack.rb#L54-L56)) and (2) clean-up tasks.

```ruby
def with_error_reporting
  yield
rescue Exception => error
  report_error(error)
  raise
end
```

```ruby
def safely_do_something
  do_something
rescue Exception
  release_resource
  raise
end
```

It would be nice if there were a configurable setting that allowed `rescue Exception` as long as the `rescue` block contained an unqualified `raise`.

**Comment by tejasbubane** [comment]
I guess this issue can be closed then based on @bbatsov's [comment](https://github.com/rubocop-hq/rubocop/pull/7548#issuecomment-562260440). 

> I'm on the fence about this, as I'm not sure we're solving a real problem here. I think almost always StandardError would be fine in those cases as well.

**Comment by akihikodaki** [comment]
I think I can provide a valid and concrete use case for this. Please take a look at the following code:

```ruby
pid = spawn('take_long')
begin
  Process.wait pid
rescue Exception
  Process.kill :KILL, pid
  Process.wait pid
  raise
end
```

This code intends to spawn a command that takes long, and wait for it. If the user sends SIGINT to the Ruby process, the command will be killed and waited.

Replacing `rescue Exception` with `rescue StandardError` does not work because it will not be able to catch SIGINT.
Replacing `rescue Exception` with `ensure` does not work because the process will not exist if the first `Process.wait` succeeds.

**Comment by jmanian** [comment]
I have a real-world situation as well where I needed to `rescue Exception` and re-raise it. In this case a Sidekiq job doing some processing that can take a little time:
- We have a record tracking that processing is occurring, to avoid two processes trying to do it at the same time. (And that record is updated using locks.)
- If an error occurs, we need to rescue and set that record to `processing: false` and then re-raise.
- We were rescuing `StandardError`, but the sidekiq process was restarted while the job was running, raising `Interrupt` (I think) which was not rescued and the record was left at `processing: true` with the job put back in the queue by Sidekiq.

So I've change this to `rescue Exception` and I had to use `rubocop:disable Lint/RescueException` which is not ideal.

**Comment by jmanian** [comment]
Also worth noting that sidekiq itself has multiple places where it rescues `Exception` and re-raises. Just examples of other cases in a widely used ruby gem.
- [example](https://github.com/sidekiq/sidekiq/blob/0f150827ac8816dff369ff7bcc9635f95922d23f/lib/sidekiq/job_logger.rb#L19-L22)
- [example](https://github.com/sidekiq/sidekiq/blob/0f150827ac8816dff369ff7bcc9635f95922d23f/lib/sidekiq/metrics/tracking.rb#L39-L44)
- [example](https://github.com/sidekiq/sidekiq/blob/0f150827ac8816dff369ff7bcc9635f95922d23f/lib/sidekiq/job/iterable.rb#L231-L234)

**Comment by koic** [comment]
Yeah, it seems sufficient as a rationale to me. I've opened #14579 to resolve this issue.
