### ISSUE TITLE
Layout/SpaceInsideArrayLiteralBrackets should correct empty lines

### ISSUE THREAD

**Issue by ayacai115** [rubocop-hq/rubocop#7509]
## Expected behavior

```rb
foo = [
]
foo
```

When I `rubocop -a`, rubocop corrects the empty line.
```rb
foo = []
foo
```

## Actual behavior
When I `rubocop -a`...

```rb
Offenses:

sample.rb:1:7: C: [Corrected] Layout/SpaceInsideArrayLiteralBrackets: Do not use space inside empty array brackets.
foo = [ ...
      ^

1 file inspected, 1 offense detected, 1 offense corrected
```
But it's not actually corrected and I keep getting this message.
I think this is a bug.

## Steps to reproduce the problem
```rb
$ vi sample.rb
foo = [
]
foo
```
```rb
$ rubocop -a sample.rb
Inspecting 1 file
C

Offenses:

sample.rb:1:7: C: [Corrected] Layout/SpaceInsideArrayLiteralBrackets: Do not use space inside empty array brackets.
foo = [ ...
      ^

1 file inspected, 1 offense detected, 1 offense corrected
```
But it's not corrected and I get the same message again.

```rb
$ rubocop -a sample.rb
Inspecting 1 file
C

Offenses:

sample.rb:1:7: C: [Corrected] Layout/SpaceInsideArrayLiteralBrackets: Do not use space inside empty array brackets.
foo = [ ...
      ^

1 file inspected, 1 offense detected, 1 offense corrected
```

## RuboCop version

```
$ rubocop -V
0.57.2 (using Parser 2.5.1.0, running on ruby 2.5.1 x86_64-darwin16)
```

**Comment by ayacai115** [comment]
Same issue here: https://github.com/rubocop-hq/rubocop/issues/5585

**Comment by ayacai115** [comment]
I'll create a PR to fix this bug.

**Comment by buehmann** [comment]
@ayacai115 This seems to do the trick: https://github.com/rubocop-hq/rubocop/compare/master...buehmann:empty-array-literal/7509 – Could you take it from there? We need a spec for this case and a changelog entry for a full PR.

**Comment by ayacai115** [comment]
@buehmann Great! I'll do that.

**Comment by ayacai115** [comment]
I created a PR: https://github.com/rubocop-hq/rubocop/pull/7511
