### ISSUE TITLE
Disabling Lint/SuppressedException with a comment is removed when autocorrect is enabled

### ISSUE THREAD

**Issue by coaxial** [rubocop-hq/rubocop#7519]
The cop `Lint/SuppressedException` cannot be disabled with a comment when autocorrect is also enabled.

--------

## Expected behavior

The error is ignored and the comment stays.

## Actual behavior

RuboCop deems the cop to be unknown and removes the comment.

## Steps to reproduce the problem

Consider this code:

```ruby
def some_method
  do_something
rescue # rubocop:disable Lint/SuppressedException
end
```

RuboCop should be green as the Lint/SuprressedException is ignored.

Instead, it gives the following (with autocorrect enabled):
```
my_file.rb:3:9: W: Do not suppress exceptions.
        rescue # rubocop:disable Lint/SuppressedException
        ^^^^^^
my_file.rb:3:20 W: [Corrected] Unnecessary disabling of Lint/SuppressedException (unknown cop).
        rescue # rubocop:disable Lint/SuppressedException
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.76.0 (using Parser 2.6.5.0, running on ruby 2.6.5 x86_64-linux)

```

**Comment by buehmann** [comment]
The cop was renamed recently: https://github.com/rubocop-hq/rubocop/pull/7468 – In v0.76.0 it is still named `Lint/HandleExceptions`.

**Comment by koic** [comment]
Yeah, as described by @buehmann. It is named `Lint/HandleExceptions` in RuboCop 0.76.0. The renamed `Lint/SuppressedException` has not been released yet.

**Comment by coaxial** [comment]
Thank you. Would it make sense to show the name of the cop in the description of the problem? JavaScript linters do that for example, so does shellcheck, so the users can easily lookup the exact issue unambiguously by the rule name. With rubocop, I have to guess what the cop is called from looking at the list. Unless there is already an option for that and I didn’t know?

**Comment by buehmann** [comment]
:smile: There is an option:
```
    -D, --[no-]display-cop-names     Display cop names in offense messages.
                                     Default is true.
```

**Comment by coaxial** [comment]
Alright, I’ll have to check my config then because it’s not showing for me.
