### ISSUE TITLE
Quick jump from terminal to editor. vscode

### ISSUE THREAD

**Issue by dukaev** [rubocop-hq/rubocop#7521]
Hello!
Editors support quick jump to files from terminal. In vscode: `cmd + click`. But it doesn't work with **rubocop** if file located it root
![image](https://user-images.githubusercontent.com/6534897/69484107-6695a380-0e40-11ea-949e-e8a19a9f5a40.png)

Navigation works after added `./` to the path
![image](https://user-images.githubusercontent.com/6534897/69484103-58e01e00-0e40-11ea-90e8-4507655ff00a.png)

What about add `./` to the path for quick jump to the files?

**Comment by buehmann** [comment]
Have you already tried a different output formatter (e.g. `emacs`, which emits absolute paths)? See https://rubocop.readthedocs.io/en/latest/formatters/

**Comment by dukaev** [comment]
@buehmann thank you
