### ISSUE TITLE
Support to detect undeclared / undefined variables

### ISSUE THREAD

**Issue by tonatiuh** [rubocop-hq/rubocop#7524]
Problem:
* it happens sometimes that you have a typo on a variable you wanted to call 
* if for any reason you don't realize about that and code goes to production, then you'll find out there was a typo too late :/ 

Solution I'd like: 
* it'd be great if rubocop adds (I'm assuming it doesn't exist yet, please correct me if I'm wrong) support for that type of offense. For reference, Eslint integrates one for that https://eslint.org/docs/rules/no-undef

Thanks for all the great work you've done so far!

**Comment by tejasbubane** [comment]
This is tricky to get right with static analysis in Ruby. Few reasons that I can think of (which don't apply to Javascript's eslint):

1. Ruby method calls don't require parens. So `foo` may refer to variable or method.
2. With mixins, the method can come from other files. I am not sure if Rubocop is able to scan dependent files at the moment.
