### ISSUE TITLE
TargetRubyVersion error message doesn't give path

### ISSUE THREAD

**Issue by tas50** [rubocop-hq/rubocop#7555]
## Expected behavior

If a user sets a TargetRubyVersion to a version not supported by RuboCop they should receive an error message that includes the version they were trying to set, the supported versions *and* the location of the config where they defined this. This is necessary when someone is running Rubocop against directories with multiple .rubocop.yml files.

## Actual behavior

You will receive a message that doesn't tell you where the config file is actually located so you don't know where you need to update things:

```
Error: RuboCop found unsupported Ruby version 2.0 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.0-compatible analysis was dropped after version 0.50.
Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7
```

## Steps to reproduce the problem

Create a .rubocop.yml file with the following config:

```yaml
AllCops:
  TargetRubyVersion: 2
```

Run rubocop and note the error message doesn't include a path to the .rubocop.yml file.

## RuboCop version

0.77

**Comment by buehmann** [comment]
I can't really reproduce this:
```console
$ rubocop --version
0.77.0
$ tree -a
.
└── a
    └── b
        └── c
            ├── d
            │   └── e
            │       └── code.rb
            └── .rubocop.yml

5 directories, 2 files
$ cat a/b/c/.rubocop.yml 
AllCops:
  TargetRubyVersion: 2.0
$ rubocop
Inspecting 1 file
.

0 files inspected, no offenses detected
Error: RuboCop found unsupported Ruby version 2.0 in `TargetRubyVersion` parameter (in a/b/c/.rubocop.yml). 2.0-compatible analysis was dropped after version 0.50.
Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7
$ cd a/b/c/d/e
$ rubocop
Error: RuboCop found unsupported Ruby version 2.0 in `TargetRubyVersion` parameter (in /tmp/7555/a/b/c/.rubocop.yml). 2.0-compatible analysis was dropped after version 0.50.
Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7
```
In this example, we get `(in a/b/c/.rubocop.yml)` and `(in /tmp/7555/a/b/c/.rubocop.yml)`.

**Comment by tas50** [comment]
Sounds like we can close this bit out based on the analysis above. Thanks @buehmann
