### ISSUE TITLE
Add command line option for ignoring TargetRubyVersion and .ruby-version

### ISSUE THREAD

**Issue by tas50** [rubocop-hq/rubocop#7557]
## Is your feature request related to a problem? Please describe.

We use RuboCop for analyzing codebases that we don't control. That can be problematic when a user includes a .ruby-version file or has a .rubocop.yml file that sets TargetRubyVersion. If the user sets either of these to unsupported Ruby versions then RuboCop will fail.

## Describe the solution you'd like

Instead of failing on these codebases that define support for EOL Ruby releases it would be wonderful if there was a flag to ignore TargetRubyVersion and .ruby-version constraints so we could continue analyzing these codebases against the current default. Alternatively, there would be an option for specifying the ruby version on the CLI and that would override other methods.

## Describe alternatives you've considered

As I mentioned above perhaps specifying the ruby version on the CLI makes more sense. 🤷‍♂

**Comment by bbatsov** [comment]
Great idea!

**Comment by tas50** [comment]
I'd agree that giving the ability to just override it on the CLI would probably be the way to go. Especially if there was the ability to use the ~ style config notation and just use the engine default.

**Comment by kojix2** [comment]
Is this option available?
