### ISSUE TITLE
Installation Error on MacOS

### ISSUE THREAD

**Issue by zzj0402** [rubocop-hq/rubocop#7564]
RuboCop doesn't install.
--------

## Expected behavior

RuboCop installs

## Actual behavior

Console outputs:
```
ERROR:  Error installing rubocop:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191212-97928-1pj6l4t.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1
```

## Steps to reproduce the problem

New macOS version 10.14.5, run in terminal:
`sudo gem install rubocop`

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.77.0 (using Parser 2.5.1.2, running on ruby 2.5.1 x86_64-linux)
```

**Comment by koic** [comment]
It seems that jaro_winkler gem installation failed. Can you open the issue to jaro_winkler?
https://github.com/tonytonyjan/jaro_winkler/issues

Thank you for the feedback.

**Comment by mojavelinux** [comment]
Having a dependency on a native gem that basically requires the full suite of development tools makes this gem tremendously difficult for a lot of people and CI environments to install. Is it absolutely necessary to depend on this gem? Could it be an optional dependency with a graceful fallback?

**Comment by buehmann** [comment]
@mojavelinux Thanks. Indeed we could do without the `jaro_winkler` gem, I guess. Opened a PR: https://github.com/rubocop-hq/rubocop/pull/7673

**Comment by mojavelinux** [comment]
Thanks @buehmann!
