### ISSUE TITLE
Integrate code to check only modified/new LINES

### ISSUE THREAD

**Issue by kirylpl** [rubocop-hq/rubocop#7572]
## Is your feature request related to a problem? Please describe.

I'd like to have a possibility to check only modified/new lines to avoid touching legacy which just should work.

## Describe the solution you'd like

There is a wrapper that exists already. https://gist.github.com/skanev/9d4bec97d5a6825eaaf6
Currently, I use it but it will be nice to add this solution from the box.

**Comment by koic** [comment]
#5477 had a similar discussion.

**Comment by kirylpl** [comment]
I think we can close this. Thanks!

**Comment by kirylpl** [comment]
Well, I agree that this issue contradict the idea of simplicity. We probably can close it.

**Comment by vishnun** [comment]
I'm surprised that this got closed without addressing the issue at hand. Rubocop is a great tool but it fails badly if you are introducing it at a later stage of a project AS WILL BE THE CASE FOR EVERY START-UP !!!
I'd also argue that code for tools can be a bit complex if it makes the process simpler. That is the goal of rubocop no? Isn't it supposed to simplify moving towards a cleaner codebase without adding a lot of headache? No real company code is going to do a big-bang modification to their entire codebase.

Being able to run rubocop only on lines changed is necessary!!!

Apologies if the above rant reflects the frustration I'm dealing with but it's an important issue and I'm just surprised that this got closed without addressing it. Please reconsider it or provide a better solution to a real issue.
