### ISSUE TITLE
Lint/AmbiguousBlockAssociation with rspec `satisfy`

### ISSUE THREAD

**Issue by ShockwaveNN** [rubocop-hq/rubocop#7573]
I'm aware of https://github.com/rubocop-hq/rubocop/issues/4222 issue, but it's pretty old, more complicated and maybe something changed since

## Steps to reproduce the problem

1. Create rspec file with single example from https://relishapp.com/rspec/rspec-expectations/v/3-0/docs/built-in-matchers/satisfy-matcher

```
RSpec.describe 10 do
  it { is_expected.to satisfy { |v| v > 5 } }
end
```
2. `rubocop test_spec.rb`
Result is:
```
test_spec.rb:4:8: W: Lint/AmbiguousBlockAssociation: Parenthesize the param satisfy { |v| v > 5 } to make sure that the block will be associated with the satisfy method call.
  it { is_expected.to satisfy { |v| v > 5 } }
```

Is there any way to use `to satisfy` matcher without disabling `Lint/AmbiguousBlockAssociation`?

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.77.0 (using Parser 2.6.5.0, running on ruby 2.5.7 x86_64-linux)
```

**Comment by buehmann** [comment]
> Is there any way to use `to satisfy` matcher without disabling `Lint/AmbiguousBlockAssociation`?

You can do what the cop suggests. Not sure that you will like the result; usually the `to` method is used without parentheses in RSpec code.
```ruby
RSpec.describe 10 do
  it { is_expected.to(satisfy { |v| v > 5 }) }
end
```

**Comment by ShockwaveNN** [comment]
@buehmann Thanks, that'll do for me, could not figure it out by myself
