### ISSUE TITLE
Hash literal not being reformatted

### ISSUE THREAD

**Issue by pitosalas** [rubocop-hq/rubocop#7613]
I have a hash literal that looks like this:

`MAPPING = {"Strongly agree" => 4, "I agree" => 3, "I'm not sure" => 2, "I disagree" => 1, "Strongly disagree" => 0}.freeze
`
Rubocop reports that the line is too long but doesn't reformat it. I am calling Rubocop from vscode as a ruby formatter. 

"Line is too long [122/100] (convention:Layout/LineLength)"

But in my rubocop.yml I have:

```
Layout/HashAlignment:
  Enabled: true
```

**Comment by alex-andreiev** [comment]
just writing something like

`MAPPING = {`
  `'Strongly disagree' => 0,`
  `'I disagree' => 1,`
  `'I\'m not sure' => 2,`
  `'I agree' => 3,`
  `'Strongly agree' => 4`
`}.freeze`
or write
`Metrics/LineLength:`
  `Max: 120`
in .rubocop.yml

**Comment by pitosalas** [comment]
Hi Oleksandr,

I am running Rubocop Gem 0.78.0 and using the VSCode Ruby-Robocop Extension version 0.8.1. 

When I enter 

> Metrics/LineLength:
> Max: 120

I get an error: "Metrics/LineLength has the wrong namespace - Should be Layout"

Also I wonder why a formatting parameter would be in Metrics.

Can you tell what I am doing wrong?

Pito Salas
Brandeis Computer Science
Volen 134
