### ISSUE TITLE
Poor logic with Layout//MultilineMethodCallIndentation

### ISSUE THREAD

**Issue by tenpaiyomi** [rubocop-hq/rubocop#7618]
In a section of code, `Layout/MultilineMethodCallIndentation` is providing some interesting logic on how it feels it should be formatted.  The section of code in question:

```ruby
          expect { user.activate! }.to change { ActionMailer::Base.deliveries.count }.by(1)
                                   .and change { user.active? }.to(be_truthy)
                                   .and change { user.expires_at }.to(be_within(1.minute).of(Time.current + 14.days))
```

--------

## Expected behavior

I would expect Rubocop to see this alignment as valid, or request me to indent the following line over 2 spaces, either/or.

## Actual behavior
Rubocop expects the alignment to be as follows, with the middle low aligned far to the right with the last `.of`, and the line below that indented 2 places past the beginning of the initial line:

```ruby
          expect { user.activate! }.to change { user.expires_at }.to be_within(1.minute).of(Time.current + 14.days)
                                                                                        .and change { user.active? }.to(be_truthy)
            .and change { ActionMailer::Base.deliveries.count }.by(1)
```

## Steps to reproduce the problem

Utilizing the section of code above should be enough, but it seems to be due to the fact that my initial line has several instances of `.to` and `.of`, as I have another section of code in another test as follows:

```ruby
          expect { user.activate! }.to_not change { user.expires_at }
            .and change { user.active? }.to(be_truthy)
            .and change { ActionMailer::Base.deliveries.count }.by(0)
```

which is seen as valid.

## RuboCop version

```
0.78.0 (using Parser 2.6.5.0, running on ruby 2.6.3 x86_64-linux)
```

**Comment by ixti** [comment]
Still, a problem on v0.79.0. Here's how I found it:

``` ruby
expect(something)
  .to receive(:new)
    .and_wrap_original { |m, *args| instance_double(m.call(*args), :call => nil) }
  .once
```

It's clear that it should be:

``` ruby
expect(something)
  .to receive(:new)
    .and_wrap_original { |m, *args| instance_double(m.call(*args), :call => nil) }
    .once
```

**Comment by amyspark** [comment]
It also breaks with `do..end` blocks. `EnforcedStyle: indent` as follows, see how it breaks alignment after the `end`. It doesn't happen with curly blocks.

```ruby
    css_modified = dom
                   .css('link[rel=stylesheet]:not([integrity])')
                   .each
                   .collect do |node|
                     integrity(node, root, document.dirname)
                   end.any?
```
```ruby
    css_modified = dom
      .css('link[rel=stylesheet]:not([integrity])')
      .each
      .collect do |node|
      integrity(node, root, document.dirname)
    end.any?
```
