### ISSUE TITLE
Style/NumericLiterals : Grouping Configuration

### ISSUE THREAD

**Issue by coding-bunny** [rubocop-hq/rubocop#7649]
## Is your feature request related to a problem? Please describe.

At the moment the configuration for the `Style/NumericLiterals` Cop is hard-coded to expect/require three digits between separators when the Cop is enabled.
Our application deals with CreditCard information, which are long numbers and grouped in segments of four.

To keep our code readable, we write often data like this:

```
TEST_CREDIT_CARD = 1234_5678_1234_5678
```

The above however is not accepted by the Cop and requires it to be written as `1_234_567_812_345_678`

## Describe the solution you'd like

A Configuration option that allows us to specify the amount of digits per group:

```
Style/NumericLiterals:
  Enabled: true
  DigitsPerGroup: 4 # Defaults to three for the original behavior
```

## Describe alternatives you've considered

Right now we keep the notation we want and disable RuboCop on these specific lines.
Perhaps a new Cop could help here, but would most likely conflict, so more fine-tuning as option seems to be the only solution for me.

**Comment by koic** [comment]
AFAIK, it seems that the International System of Units (SI) has defined that numbers can be divided into three digits for representation. It is essentially a numeric.
On the other hand, the standard for credit card number is defined by ISO/IEC 7812. The leading zero is reserved by ISO and do not seem to be commonly used. However I doubt that numeric object is eligible for representing values that start with possible zero. Also, the leading zero is significant in Ruby.

```ruby
0123_4567_8901_2345   # => SyntaxError: Invalid octal digit
123_4567_8901_2345    # => 123456789012345 however, the number of digits changes.
```

Thanks for showing the use case. But I don't think `NumericLiterals` cop should have this feature.
