### ISSUE TITLE
Need ability to temporarily suppress unrecognized & obsolete cops

### ISSUE THREAD

**Issue by robbat2** [rubocop-hq/rubocop#7653]
## Is your feature request related to a problem? Please describe.
On a large internal codebase, it's not possible to gradually move all developers between versions of Rubocop without getting `Warning: unrecognized cop` on renamed cops used in `.rubocop.yml` files.

e.g. `Layout/IndentHash` was renamed to `Layout/IndentFirstHashElement`.
The obvious solution for `.rubocop.yml` to contain BOTH blocks at once:
```
Layout/IndentHash:
  Enabled: false
Layout/IndentFirstHashElement:
  Enabled: false
```

- Any early upgraders will get the renamed cop warning
- Any late upgraders will get `Warning: unrecognized cop`

## Describe the solution you'd like
Provide a configurable way to temporarily suppress the warnings for certain obsolete or unrecognized cops.
```
SuppressObsoleteCop:
- (list of obsolete cops to NOT give warnings for)
SuppressUnrecognizedCop:
- (list of unrecognized cops to NOT give warnings for)
```

I realize that everybody will have to upgrade to a new enough rubocop that has this suppression feature first, but hopefully it will reduce future cases of obsolete cop in the meantime.

## Alternate solutions
1. Ways to mark parts of the config to be used in certain versions of Rubocop only.
- This is probably going to end up much too complex, and old versions of Rubocop might break anyway on it.
2. Accept obsolete names transparently and run the check by the new name name. This provides maximum compatibility with old versions. This only works for straight rename of Cops, and not other changes to the Cops.

**Comment by tansaku** [comment]
I'd really like to see this as well in order to suppress warnings about Rails cops being pulled in from an inherited gem when we're not using Rails
