### ISSUE TITLE
infinite loop when using --disable-uncorrectable when offense in HEREDOC

### ISSUE THREAD

**Issue by thijsnado** [rubocop-hq/rubocop#7670]
## Expected behavior

Rubocop would add `# rubocop:todo Naming/VariableName` at top of HEREDOC and re-enable at end of HEREDOC. The same issue exists for %Q tags.

## Actual behavior

Excessive amount of `# rubocop:todo Naming/VariableName` are generated within the heredoc instead of on top of it and program crashes.

## Steps to reproduce the problem

Given the following ruby:

```ruby
# frozen_string_literal: true

def our_function
  ourVariable = "foo"
  script = <<~JS
    <script>
      window.stuff = "#{ourVariable}"
    </script>
  JS
  puts(script)
end
```

When running: `rubocop --disable-uncorrectable --safe-auto-correct`, you get an infinite loop detected error, and the following code is generated:

```ruby
# frozen_string_literal: true

def our_function
  ourVariable = 'foo' # rubocop:todo Naming/VariableName
  script = <<~JS
    <script>
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # etc, etc
      window.stuff = "#{ourVariable}"
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # rubocop:todo Naming/VariableName
      # etc
```

## RuboCop version

0.79.0

**Comment by moger777** [comment]
I think this is more than just camelCase issue. Pretty much any non-correctable linting issue in a heredoc causes this.
