### ISSUE TITLE
Metrics/MethodLength should ignore/configure configuration lists

### ISSUE THREAD

**Issue by schmijos** [rubocop-hq/rubocop#7724]
Rubocop's `Metrics/MethodLength` prefers

```ruby
  def build_filter_chain
    [ByCategory.new(@category_id.presence),
     ByMarketing.new(@promotion.presence, @novelty.presence),
     ByPlainScopes.new(featured: @featured, random: @random, slugged: @slugged, unslugged: @unslugged,
                       with_volume_discounts: @with_volume_discounts, with_images: @with_images),
     ByBrand.new(@brand_id.presence),
     BySupplier.new(@supplier_id.presence),
     ByCustomerHistory.new(customer, @historical),
     ByHavingShop.new(@shop),
     BySearch.new(@q, customer)]
  end
```

over

```ruby
  def build_filter_chain
    [
      ByCategory.new(@category_id.presence),
      ByMarketing.new(@promotion.presence, @novelty.presence),
      ByPlainScopes.new(
        featured: @featured,
        random: @random,
        slugged: @slugged,
        unslugged: @unslugged,
        with_volume_discounts: @with_volume_discounts,
        with_images: @with_images
      ),
      ByBrand.new(@brand_id.presence),
      BySupplier.new(@supplier_id.presence),
      ByCustomerHistory.new(customer, @historical),
      ByHavingShop.new(@shop),
      BySearch.new(@q, customer)
    ]
  end
```

I find the second one much more readable and would like if there was a possibility to opt-out from `Metrics/MethodLength` for configuration lists. This means, I'd count an array as 1 line. 

Does this sound sane? I don't propose a new cop, but a new configuration option like:
`CountAsOne` defaulting to `[]`. Possible values could be `Array`, `Hash`, `Heredoc`.

We would do the same thing for these if wanted: https://github.com/rubocop-hq/rubocop/issues/5394, https://github.com/rubocop-hq/rubocop/issues/1077, https://github.com/rubocop-hq/rubocop/issues/2686 and many more.

**Comment by Drenmi** [comment]
Yes. I've been thinking about a configuration option allowing a method containing _any_ single literal to have unlimited lines.

**Comment by fatkodima** [comment]
Hey, I have implemented this - https://github.com/rubocop-hq/rubocop/pull/8159 😄

**Comment by marcandre** [comment]
Just for the record, this is related to #7668 and #7204. Same question applies: have you thought of using a size / complexity metric instead of method length (like Metrics/AbcSize)

**Comment by fatkodima** [comment]
Sorry, if the question was to the original poster, and not to the last commenter 😄 

I'm using both and see values in both of them. While I want to limit `abc` size of methods, I'd also like to have moderate sized methods in terms of not empty/comment lines. And to fold some constructions which otherwise will force me to expand `Max` setting or inline and compact them making them unreadable.

**Comment by bbatsov** [comment]
While I generally echo @marcandre's thoughts, it seems this topic has been constantly recurring for years and that maybe I should concede and accept some configuration of that nature. Let me think about this a bit more.
