### ISSUE TITLE
Suggest case/when if an if/elsif/else can be easily translated

### ISSUE THREAD

**Issue by Lykos** [rubocop-hq/rubocop#7736]
## Is your feature request related to a problem? Please describe.

I only learned about the power of case statements quite recently, so there are lots of opportunities in my code that could be written more nicely with a cop that recognizes these patterns. I am sure there are others with the same situation.

## Describe the solution you'd like

If there is an if/elsif/else construct with at least one elsif and all conditions can be translated appropriately, suggest using a case/when construct instead.

## Additional context

E.g. something like this can be translated:

```
if a == 1
  # do something
elsif a == 2 || a == 3
   # do something
end
```

Or something like this:

```
if a.is_a?(Integer)
  handle_integer(a)
elsif a.is_a?(Float)
  handle_float(a)
end
```

Note that I might even implement this myself eventually, I'll just add the issue so it's tracked.

**Comment by rrosenblum** [comment]
I like this idea. This is something that I look for myself in code reviews. I don't think it would be too difficult to implement

**Comment by marcandre** [comment]
Be mindful about the difference between `if a == 1` (can be switched to case) and `if a == SomeClass` (can't be), or `if a == method_call` (maybe)
