### ISSUE TITLE
Style/NestedParenthesizedCalls autocorrect breaks code

### ISSUE THREAD

**Issue by kalsan** [rubocop-hq/rubocop#7742]
Code before rubocop -a is run:
```
Dalli::Client.new(
  Settings.get! :memcached_url,
  serializer: self
)
```

## Expected behavior

 ```
Dalli::Client.new(
  Settings.get!(:memcached_url),
  serializer: self
)

```

## Actual behavior

```
Dalli::Client.new(
  Settings.get!(:memcached_url,
  serializer: self)
)

```

(spacing corrupted by copy-paste to github, the relevant misbehaviour is the wrongly place parenthesis)

## Steps to reproduce the problem

Run `rubocop -a` on the first snippet.

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ [bundle exec] rubocop -V
0.77.0 (using Parser 2.6.4.1, running on ruby 2.6.2 x86_64-linux)
```

**Comment by koic** [comment]
This is an expected behavior. The coupling for each parentheses position is as follows.

```console
% ruby-parse -e 'foo(bar :arg, key: value)'
(send nil :foo
  (send nil :bar
    (sym :arg)
    (hash
      (pair
        (sym :key)
        (send nil :value)))))
```

```console
% ruby-parse -e 'foo(bar(:arg, key: value))'
(send nil :foo
  (send nil :bar
    (sym :arg)
    (hash
      (pair
        (sym :key)
        (send nil :value)))))
```

The above two are the same result. If parentheses are added to the method call of the first argument, the result will be different.

```console
% ruby-parse -e 'foo(bar(:arg), key: value)'
(send nil :foo
  (send nil :bar
    (sym :arg))
  (hash
    (pair
      (sym :key)
      (send nil :value))))
```

And an executed example is as follows.

```ruby
% cat example.rb
def foo(arg, **options)
  puts "foo(#{arg}, #{options})"
end

def bar(arg, **options)
  puts "bar(#{arg}, #{options})"
  :bar
end

puts '## Case 1'
foo(bar 'hello', key: :value)
puts '## Case 2'
foo(bar('hello', key: :value))
puts '## Case 3'
foo(bar('hello'), key: :value)

% ruby example.rb
## Case 1
bar(hello, {:key=>:value})
foo(bar, {})
## Case 2
bar(hello, {:key=>:value})
foo(bar, {})
## Case 3
bar(hello, {})
foo(bar, {:key=>:value})
```

**Comment by kalsan** [comment]
Thanks for your reply. I'll bookkeep this as you describe it.

**Comment by kalsan** [comment]
BTW the actual Ruby behavior depends on the kind of the last argument.

Rubocop's behavior would be the same as Ruby's view if the last argument was only `self`. In the above case however, we have `serializer: self` which alters Ruby's behavior and binds the argument to the `get!` method, which lead me to creating this issue.

I assume that Rubocop does not differenciate between `self` and `serializer: self`. In any case, the code in the first block above should be avoided in any Ruby program since it is ambiguous.
