### ISSUE TITLE
ability to silence some cops pulled in via inherit_gem

### ISSUE THREAD

**Issue by tansaku** [rubocop-hq/rubocop#7743]
## Is your feature request related to a problem? Please describe.

I'm trying to work out a  way to automatically ignore rails cops in non-rails projects.  At the moment we have some rails cops pulled in via an inherit_gem operation into a non-rails project, where we get the issues I've described in https://github.com/rubocop-hq/rubocop-rails/issues/204

## Describe the solution you'd like

I'd love to be able to do something like:

```
inherit_gem:
  common_general: .rubocop.yml
  ignore: Rails
```

## Describe alternatives you've considered

Adding require 'rubocop-rails' opens a can of worms as Rails cops are applied to a non-rails app.  Could we break up our common_general gem into common_general and common_general_rails ? I guess, but would love to be able to filter out sections of cops that are just not applicable - is there already a command for that?

**Comment by dadah89** [comment]
I was dealing with the same issue, I tried to override the `require` array to no avail. I was able to to get around by simply disabling the cop though:
```yml
Rails:
  Enabled: false
```
Maybe that will do what you want?

**Comment by tansaku** [comment]
@dadah89 that works perfectly - thanks so much!

**Comment by tansaku** [comment]
unfortunately I think I was mistaken - doesn't seem to help unfortunately :-(

**Comment by tejasbubane** [comment]
@tansaku What errors do you see after adding @dadah89's solution? Ideally you should be able to disable Rails cops just like that. Can you give more details & minimal steps to help us reproduce the issue?

**Comment by tansaku** [comment]
@tejasbubane so there aren't any errors - the warnings just continue to appear.  I think the issue is that we don't have rubocop-rails pulled into the second repo.  That might be the solution ... hmm, even then I still get:
```
Warning: unrecognized cop Rails/ActionFilter found in /Users/tansaku/.rvm/gems/ruby-2.6.5/bundler/gems/common_general-ab08972b5209/.rubocop.yml
Warning: unrecognized cop Rails/FindEach found in /Users/tansaku/.rvm/gems/ruby-2.6.5/bundler/gems/common_general-ab08972b5209/.rubocop.yml
Warning: unrecognized cop Rails/HasAndBelongsToMany found in /Users/tansaku/.rvm/gems/ruby-2.6.5/bundler/gems/common_general-ab08972b5209/.rubocop.yml
Warning: unrecognized cop Rails found in .rubocop.yml
Warning: unrecognized cop Rails/ActionFilter found in .rubocop.yml
Warning: unrecognized cop Rails/FindEach found in .rubocop.yml
Warning: unrecognized cop Rails/HasAndBelongsToMany found in .rubocop.yml
```

it might be that our shared repo `common-general` has some outdated cops?

at the moment I've tried the following .rubocop.yml files to no avail:

```yaml
inherit_gem:
  common_general: .rubocop.yml

Rails:
  Enabled: false
```

```yaml
Rails:
  Enabled: false

inherit_gem:
  common_general: .rubocop.yml
```

I'll try and find some time to set up some minimal repos that replicate the issue ...

**Comment by tansaku** [comment]
ah fixed it!  This was the solution:

```
require: rubocop-rails

Rails:
  Enabled: false

inherit_gem:
  common_general: .rubocop.yml
```
