### ISSUE TITLE
Prefer executing command without a shell to Shellwords

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop#7756]
## Is your feature request related to a problem? Please describe.

We have `Shellwords` module to escape shell meta characters.
https://docs.ruby-lang.org/en/2.7.0/Shellwords.html

But `Shellwords` is not the best way to avoid shell command injection in many cases.
Executing command without shell is the best way if it's possible.

```ruby
# It can reduce shell command injection, but...
system("ls #{Shellwords.escape(str)}")

# The following is the best way because it avoids shell command injection completely.
system("ls", str)
```

## Describe the solution you'd like

Add a cop to detect the problem.

Note that we have many methods to execute a command.

* `system`
* Open3
* IO.popen
* spawn
* etc...

And `Shellwords` has three ways to escape a string.

* `Shellwords.escape`
* `Shellwords.shellescape`
* `String.shellescape`

## Describe alternatives you've considered

Nothing

## Additional context

I guess the cop should not add an offense to the following code.

```ruby
system("ls *#{Shellwords.escape(str)}")
```

Because it uses a shell feature (`*`).

**Comment by bbatsov** [comment]
Nice idea! This should be documented in the style guide as well.

**Comment by pocke** [comment]
> This should be documented in the style guide as well.



I think so too!



By the way, a friend gave me advice about the cop. RuboCop also can detect `system` with a string interpolation even if `Shellwords` is not used. For example:

```ruby
system("ls #{input_from_user}")
```


It is a good idea but personally I think they're different (but really similar) problems. So we can create two cops, or make it configurable for the problems.


The difference is the amount of false positives. If the cop only targets ShellWords, it has no false positives. 
We expect the shell does not evaluate any meta-characters from an escaped string. It means we can replace ShellWords with command execution without a shell.

But it may need a shell to execute process if the string interpolation does not have ShellWords.
For example:


```ruby
glob = "**/*.rb"
# It actually uses a shell feature, so we can't replace it with `system 'ls', glob`
system "ls #{glob}"
```
