### ISSUE TITLE
[Corrected] Naming/RescuedExceptionsVariableName: Use e instead of error.

### ISSUE THREAD

**Issue by tit** [rubocop-hq/rubocop#7766]
Ruby 2.7.0
Rubocop 0.80.0

I have some code:

```ruby
# frozen_string_literal: true

def main
  raise
rescue StandardError => error
  error = {
    error_message: error.message
  }
  puts error
end
```

I run CLI rubocop with argument `--auto-correct`:

```bash
$ rubocop --auto-correct main.rb
```

↓

```
Inspecting 1 file
W

Offenses:

main.rb:5:25: C: [Corrected] Naming/RescuedExceptionsVariableName: Use e instead of error.
rescue StandardError => error
                        ^^^^^
main.rb:6:3: W: Lint/UselessAssignment: Useless assignment to variable - error.
  error = {
  ^^^^^

1 file inspected, 2 offenses detected, 1 offense corrected
```

Rubocop corrected my code, renamed rescued exception variable name from `error` to `e`.
But this correcting is changed code logic.

Before use Rubocop method `main()` return Hash: `{ error: { error_message: String} }`.
After use return `RuntimeError`.

**Comment by anuja-joshi** [comment]
@koic  what is expected correction here?  should it be 1 or 2


**1.**

```
# frozen_string_literal: true

def main
  raise
rescue StandardError => error
  error = {
    error_message: e.message
  }
  puts error
end
```

**2.**

```
# frozen_string_literal: true

def main
  raise
rescue StandardError => error
  e = {
    error_message: e.message
  }
  puts e
end
```

**Comment by lisacf** [comment]
I believe you might be looking for a third option:
```
# frozen_string_literal: true

def main
  raise
rescue StandardError => e
  e = {
    error_message: e.message
  }
  puts e
end
```
or 
```
# frozen_string_literal: true

def main
  raise
rescue StandardError => e
  error = {
    error_message: e.message
  }
  puts error
end
```

**Comment by koic** [comment]
I agree with @lisacf. Ideally, auto-correction would be expected to change only a variable specified by `rescue =>`.

**Comment by tit** [comment]
> not create a variable with the same name as the error object

I agree that calling a variable by the same name as an exception variable is not very correct.

However, I am sure that automatic code correction should not affect the logic of its operation.

Since I found a scenario in which the automatic correction changed the logic, I suggest removing the automatic code correction from this cop.

**Comment by marcandre** [comment]
`Naming/RescuedExceptionsVariableName` should rename the variable correctly, i.e. all occurrences of `error` should be changed to `e`, ideally in the correct scope, or at least in the rescue block.

**Comment by dvandersluis** [comment]
I was looking into this and it already corrects variables in the rescue body, so this can be closed.

**Comment by asterite** [comment]
This is happening again in version 1.6.1

Can this be reopened? Thank you!

**Comment by marcandre** [comment]
I can reproduce in 1.8.1

**Comment by asterite** [comment]
I can send a PR to fix this.

**Comment by marcandre** [comment]
Not fixed (yet). I thought that rewriting the commit message would not close this but it did 🤷‍♂️
