### ISSUE TITLE
Rubocop places commas into comments, generating invalid ruby code

### ISSUE THREAD

**Issue by adfoster-r7** [rubocop-hq/rubocop#7777]
When formatting the following code, rubocop will generate invalid ruby:

```ruby
class Bar
  def initialize(*args)
  end
end

class Foo < Bar
  def initialize
    super(
      'firstKey' => [ 'value a', #description1
                      'value b' #description2
      ],
      'secondKey' => 'Bar'
    )
  end
end
```

## Expected behavior

Not to generate invalid ruby code

## Actual behavior

Invalid ruby code is created due to incorrectly handling the comment and placing a comma on the comment line:

```ruby
class Bar
  def initialize(*args)
  end
end

class Foo < Bar
  def initialize
    super(
      'firstKey' => ['value a', # description1
                      'value b'] # description2,
      'secondKey' => 'Bar'
    )
  end
end
```

## Steps to reproduce the problem

1. Create new ruby file
2. add original code snippet
3. bundle exec rubocop  -x --safe-auto-correct new_file.rb
4. Run again, verify invalid ruby code has been generated

## RuboCop version

```
$ [bundle exec] rubocop -V
0.80.0 (using Parser 2.7.0.2, running on ruby 2.6.5 x86_64-darwin18)
```

**Comment by MattBeaty** [comment]
whoever works on https://github.com/rubocop-hq/rubocop/issues/7776 should also work on this issue.

**Comment by shekhar-patil** [comment]
I am working on this issue.
