### ISSUE TITLE
Gemfile for --parallel

### ISSUE THREAD

**Issue by veganstraightedge** [rubocop-hq/rubocop#7785]
## Is your feature request related to a problem? Please describe.

I want to run Rubocop in `--parallel` on a very large codebase.

In not `--parallel` mode, I'm able to `gem install` a very limited set of gems, very quickly.
`gem install bundler rubocop rubocop-performance rubocop-rspec`

In `--parallel` mode, it seems like I have to `bundle install` my whole `Gemfile` which takes several minutes as a part of our CI build.

## Describe the solution you'd like

I think would what be easy _for me_ would be in `rubocop --parallel` provided its own `Gemfile` needed for itself to run.

## Describe alternatives you've considered

Figuring out for myself the subset of all of my `Gemfile` that's needed for `rubocop --parallel`.

## Additional context

n/a

**Comment by mvz** [comment]
What error message do you get when you run `rubocop --parallel` with just the dependencies listed in the gem?

**Comment by veganstraightedge** [comment]
Sorry I lost track of this for a while. 

It's all working now. It's unclear what the problem was or what fixed it.

Sorry for the confusion and not having a better snapshot of the error at the time.
