### ISSUE TITLE
--ignore-parent-exclusion does not work if --parallel is used

### ISSUE THREAD

**Issue by dhinus** [rubocop-hq/rubocop#7790]
The switch `--ignore-parent-exclusion` seems to be ignored if `--parallel` is also present.

--------

## Expected behavior

The following commands should always inspect the same number of files:

```
rubocop --ignore-parent-exclusion
rubocop --ignore-parent-exclusion --parallel
```

## Actual behavior

Adding `--parallel` seems to disable the effect of `--ignore-parent-exclusion`.

## Steps to reproduce the problem

```
.
├── .rubocop.yml
└── subdir
    ├── .rubocop.yml
    └── test.rb
```

Content of `.rubocop.yml`:
```
AllCops:
  Exclude:
    - "subdir/*"
```

Content of `subdir/.rubocop.yml`:
```
AllCops:
  Exclude:
    - "foobar"
```

This is the output of running Rubocop with different switches, from inside the `subdir` directory:

* `rubocop`: "0 file inspected"
* `rubocop --parallel`: "0 file inspected"
* `rubocop --ignore-parent-exclusion`: "1 file inspected"
* `rubocop --ignore-parent-exclusion --parallel`: "0 files inspected"

**NOTE:** to be fair, I'm not even sure why I need to use the `--ignore-parent-exclusion` flag, as I'm not specifying `inherit` in the config file inside `subdir`, so I would expect Rubocop to use that file and ignore the config file in the parent directory.

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
$ rubocop -V
0.80.1 (using Parser 2.7.0.2, running on ruby 2.5.1 x86_64-darwin18)
```

**Comment by jonas054** [comment]
> NOTE: to be fair, I'm not even sure why I need to use the --ignore-parent-exclusion flag, as I'm not specifying inherit in the config file inside subdir, so I would expect Rubocop to use that file and ignore the config file in the parent directory.

That's by design. If RuboCop, when run from a subdirectory, would inspect files that are excluded when running from the project root, that would be kind of a gotcha. I'm not sure about the exact scenarios when this becomes an issue, but the behavior is not an accident.
