### ISSUE TITLE
`Style/EndBlock` & `Lint/EndInMethod` are redundant

### ISSUE THREAD

**Issue by tejasbubane** [rubocop-hq/rubocop#7813]
Both `Style/EndBlock` & `Lint/EndInMethod` do the same thing. `END` block being inside/outside method makes no difference.

Both were added long back in [0.9.0](https://github.com/rubocop-hq/rubocop/blob/v0.9.0/CHANGELOG.md). 

Commits don't tell the reasoning either: [[1]](https://github.com/rubocop-hq/rubocop/commit/080be429984a93c3d5b1033f8371a7d13f14043c) & [[2]](https://github.com/rubocop-hq/rubocop/commit/8466928ad6793532136ba58324f8a3a21e01cee8)

Also the documentation of `Lint/EndInMethod` suggests `END` outside method is `good` which contradicts `Style/EndBlock`.

--------

## Expected behavior

One cop to deal with `END` blocks.

## Actual behavior

Duplicate cops.

## Steps to reproduce the problem

NA

## RuboCop version

Current master branch.

**Comment by bbatsov** [comment]
Great catch! Looking at https://github.com/rubocop-hq/rubocop/commit/8466928ad6793532136ba58324f8a3a21e01cee8 it seems I did this first and then created the other cop based on the remark @whitequark made. I agree it probably doesn't make sense to have two of those.
