### ISSUE TITLE
Cop idea: Check no spaces between `.` and the method being called

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubocop-hq/rubocop#7826]
## Is your feature request related to a problem? Please describe.

`A. new` or `Kernel.            puts` is valid ruby, but very weird.

## Describe the solution you'd like

I'd like a cop to enforce that no spaces are used between the `.` and the method being called. Not sure about naming, perhaps, `DotSpacing` inspired by the `DotPosition` cop, or maybe `SpaceAfterDot`?

## Describe alternatives you've considered

None.

## Additional context

None.

**Comment by bbatsov** [comment]
I'm shocked we didn't write a lint cop about this by now. :-)

**Comment by deivid-rodriguez** [comment]
Actually, just found https://github.com/rubocop-hq/rubocop/issues/7273, which wants to check for spaces _before_ the dot, but the cop I'm proposing here is suggested in a followup comment on the issue. So maybe both tickets can be merged :man_shrugging:
