### ISSUE TITLE
Add integration with pre-commit project

### ISSUE THREAD

**Issue by adithyabsk** [rubocop-hq/rubocop#7827]
## Is your feature request related to a problem? Please describe.

It would be really nice if the project integrated with the [pre-commit project](https://pre-commit.com/), a widely used pre-commit hook management tool. Only a single file is required for integration (the `.pre-commit-hooks.yaml` file)

## Describe the solution you'd like

I've already set up a project mirror doing exactly that would suggest a link to my mirror (which auto-sync to the mainline project's releases)

Based on #1993 it seems like such integrations were added in a separate project.

https://github.com/adithyabsk/mirrors-rubocop

## Describe alternatives you've considered

The mirror above ^

## Next steps

**Option A (most preferred)**
Move forward with integrating pre-commit tool using my project's mirror as a starting point
**Option B**
Add a link in the docs to suggest using the mirror one is interested in using pre-commit hooks
**Option C (least preferred)**
Do nothing 😦

**Comment by adithyabsk** [comment]
I'm still interested in this feature. I thought I'd comment to mark this as not stale.

**Comment by marcandre** [comment]
I don't understand the detail, but if it's just a single .yaml file, maybe a PR would be clearer?

**Comment by adithyabsk** [comment]
@marcandre Just added a PR here, we can move the discussion there? https://github.com/rubocop-hq/rubocop/pull/8969

**Comment by koic** [comment]
I'll close this issue due to https://github.com/rubocop-hq/rubocop/pull/8969#issuecomment-719116699. Thank you.
