### ISSUE TITLE
Consider a way to anonymously collect cop settings

### ISSUE THREAD

**Issue by andyw8** [rubocop-hq/rubocop#7844]
Following up from @mbj's suggestion here:

https://twitter.com/_m_b_j_/status/1245376535785287691

Needs further thought and discussion but I thought it would useful to track this.

**Comment by bbatsov** [comment]
Implementing upload of the config is easy, but we need to consider:

* Where exactly do we upload this - e.g. some service, static storage, etc.
* How do we process the data (e.g. if it's a service you can submit to it can also process the data, otherwise there should be some tool doing so)

Alternatively we can mine harder GitHub for public configs, but this will leave us oblivious to thousands of private configs, which are quite common in commercial software.

**Comment by andyw8** [comment]
I don't expect there would a huge amount of data, perhaps a few thousand submissions, and < 100KB per file, so ~1GB/month for storage, stored on S3?

I'm imagining a basic API which accepts a POST containing the `.rubocop.yml` content, along with some metadata, e.g. the versions of RuboCop and Ruby in use. It might also be useful to have a simple form available that people could paste their config into, in case they're concerned about what data the upload might expose.

In terms of processing, I think the service should first make the raw data publicly available to allow for a variety of tools to built. Perhaps there could be a nightly gzip published.

As a first iteration, the configs could be parsed and extracted into a relational DB with these tables:
* **submissions** - one record corresponding to each `.rubocop.yml`, along with its metadata
* **rules** - a list of all RuboCop rules (this would also need to handle renamed or deleted rules)
* **entries** - a join between submission and rules, with a boolean to indicate if a particular rule has been marked as disabled

Obviously there are a lot of other things still to consider, for example:
- Handling malformed configs
- Dealing with configs split over multiple files
- Ignoring custom cops
- Handling extensions such as rubocop-rspec

**Comment by mbj** [comment]
On duplicate submissions, I think you should use the machines hostname as key. But: Do not submit it plain text.

Instead: Submit it hashed. This way you preserve the key identity but do not gain more information than you should get.
