### ISSUE TITLE
Rubocop Hangs When Using --stdin option

### ISSUE THREAD

**Issue by mzagaja** [rubocop-hq/rubocop#7865]
## Expected behavior

When executing the command

```
rvm-auto-ruby -S rubocop --format emacs --force-exclusion --stdin /Users/mzagaja/Developer/digitalhub/vendor/extensions/taggings/app/controllers/refinery/taggings/taggings_controller.rb
```

I would expect to get a list of errors to be fixed in taggings_controller.rb in my console.
## Actual behavior
The ruby process hangs indefinitely. Activity monitor shows ruby running and using 0% CPU.
## RuboCop version
```
mzagaja@Matthew-Zagaja-MacBook-Pro ~/D/digitalhub> rvm-auto-ruby -S rubocop -V
0.81.0 (using Parser 2.7.1.0, running on ruby 2.5.3 x86_64-darwin18)
```

**Comment by jonas054** [comment]
The `--stdin` option takes a file name argument. This is the file name that will be used to report offenses in, but RuboCop doesn't read that file. It reads from `stdin`, and that's whats happening here. RuboCop is waiting for source code to inspect on `stdin`.

**Comment by mzagaja** [comment]
Thanks Jonas, this information is helpful. I'm likely combatting a different issue with SublimeLinter-Rubocop then.
