### ISSUE TITLE
RequiredRubyVersion

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#7876]
The `Gemspec/RequiredRubyVersion` cop checks that `spec.required_ruby_version=` (if present) corresponds to `TargetRubyVersion`.

That's good.

I'd like a more basic check: that `required_ruby_version` is there at all. I believe that it should be an accepted community standard to have it; there is no valid reason not to have a `required_ruby_version` specified that I can think of.

I opened an [rfc about that](https://github.com/rubygems/rfcs/pull/26), but it would probably take time before this is accepted / implemented / released and mostly updated... A Rubocop might make things faster.

In case there is a `.travis.yml` file, it would be nice to check it correponds too.

1) How does a cop making `required_ruby_version` mandatory sound?

2) If that's a go, should it be a different cop?

3) What about `.travis.yml` check?

**Comment by bbatsov** [comment]
I like the idea. I can't come up with a good reason why a gem shouldn't specify some required Ruby version.

**Comment by marcandre** [comment]
2. should it be a different cop?

3. What about .travis.yml check?

**Comment by fatkodima** [comment]
Should this gets closed?
