### ISSUE TITLE
Detect path expansions using `__FILE__` that could be replaced with `__dir__`

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubocop-hq/rubocop#7878]
## Is your feature request related to a problem? Please describe.

I'd like to be able to detect file expansions based on the current file and that go up in the folder hierarchy from there, like

```ruby
File.expand_path("../../foo.rb", __FILE__)
```

And simplify them to use `__dir__` instead, like

```ruby
File.expand_path("../foo.rb", __dir__)
```

Those are equivalent the great majority of the times, but not always if inside a symlinked folder, `__dir__` resolves the symlink, whereas `__FILE__` doesn't.

## Describe the solution you'd like

I'd like a cop that detects and autocorrects these cases, marked as unsafe due to the gotcha I explained.

**Comment by ngan** [comment]
Isn't that this one? https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/ExpandPathArguments

**Comment by deivid-rodriguez** [comment]
Absolutely! I didn't know that existed, thanks!! :)
