### ISSUE TITLE
--parallel disables --force-default-config

### ISSUE THREAD

**Issue by defsprite** [rubocop-hq/rubocop#7881]
It seems like the `--parallel`-switch breaks using `--force-default-config` when `inherited_from` uses a broken / unavailable URL. 

This is probably related to #7790

--------

## Expected behavior

In a project with a local `.rubocop.yml`, running 
```
rubocop --parallel --force-default-config .
```
should ignore the config given in `.rubocop.yml`

## Actual behavior

```
rubocop --parallel --force-default-config .
```
still uses the local `.rubocop.yml`. The same applies to using `--config /dev/null` instead of `--force-default-config` 

## Steps to reproduce the problem

- Create a project with a local `.rubocop.yml` config
- Make sure the config uses `inherit_from` with an unresolvable URL. 
- Compare running rubocop with `--force-default-config` and `--force-default-config --parallel`

Alternatively use the example project at https://github.com/defsprite/rubocop-bug

## RuboCop version

```
🌀 rubocop -V
0.82.0 (using Parser 2.7.0.2, running on ruby 2.6.5 x86_64-darwin19)
```

**Comment by jonas054** [comment]
This one I have not been able to reproduce. I could reproduce #7790 without problem, and I will provide a fix for it.

**Comment by defsprite** [comment]
Did a bit more sleuthing on this: It only happens when the local config contains `inherit_from` with a broken/unavailable URL. 

Added an example project here as well: https://github.com/defsprite/rubocop-bug
