### ISSUE TITLE
Lint/RedundantCopDisableDirective for pending Cops

### ISSUE THREAD

**Issue by tonobo** [rubocop-hq/rubocop#7894]
## Is your feature request related to a problem? Please describe.

I have to disable `Lint/RedundantCopDisableDirective`, in order to disable future cops.

## Describe the solution you'd like

I like to see an further option on `RedundantCopDisableDirective` for disabling the behavior on pending cops.

## Describe alternatives you've considered

Disabling `Lint/RedundantCopDisableDirective` at all.

## Example

```
rubocop --color -fp -fo
[lint] The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
[lint]  - Layout/SpaceAroundMethodCallOperator (0.82)
[lint]  - Lint/RaiseException (0.81)
[lint]  - Lint/StructNewOverride (0.81)
[lint]  - Style/ExponentialNotation (0.82)
[lint]  - Style/HashEachMethods (0.80)
[lint]  - Style/HashTransformKeys (0.80)
[lint]  - Style/HashTransformValues (0.80)
[lint] For more information: https://docs.rubocop.org/en/latest/versioning/
[lint] Inspecting 120 files
[lint] ..........................................................................................W.............................
[lint] 
[lint] Offenses:
[lint] 
[lint] iptables.rb:13:49: W: Lint/RedundantCopDisableDirective: Unnecessary disabling of Lint/StructNewOverride.
[lint]         Policy = Struct.new(:chain, :target) do # rubocop:disable Lint/StructNewOverride
[lint]                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by tejasbubane** [comment]
I think `Lint/RedundantCopDisableDirective` by default should not register offenses for `pending` cops - because the cops are not `disabled`.

**Comment by rrosenblum** [comment]
That makes sense to me. `pending` cops don't register offenses or give any information. In my mind, they are effectively disabled and can be ignored.

**Comment by tonobo** [comment]
I think the recently introduced pending cops feature is quite cool, as it normally allows you to check and prepare your code for upcoming releases or at least i hope it. By having a fleet of projects all running the latest rubocop i can confirm this is much better to be prepared, but this only makes sense to me if rubocop let me prepare the code for upcoming changes. I've discussed this internally with my coworkers and we decided to disable `Lint/RedundantCopDisableDirective`, as the benefit of preparing for upcoming releases takes more affect then checking for redundant cops
