### ISSUE TITLE
Replace single dig to [] access

### ISSUE THREAD

**Issue by wbotelhos** [rubocop-hq/rubocop#7949]
## Is your feature request related to a problem? Please describe.

When you refactor you code from:

```rb
{ key: { subkey: 'value' } }.dig(:key, :subkey)
```

to:

```rb
{ key: 'value' }.dig(:key)
```

You can forget to use just `[]` to access the value.

## Describe the solution you'd like

Replace single `dig` methods to `[]` access.

From:

```rb
{ key: 'value' }.dig(:key)
```

to:

```rb
{ key: 'value' }[:key]
```

**Comment by volfgox** [comment]
I'd like to try to implement this feature.

**Comment by fatkodima** [comment]
@volfgox I have seen you did some work on this. Mind opening a PR?

**Comment by volfgox** [comment]
@fatkodima I finalized the development and sent a PR and waited long long time to merge. But, It's never been merged. You can review the PR [here](https://github.com/rubocop-hq/rubocop/pull/7994).

P.S. @bbatsov Would you please consider the PR?

**Comment by wbotelhos** [comment]
Thank you, @volfgox !

**Comment by volfgox** [comment]
@wbotelhos Thank you too. I hope I can contribute more.

**Comment by amiedes** [comment]
I'm getting this cop triggered in the following case

```ruby
class SomeClass

  # ...

  def method_a
    params[:foo]
  end

  def method_b
    # cop gets triggered here, but replacing with method_a[:bar] is not really equivalent
    method_a.dig(:bar)
  end

end
```

wouldn't that break?

**Comment by amiedes** [comment]
Sorry, I got confused, it would break in both cases. I'm removing my previous comment as it's misleading.
