### ISSUE TITLE
Allow Rails attribute in EmptyLinesAroundAttributeAccessor

### ISSUE THREAD

**Issue by legendetm** [rubocop-hq/rubocop#7981]
## Is your feature request related to a problem? Please describe.

I prefer to group all attributes together including ActiveModel::Attributes#attributes

```
  attr_accessor :foo
  attr_reader :bar
  attr_writer :baz
  attribute :time, :datetime
```

## Describe the solution you'd like

I would expect that `EmptyLinesAroundAttributeAccessor` allow to group `attribute` with other accessors

**Comment by koic** [comment]
This issue similar to #7976. I've opened #7982. Rails-specific methods will be configured by user applications or RuboCop Rails gem using `IgnoredMethods` option because RuboCop core is focused on Ruby.

**Comment by legendetm** [comment]
Yes I know, that RuboCop is Ruby specific and the `IgnoredMethods` option is suitable

**Comment by koic** [comment]
#7981 has been merged. `IgnoredMethods` renamed to `AllowedMethods`. Thank you.
