### ISSUE TITLE
A new formatter for GitHub Actions

### ISSUE THREAD

**Issue by ybiquitous** [rubocop-hq/rubocop#8004]
## Is your feature request related to a problem? Please describe.

I have the following workaround to run RuboCop on GitHub Actions and show detected RuboCop issues to a pull request page:

https://gist.github.com/ybiquitous/72a1d7cf0eb9bbb9255d84d1ee904881

I think there are the following problems:

- Regex written in the workaround above is complicated and hard to read and maintain.
- Users who don't know the workaround cannot easily use RuboCop in Actions.

## Describe the solution you'd like

Add a new formatter for GitHub Actions.

## Describe alternatives you've considered

Add a description of the usage on GitHub Actions to the RuboCop documentation.

## Additional context

Here are the GitHub Actions' messaging specs:

- https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message
- https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

RuboCop has more severities than warning and error, so we need to map RuboCop's severities and GitHub Actions' severities. For example:

| RuboCop    | GitHub Actions |
|------------|----------------|
| refactor   | warning        |
| convention | warning        |
| warning    | warning        |
| error      | error          |
| fatal      | error          |

**Comment by Xorima** [comment]
Hey,

I run actionshub on github and we had this type of issue already around cookstyle (Chef extended Rubocop) and use the following code as a fix: https://github.com/actionshub/chef-delivery/blob/master/cookstyle.json

Now if there is the want I can extend this or create an action to cover rubocop directly?

Thanks

Jason

**Comment by ybiquitous** [comment]
Thank you so much! I can't wait for the next release! 😄
