### ISSUE TITLE
Layout/SpaceAroundMethodCallOperator is slow

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#8021]
This cop inspects in `O(n^2)` instead of `O(n)` as it should (culprit is [this loop](https://github.com/rubocop-hq/rubocop/pull/7857/files#diff-5ee306df3901cef62ea14bbdcbbae126R87)) (where `n` is the order of send nodes / tokens)

As an example, about 10% of `rake internal_investigation` is currently spent in this cop alone. This would be way worse if the source files were not kept kind of small.

@saurabhmaurya15 would you like to look at this? Using tokens may have been a nice generic way of handling things but we can't afford it. We must use `node.loc`.

**Comment by marcandre** [comment]
Note: one could use `token(node)` as a quick improvement, but ideally this could be done without tokens I think

**Comment by saurabhmaurya15** [comment]
@marcandre Can you help me out with how you did profiling on this? I can give it a shot then.

**Comment by marcandre** [comment]
I need to create a rake task to do this properly, but I want to finish #7868 beforehand. In the meantime there's a rake task for testing a particular cop you could use. If you manage not to use tokens at all it would be a big improvement. Or wait a few days and there will be a rake task to measure the cops...

**Comment by ric2b** [comment]
Also ran into the same issue, enabling this cop pushed rubocop run (cache disabled) from ~1 or 2 minutes to over 20 minutes on my codebase.
