### ISSUE TITLE
Misalignment with macro + method definition + ensure

### ISSUE THREAD

**Issue by sobrinho** [rubocop-hq/rubocop#8033]
## Expected behavior

Calling `rubocop --fix x.rb` with no rubocop configuration:

```ruby
my_macro def something
  blah
ensure
  bleh
end
```

OR

```ruby
my_macro def something
           blah
         ensure
           bleh
         end
```

## Actual behavior

Misalignment:

```ruby
my_macro def something
  blah
         ensure
           bleh
end
```

## Steps to reproduce the problem

Create a file with this:

```
my_macro def something
  blah
ensure
  bleh
end
```

And call `rubocop --fix file.rb` with no rubocop configuration set.

## RuboCop version
```
$ rubocop -V
0.84.0 (using Parser 2.7.1.1, rubocop-ast 0.0.3, running on ruby 2.7.1 x86_64-darwin19)
```

**Comment by sobrinho** [comment]
Reported originally in https://github.com/testdouble/standard/issues/178.

**Comment by dvandersluis** [comment]
There was a bug in `Layout/RescueEnsureAlignment` that's been since fixed. This can be closed!
