### ISSUE TITLE
Update docs generation rake task

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#8045]
We need to update our cop docs generator to output AsciiDoc, as that's what our new docs publishing system Antora uses. 

When I migrated the docs I just converted the markdown pages to AsciiDoc, but eventually we'll have to update the rake task to output AsciiDoc so we can again automate the docs publishing process at some point. 

@koic Can you look into this?

**Comment by koic** [comment]
Yeah, I will look into this!

**Comment by bbatsov** [comment]
Much appreciated! 🙇‍♂️
