### ISSUE TITLE
Incorrect URL in warning

### ISSUE THREAD

**Issue by jbeker** [rubocop-hq/rubocop#8057]
When running rubocop and there are new cops, you get the following message:

```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Lint/DeprecatedOpenSSLConstant (0.84)
For more information: https://docs.rubocop.org/en/latest/versioning/
```

The "For more information:" link is invalid. It should be `https://docs.rubocop.org/rubocop/versioning.html`

--------

## Expected behavior

The link provided as documentation should not 404.

## Actual behavior

It 404s

## Steps to reproduce the problem

Click on the link.

## RuboCop version

```
$ rubocop -V
0.84.0 (using Parser 2.7.1.1, rubocop-ast 0.0.3, running on ruby 2.6.3 universal.x86_64-darwin19)```

**Comment by bbatsov** [comment]
Thanks for spotting this!

**Comment by betelgeuse** [comment]
@koic Should there also be a server side redirect because already released gem versions will not be getting this fix?

**Comment by bbatsov** [comment]
@betelgeuse I'm not sure we can set up redirects with GH pages. We can have some blank pages with redirects in them, but that's a pretty painful arrangement and I'd rather avoid it.

**Comment by betelgeuse** [comment]
> @betelgeuse I'm not sure we can set up redirects with GH pages. We can have some blank pages with redirects in them, but that's a pretty painful arrangement and I'd rather avoid it.

Based on this there’s at least some ways to do server side redirectd with github pages. I didn’t look how it fits your stack.

https://stackoverflow.com/questions/9276817/301-redirect-for-site-hosted-at-github

**Comment by bbatsov** [comment]
We're not using Jekyll, so this doesn't help us.

**Comment by matkoniecz** [comment]
Even page with "you reached this page due to bug, documentation is at XYZ" would be nice.
