### ISSUE TITLE
Infinite corrections in some of our cops?

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#8076]
If we change all the default of `expect_correction(loop: false)` to `loop: true` there seem to be  some infinite loop corrections in our test base... Are these cops conflicting in their corrections? are these potential issues?

**Comment by bquorning** [comment]
I have been looking a bit in to this, and there seems to be

- issues with my changes in #8062, and
- actual bugs in a few cops.

I am working on a PR and/or some issues to open. I hope I will have them ready by tomorrow.
