### ISSUE TITLE
Lint/MixedRegexpCaptureTypes premature end of caputre

### ISSUE THREAD

**Issue by fidalgo** [rubocop-hq/rubocop#8100]
I have the following expectations on a spec:

```
        expect(message).to match(/headers={user-agent=Firefox}/)
```
With debug enabled Rubocop gives me the message:
`Premature end of pattern at ={user-agent=Firefox}`

I would expect to not have an error here, as the expectation is passing.

**Comment by koic** [comment]
Dup with #8083 and fixed by #8093.
