### ISSUE TITLE
CI broken on `master`

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#8103]
Is anyone looking at solving our failing CI?

`spec/rubocop/config_loader_spec.rb:1222` and
`spec/rubocop/config_loader_spec.rb:1233`
are failing on CircleCI.

Very strange to me that the almost identical spec on line 1268 does not fail.
Those 3 specs are the only ones using `in_its_own_process_with`

**Comment by bbatsov** [comment]
I'm guessing those failures are related with some upstream Ruby changes. I wouldn't consider them a release blocker, but obviously it'd be great if we managed to sort them out.

**Comment by marcandre** [comment]
I've disabled those two specs on the two jobs so at least the CI is green again.

**Comment by koic** [comment]
Thank you! I think these surveys can be done separately 👍

**Comment by marcandre** [comment]
It would be good to see what's up with ruby-head though, might be a regression they are not aware of.

**Comment by koic** [comment]
This issue has been resolved by https://github.com/rubocop-hq/rubocop/pull/9004.
