### ISSUE TITLE
Drop support for Ruby 2.4

### ISSUE THREAD

**Issue by tejasbubane** [rubocop-hq/rubocop#8112]
Ruby 2.4 has [reached EOL](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/). Should we drop support for it? Perhaps this should be done as a part of 1.0 release?

Previous discussion about 2.2 & 2.3 https://github.com/rubocop-hq/rubocop/issues/6945

@bbatsov Mentioned [here](https://github.com/rubocop-hq/rubocop/issues/3325#issuecomment-233143082) that we should adhere to same EOL as MRI itself.

**Comment by bbatsov** [comment]
Good point. Generally I don't think we have some burning need to drop 2.4, as it doesn't create much maintenance overhead, but dropping it before 1.0 might be a good idea, otherwise we might be stuck with it for a while. @rubocop-hq/rubocop-core as always, I'd love to hear your take on this.

**Comment by marcandre** [comment]
My opinion (I don't know how prevalent it is) is that dropping compatibility with a Ruby version does not require a major version upgrade since it is part of the gem manifest and won't introduce any incompatibility with another Ruby version (as it simply won't install). So my take is that we should continue supporting it, especially since it's not a big overhead, and we can decide to drop support when we feel like it is worthwhile

**Comment by bquorning** [comment]
I looked through old PRs to find out when we dropped support for older rubies:

- #3328 dropping 1.9 was merged on 18 Jul 2016.
- #4787 dropping 2.0 was merged on 2 Oct 2017.
- #5990 dropping 2.1 was merged on 18 Jun 2018.
- #7026 dropping 2.2 was merged on 8 May 2019.
- #7869 dropping 2.3 was merged on 12 Apr 2020.

If we drop support for old Rubies with the same frequency as new versions are released (once per year), I would expect us to drop support for 2.4 in April/May 2021.

**Comment by bbatsov** [comment]
Thanks for looking into this! Seems we've been quite consistent in sticking to unsupported Rubies for at least a year. I guess we should update our support policy then. :-)

**Comment by koic** [comment]
RuboCop has customarily provided support for about a year after EOL of Ruby version. And this span seems to be working as it is. I don't think it's time to drop it, as it will impact gems and apps that rely on RuboCop support.
I can take this as part of the maintenance when dropping. I think RuboCop core should provide the community with a margin of transition.

**Comment by bbatsov** [comment]
Fair enough. Seems we have a deal then.

**Comment by tejasbubane** [comment]
I've added the policy to README. Should we add it somewhere else as well? Should it be shown on the docs/website?

**Comment by bbatsov** [comment]
Probably we should have some dedicated section on the docs about the Ruby support/compatibility policy, but we can address this down the road. I like this as a reference https://nrepl.org/nrepl/0.7.0/about/compatibility.html (probably because I wrote it myself :D )
