### ISSUE TITLE
Create a code style badge that projects can add to their README

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#8182]
I've noticed this in StandardRB https://github.com/testdouble/standard#is-there-a-readme-badge and it seems to me we can do something similar for the community style guide.

**Comment by vaporyhumo** [comment]
Is it fine if it's just the same with the rubocop text? Should we add a section about the badge like in standard?

**Comment by bbatsov** [comment]
Yes and yes. :-)

**Comment by vaporyhumo** [comment]
I'll put up a PR with the changes :)
