### ISSUE TITLE
Style/RedundantRegexpCharacterClass unintentional changes in specific case

### ISSUE THREAD

**Issue by renyamizuno** [rubocop-hq/rubocop#8193]
`Style/RedundantRegexpCharacterClass` is problematic under in specific case:

```ruby
def escape(text)
  text.gsub(/.[\b]/, '')
end
```

`# Style/RedundantRegexpCharacterClass: Redundant single-element character class, [\b] can be replaced with \b.`.

but, `\b` `[\b]` behave differently.

https://docs.ruby-lang.org/en/2.7.0/Regexp.html#class-Regexp-label-Anchors
> \b - Matches word boundaries when outside brackets; backspace (0x08) when inside brackets

--------

## Expected behavior

Ignore `[\b]` case.

## Actual behavior

Change `[\b]` to `\b`.

## RuboCop version

```
$ [bundle exec] rubocop -V
0.86.0 (using Parser 2.7.1.4, rubocop-ast 0.0.3, running on ruby 2.7.1 x86_64-darwin18)
```

**Comment by bbatsov** [comment]
@owst Can you take a look?

**Comment by owst** [comment]
Aha, I missed this difference in behaviour, apologies - I'll have a look this evening UK time 👍

**Comment by renyamizuno** [comment]
thx!
