### ISSUE TITLE
Detect top-level qualified constant lookups (cbase)

### ISSUE THREAD

**Issue by biinari** [rubocop-hq/rubocop#8215]
## The problem

Some cops look for usage of constants, and typically assume that the bare constant is used like `Const`. Another way of referencing constants is to qualify it to the top-level as `::Const`. This can be useful to disambiguate in situations where namespaced classes and modules clash with ones at the top-level.

An example of code that has not been detected due to this omission, `Lint/NonDeterministicRequireOrder` checks for `Dir['./support/**/*.rb'].each` but not for `::Dir['./support/**/*.rb'].each`.

## The solution I would like

I would like for cops that detect patterns involving constants to detect both bare and qualified usage.

## Alternatives I have considered

One option is to modify node patterns like `(const nil? :Array)` to one of the following:
* `(const {nil? cbase} :Array)`
* `(const {cbase nil?} :Array)`
* `(const {nil? (cbase)} :Array)`

All of the above patterns seem to be used at least once in rubocop, and all would be equivalent. The top form seems to be the most used.

An additional thought is that perhaps an internal cop might want to check for patterns containing `(const nil?` to prevent future cops from missing the chance to detect qualified constants.
Clearly `Lint/ConstantResolution` needs to remain without matching `cbase` as that is what it would autocorrect to.

## Additional context

Cops that pattern match for `(const nil? ...)`:

```sh
$ grep -R "(const nil?" -l
lib/rubocop/cop/mixin/enforce_superclass.rb
lib/rubocop/cop/lint/rand_one.rb
lib/rubocop/cop/lint/redundant_splat_expansion.rb
lib/rubocop/cop/lint/non_deterministic_require_order.rb
lib/rubocop/cop/lint/constant_resolution.rb # should not change for this issue
lib/rubocop/cop/lint/debugger.rb # pattern could be condensed to (const {nil? (cbase) :Kernel)
lib/rubocop/cop/lint/useless_access_modifier.rb
lib/rubocop/cop/lint/nested_method_definition.rb
lib/rubocop/cop/lint/unused_method_argument.rb
lib/rubocop/cop/style/dir.rb
lib/rubocop/cop/style/documentation.rb
lib/rubocop/cop/style/stderr_puts.rb
lib/rubocop/cop/style/date_time.rb
lib/rubocop/cop/style/empty_literal.rb
lib/rubocop/cop/style/rescue_standard_error.rb
lib/rubocop/cop/style/proc.rb
lib/rubocop/cop/style/signal_exception.rb
lib/rubocop/cop/style/struct_inheritance.rb
lib/rubocop/cop/style/symbol_proc.rb
lib/rubocop/cop/style/zero_length_predicate.rb
lib/rubocop/cop/style/redundant_freeze.rb
lib/rubocop/cop/style/redundant_exception.rb
lib/rubocop/cop/style/random_with_offset.rb
lib/rubocop/cop/style/expand_path_arguments.rb
lib/rubocop/cop/style/colon_method_call.rb
lib/rubocop/cop/style/mutable_constant.rb
lib/rubocop/cop/internal_affairs/redundant_message_argument.rb # `::MSG` would never be used here so no need to change
```

## Implementation Direction

I am happy to prepare a PR for this if people agree it would be useful.

Questions that would be useful to have answers to before diving in:

1. Would `(const {nil? cbase} :Name)` be the preferred pattern for cops that refer to top-level constants?
2. Would it be worth adding a spec for the mixin `EnforceSuperclass`? This seems to have been added for rails cops but they have moved out to rubocop-rails gem. It is entirely possible that it's used in other extension gems too...
3. Are there any other exclusions to those mentioned above for cops that should only check for bare `Const`?
4. Would an internal cop be useful to persuade new patterns involving constants to check for the qualified form `::Const` too?

**Comment by biinari** [comment]
On reflection, I don't think an internal cop to force later patterns to check for top-level constants is justified.

**Comment by marcandre** [comment]
Sorry I missed this issue. I agree with everything.
