### ISSUE TITLE
Does a "secrets detector" cop make sense as a Security cop for Rubocop?

### ISSUE THREAD

**Issue by ThomasOwens** [rubocop-hq/rubocop#8225]
## Is your feature request related to a problem? Please describe.

I'd like a method to detect potential secrets in my Ruby codebase, in a manner that is well integrated with my IDE and build process.

## Describe the solution you'd like

A cop in the Security department can be used to analyze source files for things that look like access keys, tokens, and passwords.

## Describe alternatives you've considered

There are various scripts that exist. Some of them are centered around the version control systems (like https://github.com/awslabs/git-secrets as an example). Others scan only the current code. However, adding them is adding another tool.

## Additional context

When I work in Ruby, I often include Rubocop. My primary thinking is to include an extensible secrets detector in Rubocop to minimize dependencies on other scripts and gems.

I haven't given much thought to feasibility and architecture at this point - just trying to see if anyone has thought of this before and if it may be something to look at.

**Comment by bbatsov** [comment]
Seems like a good idea to me.

**Comment by ThomasOwens** [comment]
Thanks, @bbatsov - I want to invest a lot more time thinking about this and seeing what is possible, then. Just wanted to make sure that the idea was good before spending a lot of time on something. I think there are a lot of architectural questions, like how to (or not to) break up different types of secrets detection into different cops, and I think the amount of logic/complexity to detect and configuration necessary may drive this.

I'll probably start thinking this through in a lot more detail. If anyone is aware of any previous work (even something that didn't work) in this area, please let me know. I'd like to take advantage of any existing work that I can.

**Comment by ThomasOwens** [comment]
I spent a little bit of time playing around with Rubocop and the parser. I'm no longer convinced that this is a good idea.

The biggest limitation is that it feels very unnatural to expand this beyond Ruby code files. Secrets can live in configuration files (like YML or .env files) as well as code. In addition, there are lots of different patterns and types of secrets. Another consideration is for multi-language projects that aren't fully covered by Rubocop. I think that implementing a secrets detector in a tool like Rubocop would give a false sense of security and be likely to have false negatives as well as false positives.

Although it adds a separate step to a build process, I'd really recommend something like Yelp/detect-secrets. It has a plugin architecture to support a wide variety of secrets and it's cross-language.

I'm going to give it a little more thought, but I'm struggling to see viability for this type of functionality in Rubocop.
