### ISSUE TITLE
Updating our support channels

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop#8320]
Recently I was thinking about https://docs.rubocop.org/rubocop/0.87/support.html

Everything listed there, except StackOverflow is effectively dead - the mailing list has 0 traffic, IRC as well, gitter is almost dead. All of those are historical and tended to be more popular when they were adopted almost a decade ago. I wonder if we can modernize things a bit and adopt something like Discord or whatever. I definitely think it's worth having a place where users can chat and support each other (and maybe interact with the maintainers if they'd be inclined to visit those comm channels as well).

My other big project, CIDER, has a very active Slack community around it, as part of the Clojurians Slacks, but I don't think there's something similar in the world of Ruby. 

@rubocop-hq/rubocop-core What would you suggest? Do you have any observations what other projects are doing these days?

**Comment by marcandre** [comment]
Can't make an informed recommendation, sorry. FWIW, I just added a personal alert for StackOverflow questions tagged `rubocop` (I thought I had, but apparently not).

**Comment by koic** [comment]
Rails community has recently introduced Discourse.

- https://discuss.rubyonrails.org/
- https://weblog.rubyonrails.org/2020/4/27/this-week-in-rails-security-releases-new-mailing-list-new-features-and-refactoring/

I'm not sure if it's the best approach for the issue, anyway just for reference 😅

**Comment by aried3r** [comment]
Sorry, I'm not part of the rubocop-core team, but there is another option, GitHub discussions which could be considered.

See also:
https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions
https://dzhavat.github.io/2020/04/04/my-thoughts-on-github-discussions.html (mainly linked because it links to 4 examples)

**Comment by bbatsov** [comment]
@aried3r Thanks for the suggestion! Everyone's opinion is valuable!

Somehow I had missed the announcement for GitHub discussions, but they seem like a reasonable alternative to a dedicated forum.

**Comment by bbatsov** [comment]
After some experiments I've opted to promoted more GitHub Discussions and to replace Gitter with Discord. I've updated the documentation to reflect this. We'll refine the channel/topic structure in both of them depending on the traction they gain.
