### ISSUE TITLE
Style/RedundantRegexpEscape can generate incorrect fixes for hyphens in character classes

### ISSUE THREAD

**Issue by bpo** [rubocop-hq/rubocop#8335]
`RedundantRegexpEscape` is meant to detect and remove unneeded escapes for regular expressions. In certain cases an escaped hyphen in the middle of a character class can be automatically unescaped such that its meaning changes from a literal hyphen to creating a range match.

--------

## Expected behavior

A hyphen in the middle of a character class should only be unescaped if its resulting meaning stays the same.

## Actual behavior

In at least some scenarios the hyphen can be converted to a range meaning. See below for a concrete example.

## Steps to reproduce the problem

Example regexp: `%r{[:\.\-/]*[^:\.\-/]+[:\.\-/]*}`
This regexp could be safely reduced to `%r{[:./-]*[^:./-]+[:./-]*}` (moving the hyphen to the end of each class to avoid creating a range). Or one could leave the hyphen in place but leave it escaped (only un-escaping the period).
Test string `"america:pnw.oregon-portland/kenton"`
Using Ruby `scan`, results are: `["america:", "pnw.", "oregon-", "portland/", "kenton"]`

Under this version of Rubocop the regexp above is incorrectly simplified to `%r{[:\.-/]*[^:.\-/]+[:\.-/]*}`
Ruby `scan` with this change instead yields: `["america:", "pnw.", "oregon", "portland/", "kenton"]`

## RuboCop version

```
$ bundle exec rubocop -V
0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.6.6 x86_64-darwin19)
```

**Comment by marcandre** [comment]
@owst would you like to check this out?

**Comment by owst** [comment]
Thanks for the heads-up @marcandre! PR opened that will fix this. 

Apologies @bpo - this was caused by the leading `:` in the character classes tripping up some incorrect logic that was attempting to handle POSIX bracket expressions, which has now been simplified/corrected

**Comment by bpo** [comment]
:+1: Nice @owst, thank you for the very handy feature and quick response
