### ISSUE TITLE
shared_context should allow for multiple cops

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#8352]
There's no easy way to test interactions between multiple cops' autocorrections currently.

**Comment by dorner** [comment]
I can push my PR for #8351 and repurpose it for this instead, since I got it working there.

**Comment by marcandre** [comment]
Not as clearly needed as I thought. Closing for now.

**Comment by marcandre** [comment]
Also: I can't recall when I tweaked how the correctors are merged, but it might be more difficult to create issues that need to happen at the same time. Should be ever more true whenever I manage to [tweak the `TreeRewriter` to improve conflicts detection](https://github.com/whitequark/parser/pull/727).
