### ISSUE TITLE
Style/RedundantParentheses false negatives

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#8379]
It would be nice to refactor `( literal )` => `literal`, and `"...#{( anything )}..."` to `"...#{ anything }..."`

@fatkodima will probably handle this; let him know if you'd like to do it.

Noticed because of #8378

**Comment by fatkodima** [comment]
There are so many cops that it is hard to remember all of them 😄 https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/style/redundant_parentheses.rb

It handles the first case and many more. Not sure if the second case is popular enough to worth implementing?

**Comment by marcandre** [comment]
Good find.

> It handles the first case

Clearly it does not as `("\#{user.name} \#{user.email}") * 5` was not autocorrected in #8378

> Not sure if the second case is popular enough to worth implementing?

It might not be popular, but it can happen after auto-correcting (especially after #8378), so it would definitely be nice to enhance `redundant_parentheses`.

**Comment by fatkodima** [comment]
> Clearly it does not as ("\#{user.name} \#{user.email}") * 5 was not autocorrected in #8378

`expect_correction` runs only tested cop, so that cop hadn't a chance to run. I tested it separately and it detects and autocorrects that case.

**Comment by marcandre** [comment]
🤦‍♂️my bad, sorry, you're right.
