### ISSUE TITLE
New cop: `Style/EachWith` to replace `each.with_...` with `each_with_...`

### ISSUE THREAD

**Issue by fatkodima** [rubocop-hq/rubocop#8402]
`each.with_index`   => `each_with_index`
`each.with_object` => `each_with_object`

I was initially thinking that this is a good candidate for `performance` gem, but have seen only 10% perf speedup for `each_with_index` and good savings regarding memory, but haven't seen any improvements by `each_with_object`. 

This this is better suited for `Style`, imo.

**Comment by pirj** [comment]
But ... it's all about consistency, right? `.with_object` works as a specifier to the behavior for other methods, e.g.:
```ruby
# filter_map-alike
[1,2,3].select.with_object([]) { |x, o| o << x*2 if x > 1 }
=> [4, 6]
```

Also, `each_with_index` doesn't support the initial index (offset) parameter as `with_index` does.

Maybe do it the other way around, recommend a specifier instead of `each_with_...`?

**Comment by fatkodima** [comment]
> Also, each_with_index doesn't support the initial index (offset) parameter as with_index does.

Ah, true, good point. This, I think, makes this feature request useless. Haven't ever used that argument.

> Maybe do it the other way around, recommend a specifier instead of each_with_...?

Personally, I'm not seeing benefits of using `each.with_index {...}` over `each_with_index {...}`, even for consistency. Would prefer `each_with_index` if `offset` argument is not needed.

Feel free to close this if you think that this feature request is not worth it.

**Comment by G-Rath** [comment]
I'd be interested in exploring this - while I think the gain is minimal, it would still be nice to be consistent; it can help with large scale refactors, and educating people.

Would folks be ok if I explored creating a new rule for this which defaulted to `each.with_index` and potentially allowed you to configure it to go the other way?
