### ISSUE TITLE
Adjust opt-in to be copy & pasteable into config file

### ISSUE THREAD

**Issue by colszowka** [rubocop-hq/rubocop#8413]
## Is your feature request related to a problem? Please describe.

The recently adjusted opt-in behaviour to new cops comes with a warning printed on rubocop runs that lists all not-yet configured cops, like this:

```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Lint/DuplicateElsifCondition (0.88)
 - Lint/MixedRegexpCaptureTypes (0.85)
 - Style/AccessorGrouping (0.87)
```

## Describe the solution you'd like

As I usually find myself wanting to opt-in to all new cops I would appreciate if the output would be formatted in a way that is directly copy&pasteable. I tried this out locally by adjusting the [corresponding code in config loader](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/config_loader.rb#L153) to print like this instead:

```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
Lint/DuplicateElsifCondition: # (new in 0.88)
  Enabled: true
Lint/MixedRegexpCaptureTypes: # (new in 0.85)
  Enabled: true
Style/AccessorGrouping: # (new in 0.87)
  Enabled: true
```

I would be willing to send a PR with the corresponding changes, but wanted to check in whether this is a change that would be accepted.

Thanks for the extremely useful tool!

**Comment by marcandre** [comment]
> I would be willing to send a PR 

Yes please! 👍 😄

**Comment by colszowka** [comment]
@marcandre Here you we go: https://github.com/rubocop-hq/rubocop/pull/8414
