### ISSUE TITLE
Auto-correct for Style/FrozenStringLiteralComment broken?

### ISSUE THREAD

**Issue by utkarsh2102** [rubocop-hq/rubocop#8418]
Hiya,

With RuboCop v0.88.0, I can't seem to use `Style/FrozenStringLiteralComment` cop's auto-correct. I used it earlier and it worked pretty alright.

Steps to reproduce: `rubocop --only Style/FrozenStringLiteralComment -a` shouldn't work whilst it should.

**Comment by tas50** [comment]
It's marked unsafe now so you need to use -A to autocorrect that.

**Comment by marcandre** [comment]
Indeed, and hopefully someone will pick up #8362 to make that more obvious...

**Comment by utkarsh2102** [comment]
Aye, aye, aye. I totally forgot about `-A`. 
Sorry and thanks! :heart:
