### ISSUE TITLE
puts Benchmark.measure { error

### ISSUE THREAD

**Issue by EnzoGuerra** [rubocop-hq/rubocop#8429]
-------
## Describe here how you expected RuboCop to behave in this particular situati
expected no error message on this code

    # test_sequence_getters
    def test__0
      puts 'test_sequence_getters'
      puts Benchmark.measure {
        ARR.each do |b, e, p|
          seq = Sequence.new(b, e, p)
          assert_kind_of Sequence, seq, 'seq is kind_of Sequence'
          assert_equal b, seq.start,        'b == seq.start'
          assert_equal e, seq.stop,         'e == seq.stop'
          assert_equal p, seq.position,     'p == seq.position'
        end                                                                     
      }                                                                         
    end                                                                         
                                                                              
## Describe here what actually happened.
    test/Sequence_test.rb:55:5: W: Lint/AmbiguousBlockAssociation: Parenthesize the param Benchmark.measure {
      ARR.each do |b, e, p|                                                   
        seq = Sequence.new(b, e, p)                                           
        assert_kind_of Sequence, seq, 'seq is kind_of Sequence'
        assert_equal b, seq.start,        'b == seq.start'
        assert_equal e, seq.stop,         'e == seq.stop'
        assert_equal p, seq.position,     'p == seq.position'
      end                                                                     
    } to make sure that the block will be associated with the Benchmark.measure method call.
    puts Benchmark.measure { ...
    ^^^^^^^^^^^^^^^^^^^^^^^^
 ## Steps to reproduce the problem
 ## This is extremely important! Providing us with a reliable way to reproduce
 ## a problem will expedite its solution.
 used similar template on more files, i thought rubocop and benchmark would
 work together.  i can just remove all benchmark copy, and the tests will all
 pass, just thought it might be of interset to you
 
 ## RuboCop version
 ## Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:
43  0.88.0 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.7.1 x86_64-linux-gnu)(debian 'Bullseye', all packages
installed by aptitude

**Comment by marcandre** [comment]
This is intended. You should write `puts Benchmark.measure do` or `puts(puts Benchmark.measure {`
