### ISSUE TITLE
Add cop for regexes uses to look for the first character of a string

### ISSUE THREAD

**Issue by tas50** [rubocop-hq/rubocop#8515]
## Is your feature request related to a problem? Please describe.

I've noticed that a lot of people use a regex for string matching when there are simpler and faster tools available to them. It would be nice to detect and correct conditions where a regex is not the best.

## Describe the solution you'd like

detect:
```
param.match?(/^-/) 
```

correct to one of these:
```
param.start_with?('-')
param[0] == '-'
```

**Comment by fatkodima** [comment]
This https://github.com/rubocop-hq/rubocop-performance/blob/master/lib/rubocop/cop/performance/start_with.rb 😃 ? 
It handles not just single characters.

**Comment by tas50** [comment]
Perfect. Thanks @fatkodima
