### ISSUE TITLE
Does not recognize typos

### ISSUE THREAD

**Issue by owen2345** [rubocop-hq/rubocop#8528]
Having the following typo, the error is not recognized:

<img width="641" alt="Screen Shot 2020-08-12 at 9 19 44 AM" src="https://user-images.githubusercontent.com/1148415/90019865-fe604980-dc7c-11ea-8cb9-8ea83aec6385.png">

## Expected behavior

The typo should be recognized

## Actual behavior

It does not detect the problem

## Steps to reproduce the problem

rubocop file_with_typo.rb

## RuboCop version

0.79.0

**Comment by koic** [comment]
This is a valid Ruby code. `every 1.day at: '04:00'` means `every(1.day(at: '04:00'))`. So, `Lint/Syntax` cop will not detected. A DSL-specific linter implementation will have the role to detect. Thank you.
