### ISSUE TITLE
Preferring ActiveRecord#discard over #destroy/delete

### ISSUE THREAD

**Issue by boardfish** [rubocop-hq/rubocop#8544]
## Is your feature request related to a problem? Please describe.

When using the [discard](https://github.com/jhawthorn/discard) gem, I'd like to prefer use of the `discard` method over hard-deleting methods such as `destroy` and `delete` to prevent data loss.

## Describe the solution you'd like

I'd like a Cop that will raise warnings if `destroy`/`delete` or their `_all` equivalents are used where `discard` could be applied instead. This will depend on whether `Discard::Model` has been `include`d on the model class itself. 

## Describe alternatives you've considered

I've actually written most of this myself and will share the source if permitted. The only thing that's missing is the above caveat - my Cop will raise warnings independent of whether the instance can actually call `discard` methods. It'd be sufficient for me to know how I can check whether a node in the parse tree can actually call `discard`, but I'm not sure if this is possible.

**Comment by tejasbubane** [comment]
I am not sure if rubocop should we add cops for auxiliary gems. If yes then this should be done in https://github.com/rubocop-hq/rubocop-rails
