### ISSUE TITLE
NewCop Configuration Ignored

### ISSUE THREAD

**Issue by coding-bunny** [rubocop-hq/rubocop#8560]
The latest versions of RuboCop have introduced new Cops.
Because in our projects we want to automatically have these enabled as we upgrade each time, we have the following defined in our configuration:

```
AllCops:
  NewCops: enable
```

This is stored in a seperate configuration file, which is included in every project.
We use a shared configuration file because all projects should follow the same settings.
With the latest version, we keep getting the same output that new cops have been added and should be activated:

```
bundle exec rubocop
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Layout/EmptyLinesAroundAttributeAccessor (0.83)
 - Layout/SpaceAroundMethodCallOperator (0.82)
 - Lint/BinaryOperatorWithIdenticalOperands (0.89)
 - Lint/DeprecatedOpenSSLConstant (0.84)
 - Lint/DuplicateElsifCondition (0.88)
 - Lint/DuplicateRescueException (0.89)
 - Lint/EmptyConditionalBody (0.89)
 - Lint/FloatComparison (0.89)
 - Lint/MissingSuper (0.89)
 - Lint/MixedRegexpCaptureTypes (0.85)
 - Lint/OutOfRangeRegexpRef (0.89)
 - Lint/RaiseException (0.81)
 - Lint/SelfAssignment (0.89)
 - Lint/StructNewOverride (0.81)
 - Lint/TopLevelReturnWithArgument (0.89)
 - Lint/UnreachableLoop (0.89)
 - Style/AccessorGrouping (0.87)
 - Style/ArrayCoercion (0.88)
 - Style/BisectedAttrAccessor (0.87)
 - Style/CaseLikeIf (0.88)
 - Style/ExplicitBlockArgument (0.89)
 - Style/ExponentialNotation (0.82)
 - Style/GlobalStdStream (0.89)
 - Style/HashAsLastArrayItem (0.88)
 - Style/HashEachMethods (0.80)
 - Style/HashLikeCase (0.88)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
 - Style/OptionalBooleanParameter (0.89)
 - Style/RedundantAssignment (0.87)
 - Style/RedundantFetchBlock (0.86)
 - Style/RedundantFileExtensionInRequire (0.88)
 - Style/RedundantRegexpCharacterClass (0.85)
 - Style/RedundantRegexpEscape (0.85)
 - Style/SingleArgumentDig (0.89)
 - Style/SlicingWithRange (0.83)
 - Style/StringConcatenation (0.89)
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 149 files
.....................................................................................................................................................

149 files inspected, no offenses detected
```

--------

## Expected behavior

I expect my configuration to be respected and this warning not to be shown

## Actual behavior

The setting seems to be to be ignored.

## Steps to reproduce the problem
* Created a shared file called `settings.yml`
* Add the `AllCops` directive there
* Reference this file in your `.rubocop.yml`

```
inherit_from: .rubocop_todo.yml

---
inherit_gem:
  inkycop:
    - config/rspec/2.7/rubocop.yml
    - config/customink.yml
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.89.1 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.1 x86_64-darwin19)
```

**Comment by roberts1000** [comment]
What is loading `settings.yml`? 

> Reference this file in your .rubocop.yml

I don't see a reference to `settings.yml` in the .rubocop.yml you posted. Is it getting loaded inside `config/customink.yml` or `config/rspec/2.7/rubocop.yml`?

**Comment by coding-bunny** [comment]
I figured it out, it's a dependency issue.
The problem with this project was that they loaded the `.rubocop_todo.yml` before loading the `settings.yml`, which enabled the `AllCops` configuration settings.

Maybe a point to improve with using RuboCop : `--auto-gen-config` shouldn't insert the `inherit_from:` statement at the top of the file, but after the `inherit_gem:` statement if present? Not sure if that's a sensible approach however.
