### ISSUE TITLE
Cops using `on_send` can be optimized

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#8606]
Now that #8365 is merged, most cops using `on_send` can now be optimized by defining a constant `RESTRICT_ON_SEND` with the list of methods the cop needs to watch for.

Cops that don't depend on a particular list of methods (say because they only look at the arguments) should be left as is.

If you want to help, just comment on which cops you want to look at first (e.g. `Lint/A-E`)

**Comment by fatkodima** [comment]
Style/A-Z

**Comment by fatkodima** [comment]
All other (except Style) departments
