### ISSUE TITLE
Using the `--fix` option with `--stdin` appends file content to the json result

### ISSUE THREAD

**Issue by jgiovaresco** [rubocop-hq/rubocop#8673]
When I run `rubocop` using `--fix` and `--stdin` flags, I can see that the content of the file is appended to the JSON result.
This prevent tools (like RubyMine) to parse the response (https://youtrack.jetbrains.com/issue/RUBY-27006)

## Expected behavior

I would expect to have only the JSON result.

## Actual behavior

Example:
```
❯ rubocop --format json --force-exclusion --fix --stdin application_controller.rb < app/controllers/application_controller.rb 
{"metadata":{"rubocop_version":"0.90.0","ruby_engine":"ruby","ruby_version":"2.7.0","ruby_patchlevel":"0","ruby_platform":"x86_64-darwin19"},"files":[{"path":"application_controller.rb","offenses":[]}],"summary":{"offense_count":0,"target_file_count":1,"inspected_file_count":1}}====================
class ApplicationController < ActionController::API
end
```

## Steps to reproduce the problem

Just run the following in a Rails project:

`rubocop --format json --force-exclusion --fix --stdin application_controller.rb < app/controllers/application_controller.rb `

## RuboCop version

```
❯ bundle exec rubocop -V              
0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.0 x86_64-darwin19)
```

**Comment by ngouy** [comment]
nice fix but breaking change for other tools that were somehow dealing with the "bugged" output (ruby-robocop vs extension as an example)

**Comment by bbatsov** [comment]
That's unfortunate, but I guess it won't be a hard to adjust the VS Code extension.
