### ISSUE TITLE
Changelog conflicts

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#8697]
Could we implement a solution to avoid Changelog conflicts?

I don't particularly care which one, as long it doesn't generate conflicts. I haven't looked around for such tools, but maybe each commit can add a file say `entries/bug_1234.md` and a tool would aggregate that automatically and delete them when making a release?

The conflicts we get are quite annoying, and there are cases where we don't get conflicts but the fact that we make a release leaves the new entry in the wrong section (a previous release instead of `master`). The tools won't always detect this, and there are so many changes between releases that it's not even obvious when checking ourselves (is it ok that the changelog entry is on line 34?)

cc/ @rubocop-hq/rubocop-core

**Comment by bbatsov** [comment]
I think we've looked into some smarter git merge strategies in the past, but those weren't supported by GitHub. I also recall we've discussed a few times auto-generating the changelog, but I don't like this approach as it depends a lot on a very consistent commit title/message structure that'd be hard to instill in the contributors. For me the problem stopped being a big deal when GH added conflict resolution via their web UI a few years ago, but it still would be nice to find a proper solution. Might be a good idea to see what other bigger projects are doing to tackle this. 

> I don't particularly care which one, as long it doesn't generate conflicts. I haven't looked around for such tools, but maybe each commit can add a file say entries/bug_1234.md and a tool would aggregate that automatically and delete them when making a release?

This could work, but it sounds a bit like an overkill to me. I'm hoping we can come up with something simpler.

**Comment by marcandre** [comment]
Did a quick search.

First link is `gitlab` describind exactly my idea: https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/

Next few links refer to that post.

After that there's a repeat of this idea: https://pspdfkit.com/blog/2018/the-challenges-of-changelogs/

Looks like it's the right approach.

We could have `rake changelog:bug|change|feature` that creates a file, copies the last commit's message, inserts a link to the referred issue if it starts with `[Fixes #...]`, and appends the github user (which is what I typically do anyways). Edit and commit at will.

`rake changelog:build` would take amend the ChangeLog with those files and delete them.

**Comment by marcandre** [comment]
@bbatsov should I implement something? It could even be compatible with our current way of doing things (i.e. one could modify the Changelog directly *or* add an entry that would later be merged into the Changelog)
