### ISSUE TITLE
Weird behavior in Lint/AmbiguousBlockAssociation

### ISSUE THREAD

**Issue by fynsta** [rubocop-hq/rubocop#8732]
When analysing my code, the cop Lint/AmbiguousBlockAssociation throws a warning that in my opinion should not be there (in this case at least).

The code in question (rspec):
` expect { MyWorker.new.perform }.not_to change { Model.count }`

--------

## Expected behavior

No error raised because rspec requires the code to be written this way, both parameters need these brackets.

## Actual behavior

> W: Lint/AmbiguousBlockAssociation: Parenthesize the param change { Model.count } to make sure that the block will be associated with the change method call.

## Steps to reproduce the problem

Just copy the line above inside your project and run rubocop

## RuboCop version
0.91.0

**Comment by betesh** [comment]
You misunderstand what rubocop is suggesting.  There is ambiguity here, and rubocop is suggesting you remove it by changing the code to:

    expect { MyWorker.new.perform }.not_to(change { Model.count })

**Comment by fynsta** [comment]
Oh no you are right... I'm sorry!
