### ISSUE TITLE
Read TargetRubyVersion from gemspec `required_ruby_version` if not specified

### ISSUE THREAD

**Issue by donv** [rubocop-hq/rubocop#8761]
## Is your feature request related to a problem? Please describe.

Gemspec/RequiredRubyVersion enforces that gemspec.required_ruby_version is set and then complains that it differs from TargetRubyVersion in .rubocop.yml even if it is not specified in .rubocop.yml.

Having to specify TargetRubyVersion in .rubocop.yml in addition to gemspec.required_ruby_version duplicates the information.

## Describe the solution you'd like

If TargetRubyVersion is not specified in .rubocop.yml it should be read from gemspec.required_ruby_version if present.

**Comment by bbatsov** [comment]
Fine by me.

**Comment by HeroProtagonist** [comment]
👋 I am going to take a stab at this one

**Comment by HeroProtagonist** [comment]
PR submitted 👍
