### ISSUE TITLE
Lint/ConstantDefinitionInBlock has conflict with ActiveSupport::Concern synthax

### ISSUE THREAD

**Issue by fwininger** [rubocop-hq/rubocop#8762]
## Expected behavior

According the concern documentation here : https://api.rubyonrails.org/classes/ActiveSupport/Concern.html

we would like to have this type of code : 

```ruby
module M
  extend ActiveSupport::Concern

  included do
    MY_LEGITIMATE_CONST = 'A'.freeze
  end

  class_methods do
    MY_LEGITIMATE_CONST_BIS = 'A'.freeze
  end
end
```

## Actual behavior

In the rubocop 0.91 version we have the exception : Lint/ConstantDefinitionInBlock: Do not define constants within a block. 

## Steps to reproduce the problem

```ruby
module M
  extend ActiveSupport::Concern

  included do
    MY_LEGITIMATE_CONST = 'A'.freeze
  end

  class_methods do
    MY_LEGITIMATE_CONST_BIS = 'A'.freeze
  end
end
```

## RuboCop version

```
$ [bundle exec] rubocop -V
0.91.0 (using Parser 2.7.1.4, rubocop-ast 0.4.2, running on ruby 2.7.1 x86_64-linux)
```

**Comment by marcandre** [comment]
Did you try including your module `M` in two different classes? I believe you will get an exception. The code above adds a constant to `M`, not to the including class/module.

So that is exactly the purpose of this cop, as that code will not work as expected. You have to use `const_set` here.

**Comment by marcandre** [comment]
I've improved the documentation for cases similar to this one in #8763 
Further improvements welcome 😄
