### ISSUE TITLE
Style/MethodCallWithArgsParentheses should ignore core functions

### ISSUE THREAD

**Issue by coding-bunny** [rubocop-hq/rubocop#8765]
## Is your feature request related to a problem? Please describe.

With the addition of this Cop, all code like `require "rails"` requires the line to be written as `require("rails")`

## Describe the solution you'd like

This Cop should probably ignore some specific methods such as `require`, `require_relative`, `autoload` and other Ruby/Rails core functions.

## Describe alternatives you've considered

It's possible to manually add these to the configuration, but I believe they should be default

## Additional context

Every Ruby example has always been without those parenthesis.
It also doesn't feel "ruby like" to have to use them. I get the point in using them on normal function invocations to make it clear what's going on however.

Especially in older projects, introducing this Cop, causes a massive regression in almost all files because of it.

**Comment by marcandre** [comment]
Absolutely, that's the intent of the `IgnoreMacros` setting.

The error is in the `rubocop/ast` gem, with `Node#macro?` not returning the correct value.

**Comment by coding-bunny** [comment]
> 
> 
> Absolutely, that's the intent of the `IgnoreMacros` setting.
> 
> The error is in the `rubocop/ast` gem, with `Node#macro?` not returning the correct value.

We actually threw out the `rubocop/ast` plugin, and the behavior persists

**Comment by marcandre** [comment]
> We actually threw out the `rubocop/ast` plugin

Sorry I wasn't clear. It's not possible to remove it; `rubocop` needs it to work. I'll fix it in `rubocop-ast` and make a release soon.

**Comment by coding-bunny** [comment]
This sounds like a trick to reinstall `rubocop-ast` :D

**Comment by marcandre** [comment]
Thanks for the bug report.

I had to go fairly deep down the rabbit hole, but if you upgrade to the latest `rubocop` *and* `rubocop-ast` this should be resolved appropriately 🤞

If you find other similar issues with `Style/MethodCallWithArgsParentheses`, please open an issue and mention me 😄
