### ISSUE TITLE
Style/SafeNavigation auto-correct duplicates comments

### ISSUE THREAD

**Issue by vlad-pisanov** [rubocop-hq/rubocop#8781]
When auto-correcting `Style/SafeNavigation` offenses of code described below, comments are duplicated ~and the original comments are not properly indented~.

Consider:

```ruby
if x
  x.each do
    # Comment
  end
end
``` 

--------

## Expected behavior

```ruby
x&.each do
    # Comment
end
```

## Actual behavior

```ruby
# Comment
x&.each do
    # Comment
end
```

## Steps to reproduce the problem

Run sample code

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler. Here's an example:

```
0.91.1 (using Parser 2.7.1.4, rubocop-ast 0.4.2, running on ruby 2.4.5 x86_64-darwin19)
```

**Comment by koic** [comment]
Comment indentation is probably resolved by `Layout/CommentIndentation`. Can you enable `Layout/CommentIndentation`?
