### ISSUE TITLE
Style/IfWithSemicolon auto-correction produces invalid code when statement includes elsif

### ISSUE THREAD

**Issue by Desentso** [rubocop-hq/rubocop#8820]
Style/IfWithSemicolon auto-correction produces syntactically invalid code when `if` semicolon statement also includes `elsif` semicolon statement.

--------

## Expected behavior

I would expect it to produce valid code or not try to auto-correct at all.

## Actual behavior

Style/IfWithSemicolon auto-correction produces code that has syntax error.

In more detail, when trying to auto-correct statements that include `if;` and `elsif;` rubocop produces syntactically invalid code.

## Steps to reproduce the problem

Run it on any file that contains structure similar to:
```ruby
if x; "abc"
elsif y; "123"
end
```

You can then see that it produces =>
```ruby
x ? "abc" : elsif y; "123"
```
which is obviously syntactically invalid.

## RuboCop version

```
0.92.0 (using Parser 2.7.1.5, rubocop-ast 0.7.1, running on ruby 2.5.7 x86_64-darwin18)
```

**Comment by adrian-rivera** [comment]
I've made a PR #8831 this tries to fix this issue in the following way:

```ruby
if x; 'abc' elsif y; '123' end

if x
  'abc'
elsif y
  '123'
end
```
It also accepts multiple `elsif` statements and `else` statements.
