### ISSUE TITLE
New CLI option `--last-commit`

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#8910]
I realize that we've been avoiding caring about SCM like `git`, but I think it could be nice to have better integration with them, especially if it's made clear that support may vary. Maybe `rubocop` by default could support only `git` and extra gems could implement support for extra SCMs. Of course all handling of SCMs would go through a common abstract class to insure that other SCMs could be supported.

In particular, I'd like to have the equivalent of `rake check-commit` (but better, that task doesn't exclude non-Ruby files for example):

```sh
rubocop --last-commit  # => run rubocop only on files modified by last commit (and any uncommitted changes)
rubocop --last-commit 3 # => same, on last 3 commits
rubocop --last-commit 0 # => only on uncommitted changes
```

If it proves popular, `-n` could be a nice shorthand.

I'd love to work on a PR if it sounds like something we would like to provide.

**Comment by fatkodima** [comment]
Didn't get what will be the benefits of having this. Can you explain a bit?

**Comment by marcandre** [comment]
I'm silly. I forget that it's because I'm hacking on RuboCop that my cache gets invalidated all the time. For normal users that's a non issue 😅

**Comment by fatkodima** [comment]
😄 
I had the same idea, inspired by similar feature implemented in another linter (https://github.com/VKCOM/noverify), but then literally had the same
>  I forget that it's because I'm hacking on RuboCop that my cache gets invalidated all the time. For normal users that's a non issue 😅

though in my head.
