### ISSUE TITLE
1.0 does not add Layout/SpaceInsideBlockBraces and Layout/SpaceInsideHashLiteralBraces excluding files to .rubocop_todo.yml

### ISSUE THREAD

**Issue by marutosi** [rubocop-hq/rubocop#8938]
# 0.89

https://github.com/marutosi/redmine/blob/82b58d98dff30edd6884696b596b00aba2050369/Gemfile#L95

```
  gem 'rubocop', '~> 0.89.0'
  gem 'rubocop-performance', '~> 1.5.0'
  gem 'rubocop-rails', '~> 2.5.0'
```

https://github.com/marutosi/redmine/blob/82b58d98dff30edd6884696b596b00aba2050369/.rubocop_todo.yml#L762

```
Layout/SpaceInsideBlockBraces:
  Exclude:
    - 'app/controllers/activities_controller.rb'
    - 'app/controllers/application_controller.rb'
              .
              .
              .

Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'app/controllers/imports_controller.rb'
              .
              .
              .
```

# 1.0

https://github.com/marutosi/redmine/blob/f730543ddee2d4bc4e547908f711df3320a31d18/Gemfile#L95

```
  gem 'rubocop', '~> 1.0.0'
  gem 'rubocop-performance', '~> 1.8.0'
  gem 'rubocop-rails', '~> 2.8.0'
```

https://github.com/marutosi/redmine/blob/f730543ddee2d4bc4e547908f711df3320a31d18/.rubocop_todo.yml#L866

```
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

```

**Comment by jsmestad** [comment]
Hitting this same issue. This also applies to `Layout/SpaceBeforeBlockBraces`

**Comment by drunkel** [comment]
Experiencing this on 1.3 as well. Preventing us upgrading to use recent `rubocop-rspec`.
