### ISSUE TITLE
Should there be a warning in the Style/MultipleComparison documentation about performance impacts?

### ISSUE THREAD

**Issue by tas50** [rubocop-hq/rubocop#8958]
I'm curious if folks think it makes sense to have a warning in the description/documentation of Style/MultipleComparison that explains the performance impact of moving from multiple conditionals to an array with `include?`. I know this isn't the RuboCop performance repo, but this particular cop can have a significant performance impact depending on how you're code is structured.

With 2 conditionals:

```
   array_conditional      4.845M (± 3.1%) i/s -     24.635M in   5.089991s
multiple_conditionals
                          7.247M (± 1.6%) i/s -     36.489M in   5.036135s

Comparison:
multiple_conditionals:  7247447.1 i/s
   array_conditional:  4844894.9 i/s - 1.50x  (± 0.00) slower
```

With 3 conditionals:

```
   array_conditional      4.909M (± 1.8%) i/s -     24.941M in   5.082571s
multiple_conditionals
                          5.426M (± 2.0%) i/s -     27.453M in   5.061797s

Comparison:
multiple_conditionals:  5425711.8 i/s
   array_conditional:  4908886.2 i/s - 1.11x  (± 0.00) slower
```

I can craft some sort of text if folks feel like that makes sense here.

**Comment by tas50** [comment]
At 4 values you break even and past that `.include?` is more performant.

**Comment by marcandre** [comment]
Depends if your `array` is prebuild (constant) or not, or if it's a `Set`, and what type of objects you are comparing, ...

I'm adding a bit of doc in #8957

**Comment by bbatsov** [comment]
Style cops are meant to optimize for humans (readability), so I wouldn't fret over the performance impact that much. Especially since it will be neglible most of the time.

**Comment by tas50** [comment]
Works for me @bbatsov. Thanks

**Comment by tas50** [comment]
It's about 20% faster if you move the array into a const btw.
