### ISSUE TITLE
Metrics/MethodLength ExcludedMethods Regex

### ISSUE THREAD

**Issue by Callion** [rubocop-hq/rubocop#8993]
## Is your feature request related to a problem? Please describe.

Maybe this one is actually working, but I couldn't do it. It would be nice if you could add a regular expression to the ExludedMethods array.

## Describe the solution you'd like
I would love to add Regex to ExludedMethods, or to know how if it's already possible.

Something like this:
`ExcludedMethods: [!ruby/regexp \b\w*params\w*\b\$/, 'create', 'update', 'new', 'edit']`
meaning all methods which have **params** string in it would be ignored, trying to archive that my controllers and their's permitted params are always skipped when MethodLenght check is being controlled.

## Describe alternatives you've considered
Ofc I could skip this check for whole controllers folder, but I want it to be as much precise as possible.

**Comment by marcandre** [comment]
Seems like a good idea to me.

More knowledgeable folks might have a better idea though
