### ISSUE TITLE
What is the difference between rubocop -a and rubocop -A?

### ISSUE THREAD

**Issue by codemicky** [rubocop-hq/rubocop#9021]
What is the difference between `rubocop -a` and `rubocop -A`?

**Comment by dvandersluis** [comment]
`rubocop -a` only performs autocorrections that are marked as safe, whereas `rubocop -A` will perform all autocorrections. Some autocorrections have the possibility to change the meaning of the code, so when this is known, the autocorrect is marked as unsafe (so it should be done manually or evaluated after completion). See https://docs.rubocop.org/rubocop/usage/auto_correct.html for more info.

**Comment by koic** [comment]
Yeah, I'm going to close this issue because as it has already been explained by above comment. @dvandersluis Thank you :-)
