### ISSUE TITLE
Apply Layout/EmptyLineBetweenDefs to class definitions as well

### ISSUE THREAD

**Issue by jtannas** [rubocop-hq/rubocop#9064]
## Is your feature request related to a problem? Please describe.

The `Layout/EmptyLineBetweenDefs` cop only applies between two functions, so the following pundit policy code raises no offenses.
```ruby
class UserPolicy < ApplicationPolicy
  class Scope < Scope
    def resolve
      scope.all
    end
  end
  def show?
    true
  end
end
```
I would like a cop to raise an offense about how there's no empty line between the end of the `Scope` class and the `def show?` line.

## Describe the solution you'd like

My preference would be to modify the `Layout/EmptyLineBetweenDefs` to also apply to class definitions. This is within the intent of the cop that definitions should be visually spaced out to help readability.

## Describe alternatives you've considered

Options are to:
1) Modify the cop in place.
	- Pro: gets the most adoption with no user configuration
	- Con: raises offenses on code that was previously inoffensive
2) Add a configuration option to the cop
	- Pro: this is safer since it lets people toggle the behaviour
	- Con: more complicated configuration
3) Add a new cop
	- Pro: safe option for users that doesn't require more configuration
	- Con: Possible interactions with `Layout/EmptyLineBetweenDefs` cop

## Additional context

There's nothing specifically addressing this situation in the Ruby style guide so I can't be 100% certain my suggestion is correct. If there's no consensus that it is, then option 2 or 3 will let people choose their own preference.

I'd be happy to make the PR once people agree on which option to go with.

**Comment by bbatsov** [comment]
I think option 2) is the best one. Something like this should be fairly easy to implement.

**Comment by jtannas** [comment]
Sounds good - just a boolean `ApplyToClassDefs`? Default value false?
