### ISSUE TITLE
Problem on creating a HTML report

### ISSUE THREAD

**Issue by fabriciobedin** [rubocop-hq/rubocop#9084]
## Expected behavior

The formatter should create a HTML report based on a template inside assets folder.

## Actual behavior

There isn't the assets folder inside the new release, so the formatter can't get the template.

I think the problem is in this commit https://github.com/rubocop-hq/rubocop/commit/c40141c52ba76bfd76444c44e65b7be8cdd4ca14

## Steps to reproduce

```
rubocop --format html --out rubocop.html
```

```
No such file or directory @ rb_sysopen - /Library/Ruby/Gems/2.6.0/ruby/2.6.0/gems/rubocop-1.4.0/assets/output.html.erb
```

## RuboCop version

1.4.0 (using Parser 2.7.2.0, rubocop-ast 1.1.1, running on ruby 2.6.3 universal.x86_64-darwin19)

**Comment by bbatsov** [comment]
See https://github.com/rubocop-hq/rubocop/pull/9082

I'll cut a bugfix release shortly.

**Comment by bbatsov** [comment]
Done.
