### ISSUE TITLE
Metrics/MethodLength blows up when inspecting index method

### ISSUE THREAD

**Issue by Drenmi** [rubocop-hq/rubocop#9110]
## Expected behavior

No exceptions.

## Actual behavior

```
Inspecting 1 file
Scanning [redacted]
An error occurred while Metrics/MethodLength cop was inspecting [redacted].
empty char-class: /[]/
/Users/ted/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-1.4.2/lib/rubocop/cop/metrics/method_length.rb:39:in `match?'
/Users/ted/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-1.4.2/lib/rubocop/cop/metrics/method_length.rb:39:in `block in on_def'
/Users/ted/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-1.4.2/lib/rubocop/cop/metrics/method_length.rb:39:in `any?'
/Users/ted/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-1.4.2/lib/rubocop/cop/metrics/method_length.rb:39:in `on_def'
```

## Steps to reproduce the problem

**1. Configure `ExcludedMethods` to any value. In this case:**

```yaml
Metrics/MethodLength:
  ExcludedMethods:
    - "call"
```

**2. Inspect a class that defines the `#[]` method:**

```ruby
class Foo
  def [](key)
    # Do stuff.
  end
end
```

## RuboCop version

```
1.4.2 (using Parser 2.7.2.0, rubocop-ast 1.2.0, running on ruby 2.7.1 x86_64-darwin18)
```

**Comment by Drenmi** [comment]
As an aside, I find it a bit awkward that this configuration key is deprecated, but the new one is not introduced? 😅 

```
Warning: Metrics/MethodLength does not support IgnoredMethods parameter.
```

**Comment by bbatsov** [comment]
@Drenmi It's deprecated only on `master` and `IgnoredMethods` should work there.

**Comment by Drenmi** [comment]
@bbatsov I see! I was too quick to assume that change was the culprit. I didn't realize there were several rapid changes to the cop. 🙂 

The offending call is [here](https://github.com/rubocop-hq/rubocop/commit/499e50fbd75e4c9defcbd729ae5f4f4f10bf88be#diff-973df3513a2d3ce211512584b0db23529577c29ea93eb0fa1ecaeb74ee9324cbR39).

After testing, I think this might be fixed on `master`, so I'm closing this and awaiting next release.
