### ISSUE TITLE
Invalid Offense / Invalid Autofix: Layout/MultilineHashBraceLayout

### ISSUE THREAD

**Issue by luke-hill** [rubocop-hq/rubocop#9111]
--------

## Expected behavior

Not to flag a cop

## Actual behavior

```
Layout/MultilineHashBraceLayout: Closing hash brace must be on the same line as the last hash element when opening brace is on the same line as the first hash element.
```

## Steps to reproduce the problem

Inside an rspec expectation write the following code

```
        is_expected.to have_attributes(
          { options:
            { browser: :chrome, clear_local_storage: nil, clear_session_storage: nil }
          }
        )
```
## RuboCop version

0.91.1 (using Parser 2.7.2.0, rubocop-ast 0.8.0, running on ruby 2.7.2 x86_64-linux)

## Extra Info

When auto-fixing this, it formats the code in an ugly way, putting a double brace on the line next to nil. Yet doesn't move the opening brace / line

**Comment by koic** [comment]
I think this behaviour is an expected.

```ruby
# EnforcedStyle: symmetrical (default)

# bad
{ a: 1,
  b: 2
}

# good
{ a: 1,
  b: 2 }
```

https://docs.rubocop.org/rubocop/1.4/cops_layout.html#layoutmultilinehashbracelayout

By default `EnforcedStyle: symmetrical`, `{` and `options` should be on different lines. e.g.:

```diff
        is_expected.to have_attributes(
-         { options:
-           { browser: :chrome, clear_local_storage: nil, clear_session_storage: nil }
+         {
+           options: { browser: :chrome, clear_local_storage: nil, clear_session_storage: nil }
          }
        )
```

Auto-corrected code also seems to follow the good case.

```diff
@@ -1,5 +1,4 @@
 is_expected.to have_attributes(
   { options:
-    { browser: :chrome, clear_local_storage: nil, clear_session_storage: nil }
-  }
+    { browser: :chrome, clear_local_storage: nil, clear_session_storage: nil }}
 )
```

**Comment by luke-hill** [comment]
Fair does I guess. I think the bottom bit looks really crap. I'm happy with the top one though. So if it's intended let's close it off and I'll work around it.
