### ISSUE TITLE
Nudge about standard extensions

### ISSUE THREAD

**Issue by tejasbubane** [rubocop-hq/rubocop#9122]
## Is your feature request related to a problem? Please describe.

Although it has been long time since we [extracted `rubocop-rails` from core](https://github.com/rubocop-hq/rubocop/issues/5976) some users never discover our extensions. I have seen quite a few modern Rails projects using only `rubocop`.

## Describe the solution you'd like

I would like when `rubocop` is run, it recognizes and prints a log message suggesting standard plugins like `rubocop-rails`, `rspec`, `minitest`, `rake`, `sequel` - whichever applicable to the project. 

An option to disable this message.

## Describe alternatives you've considered

A generic log message suggesting to have a look at our extensions.

**Comment by bbatsov** [comment]
Good idea. Shouldn't be hard to implement it.

**Comment by dvandersluis** [comment]
I'm taking a stab at this.
