### ISSUE TITLE
Better support for packages: `rubocop -V`

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#9124]
It would be nice if there was a way for packages like `rubocop-performance/rspec/...` to "register" themselves so we could output their versions in `rubocop -V`.

For example I couldn't confirm in https://github.com/rubocop-hq/rubocop-performance/issues/200 that the report was due to an older version of `rubocop-performance`.

**Comment by koic** [comment]
`-V` option has been extended from RuboCop 1.0 for extension cop versions.
https://github.com/rubocop-hq/rubocop/pull/8908

e.g.

```console
% rubocop -V
1.4.2 (using Parser 2.7.2.0, rubocop-ast 1.2.0, running on ruby 3.0.0 x86_64-darwin19)
  - rubocop-performance 1.9.1
  - rubocop-rspec 2.0.0
```

I've updated the issue template example for users by #9126.
