### ISSUE TITLE
Better support for packages: renamed / obsolete cops / config

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#9125]
It would be nice if packages had an API to tap into our [config_obsoletion class](https://github.com/rubocop-hq/rubocop/blob/5784d45f6c17d15c7aa72cb6d727352819351bcb/lib/rubocop/config_obsoletion.rb)

See https://github.com/rubocop-hq/rubocop-performance/issues/198#issuecomment-733497898

**Comment by marcandre** [comment]
Maybe related to #9124

**Comment by bbatsov** [comment]
Good idea. In general config obsoletion should be polished, so it's easier to do rename/replace stuff, without breaking the user configuration. Recently @dvandersluis did some work on that front for https://github.com/rubocop-hq/rubocop/pull/9098

**Comment by dvandersluis** [comment]
I've started on working on this, I hope to have something tomorrow!
