### ISSUE TITLE
RedundantRegexpEscape auto correct mangles code

### ISSUE THREAD

**Issue by baelter** [rubocop-hq/rubocop#9133]
Not sure exactly what in the regex that triggers this bug but this:

```ruby
INVALID_CHARS = %r{
  [^’a-zåäöéáœæøüA-ZÅÄÖÉÁÜŒÆØ0-9 –:.`´',;\^¤#%§£$€¢¥©™°&/\(\)=\+\-\*_\!?²³®½\@\n\r]
}x.freeze
def team_record(team); end
```

Get auto corrected to:

```ruby
INVALID_CHARS = %r{
  [^’a-zåäöéáœæøüA-ZÅÄÖÉÁÜŒÆØ0-9 –:.`´',;\^¤#%§£$€¢¥©™°&/\(\)=\+\-\*_\!?²³®½\@\n\r]
}x.freeede tem_ecord(team; end
```

Which is obviously wrong.

`1.4.2 (using Parser 2.7.2.0, rubocop-ast 1.1.1, running on ruby 2.7.2 x86_64-darwin19)`

**Comment by dvandersluis** [comment]
@baelter I can't duplicate this, can you give the rubocop output from autocorrecting?

**Comment by pdobb** [comment]
Just to try to help out, I tried to replicate too. Autocorrect changed to this for me:
```ruby
INVALID_CHARS = %r{
  [^’a-zåäöéáœæøüA-ZÅÄÖÉÁÜŒÆØ0-9 –:.`´',;\^¤#%§£$€¢¥©™°&/()=+\-*_!?²³®½@\n\r]
}x.freeze
def team_record(team)
end
```
Which looks right.

**Comment by marcandre** [comment]
Please update to latest RuboCop. I believe support for UTF-8 has been fixed with latest `regexp_parser` gem which `rubocop` uses.
Closing, but just comment if it's still an issue.

**Comment by baelter** [comment]
I can verify that this is not reproducible with just rubocop cli. Still getting it in vscode though so must be a bug somewhere there.
