### ISSUE TITLE
Style/SoleNestedConditional incorrectly merges conditionals

### ISSUE THREAD

**Issue by mmuehlberger** [rubocop-hq/rubocop#9152]
I've been observing an issue with the auto-correct functionality of `Style/SoleNestedConditional` that incorrectly merges two conditionals, which have more than one condition.

## Input

```ruby
if a
  if b || c
    # ...
  end
end
```

## Expected behavior

Resulting code will be

```ruby
if a && (b || c)
  # ...
end
```

## Actual behavior

Resulting code is 

```ruby
if a && b || c
  # ...
end
```

## RuboCop version

```
1.5.0 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.6.5 x86_64-darwin18)
  - rubocop-performance 1.9.1
  - rubocop-rails 2.8.1
  - rubocop-rspec 2.0.1
```

**Comment by marcandre** [comment]
Thanks for the report.

@koic did you want to have a look at this?

**Comment by koic** [comment]
Yeah, I will take this one!
