### ISSUE TITLE
Suggestion: `--only` to run only enabled cops and warn/fail if cops are disabled

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/rubocop#9163]
## Problem

It always hits me by surprise when running RuboCop with `--only <cop-name>` flag that there are no warning telling me that if I would run without `--only` flag, the offences would not be raised.

I think of `--only` as a way to filter the lengthy list of a normal `rubocop` run (that are at times hundreds of screens long.

## Solution

When `rubocop` is run with `--only`:
 - union the list of passed cops with the cops enabled setting from config, and only run enabled ones
 - warn/fail when cops passes as arguments are not enabled in the config

Introduce a `--force--enable` flag (similar to `--force-default-config`/`--force-exclusion` in a sense) to be able to run with a limited number of cops passed as arguments even if they are disabled in the configuration.

## Alternatives

Don't know any. Maybe `--no-force-default-config`?

**Comment by marcandre** [comment]
I'm curious... When does it surprise you, i.e. in what context are you typing `rubocop --only SomeDisabledCop` in the first place?

**Comment by pirj** [comment]
I've recently updated RuboCop version and added `rubocop-rspec` to a massive application.
As it is usually, there are thousands of offences.
There was a really painful bug in the recently deployed code, one that RuboCop could prevent.

And there is a cop that does raise an offence when inspecting this code. I've checked it by running `rubocop --only <that-cop> <that-file>`.
I've also checked that this cop is never mentioned (disabled) anywhere in the project.

Unfortunately, `.rubocop.yml` is set to opt-in mode with `DisableByDefault: true`.
So this cop is not inspecting the code.
I could be fooled by `--only` if it would be disabled somewhere in `app/.rubocop.yml` and I wouldn't grep the whole project.

I clearly understand, though, that it's not the way how RuboCop works by default, e.g. if `app/some_file.rb` is part of `AllCops/Exclude`, running `rubocop app/some_file.rb` **will** inspect it unless `--force-exclusion` option is provided.

This was not the first time I've made the same mistake. I'd love to know how to avoid it in the future.
This ticket is more like a suggestion or an invitation for a discussion.
Also, no rush. My solution from the description is a breaking one, and I wouldn't expect it to be accepted before RuboCop hits 2.0.

Just for the background, the cop is `Style/ClassAndModuleChildren`, and the problem was a failed deployment due to a "Circular dependency detected".

**Comment by bbatsov** [comment]
Hmm, I was under the impression that `--only` was ignoring weather a cop is disabled or enabled. I'm guessing this got changed when we added support to run entire departments via it, which makes sense. Still, it the target is a single cop I think it's a no brainer we need to run it.

**Comment by marcandre** [comment]
> Hmm, I was under the impression that `--only` was ignoring weather a cop is disabled or enabled. I'm guessing this got changed when we added support to run entire departments via it, which makes sense. Still, it the target is a single cop I think it's a no brainer we need to run it.

My understanding is that this is still the case but that @pirj would like to change that. It's still not clear to me why 😅

I'm not against a "Note that cop Xyz is currently disabled in the config", but it should still run.

**Comment by pirj** [comment]
> I'm not against a "Note that cop Xyz is currently disabled in the config", but it should still run.

Sounds reasonable, that's all I need 👍
I can handle adding this warning if you don't mind the idea.

**Comment by bbatsov** [comment]
I'm fine with this. Seems I once again misread what the issue was about. 😆

**Comment by bbatsov** [comment]
It's probably prudent to document better the behavior in general as well.

**Comment by pirj** [comment]
Supposedly fixed in https://github.com/rubocop-hq/rubocop/pull/9241
