### ISSUE TITLE
Gem warning for parser

### ISSUE THREAD

**Issue by dvandersluis** [rubocop-hq/rubocop#9164]
Gem gives a warning when the gemspec is loaded (and via Bundler.load, which we do in a couple places):

```
WARNING:  open-ended dependency on parser (>= 2.7.1.5) is not recommended
  if parser is semantically versioned, use:
    add_runtime_dependency 'parser', '~> 2.7', '>= 2.7.1.5'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
```

Would it be ok to make the suggested change?

**Comment by marcandre** [comment]
"if parser is semantically versioned" => it is not.

Is there a way to disable this? Or else add '<= 42.0.0' 😆

**Comment by dvandersluis** [comment]
Haha yeah that’s what I wasn’t sure. We can just ignore the warning, but it gets spit out in test output sometimes.
