### ISSUE TITLE
Wrong number of autocorrections

### ISSUE THREAD

**Issue by fynsta** [rubocop-hq/rubocop#9175]
When running `rubocop -a --only=Layout/LineLength`, it displays a total of 12 offenses, of which 7 were autocorrected. In fact, none of those offenses were corrected.

```
app/models/user.rb:77:151: C: [Corrected] Layout/LineLength: Line is too long. [151/150]
    last_push_token = user_tokens.where.not(push_token: [nil, '']).where.not(updated_at: nil).where.not(last_sign_in: nil).order('updated_at ASC').last
```

Here, for example, an offense was supposedly corrected, although nothing in this line was changed. And, sure enough, next time I run the same command, the offense shows up again.

I am not sure what is causing the problem as it seems to occur randomly on different line lengths (150-190 characters in my case).

--------

## Expected behavior

Either not to show that the offense was corrected, or correct it once and for all.

## Steps to reproduce the problem

In rubocop.yml, specify 
```
Layout/LineLength:
  Max: 150
```

Then run the autocorrection on the line above.

## RuboCop version

```
1.5.2 (using Parser 2.7.2.0, rubocop-ast 1.3.0, running on ruby 2.6.1 x86_64-darwin19)
  - rubocop-faker 1.1.0
  - rubocop-performance 1.9.1
  - rubocop-rails 2.8.1
  - rubocop-rake 0.5.1
  - rubocop-rspec 2.0.1
```

**Comment by dvandersluis** [comment]
This is a continuation of #8978 and #9073. `LineLength` is a special case for autocorrect because it can only split lines at certain places. Your example should actually autocorrect, but it looks like my fix from #8978 (from before AutoCorrect was enabled by default) is preventing the autocorrect from actually running. I have a fix coming.
