### ISSUE TITLE
Fork rubocop-i18n

### ISSUE THREAD

**Issue by mvz** [rubocop-hq/rubocop#9216]
## Is your feature request related to a problem? Please describe.

[rubocop-i18n](https://github.com/puppetlabs/rubocop-i18n) is no longer being maintained and is not compatible with the latest version of rubocop. The repository has been archived.

## Describe the solution you'd like

I'd like (a fork of) rubocop-i18n to be maintained under the rubocop-hq organization. Options are:

1. Fork or transfer the current rubocop-i18n repo to rubocop-hq, and acquire access to push the rubocop-i18n gem to rubygems
2. Fork and split rubocop-i18n into rubocop-gettext and rubocop-rails-i18n, to avoid the need to acquire access to rubygems.

The first step I think would be choosing between options 1 and 2.

## Describe alternatives you've considered

I could create my own fork. In that case I would probably go with option 2. However, I would prefer some group effort to maintain this code in the future.

## Additional context

https://github.com/rubocop-hq/rubocop/pull/8490#issuecomment-742092996

**Comment by bbatsov** [comment]
I'm all for maintaining the gem(s) here.

Unless there are strong arguments in favour of option 2), I guess we should try option 1) first as it would present less hassle for the existing users of the gem. 

@highb, can you help us out with this or point us in the right direction? (I've noticed you were doing most of the work on the gem before it was archived)

**Comment by bbatsov** [comment]
Btw, we now have https://github.com/rubocop-hq/rubocop/discussions as well, but I guess it's fine to keep discussing the topic in this ticket.

**Comment by highb** [comment]
@bbatsov @mvz I've been working with my contacts at Puppet to get maintainer access for the gem and get the repo un-archived. Hopefully I'll get access soon and can work on merging the outstanding PRs and doing some maintenance.

**Comment by highb** [comment]
I'm also open to working with the Puppet org to transfer ownership to rubocop-hq, I'm just not sure what Puppet wants to do there.

**Comment by bbatsov** [comment]
Thanks! Any idea why the repo was archived? Seems the project was fairly popular.

**Comment by mvz** [comment]
Thanks, @highb!

**Comment by highb** [comment]
> 
> 
> Thanks! Any idea why the repo was archived? Seems the project was fairly popular.

Long story short is that internationalization and localization were a company-wide priority at Puppet. Then suddenly, they weren't. 😞 It is very easy to open source something. The hard part is maintenance and community engagement. I'll try my best to help out in my free time, but my day job doesn't have an open source maintenance budget and doesn't make use of this library so my time will be limited.

**Comment by binford2k** [comment]
Hey @bbatsov. Like @highb said, i18n is not a priority at the moment. We've been cleaning up some projects that weren't being effectively maintained to help our eng teams focus and this one was accidentally included in that due to an internal miscommunication. We were actually planning to offer it to @highb for maintenance instead. The repo has been unarchived and @highb has admin access and publish rights.

You're welcome to fork it to the `rubocop-hq` namespace if you'd like, too. Cheers!

**Comment by bbatsov** [comment]
Thanks! I'll leave the next steps to @highb - if he wants he can transfer the repo to RuboCop HQ. I think that's better than forking it, as it always creates confusion for the users.

**Comment by highb** [comment]
I've shipped a [3.0.0 release ](https://github.com/puppetlabs/rubocop-i18n/releases/tag/v3.0.0) with @mvz 's changes. I think for now, we can keep it in the Puppetlabs namespace, as I've been given full maintainer permissions on the repo. If that's acceptable to everyone, this issue can hopefully be closed?

**Comment by bbatsov** [comment]
Indeed! Thanks for your help! 🙇‍♂️
