### ISSUE TITLE
SyntaxError after "safe" correction into end-less  method definition

### ISSUE THREAD

**Issue by paddor** [rubocop-hq/rubocop#9355]
`rubocop -a` turns one-line method definitions into syntactically incorrect end-less method definitions on Ruby 3.0.

Example:
```ruby
      def sndhwm() Zsock.sndhwm(@zocket) end
```

--------

## Expected behavior

Correct syntax:
```ruby
      def sndhwm = Zsock.sndhwm(@zocket)
```

## Actual behavior

```ruby
      def sndhwm(()) = Zsock.sndhwm(@zocket)
```

## RuboCop version

`1.8.0 (using Parser 3.0.0.0, rubocop-ast 1.4.0, running on ruby 3.0.0 x86_64-linux)` 

## Ruby version

`ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]`

**Comment by dvandersluis** [comment]
I'll take a look at this.
