### ISSUE TITLE
`TargetRuby` and `required_ruby_version` crash

### ISSUE THREAD

**Issue by marcandre** [rubocop-hq/rubocop#9482]
Followup to #9329

There seem to be multitude issues with `TargetRuby` and `required_ruby_version` of gemspec:
* while `<= 3.0.0` will use `DEFAULT_VERSION` (good), `>= 2.0.0` will use `2.0.0` which will then raise an error and stop (really bad)
* same for list of versions
* does not understand `>` and `<`, `!=` and `~>`.

Code should probably use https://docs.ruby-lang.org/en/2.6.0/Gem/Requirement.html and find the minimal correct version that is `satisfied_by?`

**Comment by marcandre** [comment]
@HeroProtagonist are you interested in tackling this?

**Comment by HeroProtagonist** [comment]
@marcandre 👋  
Sure, I should have time to take a look this week
