### ISSUE TITLE
Style/HashConversion splatted array should not error

### ISSUE THREAD

**Issue by bkuhlmann** [rubocop-hq/rubocop#9526]
## Expected behavior

It would be nice to enable `Style/HashConversion` but not flag `Hash[*values]` usage as invalid.

## Actual behavior

Getting the following error when using splatting an array to a hash:

``` 
snippet.rb:4:16: C: Style/HashConversion: Prefer array_of_pairs.to_h to Hash[*array].
  def to_env = Hash[*values]
```

## Steps to reproduce the problem

Create the following files locally to reproduce:

``` ruby
# File: .rubocop.yml
Style/HashConversion:
  Enabled: true
```

``` ruby
# frozen_string_literal: true

# File: snippet.rb
Pair = Struct.new :key, :value do
  def to_env = Hash[*values]
end
```

Now run the following:

`rubocop snippet.rb`

Notice you'll get the following error:

``` 
snippet.rb:4:16: C: Style/HashConversion: Prefer array_of_pairs.to_h to Hash[*array].
  def to_env = Hash[*values]
```

## RuboCop version

```
# rubocop -V
1.10.0 (using Parser 3.0.0.0, rubocop-ast 1.4.1, running on ruby 3.0.0 x86_64-darwin20)
```

**Comment by koic** [comment]
Thank you for the feedback. I opened a proposal as #9527.
