### ISSUE TITLE
`Naming/VariableNumber` does not support `AllowedNames` parameter

### ISSUE THREAD

**Issue by pjg** [rubocop-hq/rubocop#9536]
## Is your feature request related to a problem? Please describe.

I believe this cop should support the `AllowedNames` parameter, so that exceptions can be made for existing model attributes. This would mimic the option available for `Naming/MethodParameterName`.

## Describe the solution you'd like

Add support for `AllowedNames` option to `Naming/MethodParameterName` cop.

## Describe alternatives you've considered

Alternative is to just disable the whole cop, which is not ideal.

**Comment by koic** [comment]
I think `AllowedIdentifiers` configuration option will solve the issue.
https://docs.rubocop.org/rubocop/1.10/cops_naming.html#allowedidentifiers-capture3

Below is an example configuration.
https://github.com/rubocop-hq/rubocop/blob/v1.10.0/config/default.yml#L2598-L2604

**Comment by pjg** [comment]
D'oh! Somehow I overlooked it 😞  Thanks!
